### ISSUE TITLE
After upgrade from 15 to nzbget 16 RSS not working

### ISSUE THREAD

**Issue by mikeo999** [nzbget/nzbget#105]
I have a RSS running in NZBGet that downloads every day a episode from Masterchef from Spotweb.
Running fine week.

Last week there was a package upgrade for NZBGet for Synology.
After the upgrade there is not automatic download anymore.

When i click on the Feed button i can see there is a new episode and can start it fine but now automatic download anymore.

**Comment by hugbug** [comment]
It's hard to tell because I do not maintain this package. It's possible that the feed status was reset by update routine (not part of nzbget project).
What was the status of the item: backlog or new?

**Comment by mikeo999** [comment]
I made a change (change the name a bit)  to the RSS Feed so i could save the RSS feed again and NZBGet did a reload after it. At that moment he pick up the feed again. So it look like a easy fix i hope and will have to wait till Thursdaymorning then there will be a new episode for me and let you know how it goes.

Status was new by the way.

**Comment by hugbug** [comment]
New is OK. It means the feed wasn't fetched yet or the item wasn't in the feed on the last fetch. How are you so sure it wasn't a problem on indexer side?

**Comment by mikeo999** [comment]
Because i use my local Spotweb server and was working fine every day until the upgrade. Post was already 1 hour on Spotweb and RSS is checking 15 min.

And the moment i save the RSS again is was direct downloading it.

But let see whats happens next week.

**Comment by hugbug** [comment]
Fetches of feeds are logged as DETAIL. If you have DetailTarget set to write into the log-file you can check the log-file for message like "Downloading <feed-name>" and "<feed-name> has no new items".

**Comment by mikeo999** [comment]
Problem indeed solved by saving the RSS Feed again after upgrading.
