### ISSUE TITLE
No post-processing for pp-queued items after reload

### ISSUE THREAD

**Issue by NinoFloris** [nzbget/nzbget#106]
As it is now, I have the critical health action set to 'None' instead of 'Delete' because with 'None' it will normally end the download, and kick of post-processing which reports this failure back to Sickbeard and this will trigger the search for a new suitable download (nzbToMedia).

With 'None' however there is an unnecessary wait, especially with big files before the download is finished.

I hope/propose there is an easy way to run the post-processing also after a Delete:Health failure

**Comment by hugbug** [comment]
All scripts are executed on delete as well.

**Comment by NinoFloris** [comment]
They were immediately moved to history and messages showed no such activity

NZBGet
Currently installed: 16.2

**Comment by hugbug** [comment]
Let't take a look at your log.

**Comment by NinoFloris** [comment]
Working on it, Sublime is not too happy searching through 200Meg of logfile it seems.

Really weird ;)

**Comment by hugbug** [comment]
Click on item in history, then on Log.

**Comment by NinoFloris** [comment]
Nice! 

The log:
**admin: removed link for security reasons**

Do take note of the fact that a post process happend through manual reinsert into queue. I also marked it bad (because it said failure) before moving it to the queue, don't know if that does anything to influence it.

```
INFO    Sun Oct 25 2015 14:57:31    Game.Of.Thrones.S02E07.A.Man.Without.Honor.1080p.BluRay.FLAC.x264-EbP returned from history back to download queue
```

And this is something I did not do, but I saw this happening after I did a reload (system -> reload) of NZBGet. Could a reload influence a queued post-processing event?

```
INFO    Sun Oct 25 2015 14:43:14    Collection Game.Of.Thrones.S02E07.A.Man.Without.Honor.1080p.BluRay.FLAC.x264-EbP added to history
```

**Comment by hugbug** [comment]
The correct behavior is to execute pp-scripts on heath delete. I've just retested it and it did work. Therefore there is no a general bug.

On your machine:

> INFO   Sun Oct 25 2015 14:43:14    Collection XXX added to history
> INFO    Sun Oct 25 2015 05:22:55    Queueing XXX for post-processing
> INFO    Sun Oct 25 2015 05:22:55    Collection XXX deleted from queue
> DETAIL  Sun Oct 25 2015 05:22:55    Deleting file xxx.par2 from download queue
> ...
> WARNING Sun Oct 25 2015 05:22:54    Cancelling download and deleting XXX due to health 79.4% below critical 79.5%

As you see from message "Queueing XXX for post-processing" it wants to post-process. The next message is "Collection XXX added to history". Queueing at "05:22" and adding to history at "14:43". This is when you reloaded the program. Reloading cancelled the post-processing. For some reason the item stuck in post-processing or was waiting for post-processing.
- Wasn't post-processing paused (manually or via a scheduler task or a script)? A click on remaining time (near round button) brings the status dialog showing post-processing active/paused-status).
- Which state the item was in before reloading? ("PP-QUEUED", "PROCESSING", etc.?)
- What OS and device your use NZBGet on?
- Are you using the binaries provided on download page or install from other repository or compile yourself?

**Comment by NinoFloris** [comment]
There was another item stuck in post processing (it was 'repairing' from 5:03 until I moved it down the queue and did a reload)

The state of this and a few other items were all PP-QUEUED, all waiting on this repairing download.

OS: Windows 10, as daemon. Recent intel core i5, 16gb ram, nothing exotic.
I am using the binaries as compiling on windows is too much a nightmare for me.

**Comment by hugbug** [comment]
When you reloaded (after reordering) the current repair-item was cancelled and the other one switched to active-post-process-state. Then the program was reloaded. There is no way to continue post-processing after reloading, therefor it was moved to history.

> repairing' from 5:03

9 hours of repairing is too long for a desktop class PC. Was it stuck or was the progress moving?

Few tips:
- moving active post-processing item doesn't stop post-processing. To cancel post-processing click on the item, then on button "Actions -> Cancel post-processing". The item will be moved to history and other waiting items will start processing;
- use option ParTimeLimit.

**Comment by NinoFloris** [comment]
I know ;) wayy too long.
It was really stuck as I have succesfully completed the repair with the quickpar gui. (it still took an hour)

About stopping that stuck post-processing item
It did stop after I moved and reload it as the repair is integrated into nzbget (so no external par process) and nzbget resumes top of queue after a reload.

At least what I did worked, but good to know there is a cancel post-processing action. 

I will set a ParTimeLimit.

The other download was not switched to active post-process-state as it was still working on the stuck item (moving does nothing to influence that you said)
And I had 5 more items like this queued, all of which were instantly moved to history once there was no stuck repair (after reload) anymore.

Those logs are similar to the one I showed you.

I guess this is a perfect storm bug somewhere hidden in the codebase. Which will normally not happen, I have no issues with such an edgecase and for all I care I don't mind if you close this issue.

**Comment by hugbug** [comment]
Two issues then:
- par-repair stuck;
- no post-processing for pp-queued items after reload.

Please post the log for the item which was repairing.

I'm also renaming the topic.

**Comment by NinoFloris** [comment]
There you go

**admin: removed link for security reasons**

**Comment by hugbug** [comment]
I'll try to reproduce the issue with the reload but this will take time.

Please let me know if this happen again for you.

**Comment by hugbug** [comment]
I'm closing this issue. Please comment and reopen if the issue happens again.
