### ISSUE TITLE
Configure python path in settings

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#107]
Currently the scripts are executed as normal programs. The system reads the first line ([shebang](https://en.wikipedia.org/wiki/Shebang_%28Unix%29)) and starts the interpreter (python) passing the scripts filename as parameter.

There is an alternative way for that: we could have an option in NZBGet settings which would point to the python executable. Then NZBGet could execute the python and pass the path to the script as parameter. This has following advantages:
- scripts will not require execute-permissions. Sometimes the file system used to hold scripts doesn't allow for execute-permission. The best example is Android, where the scripts cannot be stored on sdcard, but storing them on the system partition requires root and is therefore much more troublesome.
- currently all scripts require a correct shebang or they don't start. Since the scripts come from different authors it's possible that the shebang needs to be adjusted. The usual shebang is `#!/usr/bin/env python`. Some systems don't have "/usr/bin/env"; on such systems users need to edit each script. With the new option it's necessary to set the correct path to python only once (in the program settings).
- most python scripts are written for python 2.x. If the system has python 3.x by default the user needs to install python 2.x but only one of the pythons can be used as default interpreter. With the new option the user can choose to use python 2.x for NZBGet without altering the default system python which may continue to be python 3.x

**Requirement:** provide a setting for python path and probably a similar option for bash path (again, that's of importance for Android). It can be simple settings like **PythonCmd** and **BashPath** or alternatively a more flexible solution with a new section where user can configure file extensions and corresponding interpreters (if that's not an overkill).

**Comment by hoopty** [comment]
+1 on this request.

On FreeBSD, this is needed as the default installation doesn't allow for the fact that python in in /usr/local/bin which is not in the path (along with par & archivers) for the user running nzbget.  I add the following to the nzbget init script installed to /usr/local/etc/rc.d/nzbget:

export PATH="/usr/local/bin:${PATH}"
