### ISSUE TITLE
Save nzb-log into a file (directly from web-ui)

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#108]
When option NzbLog is active (it is on by default) the program saves the download and processing log for each nzb. This log can be viewed in web-ui by clicking on queue or history item, then on button "Log".

Although the web-ui provides a nice way to look at this log, including filtering feature, sometimes the users need to share the log with developers. Currently they have to select the table in web-browser and copy/paste it into a file.

**Requirement:** We need an easy way to save processing log into a file, directly from web-ui. Probably via a button on toolbar.

**Comment by brosoft-dev** [comment]
Recently switched from SAB. Never been happier - felt the need to contribute so I whipped this up as a solution to the above:

[ajax-log-download.patch.txt](https://github.com/nzbget/nzbget/files/46463/ajax-log-download.patch.txt)

-Litch

**Comment by hugbug** [comment]
Great, thank you!
