### ISSUE TITLE
Allow adding certificate chains

### ISSUE THREAD

**Issue by CerebralXor** [nzbget/nzbget#110]
A lot of certificates issued by certification authorities don't sign with their root certificate, but sign with their  intermediate certificate. These certificates can't be used with nzbget to enable HTTPS as it doesn't allow adding the certificate chain file. I have tried concatenating the root, intermediate and server certificates into one certificate file, but that did't work.

**Comment by hugbug** [comment]
I'll try to implement this but I can't test. I could send you a compiled test version or changed source if you compile yourself. Send me a note to nzbget@gmail.com with an info which OS/CPU you run nzbget on.

**Comment by sselph** [comment]
I compiled and tested the 110-tls-cert-chain branch and running:

`openssl s_client <address>`

I got:

```
Certificate chain
 0 s:/C=US/CN=<address>/emailAddress=<email>
   i:/C=IL/O=StartCom Ltd./OU=Secure Digital Certificate Signing/CN=StartCom Class 1 Primary Intermediate Server CA
 1 s:/C=IL/O=StartCom Ltd./OU=Secure Digital Certificate Signing/CN=StartCom Class 1 Primary Intermediate Server CA
   i:/C=IL/O=StartCom Ltd./OU=Secure Digital Certificate Signing/CN=StartCom Certification Authority
```

where I used to get:

```
Certificate chain
 0 s:/C=US/CN=<address>/emailAddress=<email>
   i:/C=IL/O=StartCom Ltd./OU=Secure Digital Certificate Signing/CN=StartCom Class 1 Primary Intermediate Server CA
```

So it looks like it works!

**Comment by CerebralXor** [comment]
I have just built the 110-tls-cert-chain branch on Ubuntu 14.04.02 and can confirm that this now works using the concatenated certificate chain as the server certificate.
Thank you.
