### ISSUE TITLE
Chromebook Linux Crashes And Doesn't Start

### ISSUE THREAD

**Issue by npuchalski** [nzbget/nzbget#111]
The problem I have is when I load Steam in Linux the screen starts going back and forth to Chrome OS. Then all of the sudden I can't even start it. I continuously update crouton to get into Linux mode. Here is the code.

crosh> shell
chronos@localhost / $ sudo startxfce4
Entering /mnt/stateful_partition/crouton/chroots/precise...
/usr/bin/startxfce4: Starting X server

_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root

X.Org X Server 1.11.3
Release Date: 2011-12-16
X Protocol Version 11, Revision 0
Build Operating System: Linux 2.6.42-61-generic x86_64 Ubuntu
Current Operating System: Linux localhost 3.8.11 #1 SMP Thu Oct 15 02:29:56 PDT 2015 x86_64
Kernel command line: cros_secure console= loglevel=7 init=/sbin/init cros_secure oops=panic panic=-1 root=/dev/dm-0 rootwait ro dm_verity.error_behavior=3 dm_verity.max_bios=-1 dm_verity.dev_wait=1 dm="1 vroot none ro 1,0 2506752 verity payload=PARTUUID=fafb5367-0488-aa4b-ad08-c6462d0f62ea/PARTNROFF=1 hashtree=PARTUUID=fafb5367-0488-aa4b-ad08-c6462d0f62ea/PARTNROFF=1 hashstart=2506752 alg=sha1 root_hexdigest=04164b9d3b0b25d7b1ac9d9bbf924e48c49af65f salt=baef8d6e069d150736b4ab91f4409dc04ea62c1c16a7ddceb60bead9a34289b3" noinitrd vt.global_cursor_default=0 kern_guid=fafb5367-0488-aa4b-ad08-c6462d0f62ea add_efi_memmap boot=local noresume noswap i915.modeset=1 tpm_tis.force=1 tpm_tis.interrupts=0 nmi_watchdog=panic,lapic iTCO_vendor_support.vendorsupport=3  
Build Date: 12 February 2015  02:49:01PM
xorg-server 2:1.11.4-0ubuntu10.17 (For technical support please see http://www.ubuntu.com/support) 
Current version of pixman: 0.30.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.crouton.3.log", Time: Tue Nov 10 07:26:55 2015
(==) Using system config directory "/usr/share/X11/xorg.conf.d"

Fatal server error:
no screens found

Please consult the The X.Org Foundation support 
         at http://wiki.x.org
 for help. 
Please also check the log file at "/tmp/Xorg.crouton.3.log" for additional information.

 ddxSigGiveUp: Closing log
Server terminated with error (1). Closing log file.
/usr/bin/xinit: giving up
/usr/bin/xinit: unable to connect to X server: No such file or directory
/usr/bin/xinit: server error
Not unmounting /mnt/stateful_partition/crouton/chroots/precise as another instance is using it.

**Comment by hugbug** [comment]
Wrong project. Here is "NZBGet".
