### ISSUE TITLE
Permission issue when using custom umask

### ISSUE THREAD

**Issue by pareeohnos** [nzbget/nzbget#113]
I've run into an issue that screws up the file permissions of the queue and temp files. I'm setting up nzbget to run along side Sonarr, and as I usually do when setting up a linux box, have both apps running as a separate user, nzbget and sonarr respectively.

Obviously this then has an issue with permissions on files, so both apps are running under the same group, and I've configured nzbget to use the file permissions 0755 so the group users also have write access.

Initially this appeared to work - sonarr was able to provide nzbs, and postprocessing was then working on Sonarr as well so it seemed fine. The problem arose when it came to saving the queue.

What I've noticed now, is I am no longer able to add any nzbs to the queue, manually or via Sonarr as the queue file itself has completely the wrong permissions. I deleted the queue and all temp files as well, but it is simply recreated with the wrong permissions again straight away. For some reason, nzbget is creating the queue file with the permissions `002` so only other users can write. Nzbget is then failing to read or write to the queue and then errors on everything.

I've tried looking in the source with no luck, but I did do a `cat` on the file, and it has in fact written the queue correctly (I assume at least), it just then messes up the permissions.

I have since reverted the `umask` setting back to 1000 which obviously breaks the interaction between Sonarr and nzbget for now (which I can fix easily enough), but it resolves the issue of the queue permissions being completely wrong.

I'm running on Ubuntu server 15.10 with nzbget 16.3

**Comment by hugbug** [comment]
What value have you put into option UMask?
Are you sure you understand the concept of umask? Please read wikipedia if not certain.

**Comment by pareeohnos** [comment]
I put both `775` and `0775`, neither of which worked as expected. Doing this worked fine for the download itself when it first worked, and Sonarr was able to process the files as it had group read/write permission, however at this point the the queue file had completely the wrong permission - not even close to what I specified.

Whilst I'm not a unix pro, I do know that a umask of 775 should have resulted in the owner and group having full read/write/execute permission which it did for the downloaded files. The queue file however was given only write permission for the other accounts only. `ls -la` showed the permission as

```
--------w-
```

**Comment by hugbug** [comment]
You are confusing **file mode** and **umask**; they are not the same but rather contrary. Please read any documentation on **umask**, it will explain how umask affects permissions of created files. Just google for **umask**.

In short - set umask to 020 or 022 to achieve what you want.

**Comment by pareeohnos** [comment]
wow, TIL. Apologies for wasting your time - after your initial response I quickly googled for a umask calculator and came across http://www.webune.com/forums/umask-calculator.html which rather confusingly highlights standard file modes rather than the umask it's supposedly calculating.

Sorry again for wasting your time and thanks for pointing me in the right direction :)

**Comment by hugbug** [comment]
No apologies needed ;)
Closing the issue.
