### ISSUE TITLE
TypeError: statusData[group.Status] is undefined

### ISSUE THREAD

**Issue by greencopper** [nzbget/nzbget#114]
Cannot start nzbget, getting:

TypeError: statusData[group.Status] is undefined

**Comment by hugbug** [comment]
Very little info to be able to help.
Probably a bad install or uodate.

What nzbget version?
What OS?
How it was installed (via offiicial package or from other source)?
Was it new install or update?

**Comment by hugbug** [comment]
Closing due to lack of feedback. Feel free to comment if you have any further info.
