### ISSUE TITLE
Built From Source > Check For Updates > package-info.json Missing

### ISSUE THREAD

**Issue by war59312** [nzbget/nzbget#119]
Hey,

I prefer to build from source.

Running nzbget 16.3 on Ubuntu 14.04 Server.

If I do Settings > System > Check For Update, the following warning is logged every time:

`Web-Server: 404 Not Found, Resource: /package-info.json`

Perhaps include a default file with source?

Thanks,

Will

**Comment by hugbug** [comment]
Should not print warnings anymore.
Thanks for the suggestion.

**Comment by war59312** [comment]
Excellent, thank you. :dancers:
