### ISSUE TITLE
Download releases from GitHub

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#12]
Update links on download page to get releases from GitHub. That eliminates the 5 second wait banner from SourceForge.

**Comment by hugbug** [comment]
There is a problem: github.com supports https only. The installation manual for Linux installer starts with command

```
wget http://nzbget.net/download/nzbget-latest-bin-linux.run
```

which may not work if wget was compiled without ssl-support (http://nzbget.net/download redirects to https://github.com/...).

The problem has place on my test device.

**TODO:** make tests on all available devices to measure the problem severity.

**Comment by rcdailey** [comment]
Question: You're using the Releases feature to host your downloads, right?

**Comment by hugbug** [comment]
> Question: You're using the Releases feature to host your downloads, right?

Yes.

**Comment by hugbug** [comment]
The site mirror on http://nzbget.github.io downloads from GitHub.

**Comment by hugbug** [comment]
- Binary releases will be downloaded from **releases area**.
- For program updates (Windows and Linux packages) the releases will be downloaded via link in the info file - see #27.
- A temporary solution for already installed v15, which fetches releases from "nzbget.net/download" - the latest stable will be also hosted on web site at the old URL. In a month or two after the next stable release this will become unnecessary.
