### ISSUE TITLE
ERROR Unhandled Exception: code: 0xE06D7363, flags: 1, address: 0x779E5B68

### ISSUE THREAD

**Issue by Magikarplvl4** [nzbget/nzbget#122]
I have this problem for a while with different versions. If I download a large series such as 24. Crashes NZBget after a while. 
After i try to start NZBget again, it immediately crashes again.
Currently installed: 16.3 on windows 8.1

The log file shows the following:

Sat Dec 05 03:46:52 2015    ERROR   Cancelling hanging download 24.S04.720p.WEB-DL.DD5.1.H.264\24.S04E05.Day.4_.11_00.A.M..-.12_00.P.M..720p.WEB-DL.DD5.1.H.264.part04.rar [47/66] @ ssl-eu.astraweb.com (ssl-eu.astraweb.com)
Sat Dec 05 03:47:54 2015    WARNING File 24.S03E06.Day.3_.6_00.P.M..-.7_00.P.M..720p.WEB-DL.DD5.1.H.264.part18.rar with 33 block(s) is missing
Sat Dec 05 03:47:54 2015    WARNING File 24.S03E06.Day.3_.6_00.P.M..-.7_00.P.M..720p.WEB-DL.DD5.1.H.264.part24.rar with 33 block(s) is missing
Sat Dec 05 03:47:54 2015    WARNING File 24.S03E06.Day.3_.6_00.P.M..-.7_00.P.M..720p.WEB-DL.DD5.1.H.264.part26.rar with 33 block(s) is missing
Sat Dec 05 03:47:55 2015    WARNING File 24.S03E06.Day.3_.6_00.P.M..-.7_00.P.M..720p.WEB-DL.DD5.1.H.264.part29.rar with 33 block(s) is missing
Sat Dec 05 03:47:55 2015    WARNING File 24.S03E06.Day.3_.6_00.P.M..-.7_00.P.M..720p.WEB-DL.DD5.1.H.264.part31.rar with 2 block(s) is missing
Sat Dec 05 03:47:55 2015    ERROR   Could not read from TLS-Socket: Connection closed by remote host
Sat Dec 05 03:47:57 2015    ERROR   Cancelling hanging download 24.S04.720p.WEB-DL.DD5.1.H.264\24.S04E05.Day.4_.11_00.A.M..-.12_00.P.M..720p.WEB-DL.DD5.1.H.264.part04.rar [47/66] @ ssl-eu.astraweb.com (ssl-eu.astraweb.com)
Sat Dec 05 03:48:15 2015    ERROR   Unhandled Exception: code: 0xE06D7363, flags: 1, address: 0x779E5B68
Sat Dec 05 11:19:42 2015    WARNING Terminating par-check for (null)

**Comment by hugbug** [comment]
From the log containing only errors and warnings it's hard to guess what the program was doing.

It has crashed at 03:48 with message "ERROR Unhandled Exception: code: 0xE06D7363, flags: 1, address: 0x779E5B68"

At 11:19 you have started the program again and it printed "WARNING Terminating par-check for (null)". This second message has probably little to do with the original crash.

Please use debug version (download link in release section on GitHub), then activate all logging options (DetailTarget=log or both, etc.). When it crashes again please send me the full log (compressed) to nzbget@gmail.com.

**Comment by Magikarplvl4** [comment]
Hi,

Thanks for your reaction. I run it again i come back later with logs :+1:

**Comment by Magikarplvl4** [comment]
Hi,

I have again a crash. But my log file is about 1.5 gb. Do you have a trick to send it to you?

**Comment by hugbug** [comment]
Sure, use zip or rar ;) Then upload via dropbox or google drive.

**Comment by whitecollar17** [comment]
Done! :-1:

**Comment by Magikarplvl4** [comment]
Done :+1:

**Comment by jjulicher** [comment]
I had the same issue. It seems a dodgy queue file (in your  main dir/queue). 

I cleared this down and it restarted however, the queue won't resume as it's missing the queue files. You'll need to clear the queue and re-add the nzb files.

**Comment by Magikarplvl4** [comment]
I have this problem only when the nzbget is unpacking a file.
@hugbug  What do you need from me to debug this problem? I have one crash every week :(

**Comment by Magikarplvl4** [comment]
@hugbug What do you need from me to debug this problem? I have one crash every week :(

**Comment by hugbug** [comment]
A crash once in a week is hard to debug and the crash-log (which you've sent me) was unfortunately not very helpful (not your fault).

In v17 I'm doing a major upgrade of Windows compiler from version 2005 to 2015. This alone may help, at least the crash reporting may improve. If you can't wait for v17-testing release I could send you the current development version, but it's not too much tested yet and can have serious bugs.

Please send me a note via E-Mail if you are interested.

**Comment by Magikarplvl4** [comment]
@hugbug ,  I found out that my CPU cooler was broken.
Everytime i have a crash when nzbget was repairing or unpacking.

I think that was the problem, i let you know next week
