### ISSUE TITLE
Option for setting password when adding via URL

### ISSUE THREAD

**Issue by mrlokalhost** [nzbget/nzbget#123]
Hi, this would be a very useful feature for me in NZBGet, as I usually grab password-protected NZBs. I know the passwords, and would rather not add them to a password file, as the passwords can change for each download.

Right now I have to add the NZB, click it, open up post-processing, add the password and hit save. This could be done when adding a new file. I am not sure how to handle multiple files though... a single password input for each file added would be fine.

Something like this:
![image](https://cloud.githubusercontent.com/assets/16175976/11613318/3573eb2a-9c1d-11e5-9fbc-9337474dece8.png)

**Comment by hugbug** [comment]
Setting passwors are already possible for nzb-files, see http://forum.nzbget.net/viewtopic.php?f=10&t=2087#p13989

This doesn't work for adding via URLs though, mostly because adding via URL through web-interface is a rarely used feature anyway.

**Comment by mrlokalhost** [comment]
Thanks, I was not aware of that feature! Very useful. Would it be much work to support passwords directly when adding from URLs like when manually uploading files? I do understand this is a low priority feature, would be nice anyway. I use the "Add from URL" feature often.

**Comment by hugbug** [comment]
I have to think out a proper UI for that.

I wonder about your use case, what's the source for URLs with passwords?
The API provides an option to pass passwords with URLs. A browser plugin could use that for example.

**Comment by hugbug** [comment]
Bump. Still interested about the use case.

**Comment by hugbug** [comment]
Closing this due to lack of feedback.
If you explain me the use case of adding via URL with password, I may reconsider. Please reply in this topic.

**Comment by mrlokalhost** [comment]
I am sorry, I forgot to check my email and this thread. My apologies.

The downloads I get from a forum that password protects all uploads. They then post a link to an indexer such as nzbindex.nl and the corresponding password. I copy this link, add it to the NZBGet client and after paste the password. This could be done in a single step.

**Comment by Sledgehamma** [comment]
I would also like that feature. I have the same use case as mrlokalhost.
