### ISSUE TITLE
tvdbid and tvmazeid in rss feeds

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#132]
After disappearing of tvrage the new fields used by newznab are `tvdbid` and `tvmazeid`.

There are few places in the program which needs to be extended to support the new fields:
- as searchable fields in rss filter rules;
- as automatically generated dupekey's.

See [RSS](https://github.com/nzbget/nzbget/wiki/RSS) for details.

**Comment by Prinz23** [comment]
tvrage.com just came online again. No new data, missing data.

But since newznab added the new ids it's probably still better to add the new onces.
