### ISSUE TITLE
Add option to ignore hidden folders in the nzb incoming directory on posix systems

### ISSUE THREAD

**Issue by rgerrits** [nzbget/nzbget#141]
After switching from version 12 to version 16, NZBGet on my NAS now also scans the .AppleDouble directory for nzb files. This results in a lot of Dupe messages in the logging.
(each nzb file in the incoming folder has a file with the same name in .AppleDouble)

**Comment by rgerrits** [comment]
Thnx for implementing.

I haven't been able to test it yet (trouble installing gcc 4.9 on my nas).
Will try again after my skiing trip

Greetings Richard

**Comment by hugbug** [comment]
I can send you installer if you want. Drop me a message to nzbget@gmail.com with the info on your CPU.
