### ISSUE TITLE
Can't compile from source on Ubuntu 14.04.3 LTS

### ISSUE THREAD

**Issue by warbringer** [nzbget/nzbget#142]
fresh clone of https://github.com/nzbget/nzbget.git on a Ubuntu 14.04.3 LTS system

```
root@Griever:/opt/nzbget# uname -a
Linux Griever 3.13.0-74-generic #118-Ubuntu SMP Thu Dec 17 22:52:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
root@Griever:/opt/nzbget# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty
```

```
root@Griever:/opt/nzbget# g++ --version
g++ (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

The first ./configure runs fine. Then the make does a ./config.status --recheck and then is b0rks on the following error:

```
root@Griever:/opt/nzbget# make
cd . && /bin/bash /opt/nzbget/posix/missing --run aclocal-1.9
configure.ac:553: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2590: _AC_COMPILE_IFELSE is expanded from...
../../lib/autoconf/general.m4:2606: AC_COMPILE_IFELSE is expanded from...
configure.ac:553: the top level
 cd . && /bin/bash /opt/nzbget/posix/missing --run automake-1.9 --foreign
Useless use of /d modifier in transliteration operator at /usr/share/automake-1.9/Automake/Wrap.pm line 60.
configure.ac:553: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2590: _AC_COMPILE_IFELSE is expanded from...
../../lib/autoconf/general.m4:2606: AC_COMPILE_IFELSE is expanded from...
configure.ac:553: the top level
cd . && /bin/bash /opt/nzbget/posix/missing --run autoconf
configure.ac:553: warning: AC_LANG_CONFTEST: no AC_LANG_SOURCE call detected in body
../../lib/autoconf/lang.m4:193: AC_LANG_CONFTEST is expanded from...
../../lib/autoconf/general.m4:2590: _AC_COMPILE_IFELSE is expanded from...
../../lib/autoconf/general.m4:2606: AC_COMPILE_IFELSE is expanded from...
configure.ac:553: the top level
/bin/bash ./config.status --recheck
running CONFIG_SHELL=/bin/bash /bin/bash ./configure   --no-create --no-recursion
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for style of include used by make... GNU
checking dependency style of g++... gcc3
checking for tar... /bin/tar
checking for make... /usr/bin/make
checking whether to test compiler features... yes
./configure: line 3578: syntax error near unexpected token `11,,'
./configure: line 3578: `    AX_CXX_COMPILE_STDCXX(11,,)'
make: *** [config.status] Error 2
```

[pastebin of config.txt](http://pastebin.com/4EFSy9yR)

It doesn't make any sense since the syntax is `AX_CXX_COMPILE_STDCXX(VERSION, [ext|noext], [mandatory|optional])` which is correct. I had to build the previous few releases with CXXFLAGS="-std=c++11" due to Ubuntu 14.04.3 still being stuck with gcc 4.8.4 and the whole reason for this script was to determine is the compiler was capable of doing C++14 or not and settings the flags according to that.

Any idea on what I'm doing wrong here?

**Comment by hugbug** [comment]
When building from git you need to touch certain files to avoid running autotools (because git doesn't restore file modification dates, on which autotools relies):

```
touch aclocal.m4 configure Makefile.in config.h.in
```

This is documented in https://github.com/nzbget/nzbget/wiki/Build-the-latest-development-version.

Since your files are already screwed you need to restore them with `git reset --hard`, then touch, then configure and make.

**Comment by warbringer** [comment]
I knew it would be something that simple. In truth, I _had_ done this before but not without resetting/freshly cloning which already tainted my build environment.

Thanks for your help and for your continuing development on nzbget!

**Comment by hugbug** [comment]
I've found a way to deactivate timestamp check of autotools generated files. The `touch`-command should not ben necessary anymore. Just usual `./configure && make`.
Please test if it works for you.

**Comment by warbringer** [comment]
Did a fresh clone from git and directly ran a `./configure && make`. NZBGet compiled without incident :+1:

**Comment by hugbug** [comment]
In process of modernization of source code base I'm going to use more new C++ features (see #88).

Recently I made changes to `configure` and now it requires a compiler supporting C++14. On Linux GCC 5.1 offers full support for C++11/C++14, GCC 4.9 offers full support for C++11 and partial support for C++14.

I will do extra efforts to make sure NZBGet is compatible with GCC 4.9. GCC 4.8 however lacks some useful features.

I've written a how-to about installing GCC 4.9 on older systems - [Prerequisites for C++ compiler](https://github.com/nzbget/nzbget/wiki/Prerequisites-for-C++-compiler). A link to how-to is printed by `configure` if it detects an older compiler.

Currently you still can compile NZBGet using GCC 4.8 by suppressing configure compiler check and setting required compiler flags manually:

``` shell
CXXFLAGS="-std=c++11" ./configure --disable-cpp-check
```

However this will not work in the future, when I start using newer C++ features. You'll become errors during compiling.

It would be great if you could test the latest develop version and give me feedback whether you had any troubles following the guide for installing GCC 4.9.
