### ISSUE TITLE
New scripts are not displayed in web interface

### ISSUE THREAD

**Issue by jwillmer** [nzbget/nzbget#144]
I installed NZBget, duplicated the email script and restarted the service but it does not display a second email script.

**Comment by hugbug** [comment]
That means you've put the script in a wrong folder. See option **ScriptDir**.

**Comment by jwillmer** [comment]
@hugbug Now I have duble checked the **ScriptDir** and you are right. The folder in `C:\Program Files (x86)\NZBGet\scripts` is not the (active) script folder because the default path of **MainDir** points to ``C:\ProgramData\NZBGet\`.

I think it is confusing to have a second script folder. Space for improvement?

**Comment by hugbug** [comment]
You are right, that must be changed.
