### ISSUE TITLE
Multi-core support ( not for par repair )

### ISSUE THREAD

**Issue by AntouanK** [nzbget/nzbget#149]
I have a 200Mbit line, and a Raspberry Pi 2 running nzbget.
My issue is that it has 4 cores, but it utilizes only one when downloading. So it can barely download at 50Mbit.

Is there any chance to do the downloading work in parallel with the other cores and use the full bandwidth?

**Comment by hugbug** [comment]
Of course it uses all cores.
What makes you think it utilizes only one core?

**Comment by AntouanK** [comment]
with `top` and `uptime` I never see more than 1.00 ( or 100% ). It's usually even less. 
If it was using 4 cores it should be around 4.00 in uptime ( and 400% in top ). Is that correct?

**Comment by hugbug** [comment]
> If it was using 4 cores it should be around 4.00 in uptime ( and 400% in top ). Is that correct?

Only if CPU were a bottleneck. RPi2' weakness is the disk subsystem.

You need something with SATA. A USB->SATA adapter will not help, of course.

See how 2-core BananaPi beats 4-core RPi2:
- http://www.htpcguides.com/raspberry-pi-vs-pi-2-vs-banana-pi-pro-benchmarks/
- http://www.htpcguides.com/raspberry-pi-vs-pi-2-vs-banana-pi-usenet-benchmarks/

**Comment by AntouanK** [comment]
I never saw that 6+ MB/s figure ( I use SSL )
It maxed at 4 MB/s
So you say because I write to the SD card it's slow?
I can mount a SATA disk via USB and see if that changes something.

Didn't know that Banana Pi has a Gigabit ethernet and SATA interface... Might switch to that.

Thanks.

**Comment by hugbug** [comment]
Most sd-cards have awful perfomance, because they don't have proper controllers.

**Comment by AntouanK** [comment]
So, I did some testing yesterday.
Turns out that my SD card, is actually faster than any NTFS disk I tried over USB.

```
NTFS disk ( tried 2 different, same results )
write 03.6 MB/s
read 18.4 MB/s

ext2 disk
write 21.4 MB/s
read 24.1 MB/s

SD card 
write 20.6 MB/s
read 19.2 MB/s
```

So since I can write at my SD card with 20MB/s, how is it a bottleneck?
And even at the beginning where all the writing goes to memory, download speed is pretty low ( I can see memory usage climbing fast up to even 700MB )

**Comment by hugbug** [comment]
What's the download speed in nzbget to hard drive?

**Comment by AntouanK** [comment]
ranges from 1.5MB/s to 3MB/s.

**Comment by hugbug** [comment]
> with top and uptime I never see more than 1.00 ( or 100% ). It's usually even less. 
> If it was using 4 cores it should be around 4.00 in uptime ( and 400% in top ). Is that correct?

Wait a minute. What is "1.0" and "4.0", do you mean "load average"? It doesn't tell much about CPU usage. You should look at CPU "idle" percentage. When it's near 0.0% the CPU is fully loaded.
