### ISSUE TITLE
nzbget -R

### ISSUE THREAD

**Issue by kylerw** [nzbget/nzbget#153]
Trying to throttle using a bash script locally using:
nzbget -R 2000

Receiving: No response or invalid response (timeout, not nzbget-server or wrong nzbget-server version)

Log says:   nzbget request received on port 6789 from 127.0.0.1, but username or password invalid

Any direction?

**Comment by hugbug** [comment]
If everything is on the same computer then the instance which sends commands probably uses another config file (not the same as server use). Command "nzbget -p" prints the name of config file (one of the first lines).

**Comment by kylerw** [comment]
Thanks, I was able to find the problem. Am running in a docker container and referening a different config so I needed to symlink over the existing and it is now working. @hugbug
