### ISSUE TITLE
Option to configure news servers as optional

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#155]
Currently all news servers are expected to work. The program doesn't go to upper level servers until servers on current level were tried. Otherwise a temporary connection error (on unlimited server) could exhaust block servers of upper levels.

However for certain servers (for example free or other unreliable news servers) it would be of benefit if the program could ignore them if they don't work properly.

Also see forum topic [Skip server it it's not available](http://forum.nzbget.net/viewtopic.php?f=10&t=2340).

**Comment by Prinz23** [comment]
One thing would here be: how would be grouped servers (same level) handled here?

Since it's possible that one has multiple free accounts (that have to renewed/reactivated from time to time) at the same level grouped, normally if they work the grouping helps not to hit the others, but in case of a authentication failure this could be not be desired.

**Comment by hugbug** [comment]
**From (updated) doc:**
Marking server as optional tells NZBGet to ignore this server if a connection to this server cannot be established. Normally NZBGet doesn't try upper-level servers before all servers on current level were tried. If a connection to server fails NZBGet waits until the server becomes available (it may try others from current level at this time). This is usually what you want to avoid exhausting of (costly) upper level servers if one of main servers is temporary unavailable. However for less reliable servers you may prefer to ignore connection errors and go on with higher-level servers instead.

**Comment by hugbug** [comment]
> One thing would here be: how would be grouped servers (same level) handled here?

That's good that you asked. This is how I've implemented it:

In a case of connection errors (or authorization errors) the servers are handled independently. If one fails all others of the same group are tried nonetheless.

If however a server fails because of missing article the others of the same group are not be tried.
