### ISSUE TITLE
TypeError: statusData[group.Status] is undefined

### ISSUE THREAD

**Issue by utookmyid** [nzbget/nzbget#159]
echoing [url]https://github.com/nzbget/nzbget/issues/114[/url] get subj error, nzbget16.4 on rPi.  Installed from [url]http://www.htpcguides.com/install-latest-nzbget-on-raspberry-pi-2-and-b-raspbian/[/url].  Worked fine, then froze downloading movie.  Now with reinstall, get as far as entering paths, then subj error.  I've been trying for a couple weeks--now pulling my hair out.  Help please.

**Comment by hugbug** [comment]
Let's try this:
- stop your nzbget instance;
- install nzbget into a separate directory using official manual - https://github.com/nzbget/nzbget/wiki/Installation-on-Linux
- start it (manually, not as a service). use restore function in web-inteface but restore only news servers and categories.

Does it work?

**Comment by utookmyid** [comment]
first 2 bullets I got, then 404 error.  I'll try again tomorrow

**Comment by utookmyid** [comment]
got 'er back.  Appears it was my configtemplate that was off w/the re-install.  It all started w/a downloads.js failure...don't want to cross-post but is there something to look for?

**Comment by hugbug** [comment]
Assume this is solved. If the issue still persists please write back (and reopen).
