### ISSUE TITLE
NZBGet can't repair using pars from "VCDZ YencPowerPost v11v", but QuickPar can

### ISSUE THREAD

**Issue by RollingStar** [nzbget/nzbget#160]
(Win10 x64, NZBget 16.3)

I found an NZB made up of 500 files + 30 par2s. The last 10 files were not present on my Usenet servers at all, so I figured NZBget would repair from the pars and all would be fine. 

The NZBget log has messages like this:

> File example.part500.rar with 35 block(s) is missing

And ends with:

> Skipping unpack for example due to par-failure

However, NZBget lists the download as "repairable", implying that there are enough blocks to repair from. My hunch is that the pars are nonstandard in some way, because I tried opening them with MultiPar and that program said each par provided "0 blocks" of recovery data. I.e., the pars were useless to MultiPar.

When I opened them in QuickPar, it said I had 2001 recovery blocks from the pars, and I instructed it to repair the files. (It then crashed 2.5 hours later, but seemed to be working.) QuickPar says the pars were created using VCDZ YencPowerPost v11v. I'm not sure from Internet searches, but I think this is one of the many forks / modifications of PowerPost.

The Par2 files don't look abnormal, so maybe my theory is incorrect.

Here are the headers for two of the par2 files:

![image](https://cloud.githubusercontent.com/assets/4810902/12468198/7003e5be-bfaf-11e5-9f70-e284b5d44aa3.png)

![image](https://cloud.githubusercontent.com/assets/4810902/12468200/78746ffc-bfaf-11e5-91f7-1a0a15af902f.png)

It seems like the effect can be recreated in MultiPar 1.2.8.7 with just 3 par2 files:

![image](https://cloud.githubusercontent.com/assets/4810902/12468208/8b1a85c4-bfaf-11e5-9724-5e2576ccc38d.png)

Par2 files from other downloads in MultiPar are recognized as having some recovery blocks.

**Comment by hugbug** [comment]
Please post full log (via pastebin.com).
Click on the item in the history, then on log-button, select 1000 records to show and copy the text.

**Comment by Safihre** [comment]
Could be this: https://github.com/Parchive/par2cmdline/issues/31
Especially because you describe the hours of restoring in quickpar.

**Comment by RollingStar** [comment]
I got QuickPar to crash at approximately (exactly?) the same spot -- in 3 hours of repair (projected), it crashed around 2 hours and 20 minutes. Maybe that corresponds to creating the new files that were omitted in the download?

So maybe these PAR files really are broken and "supporting" them in NZBget is a lost cause. However, there's still the bug of NZBget telling the user the download is repairable.

[Here is the Pastebin](http://pastebin.com/mNYJCAWS). I removed several attempts at me telling NZBget to "post process again", but kept the most recent attempt. As far as I can tell each attempt is identical.

**Comment by hugbug** [comment]
> INFO    Fri Jan 22 2016 18:02:05    Collection Example added to history
> WARNING Fri Jan 22 2016 18:02:05    Skipping unpack for Example due to par-failure
> INFO    Fri Jan 22 2016 18:02:05    Repairing Example\Example
> WARNING Fri Jan 22 2016 18:02:05    File Example.part501.rar has 35 bad block(s) of total 35 block(s)

That's weird. After "Repairing..." it should print a message with repair status (success or failure) but that message is completely missing.

Please send me the nzb to nzbget@gmail.com.

**Comment by hugbug** [comment]
Par-module reports error **Too many input blocks for Reed Solomon matrix** and terminates. Whatever that means.

Status "Repairable" in NZBGet is correct. It means the download contains necessary amount of par-blocks.

I don't really understand the mathematics behind this and I doubt I can fix this. The best I can do is to improve error reporting.

Are there more such nzbs or is this the only one?

**Comment by RollingStar** [comment]
I only found the one. Maybe deleting or ignoring some of the files would reduce the number of Par2 blocks to an acceptable level? From [Google](https://www.google.com/search?q=Too+many+input+blocks+for+Reed+Solomon+matrix), it looks like the problem is in the number of blocks, and the Reed Solomon matrix doesn't have to be a concern.

[More info](https://github.com/Parchive/par2cmdline/issues/11)

I'm looking through reedsolomon.cpp and .h and it just seems like the error is related to the block count.

**Comment by hugbug** [comment]
> When I opened them in QuickPar, it said I had 2001 recovery blocks from the pars, and I instructed it to repair the files. (It then crashed 2.5 hours later, **but seemed to be working**.)

To which extent did it work?
For me QuickPar crashed after 2 hours at about 80% of repair progress (using 915 recovery blocks). Unrar was of course not able to extract files.

**Comment by RollingStar** [comment]
Yes, that matches my experience as well. When I wrote that first post, it was still working (indicated it was repairing the files), but it later crashed at 80% through the repair process.

**Comment by hugbug** [comment]
Two things changed:
- implemented extended par-logging; in this case error message **Too many input blocks for Reed Solomon matrix** is printed;
- item status is displayed as FAILURE.

Considering this issue done.

**Comment by RollingStar** [comment]
Thank you.
