### ISSUE TITLE
API Set Rate

### ISSUE THREAD

**Issue by kylerw** [nzbget/nzbget#164]
Trying to use cURL to set the rate limit and getting

`
{
"version" : "1.1",
"error" : {
"name" : "JSONRPCError",
"code" : 1,
"message" : "Invalid procedure"
}
`

command:

`curl --data "Limit=2000" http://192.168.1.188:8089/jsonrpc/rate`

**Comment by hugbug** [comment]
Google for json-rpc.

Or use developer tools in a web-browser to see what exactly is sent when the rate limit is set.
