### ISSUE TITLE
how to cross-compiling nzbget for openwrt

### ISSUE THREAD

**Issue by debiansid** [nzbget/nzbget#173]
Makefile is for very old version, is there any updated version for now?

thanks

**Comment by hugbug** [comment]
Please read the [docs](https://github.com/nzbget/nzbget/wiki), in particular "Installation on Linux", "Installation on POSIX (BSD, Linux general, etc.)" and "Cross compiling"

**Comment by debiansid** [comment]
thanks, I get it done!
