### ISSUE TITLE
Win10 x64: "Download Again" from Web Browser Deletes Folder Containing Downloaded Files

### ISSUE THREAD

**Issue by RollingStar** [nzbget/nzbget#177]
I'm on NZBGet 16.3 but can test with 16.4 if needed. This is kind of a silly issue; I understand if you don't want to fix it.
1. Download NZB successfully
2. In WebUI, go to "history" then click on the NZB.
3. "Actions" -> "download again"
4. Any files in the downloaded folder (not just the resulting files downloaded through NZBget) are deleted

I sort of expected this to happen. I didn't have any important files in the folder anyway so I didn't take any precautions.

In a perfect world, NZBGet would only delete the files it downloaded / post-processed, and only delete the folder if it was empty.

**Comment by hugbug** [comment]
NZBGet creates a separate directory for each download. How could that happen the directory contained other files? Are you sure you are not mistaken about this?

**Comment by RollingStar** [comment]
I put a file into that directory manually. I had two similar versions of files, both downloaded from Usenet, and I wanted to compare the two. This is a silly error, and I knew the risk when I was doing it. I understand if you do not want to fix this bug.

**Comment by hugbug** [comment]
Well, that's not a bug then. Keeping a track of each downloaded file during the whole history life would significantly increase the size of history. 
Let it be this way.
