### ISSUE TITLE
UI Page in iOS Chrome is Broken

### ISSUE THREAD

**Issue by punkrockjack** [nzbget/nzbget#178]
If you open the UI page in iOS Chrome, you are greeted with the message: 

"Error in http://(you_server_ip and port) (line 3)
ReferenceError: Can't find variable: fieldset"

and the page fails to auto-reload.

iOS: 9.2.1
iOS Chrome: 48.0.2564.104
nzbget: 16.4

Seems to be an error with multiple `fieldset` tags not enclosed in a `form` ([https://bugs.chromium.org/p/chromium/issues/detail?id=570095](https://bugs.chromium.org/p/chromium/issues/detail?id=570095))

**Comment by hugbug** [comment]
If you can provide a fix (in form of pull request to develop branch) I'll be happy to merge it.

**Comment by hugbug** [comment]
OK. I've put form-tags around each fieldset-tag and it seems to not break anything on desktop browsers where I've tested it.

I can't test if it helps on iOS Chrome though. If you want to test it send me a note to nzbget@gmail.com and I'll send you the modified files.

I'm not going to commit the changed version until I have a confirmation that the fix works.

**Comment by punkrockjack** [comment]
This issue is back as of version 16.4-22 :(

**Comment by hugbug** [comment]
> This issue is back as of version 16.4-22 :(

What do you mean with "back"? It was fixed in v17 and not in v16.

**Comment by punkrockjack** [comment]
Oh sorry! I totally forgot that I had test code that had the fix for this, which must've gotten wiped out when it got updated. My mistake!
