### ISSUE TITLE
Linking fails with ncurses built with separate tinfo (termlib) 

### ISSUE THREAD

**Issue by sbraz** [nzbget/nzbget#188]
On systems where ncurses was built with  `--with-termlib`, linking fails because of a missing `-ltinfo` library. Here is the result when trying to compile latest git version:

```
g++ -std=gnu++14  -g -O2  -L/usr/lib -L/usr/lib -o nzbget Connection.o TlsSocket.o WebDownloader.o FeedScript.o NzbScript.o PostScript.o QueueScript.o ScanScript.o SchedulerScript.o ScriptConfig.o FeedCoordinator.o FeedFile.o FeedFilter.o FeedInfo.o ColoredFrontend.o Frontend.o LoggableFrontend.o NCursesFrontend.o CommandLineParser.o DiskService.o Maintenance.o nzbget.o Options.o Scheduler.o StackTrace.o ArticleDownloader.o ArticleWriter.o Decoder.o NewsServer.o NntpConnection.o ServerPool.o StatMeter.o Cleanup.o DupeMatcher.o ParChecker.o ParCoordinator.o ParParser.o ParRenamer.o PrePostProcessor.o Unpack.o DiskState.o DownloadInfo.o DupeCoordinator.o HistoryCoordinator.o NzbFile.o QueueCoordinator.o QueueEditor.o Scanner.o UrlCoordinator.o BinRpc.o RemoteClient.o RemoteServer.o WebServer.o XmlRpc.o Log.o NString.o Observer.o Script.o Thread.o Service.o FileSystem.o Util.o code_revision.o commandline.o crc.o creatorpacket.o criticalpacket.o datablock.o descriptionpacket.o diskfile.o filechecksummer.o galois.o mainpacket.o md5.o par2creatorsourcefile.o par2fileformat.o par2repairer.o par2repairersourcefile.o parheaders.o recoverypacket.o reedsolomon.o verificationhashtable.o verificationpacket.o   -lz -lncurses -lpthread  -lxml2 -lssl -lcrypto
/usr/lib/gcc/x86_64-pc-linux-gnu/5.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: NCursesFrontend.o: undefined reference to symbol 'nodelay'
/lib64/libtinfo.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:920: recipe for target 'nzbget' failed
make[1]: *** [nzbget] Error 1
make[1]: Leaving directory '/tmp/nzbget'
Makefile:824: recipe for target 'all' failed
make: *** [all] Error 2
```

Gentoo has been using pkg-config to obtain the right libraries. Here is the original bug: https://bugs.gentoo.org/show_bug.cgi?id=527262 and the patch is the following:

``` diff
diff --git a/configure.ac b/configure.ac
index 96cb50b..beb5838 100644
--- a/configure.ac
+++ b/configure.ac
@@ -46,6 +46,7 @@ AC_PATH_PROG(TAR, tar, $FALSE)
 AC_PATH_PROG(MAKE, make, $FALSE)
 AC_PROG_INSTALL

+PKG_PROG_PKG_CONFIG()

 dnl
 dnl Do all tests with c++ compiler.
@@ -306,6 +307,7 @@ if test "$USECURSES" = "yes"; then
        if test "$FOUND" = "no"; then
                AC_MSG_ERROR([Couldn't find curses headers (ncurses.h or curses.h)])
        fi
+       PKG_CHECK_MODULES(ncurses,ncurses,LIBS="$LIBS $ncurses_LIBS",)
        AC_SEARCH_LIBS([refresh], [ncurses curses],, 
                AC_ERROR([Couldn't find curses library]))
 else
```

**Comment by hugbug** [comment]
I would rather prefer to avoid using pkgconfig here.

Can you please test if this helps?

``` diff
    AC_SEARCH_LIBS([refresh], [ncurses curses],, 
        AC_ERROR([Couldn't find curses library]))
+   AC_SEARCH_LIBS([nodelay], [ncurses curses tinfo],, 
+       AC_ERROR([Couldn't find curses library]))
```

**Comment by sbraz** [comment]
Yes, that works, thanks.

**Comment by SoapGentoo** [comment]
Hi @hugbug , @SoapGentoo from Gentoo here: why do you prefer sticking to `AC_SEARCH_LIBS`? In general, pkg-config should always be preferred, as you can't forsee dependency changes down the road (as was the case with tinfo).

**Comment by hugbug** [comment]
> why do you prefer sticking to AC_SEARCH_LIBS?

Mainly because not all systems have pkg-config, for example OS X and also some cross compiling toolchains, I've used in the past.

**Comment by SoapGentoo** [comment]
@hugbug: ok here's what I suggest: I'm currently fixing the upstream `AX_WITH_CURSES` macro. It's been neglected a bit and hasn't been updated for the `-ltinfo` linkage change. The idea is that this macro first tries to use `PKG_CHECK_MODULES`, and as a fallback starts looking for the flags itself (similar in spirit to what you suggested with `AC_SEARCH_LIBS`). This solves both problems: namely being forwards compatible if you have the .pc files and stuff changes in say, ncurses 7, yet still leaves a route for those unfortunate enough not to be able to depend on pkg-config. This issue is bigger than it sounds, as the whole ecosystem is currently massfailing with the ncurses 6 linkage change. In the end, you would then resort to using the `AX_WITH_CURSES` macro.

**Comment by hugbug** [comment]
That's good, thanks.

**Comment by SoapGentoo** [comment]
@hugbug Have a look at https://github.com/peti/autoconf-archive/pull/69

My fix was accepted. Now, we first try to use pkg-config to find the flags, and failing that, we try to detect them manually. `AX_WITH_CURSES` will **not** fail if pkg-config is missing.

You will have to drop the m4 file into your `m4/` dir, as this change obviously occurred after the release made a few days ago. The required flags to stick into Makefile.am are `CURSES_LIB` and `CURSES_CPPFLAGS`.

**Comment by hugbug** [comment]
@SoapGentoo: for some reason this macro doesn't work for me as expected. It always falls back to second method even though pkg-config is available.

Not an issue for me as I've decided to use `PKG_CHECK_MODULES` directly without macro.

FYI: I've also updated the search for other libraries to use pkg-config as well (gnutls, zlib).

**Comment by sbraz** [comment]
Hi @hugbug, I've tested the latest version from the develop branch and it works fine with ncurses and tinfo, I guess we can close this issue?

**Comment by hugbug** [comment]
Thanks for testing.
Closing.
