### ISSUE TITLE
GUI: Reorder Downloads queue with Drag-n-Drop

### ISSUE THREAD

**Issue by Slevin90** [nzbget/nzbget#191]
Reordering the Downloads queue with Drag&Drop would be a nice feature make reordering the queue faster.

**Comment by hugbug** [comment]
Adding "help wanted" label as I'm not going to work on this myself any time soon.

If someone is willing to contribute (thank you for this) please post here **before coding** to discuss how it should feel and look.

**Comment by guaguasi** [comment]
I'm open to putting in some time for this.

**Comment by hugbug** [comment]
@guaguasi: sorry, I missed your comment.

I'm working on drag'n'drop and will present my progress soon.

**Comment by hugbug** [comment]
This is now in development. For progress tracking please see #301.
