### ISSUE TITLE
Show number of active downloads in page title

### ISSUE THREAD

**Issue by pezz** [nzbget/nzbget#197]
G'day,

Are you able to dynamically update the page title with appending something like "(1)" to indicate the amount of active downloads?

Would be neat to see what's happening whilst not having nzbget as the active browser tab.

Cheers.

**Comment by hugbug** [comment]
I suppose you mean the number of queued downloads because active is usually only one of them.

**Comment by pezz** [comment]
Ah yes, much better.

Thanks for the clarification.

**Comment by pezz** [comment]
Well, even just an \* or something to indicate download activity would be helpful.

**Comment by pezz** [comment]
I mean, you can have 10 things in the queue, but have them paused.

**Comment by hugbug** [comment]
Something like this: `NZBGet (2)`? where 2 is the number of queued non-paused downloads.

**Comment by pezz** [comment]
Perfect.

**Comment by war59312** [comment]
Whoops. Thought I asked here as well. Guess not.

http://forum.nzbget.net/viewtopic.php?f=10&t=2438

**Comment by hugbug** [comment]
I knew there was a similar request on forum but couldn't find it quickly. Thanks for the link.

**Comment by hugbug** [comment]
Implemented #206 as a prerequisite for this issue.

Now can proceed with this one.
How configurable the page title should be: is the number of active jobs the only info you guys need or more crazy stuff like download speed or estimated time etc.? In which combinations?

**Comment by pezz** [comment]
A simple count is fine by me, dunno about other folks.

One thing I would say is that I'd prefer "(2) NZBGet" instead of the other way around as described earlier. Be good to see the count even when you have lots of browser tabs open.

Anyhow, thanks for considering this - cheers.

**Comment by war59312** [comment]
@pezz, that makes perfect sense. Agree with number first.

@hugbug, I only need the active jobs count personally. But hell.. More info the better. ;)

I'd image a drag/drop selection of options. User can arrange combination as user sees fit.

Thanks for all your hard work. You are much appreciated!
