### ISSUE TITLE
High CPU usage on QNAP NAS

### ISSUE THREAD

**Issue by DynaMight1124** [nzbget/nzbget#198]
Hi

I have a QNAP TS251 and recently upgraded from 16.4 to 17.0-r1660, but I noticed that after a day or so, NZBGet constantly uses about 50% CPU. The memory usage remains low however. As far as I'm aware, nothing has changed except me upgrading via the NZBGet GUI. 

I've tried using 'Reload' via the NZBGet GUI but it just sits there saying "Stopping all activities and reloading..." and if I refresh the page it just works as if it never did anything but still at 50% CPU usage and I dont see the process actually reloading

I've tried stopping the app via the QNAP GUI but even when stopped the NZBGet process is still running (and still at 50%).

If I restart the NAS, I get normal CPU usage but only for a day or less. 

I dont know if this is enough information to help. If its not, please let me know.

Thanks

**Comment by hugbug** [comment]
That must be fixed in current develop. If you want give it a try please send me a note to nzbget@gmail.com and I'll send you current version.

**Comment by DynaMight1124** [comment]
Thats great thank you. I've sent you an email.

**Comment by DynaMight1124** [comment]
Hi

I tested r1685 and so far its been perfect, since I upgraded. 

Thanks
