### ISSUE TITLE
Error when trying to view the "Total Downloaded" statistics

### ISSUE THREAD

**Issue by Zer0t3ch** [nzbget/nzbget#200]
```
Error in http://foo.bar:6789/status.js (line 677)

Uncaught TypeError: Cannot read property 'SizeMB' of undefined
```

[A screenshot of the error](http://i.imgur.com/ATLlUiD.png)

**Comment by hugbug** [comment]
A little bit more of background info could be helpful, such as:
- nzbget version;
- OS;
- from which source nzbget was installed: using official installer from download page, from a package repository (which one?), self-compiled?
- browser.
- have you tried other browsers or from other computers (or phones, tablets)?

**Comment by hugbug** [comment]
Since you have also posted this on forum, I've replied there.
I'm closing this issue and we'll continue discussion on forum.
[Forum topic link](http://forum.nzbget.net/viewtopic.php?f=3&t=2487&p=16284#p16284).

**Comment by Zer0t3ch** [comment]
Okay, thanks. I went ahead and replied.
