### ISSUE TITLE
Post Process Parameters are not named correctly in environment

### ISSUE THREAD

**Issue by f0ff886f** [nzbget/nzbget#204]
It seems that PP Parameters for scripts are are not passed correctly.

The Wiki says the following:

> Post-processing parameters are passed using env-vars with prefix NZBPP_.
> (https://github.com/nzbget/nzbget/wiki/Post-processing-scripts)

However, upon inspection in my failed script of the os.environ object, it seems scripts are getting the following environment naming structure (for a Foo.py script with a Bar post-process parameter defined):

`NZBPR_Foo.py:Bar`
`NZBPR_FOO_PY_BAR`

Further info and a repro script can be found on the forum:
http://forum.nzbget.net/viewtopic.php?f=3&t=2495

Offending method seems to be here:
https://github.com/nzbget/nzbget/blob/develop/daemon/extension/NzbScript.cpp#L32

**Comment by f0ff886f** [comment]
It turns out the documentation was wrong, NZBPR_ is the correct prefix and works with full variable names. I will update the documentation.

**Comment by hugbug** [comment]
Thank you for contribution.
