### ISSUE TITLE
Paginated items are still selected in lists

### ISSUE THREAD

**Issue by tennox** [nzbget/nzbget#208]
I'm not sure if this is a bug or wanted, I just noticed it, and you can decide what to do with it.
It definitely confused my, though.

I noticed that when you move selected items in a list to the bottom, and the bottom is on a different page, they stay selected.

**Consider the following:**
You select some items in a list (in my case, the active downloads list), and tell nzbget to move them to the bottom of the list. The items are now not visible anymore, because the list is long enough to be paginated.
Then you select a different item, and choose to move it to the top. Then you are confused, because not only the freshly selected item is at the top, but also all the items you chose to move to the bottom of the list.

**Solution possibilities:**
1. Unselect items after you have moved them (I find this confusing anyways, but that's a different story)
2. Unselect items that are on other pages
3. (best option imo) show some kind of indicator, that items are selected on other pages.

I think **3.** is best, because **1.** and **2.** are behaviours that are wanted this way, I suppose.

**Comment by hugbug** [comment]
That's a correct behavior. Items are not unselected after an action, so that you can perform another action.

The checkbox on table title indicates that there are selected items.

**Comment by hugbug** [comment]
Closing this. Please write back or reopen if you have further questions.
