### ISSUE TITLE
Stuck on  "awaiting additional par-files" when Downloads are paused

### ISSUE THREAD

**Issue by Mirabis** [nzbget/nzbget#214]
Hello,

I noticed that once nzbget automatically disables downloading for low disk space / unpack / etc..
the current download will hang in 'awaiting additional par-files'  as downloads are paused.

Any way we can allow that entry to continue downloading, and pause the rest?

I'll try to make a screen capture once it happens again.

**Comment by hugbug** [comment]
That's a correct designed behavior.
"Low disk space" is considered an exceptional situation, which requires user interaction. After the fixing of the problem you can resume download.

**Comment by Mirabis** [comment]
Hmm okay.. any way I can work around that?

Files are downloaded at 53 MB/s in, then a post-process (convert to mp4) takes about 1 minute. But once I queue up 100+ downloads the downloading is faster than processing. At some point it hits my 4GB disk space limit ( low space) to disable downloads and continue processing = all good.

But once a file requires a par repair, while in paused download mode - the entire thing will just hang until I manually toggle downloads on for 5 seconds ( to allow pars to come in).

Given ur above description, I could pause all outstanding downloads (toggle) and enable the global download to allow pars to come in - until the queue empties again as workaround - but I would really love a toggle to allow par downloads to come in till X space left :) [Request]

**Comment by hugbug** [comment]
Activate options **ParPauseQueue**, **UnpackPauseQueue**, **PostPauseQueue**.
The download (of next item) will be paused until current item is fully processed.

**Comment by Mirabis** [comment]
Already experimented with the first two, but cannot find 'PostPauseQueue' :( That's ScriptPauseQueue?

**Comment by hugbug** [comment]
> That's ScriptPauseQueue?

Yep.

**Comment by Mirabis** [comment]
Okay thanks, will do that for now (until the queue clears up).

Thanks for the quick support :)!

**Comment by Mirabis** [comment]
Okay, have this again..... Any way u can add an advanced option to allow par downloads to continue ?  Two disk sizes or just 30% of the current disk limit set?

I keep stumbling upon stalled downloads ( 800+ queues' .... because it's checking for PAR's... still has 20+ stuff in post-process queue, but disabled downloads and thus halts everything...

**Comment by hugbug** [comment]
Haven't you activated options Activate options ParPauseQueue, UnpackPauseQueue, ScriptPauseQueue? They should have been fixed the issue.

**Comment by Mirabis** [comment]
Activating all of them solves the disk issue, but makes downloading unnecessary slow when running on good hardware. I worked around the issue by just buying more disk space to overcome it filling up on big downloads.
