### ISSUE TITLE
Options when deleting downloads

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#224]
When implementing #205 a new option **HistoryCleanupDisk** was added. Now the behavior of deleting of already downloaded files is controlled by two options **DeleteCleanupDisk** and **HistoryCleanupDisk**. Although there are two options it is still not very clear when the already downloaded files are deleted and when not.

To make it simpler and alternative solution is proposed:
- remove options **DeleteCleanupDisk** and **HistoryCleanupDisk**;
- in the "delete downloads dialog" allow user to decide if the already downloaded files must be deleted or not. That's how the dialog may look like:
  ![screen shot 2016-05-29 at 12 19 32](https://cloud.githubusercontent.com/assets/3368402/15632577/74b84c82-2597-11e6-91b1-2b8956fc8553.png)
  
  The new dialog will explain for each option what happens with already downloaded files.
- option **HealthCheck** will be extended with new possible value **Park** now offering:
  - Delete - to move download into history and **delete** already downloaded files;
  - Park - to move download into history and **keep** already downloaded files.
- when download is removed from history (manually by user or automatically after **KeepHistory** days) the already downloaded files will be deleted (without option);

**Comment by joshuacant** [comment]
Hi, is commenting here the right way to provide feedback? Not sure. Guess I'll do it and see what happens...

These new options should also appear when managing items from the history page. In build r1756 if there's a failed download I'd like to keep history of but delete the files, I have to pause the main queue, move the download back by picking "retry failed articles". Then, from the download page, I can delete the files while keeping history.

Thanks, and apologies if this is the wrong place for this sort of feedback.

**Comment by hugbug** [comment]
Wouldn't it be strange if command Delete in history would not delete the history item?

Why don't you just Delete items from history and choose "hide" option (default)? The files are deleted amd you still can see the hidden item if necessary. This also happens automaticaly after the KeepHistory days. So the disk space is cleaned up automatically for failed downloads.

**Comment by joshuacant** [comment]
Ah, okay, then maybe the dialog box on the History tab just needs a little tweaking. Currently it says: "Selected records will be deleted from history. All files remain on disk."

Thanks for taking the time to reply to my comment, I know that your time is valuable.

**Comment by hugbug** [comment]
You are right, the text is wrong and wasn't updated for v17. I'm opening the issue to fix this.
Thank you to bring this to my attention.
