### ISSUE TITLE
Crash when deleting without history tracking (Windows)

### ISSUE THREAD

**Issue by offhub** [nzbget/nzbget#226]
NZBGet 17.0-testing builds crashes when deleting files without history tracking on Windows 7 SP1.

nzbget 16.4  = OK
17.0-testing-r1686 = Crash
17.0-testing-r1716 = Crash

**Comment by offhub** [comment]
It was an extension script related crash. After unchecking it from `EXTENSION SCRIPTS > QueueScript`, no more crashes.

[[Queue-Script] PasswordDetector v1.7](http://forum.nzbget.net/viewtopic.php?f=8&t=1391&p=12722#p12722)

**Comment by hugbug** [comment]
Fixed in 92ae10e3388b612bf035a30cd72c99a6720ff5f9.
