### ISSUE TITLE
RSS feeds

### ISSUE THREAD

**Issue by JackDandy** [nzbget/nzbget#230]
Hello,

Question: I see many "_Error parsing rss feed: Declaration has an invalid name_." and was wondering if an RSS feed containing no `<item>` nodes is the trigger for this error e.g. a RSS cart feed can have no items, **or** perhaps it is a genuine issue at the source provider for that xml request.

Idea: Perhaps the feed number # to corresponding RSS feed# could be included for each message line. An "_Error_" tagged message line often does not reference the erroneous RSS Feed#. Is the most recent message line tagged "_Warning_" the one that following "_Error_" tagged message lines lines refer to?

Idea: Like news servers, RSS feeds could include **Feed#.Active/Inactive** instead of having to delete the feed# completely.

**Comment by hugbug** [comment]
Such errors mean the indexer has returned a non valid xml-document, usually a html-page with error message.

I'll add the feed name to error message.

You can deactivate automatic feed updating by setting **FeedX.Interval** to 0; no need to delete the feed.

**Comment by JackDandy** [comment]
Idea: _Perhaps_ move **FeedX.Interval** to the top of the list

**Comment by hugbug** [comment]
> Idea: Perhaps move FeedX.Interval to the top of the list

Moved it upwards, although not to the very top since some other options are more important.
