### ISSUE TITLE
Supply whole path for saved NZB in extension environment variables

### ISSUE THREAD

**Issue by hashworks** [nzbget/nzbget#231]
Currently one only gets a few informations about the saved NZB file:

```
[NZBPP_NZBNAME] => 15ce52d0bc0dfab710fe9925c033a1ba (1)
[NZBPP_NZBFILENAME] => 15ce52d0bc0dfab710fe9925c033a1ba (1).nzb
[NZBPR__UNPACK_PASSWORD] => 543rrjflkf4.fd;
[NZBOP_NZBDIR] => /var/lib/nzbget/destination/NZBs
```

However the actual NZB path is: `/var/lib/nzbget/destination/NZBs/15ce52d0bc0dfab710fe9925c033a1ba{{543rrjflkf4.fd;}} (1).nzb.queued`

This gets even worse when I download the NZB again and change the title and the password:

```
[NZBPP_NZBNAME] => testtesttest
[NZBPP_NZBFILENAME] => 15ce52d0bc0dfab710fe9925c033a1ba (1).nzb
[NZBPR__UNPACK_PASSWORD] => testpw
```

Final path: `/var/lib/nzbget/destination/NZBs/15ce52d0bc0dfab710fe9925c033a1ba{{543rrjflkf4.fd;}} (1).nzb.2.queued`

No way one can guess this.

**Comment by hugbug** [comment]
May I ask why you need this info?

**Comment by hashworks** [comment]
@hugbug I'm in a private Newznab community. This community requires constant NZB file uploads from their members. This is easy when you have an extension for your download client that uploads all sucessfully downloaded NZB files. I had such a plugin for SABnzbd, but not for nzbget.

**Comment by hugbug** [comment]
Thanks for the explanation.
I'll add the field to pp-scripts and queue-scripts.

**Comment by nomandera** [comment]
This should probably be documented:

https://nzbget.net/post-processing-scripts
or
https://nzbget.net/queue-scripts
