### ISSUE TITLE
No umlauts in downloads title

### ISSUE THREAD

**Issue by susnux** [nzbget/nzbget#234]
As the title says since the development version (17) no umlauts are supported in the download title.
With 16.4 it works and if there were still downloads in queue then their titles are shown correctly, but changing will result in: umlaut e.g. ö is replaced with __
I have tried different browsers and different nzbget version (compiled on different machines).
The browser seems to send the correct string (post request looks good).

**Comment by hugbug** [comment]
Thanks. Fixed.

**Comment by susnux** [comment]
Thank you, will test it :+1:
