### ISSUE TITLE
"Error: 404 Not Found" Setting Speed Limit from Chrome

### ISSUE THREAD

**Issue by m1lkman** [nzbget/nzbget#237]
When I set the speed limit and press Enter it takes me to a "Error: 404 Not Found" page. Happens on chrome but not IE/Edge. I didn't test on any other browsers. I'm running 1726 testing version on Windows Server 2012 R2. Works fine if I press the Set Limit button. Thanks.

**Comment by hugbug** [comment]
Thank you for reporting this. This must be a result of #178.
Will be fixed.

**Comment by m1lkman** [comment]
Thank for all the hard work guys
