### ISSUE TITLE
Cannot set password

### ISSUE THREAD

**Issue by charliwest** [nzbget/nzbget#238]
I cannot seem to get nzbget to ask me for a password when I load the webui, I have external access which means anyone can just log in.

I have gone to settings > Security > ControlUserName and Password, set those and reloaded, nothing changes I can just load the web page, from any browser any location. 

Any ideas?

**Comment by hugbug** [comment]
Check again options ControlUserName , Password and AuthorizedIP.

Do you connect from another computer (not to localhost)?

Do you connect directly to NZBGet or via an intermediate web-server (proxy)? What computer NZBGet runs on? What computer you connect from? Try from a handy/tablet.

**Comment by charliwest** [comment]
I have just taken the settings out from username and password, reloaded, and then put them back, same thing happens.
I access it from another machine via ngnix doing ssl proxy, and I just took out the authorizedIP and now its working, thanks so much for the pointer!
