### ISSUE TITLE
Failure to start on boot due to directory not yet mounted

### ISSUE THREAD

**Issue by DominicMe** [nzbget/nzbget#239]
Since I migrated NZBGet from my headless server to desktop pc it fails to start about half the time. Config and version was identical as was the systemd file and system user.

`systemctl status nzbget`output:

```
nzbget.service - NZBGet
   Loaded: loaded (/etc/systemd/system/nzbget.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Sun 2016-07-17 19:41:55 IST; 2min 15s ago
  Process: 666 ExecStop=/usr/bin/nzbget -Q (code=exited, status=0/SUCCESS)
  Process: 646 ExecStart=/usr/bin/nzbget -D (code=exited, status=0/SUCCESS)

Jul 17 19:41:55 workstation nzbget[646]: /mnt/downloads/nzbget/nzbget.log: Permission denied
Jul 17 19:41:55 workstation nzbget[646]: /mnt/downloads/nzbget/nzbget.log: Permission denied
Jul 17 19:41:55 workstation nzbget[646]: /mnt/downloads/nzbget/nzbget.log: Permission denied
Jul 17 19:41:55 workstation nzbget[646]: nzbget.conf(70): Invalid value for option "TempDir" (/mnt/downloads/nzbget/tmp/): could not read in
Jul 17 19:41:55 workstation nzbget[646]: nzbget.conf(67): Invalid value for option "QueueDir" (/mnt/downloads/nzbget/queue/): could not read
Jul 17 19:41:55 workstation nzbget[646]: nzbget.conf(61): Invalid value for option "NzbDir" (/mnt/downloads/nzbget/nzb/): could not read inf
Jul 17 19:41:55 workstation nzbget[666]: /mnt/downloads/nzbget/nzbget.log: Permission denied
Jul 17 19:41:55 workstation nzbget[666]: /mnt/downloads/nzbget/nzbget.log: Permission denied
Jul 17 19:41:55 workstation nzbget[666]: /mnt/downloads/nzbget/nzbget.log: Permission denied
Jul 17 19:41:55 workstation systemd[1]: Started NZBGet.

```

Permission issues (I assume) are due to the fact that the mount point is owned by root. If I start it manually with `systemctl start nzbget` it works as normal. I also tried adding `${MainDir}` as value to  `RequiredDir` with no change.

Here's my systemd file that worked before:

```
[Unit]
Description=NZBGet
After=network.target

[Service]
User=nzbget
Group=nzbget
Type=forking
ExecStart=/usr/bin/nzbget -D
ExecStop=/usr/bin/nzbget -Q
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process

[Install]
WantedBy=multi-user.target
```

Why doesn't NZBGet wait for the main directory to be mounted?

**Comment by hugbug** [comment]
As description of option **RequiredDir** says only DestDir and InterDir can be waited, other directories must be available on start.

With systemd AFAIK you can specify that a service depends on a certain mount and it will not be launched until mounted.

**Comment by DominicMe** [comment]
What if my **InterDir** is set to for example **${MainDir}/nzbget/**?

So my only option is to fix this in systemd script?

**Comment by hugbug** [comment]
MainDir doesn't matter as it is not used for any purposes other than as a substitution placeholder in other options. What does matter is that QueueDir, NzbDir, TempDir, ScriptDir are available on start. If you put them on system drive you can use RequiredDir for DestDir and InterDir.
