### ISSUE TITLE
Double click handler on Windows

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#24]
When clicking on nzb-files in Windows Explorer the files must be enqueued in NZBGet.

Current solution requires users to manually add a registry entry (with command **nzbget.exe -A %1**) and works only if NZBGet is currently running.

**Comment by brosoft-dev** [comment]
The "NZBGet must be running" clause can be solved by hijacking the RemoteClient::RequestServerDownload() which (if I'm not mistaken) is where the "-A <file>" command line args end up... If InitConnection() fails to connect to the server, then we have the option to simply copy the NZB file to $(NzbDir) where it'll be picked up by Scanner:: once the daemon starts.

In the meantime (and having never seen NSI script before) - this is my attempt to give users double-click functionality for local installations... May need some work; but if you insert this somewhere in the Main section...

``` nsi
; Ask if we should add shell shortcuts
MessageBox MB_YESNO "Add NZB file actions to shell?" \
  IDNO noshell

; Are nzb files already defined? Hijack the regkey...
ReadRegStr $R3 HKCR ".nzb" ""
${If} $R3 == ""
  ; else, define our own
  StrCpy $R3 "nzbfile"
${EndIf}

; Set the file description type
WriteRegStr HKCU "$R3" "" "NZBGet File"

;; Add an action

; (only if other commands are present) this forces our command to be the default double-click action
;WriteRegStr HKCU "$R3\shell" "" "queue"
; Gives the file a default icon
WriteRegStr HKCU "$R3\DefaultIcon" "" "$INSTDIR\nzbget.exe,1"
; This defines the text you see on right-click
WriteRegStr HKCU "$R3\shell\queue" "" "Queue in NZBGet"
; This is the actual command the system runs when actioned...
WriteRegStr HKCU "$R3\shell\queue\command" "" "$\"$INSTDIR\nzbget.exe$\" -A $\"%1$\""

; Add a "Queue first in NZBGet" command (add to top of queue)
;WriteRegStr HKCU "$R3\shell\queue1st" "" "Queue first in NZBGet"
;
;WriteRegStr HKCU "$R3\shell\queue1st\command" "" "$\"$INSTDIR\nzbget.exe$\" -A T $\"%1$\""

noshell:
```

**Comment by hugbug** [comment]
Thank you for your contribution.
1. I would happily merge it if you could make a proper pull request out of it. Provided it is fully functional and you have tested it of course :wink:.
2. Instead of message box add a checkbox to finish page similar to "Create Shortcut". See http://stackoverflow.com/questions/6531115/customizing-an-exsisting-nsis-mui2-page.

#### Another improvement (not required for the first pull request)
1. If there are no running NZBGet instance, NZBGet must start as usual in application mode, similar to when started via desktop shortcut. For that you need to add switch `-app`:
   
   `nzbget.exe -app -A /path/to/nzb`
   
   And the processing of `-A` must be extended.

**Comment by wtf911** [comment]
This works if NZBGet is already running but not if it isn't, we'll still have to figure that one out. Also, I will have to add an if statement to the uninstall so it will only remove it if it was set during the install (only remove if the key value exists)

This is tried and working with Windows 10.
