### ISSUE TITLE
FR: Make reading logs fluid by giving love to the log paginator

### ISSUE THREAD

**Issue by JackDandy** [nzbget/nzbget#240]
When intensely looking through logs (due to rapid additions from a script), the last thing you want to do is fiddle with pagination and mouse movement.

Thanks.
p.s. NG v17-testing

**Comment by hugbug** [comment]
Hey, this problem can be described with words too - http://forum.nzbget.net/viewtopic.php?f=10&t=2533 :wink: 

I acknowledge the problem but don't know what a solution is. I guess I can add keyboard shortcuts but that's more like a workaround though.

You can remove the video.

**Comment by JackDandy** [comment]
I would call keyboard added value (rather than workaround) as it would make browsing the logs easier to browse in any case ;) The bonus being, as you are unsure of a solution to the pagination buttons, keys at least would suffice for now.

**Comment by hugbug** [comment]
The keyboard shortcuts will be tracked in a separate issue.

Closing this for now. If anyone have ideas on improving the pager - feel free to comment/reopen.
