### ISSUE TITLE
Win10 x64 w/ Google Chrome: Pressing [enter] key in web client speed limiter redirects to unreachable website

### ISSUE THREAD

**Issue by RollingStar** [nzbget/nzbget#241]
This only happens in Chrome (not Firefox or Internet Explorer). So maybe it's not NZBget's fault and I should report it to Chrome / Chromium devs.
1. open web client for NZBget in Google Chrome
2. Open the speed limiter
3. Activate the text box and press enter

User is redirected to a blank page, `http://[server-address]/?#`

I tested this on a localhost server on the same PC.

**Comment by hugbug** [comment]
That's a duplicate to #237, which is fixed in the latest testing.
Aren't you on the latest?

**Comment by RollingStar** [comment]
Sorry, I looked through open issues but didn't think my NZBget would be outdated.
