### ISSUE TITLE
Keyboard support in web-interface

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#242]
Currently web-interface does not have a special keyboard support other than the default one provided by browser. Moreover an extra code was written to prevent browser of processing Enter-keys (#237).

This issue is about improving keyboard support which includes:
- Enter key in dialogs should be processed as a click on the default button;
- keyboard shortcuts should be provided for navigation through paginated lists (see related #240).

**Question to all users:** do we need keyboard shortcuts for other things?

**Comment by mannibis** [comment]
I think it would be cool to have keyboard shortcuts for the items under the Actions menu in the pop-up screen for History items. Like, pressing "p" for Post-Process Again, or "d" for Download Again

**Comment by deanishe** [comment]
> Moreover an extra code was written to prevent browser of processing Enter-keys

In 17.0-testing-r1726 this is not the case for the Speed Limit dialog. It accepts an ENTER keypress but sends you to `your.server.address/?#`, which is a 404.

**Comment by hugbug** [comment]
It's in the latest testing, which is r1735.

**Comment by deanishe** [comment]
Just updated to r1735. ESC closes dialogs, ENTER has no effect.

Is that intended?

I'm running OS X 10.11.5 and tried Safari and Chrome.

**Comment by hugbug** [comment]
> Is that intended?

Yes (as long as this issue is open; Enter will work when the feature is implemented).

**Comment by deanishe** [comment]
Right you are. Thanks for the explanation!

**Comment by hugbug** [comment]
> @mannibis:
> Like, pressing "p" for Post-Process Again, or "d" for Download Again

I think one-key-shortcuts are bad. For example in Firefox direct typing means "search on page". In NZBGet we also have a search box at the top of the page. One-key-shortcuts should not work when the search box is focused.

I don't know which key combinations are best for web pages, since different OS have different standards for shortcuts. Will need to learn best practices.

Any advice will be appreciated.

**Comment by hugbug** [comment]
Article [J, K, or How to choose keyboard shortcuts for web applications](https://medium.com/@sashika/j-k-or-how-to-choose-keyboard-shortcuts-for-web-applications-a7c3b7b408ee#.havn506d5) has good tips.

Basically web-apps should use only **single letters** as shortcuts to avoid conflicts with browser shortcuts. I allowed me also usage of `Shift+Letter` and `Arrows`.

### Implemented shortcuts in NZBGet

See new wiki-page [Keyboard shortcuts](https://github.com/nzbget/nzbget/wiki/Keyboard-shortcuts) for details.
