### ISSUE TITLE
Feature request:  minimum NZB age configuration

### ISSUE THREAD

**Issue by un33k** [nzbget/nzbget#244]
Add Minimum NZB age to the page where server retention is configured.

When nzbget is configured as a downloader to other applications, things happen automatically in an automated fashion.

This means that an nzb could be sent to nzbget via API calls minutes after its publishing.

This is problematic as the rar files referenced by such nzb may still be in uploading stage.  This results in downloads with health less than 80% which is going to fail during unraring.

`Solution`: Add a field where each server can be configured with both max retention age and min availability age.

This way, if max retention is greater than server retention, then that would be a no-op.
Also if min nzb age is less than X minutes/hours/day, that would cause a `delay` as the nzb will be in deferred state till the min age requirement is reached.

This way we ensure no unnecessary download happens, so we collectively help to uncongest the `Internet` as  a whole and help the environment while at it.

I'd appreciate your thoughts on this.

**Comment by hugbug** [comment]
We already have this, the option is called **PropagationDelay** (not per server). Tip: use search box on settings page to find the option (then you can click on option name to navigate to parent section).

**Comment by un33k** [comment]
Perfect! Thx
