### ISSUE TITLE
ActivityAnimation gets re-activated

### ISSUE THREAD

**Issue by Safihre** [nzbget/nzbget#245]
v17 on Win10.
Tested with Chrome and Edge.

Disable ActivityAnimation in Web-Interface settings.
Go back to Queue that's actually downloading something: now there's no animation.
Click on a download to see it's details in the Queue, the modal comes up, close the modal.
Now the animation is back!

(Yeah I really don't like that animation :bowtie:)

**Comment by hugbug** [comment]
Good catch, thanks.

**Comment by Safihre** [comment]
Small bug that doesn't deserve it's own issue: 
I don't think you want this in the browser console on every update?
![image](https://cloud.githubusercontent.com/assets/5703454/17697581/f05a179c-63b5-11e6-94ed-788e829075c9.png)

**Comment by hugbug** [comment]
Sure not.
Thanks!
