### ISSUE TITLE
Multiple Repair Threads per Block

### ISSUE THREAD

**Issue by tifoji** [nzbget/nzbget#248]
I noticed that right now each block that needs repair is worked on by one thread. The "ParThreads" setting is therefore the number of unique blocks that can be repaired in parallel (with one thread each per bad block). Too often though there is just one or two blocks that need repair and in a multicore/multithread environment we should be able to take advantage of multiple cores working to repair that one or two blocks.

**Comment by hugbug** [comment]
Would be nice but isn't possible.

**Comment by tifoji** [comment]
That's a bummer. Please close this as not fixable in that case (maybe with explanation? :))

**Comment by hugbug** [comment]
A repair of one block is a sequential process. I don't know how to make it parallel; that's beyond my expertise. Remember, I only use par2-library written by other developer. The fact I could make it work parallel for multiple blocks is already a big accomplishment for me.

What we have now is already very good - a multithreading repair working on all CPU types. That's more than any other par2 client can offer.

Moreover, when only one block needs to be repaired that's a quick process anyway; it's not critical that we can't do it even faster (although would be nice, yes).

**Comment by tifoji** [comment]
Thank you for the explanation. I agree the current process is also very nice indeed !
