### ISSUE TITLE
ExtCleanupDisk Can't be disabled per NZB Task

### ISSUE THREAD

**Issue by DominicMe** [nzbget/nzbget#249]
As it stand NZBGet 17.0 deletes all files listed in ExtCleanupDisk option even when post-processing and unpacking is disabled for a specific nzb job. This means it is **impossible** to download any files with extensions matching ExtCleanupDisk options without removing that extensions and reloading NZBGet. This is a bug or otherwise a terrible design flaw.

The fix can be to either disable cleanup when unpacking is disabled or to add an option to disable the ExtCleanupDisk per nzb job.

**Comment by hugbug** [comment]
ExtCleanupDisk is for files you never want, for example .nfo or .sfv, regardless of unpack.

If you need more flexible cleanup you can always write a simple post-processing script like:

``` shell
#! /bin/sh
### NZBGET POST-PROCESSING SCRIPT
rm -f *nfo *.sfv
```

You can create different scripts and use them for different nzbs.

**Comment by DominicMe** [comment]
The problem is that there are always circumstances where you may need files that you normally don't, even .sfv and .nfo

Wouldn't it make sense to have an option to enable/disable ExtCleanupDisk option in the same as UnpackCleanupDisk? I mean if you don't want the files unpacked you probably don't want anything removed.  As it is stands now there is simply no way to download all original files unless you don't use ExtCleanupDisk option at all.

**Comment by hugbug** [comment]
> Wouldn't it make sense to have an option to enable/disable ExtCleanupDisk option in the same as UnpackCleanupDisk?

Don't understand what you mean.

Maybe you mean if per-nzb parameter "Unpack" is disabled then the cleanup should not be done as well? That sounds reasonable.

**Comment by DominicMe** [comment]
I mean that there should be a way to enable/disable ExtCleanupDisk parameter just like UnpackCleanupDisk. That would allow to enable or disable ExtCleanupDisk without deleting (possibly) a long list of extensions. This is a minor issue though. The solution the primary issue is like you said to disable ExtCleanupDisk when "Unpack" is disabled either per-nzb or globally.

**Comment by hugbug** [comment]
Well, it doesn't make sense for me to have an option to disable another option.

**Comment by DominicMe** [comment]
ExtCleanupDisk is more like a list of options as you can add as many as you want. It would be a convenience when you have a long list that would want to disable temporarily. Not really a big deal to be honest.
If ExtCleanupDisk is disabled when Unpack is disabled I'm happy :)
