### ISSUE TITLE
DNS lookup failure does not lead to server change

### ISSUE THREAD

**Issue by Lalufu** [nzbget/nzbget#250]
nzbget release 16.4

One server defined on level 0, one server on level 2.

DNS lookup for the name defined on level 0 failed (the DNS lookup succeeded, but returned no data):

`ERROR   Could not resolve hostname <hostname>: ErrNo 0, Success`

This did not lead to a failover to the server on level 2, instead the server on level 0 was retried indefinitely, effectively halting all progress.

**Comment by hugbug** [comment]
That's a correct behavior for v16.

In v17 you can define server as optional (option **ServerX.Optional**). Connection errors to non-optional servers never lead to increasing of current level in order to prevent exhausting of block (higher level) accounts in a case main server goes temporary off.

**Comment by Lalufu** [comment]
So if I had had a second server on level 0 it would have tried that?

**Comment by hugbug** [comment]
Yes.

**Comment by Lalufu** [comment]
OK, thanks.
