### ISSUE TITLE
Feature request: Force IPv4 or IPv6 for server

### ISSUE THREAD

**Issue by kwaaak** [nzbget/nzbget#252]
Hello,

Use case:
Have native IPv4 and a tunneled IPv6 
Some Usenet servers have both v4 and v6 addresses
Operating system defaults to IPv6
I want to force IPv4 because I don't want to send traffic through my tunnel broker unnecessarily

To do this right now I have to disable the IPv6 interface completely or enter an IPv4 address in settings.

**Comment by hugbug** [comment]
I think you can configure the IPv4 preference for your OS. On Windows see http://superuser.com/questions/436574/ipv4-vs-ipv6-priority-in-windows-7. Other OS should have a switch too.

**Comment by kwaaak** [comment]
Unfortunately not for OS X. At least I have not found anything.

**Comment by hugbug** [comment]
I've implemented this but can't test. Are you willing to make a test? Send me a note to nzbget@gmail.com.

**Comment by hugbug** [comment]
Putting this feature on hold as I don't want to ship untested code.
If some one needs the feature and is willing to test it - please contact me.

**Comment by janipewter** [comment]
Please implement this. I am happy to test. I am in the same situation as the OP...my ISP does not have native IPv6 yet and I am using Hurricane Electric IPv6 tunnel.

I have 300Mbps fibre from my ISP but the HE tunnel is nowhere near this fast. All of my usenet traffic is going via IPv6 and the download speeds are very poor.

**Comment by hugbug** [comment]
@janipewter, do you compile nzbget yourself or use an installer package from download page? In the latter case please send me a note to nzbget@gmail.com and I'll send you a version to test.

**Comment by hugbug** [comment]
Once again:
> Putting this feature on hold as I don't want to ship untested code.
If some one needs the feature and is willing to test it - please contact me via nzbget@gmail.com.

**Comment by janipewter** [comment]
I apologise for the late reply. I used Atomic-Toolkit to install NZBGet. I would be happy to compile a beta version and test in a VM. Thankfully I control my own DNS so for now I have forced resolution of my news server to only the IPv4 addresses. Obviously this is not ideal, as those IP's may change.

**Comment by hugbug** [comment]
Please test branch [252-ipv4-ipv6](https://github.com/nzbget/nzbget/tree/252-ipv4-ipv6). News servers have new option **IpVersion**.

If you want to test and can't compile send me a note to nzbget@gmail.com and I'll provide a setup package (tell me your OS and CPU).

**Comment by janipewter** [comment]
Sorry, I am new to git. How do I clone the branch? I tried **git clone https://github.com/nzbget/nzbget/tree/252-ipv4-ipv6** but it didn't work.

**Comment by hugbug** [comment]
Try this:
```
git clone https://github.com/nzbget/nzbget.git
cd nzbget
git checkout 252-ipv4-ipv6
```

**Comment by hugbug** [comment]
@janipewter, any update on this?

If you can't compile send me a note to nzbget@gmail.com and I'll provide a setup package (tell me your OS and CPU).

**Comment by janipewter** [comment]
Sorry I haven't had a chance yet, but I'll try this morning.
