### ISSUE TITLE
Free space based InterDir

### ISSUE THREAD

**Issue by dynasticorpheus** [nzbget/nzbget#257]
Performance wise it might be nice to be able to define two InterDir locations where NZBGET decides, based on available free space, which one to use. Idea behind this is to have one ram / flash drive based InterDir for smaller downloads (series) and have a second regular one. (movies etc) Especially unpacking will be much faster.

Of course it is possible already to point InterDir to a ram drive however not everybody has 64GB memory equipped in their system and would quite easily run into problems with bigger downloads.

Just an idea I have had in my mind for long time now but feel free to tell me this is just crazy :)

**Comment by hugbug** [comment]
The idea is nice.

It will make my life so much harder :fearful: though. The program must thoroughly concern about working in constrained disk space environment.

### Difficulties
1. failed downloads remain in InterDir; the RAM-disk may quickly become full if there are many failures;
2. the program knows the size of download and can decide whether it fits into RAM-InterDir but at any time that download can be overtaken by another download - which has higher priority or the user has reordered downloads. That other download may decide to use RAM-InterDir as well. Later, when the first download become active again and will continue downloading the space on the RAM-InterDir may not suffice anymore.

Therefore it's not enough to decide once, before starting downloading, where to put intermediate files. 

### Possible solutions
1. One possible solution could be to maintain a **reserved space** metric to avoid another download placing its files into RAM-InterDir if both do not fit. That has a downside that if the first download becomes inactive for a long time the RAM cannot be used for other (more prioritized) downloads.
2. Another solution would be to move inactive download from RAM-InterDir into Disk-InterDir. This however requires time and may be difficult to achieve; the program UI may freeze for a long time, which is not good.

### Program shutdown

One way or another there should be a way to move already downloaded files from RAM-InterDir into Disk-InterDir when the program quits.

### Summary

Currently the system is simple: if amount of free space goes down below option **DiskSpace** the downloading pauses and the user must take care of the situation.

The automatic correct working in constrained disk space environment requires the program to be a lot more smarter than now.

**Possible?** Probably.

**Worth the efforts?** Well, I don't know. How many users have spare 8GB or more of RAM? Probably not so many. I would see the usage of SSD for InterDir as a possible and cheaper alternative; a small 120 GB SSD costs almost nothing and unpacking will be **probably** not much worse than from RAM.

**Comment by dynasticorpheus** [comment]
@hugbug Thank you for the extensive feedback. I completely understand, and was already afraid that, the benefits do not outweigh the added complexity going forward. Let's not waste more of your time on it.
