### ISSUE TITLE
Upgraded to v17 and cannot connect to Web interface

### ISSUE THREAD

**Issue by rr0ss0rr** [nzbget/nzbget#259]
Last night I upgraded NZBGet v16.8 ? on the Mac to v17 (via the Mac 17.0 package) and now cannot connect to the Web interface.

NZBGet.log show no errors and seems to be working:
Sun Aug  7 11:28:01 2016    WARNING nzbget.conf(778): Option "DeleteCleanupDisk" is obsolete, ignored
Sun Aug  7 11:28:01 2016    WARNING nzbget.conf(1210): Option "ParCleanupQueue" is obsolete, ignored
Sun Aug  7 11:28:01 2016    INFO    nzbget 17.0 daemon-mode
Sun Aug  7 11:28:02 2016    INFO    Scheduler: setting download rate to 1800 KB/s
Sun Aug  7 11:28:02 2016    DETAIL  Downloading 

Port 6789 is not Open according to lsof

From the browser:
http://localhost:6789/#
This site can’t be reached
localhost refused to connect.

Any ideas?

I restored the v16 NZBGet.app from Time machine and now the Web interface works but I'm getting a version mismatch:

Sun Aug  7 11:56:58 2016    INFO    nzbget 16.4 daemon-mode
Sun Aug  7 11:56:58 2016    ERROR   Could not load diskstate due to file version mismatch
Sun Aug  7 11:56:59 2016    INFO    Scheduler: setting download rate to 1800 KB/s
Sun Aug  7 11:58:18 2016    DETAIL  Downloading version info
Sun Aug  7 11:58:19 2016    DETAIL  Downloading git revision info
Sun Aug  7 11:58:19 2016    DETAIL  Downloading git branch info
Sun Aug  7 11:58:19 2016    WARNING Web-Server: 404 Not Found, Resource: /package-info.json
Sun Aug  7 11:58:32 2016    INFO    Reloading...
Sun Aug  7 11:58:32 2016    INFO    nzbget 16.4 daemon-mode
Sun Aug  7 11:58:32 2016    INFO    Scheduler: setting download rate to 1800 KB/s
Sun Aug  7 11:58:32 2016    ERROR   Could not load diskstate due to file version mismatch

Thanks

**Comment by rr0ss0rr** [comment]
So .. My root directory is ~/NZBGet .. If I rm the default ~/Application Support/NZBGet and started v17 (Which created a new root directory in ~/Library/Application Support, then the Web interface worked .. If I changed my root directory within the web interface and reloaded, then the Web interface stopped working .. If I copied over my root ~/NZBGet to the default, the web interface did not work.  So I'm assuming it's something in my config that v16 was OK with and v17 is not .. but the nzbget.log is not telling me anything except for the 2 ignores .. Hope this is helpful

**Comment by hugbug** [comment]
Please post your config via pastebin.com, remove logins and passwords first.

**Comment by rr0ss0rr** [comment]
hugbug .. Here you go:  http://pastebin.com/TpZgxW7G

What's odd is in the conf I don't see the scheduler executing a download-rate change which happens twice daily in the log.

WARNING nzbget.conf(778): Option "DeleteCleanupDisk" is obsolete, ignored
WARNING nzbget.conf(1210): Option "ParCleanupQueue" is obsolete, ignored
INFO    nzbget 17.0 daemon-mode
INFO    Scheduler: setting download rate to 1800 KB/s

and I don't see how I'm pointing to the conf file located in ~/NZBGet, but yet I know the conf file worked in v16.4 .. I don't see me starting nzbget with the -c switch (I tried it and the process was killed)
/Applications/NZBGet.app/Contents/Resources/daemon/usr/local/bin/nzbget -c /Users/name/NZBGet/nzbget.conf

I'm getting too old and confused

I did run a diff on the vanilla conf and mine .. I didn't see anything glaring .. lots of comment changes .. changes for server1 to reflect my server info and NZBtoMedia scripts

**Comment by hugbug** [comment]
Config looks OK but it seems you are not sure if this is the one used by the program. When started as applicaion the config in library path is used. You can see that file via nzbget menu icon -> Show in Finder -> Config file. Try via menu Troubleshooting - > Reset to factory defaults (backup queue, config and scripts first).

After you get it working try setting the directories without exchanging of config file. Later you can restore other parts of config in web-interface -> System -> Restore settings.

Before you do anything can you please test v16.4 again (without changing anything of config)? You can download v16.4 here - https://github.com/nzbget/nzbget/releases/tag/v16.4
You can have both versions and start one or another. When you quit nzbget please check in System monitor that no process "nzbget" is running.

Now when you have both versions, can you please confirm that v16.4 starts and works without problem and v17 doesn't?

**Comment by rr0ss0rr** [comment]
16.4 and 17.0 both work with the default config file .. It is using the one from Application Support.
When you say Library path .. is that LD_LIBRARY_PATH?  Can I move the conf to ~/.nzbget ?  I think when troubleshooting the issue occured when I changed the root path (from within the web interface) and reloaded the config the web interface stopped working.  What is the best way for me to change MainDir to ~/NZBGet .. I can live with the config file being in Application Support.

Thanks

**Comment by rr0ss0rr** [comment]
ok .. Found the issue .. Some file or files in the ~/NZBGet/queue folder .. I removed all the files and everything is working fine on v17.  conf file is in Application Support and $MainDir is pointing to ~/NZBGet.  I'm glad I had the opportunity to cleanup the config file and refresh how this was setup.  I still don't understand where the real conf file was located.  I restored NZBGet.app from last week and it said it was using the conf file from Application Support with MainDir pointing to Application Support .. But that version did not reflect the post processing scripts (nzbtomedia) located at ~/NZBGet/scripts, but yet post processing was working fine,  Still confused .. but happy

Appreciate all the help .. THANKS!

**Comment by hugbug** [comment]
> When you say Library path .. is that LD_LIBRARY_PATH?

I mean the path in **Application Support**, don't remember the full path (not on Mac at the moment).

> Can I move the conf to ~/.nzbget ?

No, the config path is hardcoded in the app. But I think you could make a symlink (not an alias) from ~/.nzbget to default location in Application Support.

**Comment by rr0ss0rr** [comment]
That's exactly what I did .. Everything looks good .. Thanks again
