### ISSUE TITLE
Feature request: Start attempting repair & extract partway through download

### ISSUE THREAD

**Issue by RollingStar** [nzbget/nzbget#266]
Imagine downloading a 20-50 GB NZB. It consists of multiple split RAR files that are combined in a single download. But sometimes, there are multiple files inside the RAR. If the RAR is packed sequentially using the "store" compression level (no compression), then it should be possible to extract the file early.

On systems that can download while also RAR extracting, this should be a speed boost. The program would continue downloading future split RAR files as it extracts the files it already has from the RARs it has already downloaded.

In the simplest case, the program would do this when the RARs are perfectly healthy (no recovery PARs needed). However, if there is minimal damage to the files, only a small number of PAR blocks would need to be downloaded.

If this is too complicated to implement, or a low priority, I understand. Honestly, I would rather have #215  than this.

**Comment by hugbug** [comment]
Besides the fact that that makes the things very complex as currently the program logic separates downloading and unpacking phases, there is a technical limitation - unrar doesn't support streaming, it just quits if it can't find a next part. I've seen a [modified version of unrar](https://github.com/vlovich/stream-unrar) which can do that, but as you would expect with a fork it's not maintained (last commit 3 years ago, I'm no sure if it supports rar 5).

So, until unrar brings that functionality in some way, we don't even have to start thinking about nzbget part.

**Comment by RollingStar** [comment]
Okay, thanks for reading.
