### ISSUE TITLE
nzbget *.nzb only works on one nzb file.

### ISSUE THREAD

**Issue by antdude** [nzbget/nzbget#270]
How come it can't queue all the nzb files I entered in Linux?

Thank you in advance. :)

**Comment by hugbug** [comment]
It was never supposed to, in simple mode.
In server mode you can use all the power of queue.

**Comment by antdude** [comment]
Oh. Is server mode basically advanced mode? I am using v0.7.0 in an old PowerPC machine.

**Comment by hugbug** [comment]
Server mode is a normal way to run nzbget.
Direct mode (nzbget file.nzb) is a relict from early years.

And you should upgrade to v17, which is 10 major releases newer than your version.
What OS? For Linux you can use the installer from download page.

**Comment by antdude** [comment]
My friend's Debian PPC. I am using the package from Debian's apt-get server that he installed. I tried downloading it manually, but it didn't like the box:

./nzbget-17.0-bin-linux.run
Installer for nzbget-17.0
Verifying package...
Checking system...
This installer supports Linux kernel 2.6 or newer and the following CPU architectures:
    i686     - x86, 32 or 64 Bit
    x86_64   - x86, 64 Bit
    armel    - ARMv5/v6 (ARM9 and ARM11 families)
    armhf    - ARMv7/v8 (Cortex family)
    mipsel   - MIPS (little endian)
    mipseb   - MIPS (big endian)
    ppc6xx   - PowerPC 6xx (603e series)
    ppc500   - PowerPC e500 (core e500v1/e500v2)

Usage: sh nzbget-17.0-bin-linux.run [options]
    --help            - print this help
    --arch <cpu>      - set CPU-architecture
    --destdir <path>  - set destination directory
    --list            - list package content
    --unpack          - just unpack, skip setup
    --silent          - silent mode
    --nocheck         - skip integrity check
    --tar <args>      - run custom tar command on archive
ERROR: CPU architecture (ppc64) isn't supported by this installer.

**Comment by hugbug** [comment]
Now please use the official installer from nzbget home page, follow installation manual near download link. It **should** work on PowePC but due to lack of devices it wasn't really tested.

**Comment by antdude** [comment]
nzbget-latest-bin-linux.run still gave me the same error about ppc64. :(

**Comment by hugbug** [comment]
Ok, I see. Try paramater "--arch", may be one of two supported ppc variants will work.
Otherwise only compiling from source remains.

What exact CPU model is it BTW?

**Comment by antdude** [comment]
No idea on the model since it is not my box. I am just a regular shell user (no sudo/root) on it. Is there a way to check without asking the admin?

Since there were two PPC choices, I tried both by only running its command (haven't downloaded anything yet) after their extractions:
ppc6xx = seems to run
ppc500 = "Illegal instruction" error.

Also, is this server mode only for web GUI? No text mode hence why I use nzbget?

**Comment by hugbug** [comment]
See https://github.com/nzbget/nzbget/wiki/Console-mode

**Comment by antdude** [comment]
Thanks. I'll have to try those. Too bad we can't add with *.nzb in client side only.

**Comment by hugbug** [comment]
Closing this as resolved.
Feel free to comment or reopen if needed.
