### ISSUE TITLE
Queue stats are flushed to disk every second causing possibly unnesecairy strain on disk

### ISSUE THREAD

**Issue by aucampia** [nzbget/nzbget#272]
I noticed the `jbd2` process for my disk was using allot of IO bandwidth - and then tried to figure out what was causing it. It turns out that without `FlushQueue=no` in config file nzget is flushing (`fsync`) `nzbget/queue/stats` to disk every second. 

Is this really necessary for the queue stats to do it this often or even at all ?

**Comment by hugbug** [comment]
It's not necessary, that's why it can be disabled. If the syncing negatively affects peformance on your system and your hardware doesn't crash often you can disable the option.

On all systems I've tried there were no performance issues. On some systems tending to overheat and crash it helps to keep disk state data intact.

**Comment by aucampia** [comment]
@hugbug My question more around `fsync` specifically for the queue `stats` file - it seems like the information contained in here is not that critical for operation and loss of it is also not that big an issue as long as other queue state files are intact. I would prefer that the other queue state files are synced to disk after updates, and as far as I can tell they are not updated quite as frequently - at least not once per second. I have previously had issues where my queue state was corrupted when there was a power failure and I would prefer to avoid this from happening again as there are power outages quite often where I live.

I'm not sure if my understanding of the criticality of `queue/stats` is accurate - but if it is I think an option to just disable `fsync` for this one file would be ideal.

**Comment by hugbug** [comment]
File "stats" holds all-time downloaded volume data for news servers. I consider it important, especially when server quatas are in use.

I don't like adding another option but if that's for performance I can do that. Can we first make a test on your system with disabled sync for stats? Do you compile yourself or use installers from nzbget home page?

**Comment by aucampia** [comment]
I compile it manually. I will make some changes to disable `fsync` only for `queue/stats` and add some debugging to log when `FlushFileBuffers` is called and for what file its called and then share data with changes.

**Comment by hugbug** [comment]
Do you have any results?

**Comment by hugbug** [comment]
Closing this for now. If you have more info feel free to comment and/or reopen.
