### ISSUE TITLE
RSS attributes for nzedb

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#275]
From forum topic [Auto generate attributes for nzedb](http://forum.nzbget.net/viewtopic.php?f=10&t=2653):

> You currently auto generate attributes for use in the RSS filter for example:
> 
> <newznab:attr name="group"....
> (automatically generates attr-group)
> 
> Could you also add?
> 
> <nZEDb:attr name="group"....
> (request this to automatically generate attr-group)

**Comment by hugbug** [comment]
What about standard attributes which are written by NZBGet to special fields:

``` xml
<newznab:attr name="size" value="5423523453534" />
<newznab:attr name="imdb" value="1588173"/>
<newznab:attr name="rageid" value="33877"/>
<newznab:attr name="season" value="S03"/>
<newznab:attr name="episode" value="E09"/>
```

Do they need to be changed as well?

An example of rss feed xml would be very helpful.

**Comment by Prinz23** [comment]
I would suggest to use the api instead of the rss feed on nZEDb. Because the RSS Feed has all these attributes (only size is there) missing. The api is full newznab compatible including using newznab:attr and has all the attributes.

Send you both feeds as example per email.

**Comment by hugbug** [comment]
Thanks for samples.

Do you mean that **any** rss feed can be obtained in newznab format by replacing `rss` with `api` in the url? If that's the case I wouldn't bother supporting the second format. However if the rss feeds are unique we probably need to support it.

**Comment by Prinz23** [comment]
No the syntax is pretty different:

Example for the 2 i provided:
https://domain/api?t=tvsearch&cat=5040&apikey=<apikey>&extended=1
https://domain/rss?t=5040&dl=1&i=<usernumber>&r=<apikey>

And many only count api hits not rss hits.
