### ISSUE TITLE
Error parsing a particular rss feed (not all feeds)

### ISSUE THREAD

**Issue by JackDandy** [nzbget/nzbget#281]
Ref: **NZBGet 18.0-testing**

Hello,

First caught my eye in Messages ... **[error]** "Error parsing rss feed: Declaration has an invalid name."

I go to Settings / RSS Feeds to search which feed the error is referring to (consider adding the Feed number to the error msg e.g. "Error parsing rss feed [n]")

I click "Change" on each feed in turn until a dialog displays ... title: "Error" ... body: "Could not read feed"
the "Feed URL" ... [_edit: link removed - no use_]

The Feed URL does render as expected in a browser and used to work fine in the app.

It may be that there has been no change in the apps RSS parser and that the change is at the server side, however, this issue highlights something amiss in the parser and shows the browser is more forgiving.

**Comment by hugbug** [comment]
Nzbget uses libxml2 to parse rss. An error can only mean that the xml is invalid.
There is usually multiple messages printed to understand context of the message.

If you can send me the content of the feed I could try to debug this although I may be not able to make the invalid xml to work as the error comes from libxml and it may not have option to ignore such kind of errors.

In any case it would be better to fix the issue on server side if it indeed generates invalid xml.

**Comment by JackDandy** [comment]
Simply add the url I posted with your own api key.

**Comment by hugbug** [comment]
He-he, if I had an api key I wouldn't ask.

**Comment by JackDandy** [comment]
https://mega.nz/#!Rwc0TKSR!CImnn-8WZJgNeLZL963I7jTXn3C8B6TGYv-K-SsHWME

**Comment by JackDandy** [comment]
Ahh, [download](https://mega.nz/#!Rwc0TKSR!CImnn-8WZJgNeLZL963I7jTXn3C8B6TGYv-K-SsHWME) rss page txt.

It may be that a particular element like say a CDATA block is throwing libxml off, perfectly legal but still causing issue.  Therefore, the feed could to be "cleansed" before being passed to the parser, that way, all other sites with a similar markup would get fixed too, this would be preferable over chasing site owners who then have to chase newznab etc devs, etc. etc.

**Comment by hugbug** [comment]
The file works OK for me. 
And everything I said about libxml is irrelevant as it seems you run NZBGet on Windows where msxml is used instead.
I'll test on Windows later.

**Comment by hugbug** [comment]
It worked on Windows too.
The issue is probably that the feed you see in a browser isn't the same feed nzbget tries to parse. For example nzbget becomes an error message from indexer.

I've improved error reporting:
- feed name or id is printed on errors;
- on error the temporary file with feed content is now preserved in tmp-directory and an error message containing file path name is printed for the info purpose.

If you compile nzbget yourself please compile from develop branch. Otherwise I can send you the current develop version. Send me a note to nzbget@gmail.com.

**Comment by JackDandy** [comment]
Issue solved. Thank you. 

Note to users: check all chars in a URL for an stray tabulation that may have come in via a copy/paste.
