### ISSUE TITLE
Priority column and sorting

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#286]
A spinoff from #166 brought by @biltongza:

> manual sorting on priority. I don't think there's anything really wrong with adding another column to the queue, there's one for category why can't there be one for priority?
> 
> That said, manual sorting on status would be nice too.

**Comment by hugbug** [comment]
An issue with priority column is that it will take place. I'm not sure which alternative is better:
1. add an always visible priority column;
2. add new web-ui option to show priority as a column or as a badge;
3. show priority column automatically when the screen width is above certain threshold.

**Comment by h4wkmoon** [comment]
Imo, the queue should be sorted by priority automatically, as first Key. User can then sort by a second Key.

**Comment by hugbug** [comment]
@h4wkmoon, if you like to discuss this please open a separate issue. This one is strictly about a new column with manual sorting possibility. This issue will be closed as soon as the feature is implemented. Discussing automatic sorting here would hinder me to close current issue, that I'd like to avoid.
