### ISSUE TITLE
Hours+minutes in custom pause

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#29]
The temporary pause dialog currently accepts only minutes:
![screen shot 2015-06-22 at 22 52 48](https://cloud.githubusercontent.com/assets/3368402/8292721/70d25392-1931-11e5-8b31-9168dad81067.png)

Being able to enter hours+minutes would be helpful. Two cases:
- pause for **hh:mm**;
- pause until **hh:mm**.

Forum topic [Add Hours to Custom Pause Time](http://nzbget.net/forum/viewtopic.php?f=10&t=1666).

**Comment by teonar** [comment]
Do you want  separate entry boxes ? 
Or do you want the <b>for</b> to be a dropdown box with choices (<b>for/until</b>)

**Comment by hugbug** [comment]
I didn't though much about this yet but how about this:
- Only one edit field:
  - **30** - pause for 30 minutes;
  - **1:30** - pause for 1 hour 30 minutes;
  - **1h** - pause for one hour;
  - **=16:30** - pause until 16:30;
  - **=16h** - pause until 16:00;
  - **=16** - pause until 16:00. it doesn't make sense to pause until xx minutes, therefore the suffix "h" is optional in that case;
-  For the "pause until" we probably need to support both 24 hours and 12 hours am/pm format for user from different countries.
- The suffix "minutes" after the edit field must be removed.
- Below the edit field add a description text with few examples.
- When the user starts typing replace the description text with info about how the input was interpreted. For example, the user typed "=16", the description shows "Pause until 16:00". That's optional, if you think it's overkill :blush:.

**Comment by guaguasi** [comment]
I've done this. I'm cleaning up the code and will have a PR tomorrow.
