### ISSUE TITLE
Disable weak crypto for the webserver

### ISSUE THREAD

**Issue by m4rg4sh** [nzbget/nzbget#295]
If you enable the secure port for the web-gui the default crypto settings are outdated and insecure.
[This SSL/TLS test](https://www.htbridge.com/ssl) gives the server the grade F.

Please disable SSLv3, RC4, DES, and maybe even 3DES. All modern browsers will still be able to connect but the security will be massively improved.

Alternatively an option to configure these settings from the gui would be welcome.

**Comment by hugbug** [comment]
I think all **modern browsers** already negotiate secure ciphers and protocols. Disabling of less secure ones will not change a thing for them but may bring troubles when connecting from older devices.

**Comment by m4rg4sh** [comment]
An attacker can manipulate the handshake and force a downgrade to SSLv3 [(POODLE)](https://www.openssl.org/~bodo/ssl-poodle.pdf)
This is why it should at least be possible to manually disable SSLv3 in the settings.
