### ISSUE TITLE
Speed Limit icon incorrectly displayed when a server is disabled

### ISSUE THREAD

**Issue by hlarsen** [nzbget/nzbget#296]
the problem is in redrawInfo() - after limit it set from status.DownloadLimit, there is some additional processing for each server. if a server is disabled, limit is flipped and we get the truck icon even if we don't have a speed limit. moving the icon change above (or removing) the additional processing fixes the issue; i didn't send a PR because i wasn't sure if the additional processing for each server is needed here/elsewhere.

repro:
- set up multiple servers
- server 1 disabled
- server 2 and 3 enabled

with no speed limit set, the truck icon is displayed rather than the plane icon.

**Comment by hugbug** [comment]
That's a correct behavior. Disabled servers are considered as a limit and therefore the truck icon is shown.

**Comment by hlarsen** [comment]
Got it - I'll just delete the server then.

Thanks.
