### ISSUE TITLE
ERROR - Binding socket failed for 0.0.0.0: ErrNo 0

### ISSUE THREAD

**Issue by legoblokje** [nzbget/nzbget#297]
Clean install (stable and testing versions) on Windows 10 64bit (version 1607) produces the following error

> ERROR   Binding socket failed for 0.0.0.0: ErrNo 0

I attached my config file (which is reset to default).
[nzbget.txt](https://github.com/nzbget/nzbget/files/556830/nzbget.txt)

**Comment by hugbug** [comment]
The message usually means the port is in use. Try a different port for option ControlPort. Check in task manager if there are no other instances of nzbget running.

**Comment by hugbug** [comment]
Closing due to lack of feedback.

**Comment by adairjim** [comment]
For future troubleshooting - this error will come up if you specify a control IP which doesn't match the IP of the machine nzbget is running on.
