### ISSUE TITLE
 While using updater, I get JSON error

### ISSUE THREAD

**Issue by billbo01028** [nzbget/nzbget#302]
Error in http://192.168.1.146:6789/config.js (line 2657)  SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

**Comment by hugbug** [comment]
Anything on the messages tab or in the log?
What's your OS, device and nzbget version?
Was nzbget installed using an installer from nzbget download page?

**Comment by billbo01028** [comment]
-this has been working for the past year
-see attached text files for messages and the log(the log was >5GB, so I ran a split command and I'll give you the last file
[xaf_nzbget.log.txt](https://github.com/nzbget/nzbget/files/568912/xaf_nzbget.log.txt)
[nzbget_Messages.txt](https://github.com/nzbget/nzbget/files/568913/nzbget_Messages.txt)

 to look at)
-original install was a git pull from the repo.  since then been using the webGUI to update
-about a month ago I went from stable release 17 to test release  18.0-testing-r1820 with no issues
-my recent change was upgrade from fedora 23 to fedora 25.  after this upgrade, the errors started coming
- device is an old gateway PC that I resurrected and replaced with new hard drives, etc.  

Thank you for any and all help you can provide.

**Comment by hugbug** [comment]
You probably means "install from git releases" because if you would install with "git pull from the repo" you wouldn't be able to update via webui.

The messages are filled with error about disk permission. Can you fix this first?

**Comment by billbo01028** [comment]
these are new errors.  first time I have seen them like this...

error   Thu Nov 03 2016 19:21:37    Error saving diskstate: Could not create file /data/apps/nzbget/downloads/queue/feeds.new: Permission denied
error   Thu Nov 03 2016 19:21:37    Error saving diskstate: Could not create file /data/apps/nzbget/downloads/queue/history.new: Permission denied

nzbget runs as nzbget here are the permissions on those files:

[root@lazarus downloads]# ls -ll
total 88
drwxr-xr-x 5 nzbget media    59 Jul 15 11:22 completed
drwxr-xr-x 2 nzbget media     6 Nov  2 20:38 intermediate
drwxr-xr-x 2 nzbget media 98304 Nov  3 19:23 nzb
---------- 1 nzbget media     4 Nov  3 19:04 nzbget.lock
---------- 1 nzbget media    68 Nov  3 08:31 nzbget.log
drw-rw-rw- 2 nzbget media    46 Nov  2 20:41 queue
drwxr-xr-x 3 nzbget media    28 Nov  3 19:23 tmp
[root@lazarus downloads]# cd queue/
[root@lazarus queue]# ls
feeds  history
[root@lazarus queue]# ls -ll
total 776
-rw-rw-rw- 1 nzbget media   1893 Nov  2 11:22 feeds
-rw-rw-rw- 1 nzbget media 787113 Nov  2 12:43 history
[root@lazarus queue]#

Kind of wondering why the permissions seem to be off.  should I give them 777?  not a big fan of that but....

**Comment by hugbug** [comment]
The directories must have x permission for list of files to be possible to read. Give the "queue" and "tmp" directories the same permissions as "completed" has.

**Comment by billbo01028** [comment]
seems to be working after resetting the permissions.... the OS upgrade must have changed something in the permissions.
