### ISSUE TITLE
Reduce RSS feed retries during times of site trouble

### ISSUE THREAD

**Issue by JackDandy** [nzbget/nzbget#306]
I can only guess that this feature applies to all error types, however, I just observed it in the context of the RSS feed reader with the following temporary error... "503 Service Temporarily Unavailable".

The feed is retried several times a minutes in fairly rapid succession and ng doesn't back away.  It would be better to stop this after a number of fails and simply resume normal activity at the next interval - if that too fails a number times, rinse repeat.

**Comment by hugbug** [comment]
This is controlled by options **Retries** and **RetryInterval**. Since these options are also used for article downloading there were a requests to provide separate configuration options for URL downloads (rss and nzb fetches).

**Comment by JackDandy** [comment]
Great. thanks.

**Comment by hugbug** [comment]
Reopening for now. Will close when the options are implemented.
