### ISSUE TITLE
[enhancement] option to skip health check

### ISSUE THREAD

**Issue by orbisvicis** [nzbget/nzbget#307]
If I add an NZB and two dupes, or a single NZB with the dupes merged, it is possible the download will be deleted for health reasons even though par2 recovery would succeed across the duplicates.

**Comment by hugbug** [comment]
It will not be deleted if **ParScan=dupe** which is a prerequisite for automatic repair across downloads.

**Comment by orbisvicis** [comment]
I am running nzbget 17.0.1735-1.20160726.git.dcf0318 with these options:

```
ParScan=dupe
HealthCheck=delete
```

When recovery fails, the download is parked and the dupe is queued. When the health check fails, however, the download is deleted and the dupe is queued.

However, I do want downloads without duplicates that fail the health check to be deleted.

**Comment by hugbug** [comment]
For automatic par repair using duplicates:

```
ParScan=dupe
HealthCheck=park
```

> However, I do want downloads without duplicates that fail the health check to be deleted.

That's a problem. Duplicates may be added to queue later (for example via rss), therefore we must keep the data of failed download.

Do you really need to delete the files immediately? The files will be deleted when the history item becomes hidden after `KeepHistory`days.

**Comment by hugbug** [comment]
> If I add ... a **single NZB with the dupes merged**, it is possible the download will be deleted for health reasons even though par2 recovery would succeed across the duplicates.

This is not possible. If health check fails the repair will fail too.

**Comment by orbisvicis** [comment]
I think the difference between how NZBGet works and what I'd prefer is a matter of disk space.

This is how NZBGet currently work with automation (sonarr,couchpotato), duplicate par recovery, and park on health-check:
1. automation-app sends nzb
2. nzb fails health check, and is moved to history with "park" status (I think, don't use this feature). Already downloaded files are kept, but additional files aren't downloaded.
3. automation-app connects to check status, and without nzb-success deletes nzb
4. nzb files are removed from disk
5. goto (1) - automation-app sends duplicate nzb

This is how NZBGet should work with automation, duplicate par recovery, and park on health-check:
1. automation-app sends nzb
2. nzb fails health check... (same as above)
3. automation-app connects to check status, and without nzb-success, drops off a duplicate - goto (1)
   
   with success:
- With enough duplicates, par recovery eventually succeeds
- The duplicate, parked files are deleted. I'm not sure if NZBGet does this, or this is a responsibility for the automation-app
  
  with failure:
- No more duplicates, par recovery fails
- Either the automation-app connects and decides to delete the parked files, or they are eventually deleted after `KeepHistory` (default: 30) days (see below for logic behind this).

Now if an automation-app handles duplicate status, I don't mind setting `HealthCheck=park`, for various reasons:
1. I tell the automation-app I'm no longer interested in a particular duplicate group, and all duplicate entries will be erased from disk. I don't have to wait `KeepHistory` days.
2. Automation is usually for new content/posts, so like RSS it makes sense to park possibly later duplicates.
3. Automation can be arbitrarily smart. If content is very old and chances of upcoming duplicates being posted is very slim, then the automation-app can immediately delete all existing duplicates.

Currently no automation supports duplicate par recovery. That's OK even when enabling park on health-check because the duplicates will be automatically deleted.

Now if I'm manually adding nzbs, I would prefer full control over the `HealthCheck` setting. (The way I do this now is through the automation-app. Then I temporarily stop the automation-app to prevent it from deleting failed downloads):
1. I prefer disabling the health-check ("none"), to download as many data blocks as possible for the recovery. The "park" setting would terminate the download too early.
2. Manual downloads are a one-shot type of thing unlike automation such as RSS, sonarr or couchpotato. So manual downloads shouldn't expect newer duplicate entries. Once all duplicate entries have been downloaded and par recovery has run, it would be convenient for NZBGet to automatically delete the input files.

Unfortunately, it is too early to determine which `HealthCheck` setting I should use. No automation-app supports duplicates and duplicate par2 recovery. I think it might be useful to allow a per-download `HealthCheck`, and expose it via the web interface (when adding files) and rpc (scripts/automation). Fine-grained control could help curb ballooning disk usage. 

I would also like a way to let NZBGet know "Don't expect any additional duplicates. If the par recovery fails, delete all the duplicate entries from disk"

**Comment by orbisvicis** [comment]
Also I'm pretty sure `nzbget.conf` doesn't mention that failed downloads will be deleted after `KeepHistory` days, so that should be fixed.

**Comment by hugbug** [comment]
> automation-app connects to check status, and without nzb-success deletes nzb

I guess you are talking about Sonarr. It shouldn't mess with nzbget history. Luckily it has an option to disable that behavior, which shouldn't be enabled by default in the first place.

> Also I'm pretty sure nzbget.conf doesn't mention that failed downloads will be deleted after KeepHistory days, so that should be fixed.

Indeed.

May be you could try **HealthCheck=park, ParScan=dupe** and see how it fits. Then we can see if an improvement is needed.

**Comment by orbisvicis** [comment]
I don't think this is a good idea. On average, there'll be about 5 downloads before success. Once one succeeds, Sonarr doesn't inform couchpotato that the other 4 are no longer required, so they'll stay on disk for `KeepHistory` days. Lets say, per week, sonarr queues 30 downloads, and each ranges from 1-3GB for an average of 2GB. In 30 days (and this applies to a rolling average too), nzbget will accumulate 1TB of useless data:

```
4*2*30*(30/7) = 1028.57
```

This is in addition to the accumulating library content, and to be honest, is 1TB I can't afford.

**Comment by orbisvicis** [comment]
That's if I prevent Sonarr from messing with nzbget history. If I don't, then using **HealthCheck=park** doesn't change anything with Sonarr. It'll fix the first half of my feature request, but what if I want to use **HealthCheck=None** for certain manually-added duplicates?

Edit: BTW, what is this Sonarr setting?

**Comment by hugbug** [comment]
>  On average, there'll be about 5 downloads before success. 

I wonder where this comes from. If you automate the first download usually succeeds.

> In 30 days (and this applies to a rolling average too), nzbget will accumulate 1TB 

Just like you could set KeepHistory to 365 if you would have spare 12TB you can set it to 5 too, right? :)
For older stuff most failed downloads are missing completely and therefore don't consume space.

> what if I want to use HealthCheck=None for certain manually-added duplicates.

If you have HealthCheck=park and ParScan=dupe you don't need HealthCheck=none.

> With enough duplicates, par recovery eventually succeeds
> The duplicate, parked files are deleted. I'm not sure if NZBGet does this, or this is a responsibility for the automation-app

To clarify. Term **duplicate** in regard to nzbget means the same title (same movie or same episode), it can be the same video file but can also be a different one with different quality. After successful download nzbget doesn't delete other (failed or waiting) duplicates because there is a chance the succeeded one isn't good enough. It may have bad video quality or wrong audio etc. If user decides the download is OK he can **mark item as good** and then all other duplicates are deleted. This mark-command is of course available via api too.

**Comment by hugbug** [comment]
> what is this Sonarr setting?

[Probably that one](https://forums.sonarr.tv/uploads/default/original/2X/c/cf59886212117619fcd6813532b9f4f881f9c526.png).

**Comment by orbisvicis** [comment]
> I wonder where this comes from. If you automate the first download usually succeeds.

There've been some repairs lately, with a lot of overnight downtime. Maybe this gives my the impression of more failures than typical?

> Just like you could set KeepHistory to 365 if you would have spare 12TB you can set it to 5 too, right? :)
> For older stuff most failed downloads are missing completely and therefore don't consume space.

Fodder for thought, perhaps that setting should be split: `KeepHistory` for metadata only and `KeepHistoryFiles` for data.

> If you have HealthCheck=park and ParScan=dupe you don't need HealthCheck=none.

Does `HealthCheck=park` behave differently with/without `ParScan=dupe`? From what I understand, `park` won't download data once the health-check fails. For duplicate par recovery wouldn't "none" be more appropriate; it would download as many data blocks as possible, skipping the health-check?

> To clarify. Term duplicate in regard to nzbget means the same title (same movie or same episode), it can be the same video file but can also be a different one with different quality. After successful download nzbget doesn't delete other (failed or waiting) duplicates because there is a chance the succeeded one isn't good enough. It may have bad video quality or wrong audio etc.

If NZBGet determines the duplicates share the same video file, isn't that a case in which it could automatically delete the other duplicates?

Also would be nice if Sonarr could expose NZBGet's **mark item as good** setting.

**Comment by orbisvicis** [comment]
OK, I'll try:
- NZBGet: **HealthCheck=park**, **ParScan=dupe**, **KeepHistory=5**
- Sonarr: **Download-Client -> Failed-Download-Handling -> Remove -> No** (this is the setting you meant, I think).

**Comment by hugbug** [comment]
Thanks for trying. Please let me know how it works for you. If you'll still need granular control over HealthCheck we'll see how to add it best.

**Comment by orbisvicis** [comment]
Question about some comments in `nzbget.conf`. This

> NOTE: When option <ParScan> is set to "Dupe" the park-action is performed
> only if article completion is below 10% (empirical threshold). This is to
> improve efficiency of dupe par scan mode.

Is it supposed to read:

> NOTE: When option <ParScan> is set to "Dupe" the **delete-action** is performed
> only if article completion is below 10% (empirical threshold). This is to
> improve efficiency of dupe par scan mode.

or:

> NOTE: When option <ParScan> is set to "Dupe" the park-action is performed
> only if article completion is **above** 10% (empirical threshold). This is to
> improve efficiency of dupe par scan mode.

**Comment by hugbug** [comment]
If you click on an item in download queue there are two important statistics - "Health (critical/current)" and "Articles (total/completion)".

When during download "Current health" drops below "Critical health" that means the download isn't repairable and the HealthCheck-action is peformed (delete, park or pause).

For dupe par-scan this is however not good because at that time usually only small part of download was downloaded. So for dupe par-scan you should disable health check. That's however stupid because the fully missing downloads will need to go to the end taking a lot of time. Therefore the folowing compromise: with "HealthCheck=park, ParScan=dupe" the health-action (park) is peformed if almost all articles (tried so far) are missing (more strictly - if completion is below 10%). As long as completion is above 10% the downloading continues, regardless of health.

As a result the fully missing downloads are deleted (parked) quickly but downloads which have usable data go to the end to provide repair blocks for other duplicates.

**Comment by orbisvicis** [comment]
These settings are working very well, I'll see how it is after five days too. However one question:

> If user decides the download is OK he can mark item as good and then all other duplicates are deleted.

When I marked a successful duplicate as **good**, the previous failed duplicate wasn't removed - files on-disk remained, and history metadata wasn't changed.

Edit: but in situations of expar:donor/expar:recipient, some (not all) files are deleted from the donor, which is nice. And I guess marking as **good** only deletes yet-to-be downloaded dupes (with **dupe** status) from history.

**Comment by hugbug** [comment]
Currently **Mark as good** deletes (hides) only items with status **dupe** (which were not tried). Failed or other successful duplicates are not touched.

Deleting failed items along with downloaded files makes sense, right?

**Comment by orbisvicis** [comment]
> Deleting failed items along with downloaded files makes sense, right?

I'm pretty sure. In my case it does. For nzbget's rss users (not me), or when duplicates represent different qualities, it should as well.

**Comment by hugbug** [comment]
BTW, do you really have items with status **expar**?
I never hade a real case where dupe par-scan helped but I download very little myself.

**Comment by hugbug** [comment]
> Fodder for thought, perhaps that setting should be split: KeepHistory for metadata only and KeepHistoryFiles for data.

I'm not sure how useful are items without files (with deleted files).

One could write a scheduler script which would periodically check history and delete files of failed items after x days.

> If NZBGet determines the duplicates share the same video file, isn't that a case in which it could automatically delete the other duplicates?

The "same video"-check isn't very reliable. It's good enough for the dupe par scan purpose.

> Also would be nice if Sonarr could expose NZBGet's mark item as good setting.

The mark-commands are available via api.

**Comment by orbisvicis** [comment]
> BTW, do you really have items with status expar?

Often with couchpotato, and even more frequently since enabling **HealthCheck=park**. For example, since yesterday two releases have been repaired using duplicate data. Because file sizes are smaller and so many alternative releases are available, it doesn't happen as often for Sonarr. Though iirc one rare episode required blocks across three duplicates to repair - though I did this manually since I hadn't enabled the correct nzbget settings.

It would be nice if nzbget were to download from higher-tier servers with block accounts only the blocks missing across all duplicates. Not sure this is possible (ie, when not reposts). Would also take more time and download more data.

> I'm not sure how useful are items without files (with deleted files).

Yes I agree with that. One thing I used to miss from hidden and failed history items was the failure reason: "par" or "health XX%". But with the new nzbget configuration you suggested it probably isn't necessary.

**Comment by hugbug** [comment]
How it's going? Can we close the issue or there are todos for me?

**Comment by orbisvicis** [comment]
Just this, but I've opened a new issue:

> Also I'm pretty sure nzbget.conf doesn't mention that failed downloads will be deleted after KeepHistory days, so that should be fixed.

For the record, the new configuration really works really well :)

**Comment by hugbug** [comment]
>For the record, the new configuration really works really well :)

I'm interested in any statistics of dupe repair usefulness.
Filter `-exparstatus:none` (alternatively `exparstatus:recipient | exparstatus:donor`) on history tab should show all relevant records (but not hidden). Do you have many?
