### ISSUE TITLE
Connections limit temporarily exceeded

### ISSUE THREAD

**Issue by clbr** [nzbget/nzbget#314]
Using nzbget 17.1 on Linux. I use a host that allows 5 connections, xsusenet. When setting server1.connections=5 in the config file, after 10-20min of downloading there starts to be a stream of errors about too many connections. It never happens when setting connections=4.

Is it possible nzbget opens a new connection before the old one has been fully terminated, causing there to temporarily be 6 connections? Or perhaps the server only clears out old connections every N seconds, and nzbget opens new ones too fast.

**Comment by hugbug** [comment]
NZBGet opens connections and use them until the whole queue is completed.

In a case a connection hangs or interrupts nzbget reconnects. It is possible that in such case the server still haven't reset connection count for the failed connection. To validate this check the nzbget log. You must have a connection failure message before the "Connections limit temporarily exceeded" message.

**Comment by clbr** [comment]
I had an overnight download last night, and it didn't happen. Will report when I get it in the logs.

**Comment by hugbug** [comment]
Closing this as solved.
