### ISSUE TITLE
[Enhancement] Add nvenc-friendly option to PostStrategy

### ISSUE THREAD

**Issue by Collisionc** [nzbget/nzbget#316]
Referencing https://github.com/nzbget/nzbget/issues/291

Nvidia's consumer level GPUs are limited to 2 encoding sessions, so it would be nice if PostStrategy had an option for a limit of 2 post-processing jobs with an additional exclusive slot for par jobs, rather than 3 multi-purpose slots.  

Thanks!

**Comment by hugbug** [comment]
I think you can use **agressive** and if you need to limit the number of instances of certain specific jobs the transcoding script should do that on it's own.

**Comment by Collisionc** [comment]
The script I use (sickbeard_mp4_automator) doesn't have a way to limit instances that I know of. I guess I could add it, but it'd be significantly easier to just edit prepostprocessor::canrunmorejobs and compile. 

no big deal either way. Thanks for the great program!

**Comment by hugbug** [comment]
I understand it's easier to change in nzbget but I don't want end up adding new option values for each use case. I hope you understand.

**Comment by Collisionc** [comment]
I understand, it does make it much more difficult for new users. :) I'll probably fork this and make a nvenc-friendly version of it sometime, consider this closed.
