### ISSUE TITLE
Unified extension scripts settings

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#319]
## Idea
Currently we have:
- option **PostScript**
- option **QueueScript**
- option **ScanScript**
- option **ServiceScript** (see #318)
- option **FeedScript**
- option **CategoryX.PostScript**
- option **FeedX.FeedScript**
- option **TaskX.Command**=*Script* with **TaskX.Param**

All these script settings palette is confusing. What I want to do is to reduce the amount of settings, ideally to one - let's call it **Extensions**. Well, that'd be too good, we still need more than one:
- option **Extensions**: combines "PostScript", "QueueScript", "ScanScript", "FeedScript" and the new "ServiceScript";
- option **CategoryX.Extensions** for per-category overrides;
- option **FeedX.Extensions** for per-feed overrides;
- scheduler options **TaskX.Command** and **TaskX.Param** remain unchanged.

That's almost one setting, if we don't count overrides and scheduler.

So, now to install a new script the user have to select it in option "Extensions"; no need to think about which option to use, regardless of script kind, be it a post-processing script, scan-script or queue-script. Only script developers need to know differences.

![extensions](https://cloud.githubusercontent.com/assets/3368402/21176871/f54d3ac2-c1e8-11e6-975c-d4e99137a024.png)

Upcoming service-scripts (#318) will not be selectable per-nzb and will rather run globally. Does it work well with the general concept of option "Extensions" providing **defaults** for new downloads? I hope to cover this with the note from description:

> Certain extensions work globally for the whole program instead of per-nzb basis. Such extensions are activated once and cannot be overriden per category or per nzb.

## About scan-scripts
In v17 scan-scripts are selected globally. Unified option "Extensions" tries to be per-nzb (and per-category) whenever possible, which the exception for service-script mentioned above.

In new implementation the scan-scripts work on per-category basis. When nzb-file is added to queue and it has a category the scan-scripts are chosen from CategoryX.Extensions (if it's not empty).

Users using per-category (post-processing) scripts must not forget to select scan-scripts in category as well. That can be see as inconvenience but on the other side provides more flexibility.

Can we live with the change?

## About queue-scripts
In v17 queue-scripts can be selected either via "QueueScript" or "PostScript" (if the script is declared as both queue-script and post-script). This makes it possible to select script globally (using "QueueScript") or per-nzb (or per-category) via "PostScript".

In new implementation queue-scripts work on per-nzb (or per-category) basis. Similarly to scan-scripts, users using per-category (post-processing) scripts must not forget to select queue-scripts in category as well (or the queue-scripts will not run for that category).

Can we live with the change?

**Comment by hugbug** [comment]
## Implementation
A working implementation is available in branch [311-extensions](https://github.com/nzbget/nzbget/tree/319-extensions). I'm asking (dear) script authors to validate it in both theory and practice. If you can't compile please let me know and I'll provide installer packages.

Note: migration of old settings is currently not completely implemented. Only option "PostScript" is migrated into option "Extensions". The migration of other script-options will be added later.

**Comment by clinton-hall** [comment]
Makes sense to me (but I really only play with post-scripts).

The questions I have are:
1. Do we still specify the order in which scripts are executed?
2. How does this ordering apply with regard queue and scan scripts (or are these assumed to run at the appropriate times irrespective of any selected order?

**Comment by hugbug** [comment]
Option **ScriptOrder** is remained and works as before.

Scripts of different kinds are executed at their respective times in order set by "ScriptOrder".

I was thinking about removing "ScriptOrder" but in this case we need to list all scripts in "Extensions". If we do so we need to mark active scripts somehow, for example be prefixing them with + sign:

    +VideoSort\videosort.py,EMail.py

Here VideoSort is active but EMail isn't. I'm not sure if that change of semantic is good so I left "ScriptOrder" for the moment.

**Comment by clinton-hall** [comment]
Ok, that makes sense.
So if ScriptOrder were to be removed, the scripts in "Extensions" would be listed in order? 
I don't mind the `+` to mark active. I assume this syntax would follow through to CategoryX. scripts and FeedX.scripts?

**Comment by hugbug** [comment]
> So if ScriptOrder were to be removed, the scripts in "Extensions" would be listed in order?

Yes.

> I assume this syntax would follow through to CategoryX. scripts and FeedX.scripts?

That's a problem. There is no need to list inactive scripts there and it's not clear what to do if they would be listed in a different order. At the end the active scripts per-nzb is determined from nzb parameters and options "Extensions" and "CategoryX.Extensions" define only defaults for new nzbs. Therefore there can be only one place to define execution order.

Currently option "ScriptOrder" makes it possible to define the order of inactive scripts too. It is possible to have scripts which are not active in PostScript nor in any CategoryX.PostScript. Such scripts still can be activated per-nzb via download details dialog and it's necessary to be able to define their order too.

**Comment by clinton-hall** [comment]
That makes sense. I believe you have it all covered, as I would expect ;)

**Comment by hugbug** [comment]
## Update
Implemented automatic migration of old settings. Scripts from old options "QueueScript" and "ScanScript" are now automatically added to "Extensions" and to "CategoryX.Extensions" (if "CategoryX.PostScript" wasn't empty).

Users don't need to reconfigure anything after update.

**Comment by hugbug** [comment]
Merged to develop.

**Comment by hugbug** [comment]
## About scheduler-scripts

Can we make scheduler scripts selectable in option "Extensions" like other scripts? The problem here is that scheduler scripts need well, a schedule. When should a script run if it was activated in option "Extensions" (instead of creating a Task in scheduler section)?

I found the following solution. For many scheduler scripts a reasonable default schedule can be provided by script author, via script definition. Example (explained below):

```python
#########################################################
### TASK TIME: *;0:00;0:30                            ###
#########################################################
### NZBGET QUEUE/SCHEDULER/POST-PROCESSING SCRIPT     ###
#########################################################
### QUEUE EVENTS: NZB_ADDED                           ###

# Test script.
#
# This is a long description for test script.

#########################################################
### OPTIONS                                           ###

# Example script option (yes, no).
#Option1=yes

### NZBGET QUEUE/SCHEDULER/POST-PROCESSING SCRIPT     ###
#########################################################
```

Here we have a multi-purpose extension script (queue, scheduler and post-processing). Script definition is enclosed between opening and closing script definition signature `NZBGET QUEUE/SCHEDULER/POST-PROCESSING SCRIPT`.

Like other queue scripts this script has event definition `### QUEUE EVENTS: NZB_ADDED`.

The script provides default scheduler task using signature `### TASK TIME: *;0:00;0:30`. In that example the script will be started at program boot (`*`) and then every 30 minutes.

You may wonder why the task definition were put before opening script definition signature (`NZBGET QUEUE/SCHEDULER/POST-PROCESSING SCRIPT`). Indeed the task definition looks nicer when put near queue event definition:
```python
#########################################################
### NZBGET QUEUE/SCHEDULER/POST-PROCESSING SCRIPT     ###
### QUEUE EVENTS: NZB_ADDED                           ###
### TASK TIME: *;0:00;0:30                            ###
```
There is however one issue with this nice style: older nzbget versions do not recognize task definition and treat it as option section which leads to crazy things happening on configuration page in web-interface. Therefore if your script must work with nzbget prior v18 you should put the task definition as shown in the first example.

**Note:** decorations `#########################################################` in both examples are used strictly for formatting and are not necessary.

### Summary
What we have now? Many scheduler scripts can now be activated as easy as other scripts by simple selection in option "Extensions". The possibility to launch scheduler scripts via task scheduler is of course remained. If a user doesn't like the default scheduling he can create a scheduler task just like before (instead of or in addition to activating the script via option "Extensions").
