### ISSUE TITLE
Clean up description field in RSS feed

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#32]
The description field may contain html-text as CDATA. The content of the field must be cleaned up from html-tags before processed by feed filter. Otherwise the filter may trigger on html-tags.

**Comment by hugbug** [comment]
@Prinz23: implemented in branch **32-rss-description-cleanup**.
Can you please test it?

**Comment by Prinz23** [comment]
This version crashes when clicking on the RSS Feed Change Button in Web UI with a  Segmentation fault.

**Comment by hugbug** [comment]
Doesn't crash for me.
Can you try with an empty filter but with the same Feed-URL? That tests if it crashes during fetching or filtering.

**Comment by Prinz23** [comment]
Emptied filter. Crashed during startup while/after fetching feed. 
Only got Downloading Feed in log and then segmentation fault.

**Comment by hugbug** [comment]
I'll send you a debug-build which produces stack trace and valuable core-files.

**Comment by hugbug** [comment]
Fixed the crash.
Please try the new version and test the original problem with CDATA too.

**Comment by Prinz23** [comment]
Doesn't crash anymore. And the CDATA works too.

**Comment by hugbug** [comment]
Thanks for testing.
Merged into **develop**.
