### ISSUE TITLE
PostStrategy in wrong tab

### ISSUE THREAD

**Issue by Safihre** [nzbget/nzbget#333]
Shouldn't `PostStrategy` be in the `Check and Repair` section?

Was searching for it after some Reddit user asked for it: https://www.reddit.com/r/usenet/comments/5r0t1e/nzbget_settings_for_powerful_hardware/

**Comment by hugbug** [comment]
I don't know. It also affects unpack and post-processing scripts, not just par-check :confused:.

**Comment by Safihre** [comment]
Aaah yes, makes sense!
