### ISSUE TITLE
1 million pulls from the dockerhub

### ISSUE THREAD

**Issue by sparklyballs** [nzbget/nzbget#334]
hi there, i'm a member of [linuxserver.io](https://www.linuxserver.io) and am just dropping you a line to let you know that our docker image for nzbget has just surpassed 1 million pulls from the dockerhub.

that doesn't mean 1 million users, it means that the combined number of pulls and checking for updates etc, has exceeded 1 million.

you can see the rest of our images and their stats on this list [container list](http://tools.linuxserver.io/dockers)

**Comment by hugbug** [comment]
Thanks for the info.

I wonder how is this related to the number of release downloads for linux installer version. For example for v17.1 stable there are 20502 downloads, according to github stats.

Does the docker version pull anything from github releases area?

Are there any common ratio to estimate the number of users from the count of docker pulls?

**Comment by sparklyballs** [comment]
unfortunately the stats from the hub, lump all the pulls of the image, update/checking for an update for an existing user together.
there's no way of knowing how that translates to individual users.

we grep the version to download from this json, but that would only add numbers to your stats when the image is built and has no relation to pulls etc.

we build a new image weekly on fridays

http://nzbget.net/info/nzbget-version-linux.json
