### ISSUE TITLE
Possible memory leaks for the browser UI on Chrome

### ISSUE THREAD

**Issue by francislavoie** [nzbget/nzbget#336]
This might just be Chrome itself having issues, (I run Chrome Dev channel), but for the past month or so, NZBGet if left open for a few hours, will get up to 1.5gb memory usage until I have to kill it to free up some RAM, else my PC starts to slow down. I like to keep a tab open and pinned for easy access. I'm just worried that the JS autorefresh might not be garbage collected properly. I have it set to refresh every 1s, and I'm using the latest testing build of nzbget.

Let me know if there's any more information you might need from me to potentially track this down.

Thanks

**Comment by francislavoie** [comment]
Here's a quick screenshot from just now, I left it running since last night and this is the memory usage of the tab in Chrome. http://i.imgur.com/5eMKCcv.png

**Comment by hugbug** [comment]
I can reproduce this in Chrome but I failed to find the cause. Even read few Chrome how-to's on the matter. The Chrome's profiler shows that only "system objects" grow; they are not in control of the javascript code.

I also tested in Firefox and Safari and they show constant memory consumption. Tested all three browsers with update interval "0.001 second" to speed up the tests. Memory usage in Safari was around 75MB, in Firefox 145MB and in Chrome growed up from 55MB to 800MB.

I'm afraid that's a Chrome bug which I'm unable to fix. Any help is appreciated.

**Comment by francislavoie** [comment]
Thanks for looking into it!

**Comment by wtf911** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=270000

On that page at the bottom might be relevant information, comments 49 and 53 perhaps.

It is mentioned again here:

http://stackoverflow.com/a/35059157

**Comment by francislavoie** [comment]
As of Chrome `Version 60.0.3100.2 (Official Build) dev (64-bit)`, I'm not seeing this issue anymore. I've had the tab running for over 2 days and memory usage is at a very reasonable 70MB. It was probably an upstream Chrome bug causing memory issues, so I'm just going to assume it's fixed for the context of nzbget.

**Comment by hugbug** [comment]
Great.
Thanks for the status update.
