### ISSUE TITLE
Stuck on 18.0-testing-r1865

### ISSUE THREAD

**Issue by th3fallen** [nzbget/nzbget#340]
Update to 18.0 gives `Download Failed, please try again later`

even manually updated via ` ./nzbget-18.0-bin-linux.run --destdir /opt/nzbget/` and still am on the same version, am i missing something?

**Comment by hugbug** [comment]
Which version `/opt/nzbget/nzbget -v` prints?
When you install manually which version is printed by installer?

If "/opt/nzbget/nzbget -v" prints correct version and web-interface shows wrong version, then make sure to terminate all instances with `killall nzbget`, then start again.

**Comment by th3fallen** [comment]
That did it! thanks a ton
