### ISSUE TITLE
After update to 18.0 : "Unable to get property 'formId' of undefined or null reference

### ISSUE THREAD

**Issue by SBNL1** [nzbget/nzbget#341]
I just upgraded to 18.0 Stable.
When I press the button to change the RSS Feeds filter I get the following error:

Error in https://XXX.XXX.XXX.XXX:6789/config.js (line 1566)
Unable to get property 'formId' of undefined or null reference.

**Comment by hugbug** [comment]
What 's the OS (on computer where nzbget runs)?
How nzbge was installed (official packages from nzbget home page)?
Tried restarting nzbget? Make sure all instances of nzbget were stopped before starting again.

**Comment by SBNL1** [comment]
>  What 's the OS (on computer where nzbget runs)?

Debian Linux 8

> How nzbge was installed (official packages from nzbget home page)?

Yes the  " nzbget-latest-bin-linux.run" installer was used and I followed the WIKI.
I created the multiline RSS filter and it worked.
Then I used the update function from within the application (prev stable 17,x?)

> Tried restarting nzbget? Make sure all instances of nzbget were stopped before starting again

I first restarted  NZBGet with system reload, didn't work, so I rebooted the server.

The RSS filter itself works perfect and has no issues. If I fetch the feed, it does exactly as I want (as I can preview it from the RSS menu and it actually downloaded them)   just can't load the RSS filter feeds multiline editor.

update 1
If I remove the filter from the single line, safe the feed without the filter, do a system reload,
then I can open the (empty) multiline editor again.

Update 2
Just tried to apply the filter again (copy/paist as a single line) and saved it, without going to the multiline editor. I reloaded NZBGet, and the same filter can be loaded and shows up as before in the multiline editor.

(All apt-get packages are up to date)

**Comment by hugbug** [comment]
Maybe that's browser specific. What browser do you use? Can you try another browser, possibly from another computer (or tablet or phone if you don't have other PCs)?

**Comment by SBNL1** [comment]
> Maybe that's browser specific. What browser do you use?

Can't recreate the error after Update 2.

I have 3 RSS feeds so I was hoping the other ones that I didn't modified would recreate the same error.
But it seems after emptying and saving the first feeds filter > reload nzbget >paste the original filter > reload nzbget, it got fixed.

And I forgot to make a backup with the original error :(
Then again, I did create, edit, saved and reloaded the filters many times in de multiline editore with the same browser (NZBGet v 17.x), and the error started immediate after the update (same day as I created the filter) as I wanted to finetune it a bit more.

(forgot to say the filter is awesome! saves a lot of usenet BS :-D Great application with killer features.
I just started using the RSS feeds. Been using this app as my no1 for many years, and never used RSS feeds before. No more sickbeard/sickrage/sonarr/etc needed :D (for me that is ;)  )

**Comment by hugbug** [comment]
> Error in https://XXX.XXX.XXX.XXX:6789/config.js (line 1566)
Unable to get property 'formId' of undefined or null reference.

Line 1566 in v18.0 doesn't access property 'formId', but in v17.1 it does. That means config.js from v17.1 was used. Either a browser caching issue or installation issue. As all is OK now there is nothing to fix on my side.

Regarding rss you might find useful [[FeedScript] ImdbWatchlist - RSS with IMDb integration](http://forum.nzbget.net/viewtopic.php?f=8&t=2112).

**Comment by SBNL1** [comment]
Ok thx for your efforts.
Closing it.
