### ISSUE TITLE
Show currently downloading on long queue

### ISSUE THREAD

**Issue by bu3alwa** [nzbget/nzbget#343]
I would like to have a whats being downloaded section possibly and then below it would be the rest of the queue. It gets difficult to find whats being downloaded when you have a list of 1000+ items. I was hoping if you could consider this as a future enhancement?

**Comment by hugbug** [comment]
Showing an item at the top of the queue, on a position it doesn't realy is, would make it not correctly moveable. A not correctly working sorting would be an another problem.

How about this: you can click on priority column to sort queue by priorities. That should bring high priority items to the top of queue and make downloading item visible on first page Unless you have many paused items.

**Comment by hugbug** [comment]
There is also a filter box at the top of the page, where you can type "downloading" (or "status:downloading") and then even save that as filter for quick access.

**Comment by bu3alwa** [comment]
I did not know you could filter downloading through search. That is effectively what I needed. Thank you and I apologize I took the bar as just search not a filter for the items tags. I probably should have done more research.

**Comment by hugbug** [comment]
No need to apologize. I'm glad it solved the issue :wink: .
