### ISSUE TITLE
Auto Screen Size Scaling?

### ISSUE THREAD

**Issue by jrdnlc** [nzbget/nzbget#344]
You guys have any plans to add support for auto scaling to any screen size? While browsing on mobile it does not look good at all.

**Comment by hugbug** [comment]
Mobile is handled specifically with a special layout and should look perfect.

Can you provide a screenshot where it looks "not good at all"?

**Comment by hugbug** [comment]
Closing this.
Feel free to comment or reopen if you have further questions.
