### ISSUE TITLE
Add host name to error message "Could not receive data on socket"

### ISSUE THREAD

**Issue by jeroenh** [nzbget/nzbget#349]
I receive regular error messages as follows:

`Could not receive data on socket: ErrNo 54, Connection reset by peer`

I have several news servers that I use at the same time, and I have a hard time pinning this down to one of them. There is nothing in the logs that I can relate it back to a single newsserver.

Could it be changed so that it is easier to track this back to one of the news servers?

**Comment by hugbug** [comment]
Yes, that make sense.

**Comment by jeroenh** [comment]
I would suggest either host name, or the configured Name when set.
