### ISSUE TITLE
Per-server quotas

### ISSUE THREAD

**Issue by rcdailey** [nzbget/nzbget#352]
I use nzbget with a primary (monthly) paid unlimited server + several block accounts. The block accounts serve as only backups for missing articles. I set them lower down in priority. I have so many of these, that it gets difficult to browse to each website to check on my quota.

Note that all of my block accounts have a quota with no time limit. For example, you can purchase 500GB and use that up over the course of 1 month or 1 year, it doesn't matter.

What would be ideal is to specify a "starting quota" to each server (optional), representing the remaining bytes available on that block account. As actual articles are downloaded on said server, it would subtract the amount of bytes from the quota. Slowly it will approach 0 bytes remaining, and maybe nzbget could allow a per-server threshhold, which will trigger that server to be effectively disabled until I can get around to purchasing more quota for it.

Think of this as tracking the mileage on your car until your next oil change.

Would this be a reasonable feature to add? I have seen similar implementations for quota, specifically #99, but this is a global quota, not per-server.

**Comment by hugbug** [comment]
What happens currently when the block is exhausted? Do servers return specific error messages allowing to distinguish the issue from other errors? Please provide message examples if you have any.

If it's possible to distinguish such errors it would be possibly better to react on them instead of trying to disable servers upfront. The usage data calculation in NZBGet and on provider servers may differ slightly. We don't want to disable servers which still may have remaining amount. In other case it may happen that the servers reach the 0 mark before NZBGet does; then we need again NZBGet to understand error messages.

**Comment by rcdailey** [comment]
Good points, I think  you make some valid arguments. I was looking into a
more preemptive approach, some way to get reminders before it actually
starts failing (ideally I don't want any downtime, while easily being able
to keep track of quotas).

As such I don't have any examples to give unfortunately. I don't have any
block accounts that are empty at the moment and probably won't in the near
future.

**Comment by hugbug** [comment]
I can offer a solution as an extension script [ServerAlert.py - server volume alert](http://forum.nzbget.net/viewtopic.php?f=8&t=2859).

Also made a few small improvements to NZBGet, which make the script easier to use and optimise performance.

**Comment by hugbug** [comment]
@rcdailey, have you tried the script?

**Comment by rcdailey** [comment]
Not yet, sorry. I'll get to it soon.

**Comment by rcdailey** [comment]
Hey @hugbug, sorry it's taken me so long to get back with you :-(

I have installed the script *but* I do not see the "Volume Statistics" option under any of my servers. The extension settings page does appear in the options tab, though, so I know that NZBget can detect that the script is installed.

I am using NZBget 18.1

**Comment by hugbug** [comment]
You missed that line in script description:

> The script requires at least nzbget v19.0-r1940.

**Comment by rcdailey** [comment]
Oh sorry. I will wait for the official release then and test again.
