### ISSUE TITLE
DupeCheck doesn't work on fetched NZBs

### ISSUE THREAD

**Issue by softrockstar** [nzbget/nzbget#354]
On NZBget 18.0 (clintonhall's QNAP Package) the DupeCheck feature works on NZB's which are scanned in from a directory, but not those sent/fetched from an indexer. To clarify, it is the "3) if nzb-file contains duplicate entries. This helps to find errors in bad nzb-files." type of duplicates which are not being caught.

For example, if an NZB containing duplicate files is sent to NZBGet from the web, it shows up in the Download queue as 23GB and produces many .duplicate1 files. If the same file is placed in the incoming NZB directory, when scanned into NZBGet it shrinks to half that size, as the duplicate files are automatically discarded.

InterDir is set, and all HealthCheck parameters were tested before this behavior was discovered.

**Comment by hugbug** [comment]
Click on the download item sent from indexer, then on button "Dupe". What is "Dupplicate Mode"?

**Comment by softrockstar** [comment]
Apologies if I was not clear:

1.) The NZB in question was not previously downloaded.

2.) It contained two sets of files, some with different completion rates, eg:
     TeST.r00 (parts: 376/400)
     TeST.r00 (parts: 400/400)
     .....
     TeST.r99 (parts: 345/400)
     TeST.r99 (parts: 400/400)
     TeST.rar (parts: 136/200)
     TeST.rar (parts: 200/200)

(Such an NZB is obviously malformed, but they are also fairly common on automated indexers. The two filesets are identical - this is not two unique sets of files given the same name. I would guess this kind of NZB stems from including a repost along with the original)

3.) When 'sent' from indexer to NZBGet (NZBGet displays "Fetching" in Download tab), every single file is downloaded, resulting in .duplicate1 files and extraction failure.

4.) When the NZB is instead downloaded through browser and placed in NzbDir, NZBGet does not download every file - it deletes the smaller (or less complete) duplicate files from that download.

What I'm getting at is: NZBGet seems to process NZBs differently depending on how they are added to its download queue. This behavior was confirmed with other users.

Hope this clears up what I was trying to explain :)

**Comment by hugbug** [comment]
I understood the issue from the first post already ;)

What I need you to do is: in nzbget click on the download item which was added automatically from indexer, then on button "Dupe". What is "Dupplicate Mode" you see in nzbget?

If duplicate mode is set to FORCE the duplicate check is disabled for that item. So if the indexer sends items with FORCE you'll have what you have. In other words - correct program behavior.

**Comment by softrockstar** [comment]
Ah! Thanks for the explanation. Unfortunately I've deleted that NZB, and the indexer did too after I reported it. After reading a bit of the Duplicate Checking documentation, I understand now that part of this process relies on information sent from the indexer during URL-fetches, so that would be the best venue to take this.

**Comment by hugbug** [comment]
You can check any other nzb sent from indexer. They probably all have the same duplicate mode unless the indexer allows you to choose it.

**Comment by softrockstar** [comment]
I did find a thread on their forum about this with links to examples, and yes, they had Duplicate Mode set to Force. Is there a way to enable the same (desirable) dupe-elimination behavior I see with scanned-in NZBs with pushed NZBs?

**Comment by hugbug** [comment]
You can override duplicate mode using a scan-script. Something like this:

```shell
echo "[NZB] DUPEMODE=SCORE";
```

By checking of parameter **NZBNP_URL** you can conditionally do this only for nzbs coming from that site.

See [Scan scripts](https://github.com/nzbget/nzbget/wiki/Scan-scripts) for details.

**Comment by hugbug** [comment]
Closing this.
Feel free to comment or reopen if you have further questions.
