### ISSUE TITLE
Feature Request: More Control Over Free DiskSpace Check

### ISSUE THREAD

**Issue by m1lkman** [nzbget/nzbget#355]
Is there anyway we could get more control over the disk space check? Now that many of us are running headless VPS systems uploading to ACD it would be nice to have the ability to enable NZBget to recheck the free disk space and unpause as well as control the frequency of the check. As files are processed and uploaded off the local disk up to acd the free space increases and downloads can safely resume. Thanks for the great product.

**Comment by hugbug** [comment]
I consider the full disk situation an exceptional situation, where a user's action is required.

If you have some kind of automation system which moves files elsewhere you can unpause NZBGet from your scripts, once all files are moved.

Another reason to not resume automatically is because the resuming would kick in the moment the space just become sufficient and NZBGet would start downloading, although the moving is probably still in progress. That may drastically decrease the move speed.

**Comment by m1lkman** [comment]
I completely hear what you're saying. Maybe there's a way to mitigate these issues. Setting an unpause threshold possibly as to when free space is at a great enough value to unpause.

I threw together a quick script yesterday to share with anyone that is looking for a possible solution. I have it checking every 15 minutes.

[https://github.com/m1lkman/NZBGetcheckpause/blob/master/NZBGetcheckpause](url)

**Comment by hugbug** [comment]
If you make this script an nzbget scheduler script it will better integrate into nzbget. You will be able to define script settings via nzbget web-interface.

See https://github.com/nzbget/nzbget/wiki/Extension-scripts and https://github.com/nzbget/nzbget/wiki/Scheduler-scripts

**Comment by m1lkman** [comment]
Sounds like a good idea. Can you point me to where I can figure out the various variables like NZBOP_STATUS and some samples of getting FreeDiskSpaceMB from a shell script? Thanks.

**Comment by hugbug** [comment]
> Can you point me to where I can figure out the various variables like NZBOP_STATUS

See links in my previous post.

Check example scripts Logger.py and Email.py. They don't read FreeDiskSpaceMB but it's very similar.

**Comment by m1lkman** [comment]
I started playing around with a scheduler script but it's only running on boot and not at the 2 minute interval I configured.

`### TASK TIME: *;0:00;0:02                            ###`

Never runs again. Am I doing something wrong? Any chance it's a bug?

**Comment by hugbug** [comment]
It was indeed a bug in the documentation. Updated the wiki page for scheduler scripts.
The example in wiki should read `*;*:00;*:30`. The usage of asterisk is explained in description of option **TaskX.Time**:

> An asterisk placed in the hours location will run task every hour (e. g. `*:00`).
An asterisk without minutes will run task at program startup (e. g. `*`).

BTW 2 minutes interval is too short. 15 minutes would be better.

**Comment by hugbug** [comment]
Closing this.
Feel free to comment or reopen if you have further questions.
