### ISSUE TITLE
[Documentation] Category in Queue-Scripts

### ISSUE THREAD

**Issue by c4tz** [nzbget/nzbget#357]
Hi Hugbug,

as I was working on [this issue](https://github.com/BlkChockr/nzbget-stream/issues/3) in my queue-script, I noticed (after half an hour of debugging) that your documentation seems to be wrong.

It says the category would be set in `NZBNP_CATEGORY`, but it is not. Its set in `NZBNA_CATEGORY `!

(Maybe `NZBNP_PRIORITY` is wrong, too, but I didn't test that one)

Please correct it so that people like me don't have to wonder if they're still sane :P

**Comment by hugbug** [comment]
Copy paste error. Prefix "NZBNP" is for scan-scripts, "NZBNA" for queue scripts, "NZBPP" for post-processing scripts.

Corrected. Thanks.
