### ISSUE TITLE
Unpack during downloading

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#371]
Currently downloading and unpacking are separate stages. The unpack starts after the nzb is completely downloaded. To better use computer resources NZBGet can download one item and post-process another item at the same time.

However if a certain nzb is needed quickly the total process could take less time if unpack would start as soon as first archive part is downloaded and continue as long as new parts come in.

This issue is to experiment with **unpack during downloading** feature.

The prerequisites to this feature are:
 - Renaming obfuscated files during downloading (#362);
 - Sort inner files for optimal download order (#364).

Unpack during downloading can obviously work only for healthy downloads. Therefore it is not intended to replace default unpack module.

Task list:
- [x] extend script controller with stdin redirecting;
- [x] create new module to do direct unpack;
- [x] handle unrar stdin to emulate user input in regard to handling of multi disk messages;
- [x] integrate direct unpack module into post-processing workflow;
- [x] cancel direct unpack on: program reload, deleting nzb, unpack errors;
- [x] support downloads with multiple independent archives;
- [x] restart direct unpack after program reload;
- [x] detect not unpacked archives which may appear after rar-rename and unpack them during post-processing.

**Comment by wtf911** [comment]
How is the progress coming along? :) I see you've made a new branch.

**Comment by hugbug** [comment]
It's working. There are few things to do left but you can already try it and tell me how well it works for you. Make sure to enable **DirectRename** and **ReorderFiles** (in addition to **DirectUnpack**).

To test use branch **371-direct-unpack**.

**Comment by hugbug** [comment]
Updated the first post with a task list for you to follow the progress.

**Comment by wtf911** [comment]
Thank you. :)
