### ISSUE TITLE
Demonize without forking

### ISSUE THREAD

**Issue by profplump** [nzbget/nzbget#372]
It would be nice if there was an option to start daemon mode without forking -- I want a supervisor process to know when the daemon dies.

Even a compile-time option via ```configure``` would be useful.

If anyone else wants this mode you can recompile with this patch:
```
diff -urN nzbget-18.1.orig/daemon/main/nzbget.cpp nzbget-18.1/daemon/main/nzbget.cpp
--- nzbget-18.1.orig/daemon/main/nzbget.cpp	2017-04-08 09:07:18.000000000 -0700
+++ nzbget-18.1/daemon/main/nzbget.cpp	2017-05-04 14:00:37.944894362 -0700
@@ -869,9 +869,10 @@
 #ifndef WIN32
 void NZBGet::Daemonize()
 {
-	int f = fork();
-	if (f < 0) exit(1); /* fork error */
-	if (f > 0) exit(0); /* parent exits */
+	// Don't fork -- we want to know when you die
+	//int f = fork();
+	//if (f < 0) exit(1); /* fork error */
+	//if (f > 0) exit(0); /* parent exits */
 
 	/* child (daemon) continues */
 	m_daemonized = true;
```

**Comment by hugbug** [comment]
Just use `nzbget -s` instead of `nzbget -D`.

**Comment by profplump** [comment]
I saw ```-s``` mode but it throws me into a UI and stops when it isn't in the foreground. Is there some way to bypass that behavior?

I don't want anything tied to a controlling terminal -- I still want the process to daemonize, just not to fork.

**Comment by hugbug** [comment]
Daemonizing without forking is nonsense; forking is the whole point.

Try
```
nzbget -s -o outputmode=log
```

**Comment by profplump** [comment]
Then I won't call it daemonizing, but there are a number of non-fork behaviors in that path I consider useful: changing users, changing the process group, closing the standard file descriptors, recording the PID, ignoring signals.

If that isn't a usage mode you want to support feel free to close this.

**Comment by hamiltont** [comment]
For folks using systemd, here are two simple options for `nzbget.service`. First one avoids the forking, while the second one uses `--daemon`

For the forking version, the only real negative I ran into is that this makes using journalctl tricky - you either need to figure out how to get nzbget to log to syslog (something I was not able to do in the last 20 min) or use some other tool that pulls log files in. 

```
[Unit]
Description=Usenet downloader
After=network.target

[Service]
Type=simple
# Using --server causes DaemonUsername to be ignored
User=nzbget
ExecStart=/usr/bin/nzbget --server --option OutputMode=loggable
# this reload approach is probably not working....
ExecReload=/usr/bin/nzbget --reload

[Install]
WantedBy=multi-user.target
```

Forking version: 
```
[Unit]
Description=Usenet downloader
After=network.target

[Service]
Type=forking
PIDFile=/var/opt/nzbget/nzbget.lock
ExecStart=/usr/bin/nzbget --daemon
ExecReload=/usr/bin/nzbget --reload
ExecStop=/usr/bin/nzbget --quit

[Install]
WantedBy=multi-user.target
```

**Comment by hugbug** [comment]
I think current possibilities `--daemon` and `--server` cover all use cases.
Therefore closing this issue.
