### ISSUE TITLE
UNPACK: FAILURE, but manual works

### ISSUE THREAD

**Issue by greencopper** [nzbget/nzbget#373]
Hi,

After upgrading to 18.1 I have a somewhat strange problem in that every now and then a file is downloaded, however I get "UNPACK: FAILURE" in the log. When I click the file and choose "Action" and then "Post-Process Again", the files unpacks fine without issues.

I am unsure about how to debug this strange problem as there is nothing specific in the logs.

Kind regards

**Comment by hugbug** [comment]
I'm sure there is an explanation in the log.
Click on history item, then on button Log and read the log carefully (not only few last entries). If in doubts post the log here (via pastebin.com).

**Comment by hugbug** [comment]
Closing this for now due to lack of feedback. Feel free to reopen with more info.

**Comment by daftware** [comment]
I think it's worth re-opening this thread as I found it whilst investigating the exact same issue here on 19.1. The unrar used by nzbget fails initially - a manually unrar using WinRAR unpacks fine... as does a Post Process Again.

It's not exactly a show stopper - just an inconvenience. Odd that it works on second passd though.

Thanks in advance,
TC

**Comment by hugbug** [comment]
For a failed download click on the item in history, then on button "Log". There should be error messages explaining the issue.

If you have troubles understanding the log please post the log by clicking on button "Save to File" and uploading it to pastebin.com.

**Comment by daftware** [comment]
I checked the log and it provides no clue as to the reason why.... simply that the unpack had failed. The original files were intact and par2 repairing was not needed.

PS. I cannot paste the original log as now the second PP attempt fixed the issue the previous logs has gone (I assume that's intended behaviour).

**Comment by hugbug** [comment]
"Post-process again" doesn't remove previous log. Only "Download again" does.

**Comment by daftware** [comment]
The only logs I can find pertain to the second PP. I'll wait until it happens again and supply a full log.

**Comment by hugbug** [comment]
Click on the item in history, then on button "Log", then on button "Save to File", upload to pastebin.com.

**Comment by daftware** [comment]
As if by magic!!!! https://pastebin.com/1Di1BG4q

**Comment by hugbug** [comment]
> Tue Dec 19 2017 17:43:10    INFO    Unrar: Extracting XXX\xxx.r04
> Tue Dec 19 2017 17:43:12    ERROR   Unpack for XXX failed

The last message printed by unrar was "Extracting XXX\xxx.r04". There is no "All OK"-message nor an error message. That means unrar-process has unexpectedly terminated (crashed). We can only guess why that happened. If the destination directory is on a network drive the connection interruptions may cause crashes (of many programs) as most programs usually expect the drives to work without errors.

**Comment by daftware** [comment]
I can confirm that the destination HD is a local internal drive. As I say, it's not a big problem for me. Considering what a great program nzbget is in terms of usability, reliability and speed I'm certainly not going to moan!!! Thanks for your input anyway.
