### ISSUE TITLE
Request: Automatically "Post-Process Again" after entering password in history

### ISSUE THREAD

**Issue by RollingStar** [nzbget/nzbget#377]
Sometimes I check my history to see that some downloads have a password I forgot to enter. I then enter the password and manually select "post-process again".

Not a big deal. If it's not too much trouble, could the program automatically post-process once a password is entered and the download previously failed due to the password?

Or, if this feature were developed, would it be accepted?

**Comment by hugbug** [comment]
You can choose "post-process again" from actions menu after typing of password. You don't have to save, then open dialog again to post-process.

Post-processing again on click on "Save" doesn't sound logical to me.

**Comment by RollingStar** [comment]
Okay, that's fine.
