### ISSUE TITLE
Feature Request: Persistent Speed Limit

### ISSUE THREAD

**Issue by Zer0t3ch** [nzbget/nzbget#380]
I always use the speed limiter, because if I don't, it slows the internet to a crawl for everyone/everything else. 

But, sometimes I reboot my server or have a power outage, and when NZBGet comes back up, it does so un-throttled.

Would it be possible to keep the speed limit the way it works now, where it can be changed at runtime and it still resets at start, but give us a config option to set the default starting speed limit?

**Comment by hugbug** [comment]
Option **DownloadRate** in section **CONNECTION**.

**Comment by Zer0t3ch** [comment]
@hugbug I'm an idiot, thank you.
