### ISSUE TITLE
Viruscanner says 19.0-testing-r1999 is a trojan

### ISSUE THREAD

**Issue by Magikarplvl4** [nzbget/nzbget#381]
![image](https://cloud.githubusercontent.com/assets/2944704/26323130/f61955e0-3f2d-11e7-869f-467b2915f92f.png)

I guess its a false positive but i'm not sure

**Comment by war59312** [comment]
I'm assuming you ran the installer from:

`https://github.com/nzbget/nzbget/releases/download/v19.0-r1999/nzbget-19.0-testing-r1999-bin-win32-setup.exe`

Yes?

The best thing to do when this sort of things happens is to check it on virustotal.com .

As you can see here: 

`https://www.virustotal.com/en/file/569c08f4a24c7c3b4f78228be546c72f20c8ae35081742bdea9850e59fe3368e/analysis/`

So yes, it's a false positive.

Now be sure you have the correct installer and it was not modified midstream:

> CRC32: 684D8B3B
> MD5: 3CF8ECE578050F5BCB5A7E34BB31400F
> SHA-1: 5ADC473FB7312ADA8B8DE12CC8448F2E3C8CB5B5
> SHA-256: 569C08F4A24C7C3B4F78228BE546C72F20C8AE35081742BDEA9850E59FE3368E
> SHA-512: D47AE84A08E3E60DEF60605D332FE36D78A20451441AE11DE0A866FF8A7AA3AD406451E0B57FB5C094D272F18E0BB8E2926231A40D7D1573563708094097E80D

PS: For Hashing I used Hashtab @ `http://implbits.com/products/hashtab/`
