### ISSUE TITLE
Migrate web-site hosting to Netlify

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#388]
Currently the main web-site (nzbget.net) is hosted on GitHub Pages. It is a great platform which however has some restrictions. There is an alternative offered by [Netlify](http://netlify.com). I've tested it a little and found it to be an excellent upgrade from GitHub Pages.

In fact Netlify integrates so seamless with GitHub that I only needed to select nzbget site repository and the new web-site was generated on a subdomain of netlify.com in a minute. No changes were needed to the site content as Netlify has picked up the existing Jekyll config from GitHub.

Netlify offers all functions which GitHub Pages has:
   - automatic html generation from markdown documents (using Jekyll);
   - integration with GitHub repository (a new commit to site content initiates regeneration of html pages);

In addition to that Netlify provides:
- SSL/HTTPS on custom domains. That is the main complain for GitHub Pages. Netlify provides SSL for custom domains for free (via Let's Encrypt). That's a much better solution than SSL proxy offered by CloudFlare.
- Redirects and Rewrite Rules. This should make it possible to download the latest NZBGet setup with `wget https://nzbget.net/download/nzbget-latest-bin-linux.run` as it did work when NZBGet was hosted on SourceForge. Haven't tested this feature on Netlify yet though.
- many other features which NZBGet web-site doesn't need at the moment. For details see [Netlify documentation](https://www.netlify.com/docs/).

The nice thing about using Netlify is that it doesn't mean removing the site from GitHub Page. It still remains on GitHub Pages and it's just a matter of DNS config where to forward the users - to GitHub Pages or to Netlify (well, as long as we don't use unique Netlify features). In any case we have GitHub Pages as backup in a case we can't use Netlify anymore in the future.

**Comment by war59312** [comment]
A few things I've noticed:

Missed history it looks like.

404: https://nzbget.net/history

And typo @ https://nzbget.net/documentation

Extensions > Feed scripts is pointing to `t`eed-scripts, of course it should be `f`eed-scripts.

On `https://nzbget.net/installation-on-posix` , GnuTLS url needs to be updated to: `https://gnutls.org/`

OpenSSL link should be made ssl as well, as in `https://www.openssl.org/`

On same page, why under `Compiling`, is `cd ` blue text. Doesn't match rest of the page.

**Comment by hugbug** [comment]
>https://nzbget.net/history

Where is this link? I thought it isn't used anywhere and deleted redirection.

> On same page, why under Compiling, is cd blue text. Doesn't match rest of the page.

For whatever reason highlighter treats it differently, because the built-in command maybe.

Thanks for checking, I'll correct the errors.

**Comment by hugbug** [comment]
Fixed all links. Thanks again.

**Comment by hugbug** [comment]
I've created a nice new page for history - https://nzbget.net/history. More info in #393.

**Comment by war59312** [comment]
Nicely done! And thanks for fixing the minor issues.
