### ISSUE TITLE
Update to 19.0-testing-r2008 fails

### ISSUE THREAD

**Issue by Magikarplvl4** [nzbget/nzbget#389]
Hi,

just a headsup.

When updating from 19.0-testing-r1999 to 19.0-testing-r2008 i got in a update failed loop.

On the moment when i launch the update system, its try to install the update, but the system says: "nzbget is still running". When i take a look on the running tasks, i don't have nzbget running.
After trying 3 times. i give up and do it manual. Not sure if there is changes in the update code. I don't saw this problem before.

(windows 10).

**Comment by hugbug** [comment]
Have you also checked **Processes** (not tasks) in Task Manager? Maybe there were a hanging process.

**Comment by Magikarplvl4** [comment]
@hugbug well i didn't :( not sure what was going on.
