### ISSUE TITLE
Force post process on failed par2 - disable par2 after it fails

### ISSUE THREAD

**Issue by nomandera** [nzbget/nzbget#390]
One scenario just for a sample context. A nzb has failed hard but manually merging multiple variants and some shell work with par2 -N, * and human effort gets a working set. Often this is because multiple files with same name intentionally have different content or multiple intentionally confusingly named par2 sets requires human intervention to manually extract the right content and delete the noise.

At this point it should be possibly to ask nzbget to ignore that it thinks the set is broken because it cant solve the par2 and continue on to running the rest of the post processing.

**Comment by hugbug** [comment]
- If NZBGet can't repair files it will see that itself and doesn't need to be told about that.
- If repairing was started the files can be repaired and there is again no need to tell NZBGet to stop repairing.
- If repair isn't possible the post-processing continues.

I don't understand what part of the process you want to change.

**Comment by nomandera** [comment]
I had typed a long reply but your comment `If repair isn't possible the post-processing continues.` made me look again and spot the issue.

It seems all my post processing scripts come from a template that checks to see if par2 or unrar failed and gracefully exists with a "none" status if that is the case

```
#If NZB has failed end early and dont run
if [ "$NZBPP_PARSTATUS" -eq 1 -o "$NZBPP_UNPACKSTATUS" -eq 1 ]; then
        echo "[INFO] Skipped. NZB did not pass par2 or unpack checks."
        STATUS=$POSTPROCESS_NONE
        exit $STATUS
fi
```

So nzbget is doing exactly what I asked it to do and this is PEBKAC.

I will need to think of a way to allow the above sane default but in exceptional cases manually set to ignore this and run anyway.

**Comment by hugbug** [comment]
Can we close the issue then?

**Comment by nomandera** [comment]
Yes I think that is for the best as it is clearly a user script logic error. I will close it now but post my eventual solution as a comment after the ticket is closed just for posterity and should anyone stumble on it.

Appreciated for the insight.
