### ISSUE TITLE
Option to set unpack directory

### ISSUE THREAD

**Issue by frebib** [nzbget/nzbget#395]
Unpacking files on my server absolutely hammers the IO. I'm not sure what the root cause is but I've come to the conclusion it's something to do with the way unrar handles writing large files to disk. The larger the archive, the more IO wait happens on the disk (and therefore locking up other programs waiting on the same array)

Having the option to set the unrar location to a tmpfs or other disk would (I think) alleviate this plague for me, hopefully solving a lot of write-backlog related problems that unrar seems to cause.

I propose something like

Unrar directory: `/tmp`
> Unpacks to this directory, in a subdirectory with the same name as the download directory
> If unset, files will be unpacked to the download directory in a `.unrar`subdirectory

**Comment by hugbug** [comment]
So you think NZBGet will be able to move (but really copy-then-delete) files in a better fashion than unrar does?

What version of NZBGet you use and what version of unrar (included with NZBGet or unrar from system packages)?

The latest testing version v19.0-r2008 includes unrar compiled with support for [fallocate](http://man7.org/linux/man-pages/man2/fallocate.2.html), which may affect (not sure in which way) performance on your system. See #379 for details.

**Comment by frebib** [comment]
As far as I can tell, moving and copying files doesn't cause as much disk wait as unrar does, however I could be wrong.

I am running the latest testing build and have been since it was released. I didn't notice any significant change in performance with the update.
I am running unrar with `ionice -c 3` in an attempt to dampen it's performance penalty and I feel like it maybe made a slight difference for the better.
The command specified is just `unrar` so I presume that prioritises the `$PATH`. The system installed version is 5.40, as is the bundled version by the looks of things. I'll try setting the path absolutely to the bundled version and test that a little bit.

**Comment by hugbug** [comment]
> I'll try setting the path absolutely to the bundled version and test that a little bit.

Any news on this?

I think we don't need a new option. Unraring locally, then copying, then deleting should not be more efficient as unraring directly to destination drive. If you really have such a case it would be appropriate to report it to unrar dev to fix the issue. I can't think of why nzbget would be more effective in writing data into disk as unrar is.

If you still want to workaround in nzbget you can set DestDir to local dir and then use a pp-script to move files to final destination. VideoSort or EasySort scripts will probably suit.

**Comment by frebib** [comment]
You are right. I did some more testing on this a couple of days ago and the issue still happens even with unpack disabled which is irritating.

The solution is in fact not a fix in nzbget, but instead about £1k of new hardware and raid controllers. Thanks anyway

**Comment by c4tz** [comment]
(Sorry for necro-bump)

But what about having the DestDir on a NAS and all other (`tmp`, `inter`, etc) locally on a NVMe? This is my case and I would like to have the `_unpack` folder on the NVMe also instead of on the NAS. Unpacking on a SMB/Network mount is pretty slow because unrar has to read AND write to it while unpacking. Unpacking locally and then moving the files to the mount should be significantly faster than unrar-ing over the network, shouldn't it?

**Comment by hugbug** [comment]
> But what about having the DestDir on a NAS and all other (tmp, inter, etc) locally on a NVMe? 

That's the correct setup.

> unrar has to read AND write to it 

No. Unrar reads from **InterDir** and writes into **DestDir**.

**Comment by c4tz** [comment]
You're totally right, sorry. I just tried with a new nzb and saw the `_unpack` folder only contained already unpacked files. Somehow I remembered seeing .rar files in there.
