### ISSUE TITLE
[API] pausedownload() also stops post processing and nzb scan

### ISSUE THREAD

**Issue by naice** [nzbget/nzbget#401]
The api function pausedownload stops post processing and nzb scan while resumedownload function only resumes the download queue. That seems not to be correct. pausedownload should only pause the download queue.

**Comment by hugbug** [comment]
`pausedownload` pauses only downloading. Please check your code, there is a bug there probably.
What language/library do you use to communicate with nzbget? Can you show your code?

**Comment by naice** [comment]
https://github.com/naice/nzbget_silk/blob/master/nzbget_silk/nzbget_silk/Service/NZBGetService.cs @ 69 

I dont think I'm doing anything wrong, but who does? ;)

**Comment by naice** [comment]
I've just tested it again, same behaviour. 

NVM, I restarted NZBGet now the behaviour is as expected.

**Comment by hugbug** [comment]
How do you test?
Try this: in nzbget web-interface click on remainig time label which brings ststus window. Then send the pause command and check the status in web-interface.

**Comment by naice** [comment]
I am testing with Postman. Chrome App.. but the restart helped out. I have
no clue what that caused.
Andrey Prygunkov <notifications@github.com> schrieb am Sa. 24. Juni 2017 um
22:27:

**Comment by hugbug** [comment]
Is this solved yet?

**Comment by naice** [comment]
??
Andrey Prygunkov <notifications@github.com> schrieb am Mo. 26. Juni 2017 um
23:05:

**Comment by hugbug** [comment]
From your previous responses I understand everything works correct now.
I can close the issue, right?

**Comment by hugbug** [comment]
Closing this as solved.
If the issue persists feel free to reopen with more info.
