### ISSUE TITLE
DirectUnpack not showing on FreeBSD Build

### ISSUE THREAD

**Issue by Jabroni** [nzbget/nzbget#402]
Reporting that the FreeBSD binary of nzbget 19 for some reason it doesnt show the new 'DirectUnpack' option within the settings GUI. Im running the binary within a jail on my FreeNAS 9.10 system. I checked on test docker version I have with similar config w/ linux/docker version it did show it correctly. Double checked and on the about box it does show its running nzbget 19.

Tried cleaning the cache of the browser/switching browsers with no luck, the first three options I see on the Settings->Unpack is Unpack, UnpackPauseQueue and UnpackCleanupDisk

**Comment by hugbug** [comment]
Something is wrong with your installation. Please use the installer from nzbget download page and install into a new directory (for a test). Make sure no other instances of nzbget are running, do not restore any older config files. Then start nzbget and check the options in web-interface.

**Comment by Jabroni** [comment]
Ok can confirm it was an issue on the config file. I was previously using the FreeBSD nzbget pkg and migrated to using the bin installer for 19.0, however it seems the config file has some specific settings that needs to be changed. (WebDir and ConfigTemplate). Thanks for pointing that out
