### ISSUE TITLE
Permissions issue with saving changes - Windows

### ISSUE THREAD

**Issue by Magic815** [nzbget/nzbget#404]
Hi there -

I'm running NZBGet on Windows 8.1, and am having permissions issues when trying to save any new settings. I first noticed this sometime in v18 or v18.1 of NZBGet, but am still having an issue with v19.

This is the message I get when I try to 'Save All Changes':
> Could not save configuration in
> C:\Program Files (x86)\NZBGet\nzbget.conf
> 
> Please check file permissions

I know that when I go to that folder in windows explorer, any change requires administrator permission, so I assume that's related. But is there a way to make it so that any changes saved in the WebUI are automatically done as administrator?

Edit: It looks like giving the 'Users' group full permissions to the NZBGet folder has fixed it. Is that something I need to keep on from now on?

**Comment by hugbug** [comment]
By default NZBGet saves settings into "C:\\**ProgramData**\NZBGet\nzbget.conf". The question is why your config is stored in "Program Files (x86)". Remove "nzbget.conf" from "Program Files (x86)" (make a backup) and start NZBGet. It will create default directory "C:\ProgramData\NZBGet" and new file "nzbget.conf" where. You can restore settings from your old config as described in [Backup And Restore Settings](https://nzbget.net/backup-and-restore-settings).

**Comment by Magic815** [comment]
Interesting. There currently is no NZBGet folder saved in 'ProgramData'. Only the one in 'ProgramData (x86)'. I initially installed NZBGet mayb 18-24 months ago, so I'm not sure how I did it then.

I removed the conf file, and restarted the PC. But then somehow NZBGet retained all of the config settings when the computer had rebooted. In addition, no new folder was made in 'ProgramData'. Thoughts?

**Comment by Magic815** [comment]
Ah, got it. So I have the conf file over in ProgramData now (and I backed up and restored). However, it seems like I had to modify the 'User' group permissions for the ProgramData/NZBGet folder as well. Until I did that, it wouldn't let me save the changes either. Is that to be expected? And is it ok that I'm moving forward with the 'User' group having full permissions?

**Comment by hugbug** [comment]
> Is that to be expected?

No, it should work without manual permission setting.
The installer sets permissions for this directory (grant to all users). If you did that manually all should work too.

Do you know what was the first version of nzbget you used on that PC? The installer works differently when it finds existing installation. In particular if nzbget.conf exist in program folder the installler assumes it must update a portable installation and doesn't create PogramData\NZBGet and doesn't set permissions.

**Comment by Magic815** [comment]
I believe the first version was v15.0 when I installed in the Sept 2015 timeframe, but then I quickly upgraded to v16.0 when it hit in Oct 2015. Since then, I've just used the internal 'search for update' inside NZBGet to make the upgrades.

**Comment by hugbug** [comment]
There were permission issues in older installers. So I think it was it.

I hope it will now work properly for you.
