### ISSUE TITLE
nzb download fails due to HTTP/1.1 307 Temporary Redirect

### ISSUE THREAD

**Issue by thmsndk** [nzbget/nzbget#420]
One of my indexers changed some of their setup resulting in HTTP 307 redirects when trying to download the nzb file.

As a result I see the following lines in my log:
- URL XXXXX @ YYYY failed: HTTP/1.1 307 Temporary Redirect
- Download XXXXX @ YYYY failed

If I take the url for the .nzb and paste it into my browser, it correctly redirects and I get a HTTP 200 with the file.

It would appear nzbget does not handle redirects?

I'm currently running on v18, but a friend of mine running v19 has the same experience :)

**Comment by hugbug** [comment]
It does support redirects but it doesn't support HTTP 1.1. The web-server misbehaves if it responds with HTTP 1.1 on requests received via HTTP 1.0.

**Comment by king-cat** [comment]
He's talking about my server. Do you have insight on this @hugbug ? We are using a load balancer now in front of the cache servers and that seems to be when this issue started.

**Comment by hugbug** [comment]
I thought nzbget doesn't like 1.1 in response. But after checking the code I can tell it doesn't check the version in response header. Moreover the spec says that the version in response header is to indicate which version server supports. Therefore 1.1 is OK here. However in the response server can only use features available in the version used in request.

Response code 307 is from version 1.1 and should not be used here. In that regard the server indeed behaves bad. NZBGet supports redirecting with codes 301 and 302. I'll add support for code 307 as this is no brainer but that doesn't help all existing clients.

If you can configure balancer to use code 301 or 302 that should fix the issue.

**Comment by king-cat** [comment]
Looking in my server and load balancer logs I do not see a 307 returned anywhere. Additionally after I did some research on the 307 code specifically on google it looks like 307 is an "internal redirect" on the client. It's something that the browser does for some reason. I'd be happy to facilitate fixing this from the server side but I don't know how. No where is it doing 307 redirects explicitly. It only redirects http to https via 301 permanent redirect. (it will also do 302 redirects if someone tries to go to a page that requires authentication on the front-end but this should not affect any api-client like nzbget)

**Comment by hugbug** [comment]
Who can try with "wget"? I believe it shows all redirects.

**Comment by king-cat** [comment]
Ok first of all, I did a wget with a getnzb link from an RSS feed and I did indeed see a 307 redirect. It was still something wget generated but has to do with HSTS headers that tell the client to always use HTTPS. The links themselves were incorrectly being output as http:// causing a redirect for every download as well as generating that hsts 307 internal redirect. 

So @hugbug was correct, this was a bug in our system, however, redirecting http to https via an HSTS header is something that nzbget should support I would imagine so it might be something to look into regardless.

For the record I have fixed this bug and all future download links will properly be displayed as https forgoing the need for a redirect at all. 

Thanks for the heads up on this @thmsndk

**Comment by hugbug** [comment]
> So @hugbug was correct, this was a bug in our system, however, redirecting http to https via an HSTS header is something that nzbget should support I would imagine so it might be something to look into regardless.

NZBGet would need to store somewhere HSTS data for all sites and apply it on each request. That would be too much work for such a small http client. The idea of HSTS is to protect users who type http-addresses into browsers address string. That's not a use case for nzbget.

Adding support for 307 code however is easy and shouldn't do any harm.
