### ISSUE TITLE
Use Linux installer on FreeBSD

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#423]
Currently we have a separate installers for Linux and FreeBSD.

The Linux installer is widely used whereas there are only few users of FreeBSD installer. Either FreeBSD users prefer to compile NZBGet on their own or they install from other repositories or there are generally not so many FreeBSD users of NZBGet.

There is an issue with the latest version of FreeBSD which was reported on forum in topic [Segmentation Fault after upgrading to FreeBSD 11.1](https://forum.nzbget.net/viewtopic.php?f=3&t=2973). NZBGet crashes during downloading, easy to reproduce. The issue seems to be in the incompatibility of used cross-compiling tools with the latest FreeBSD version. Many attempts were made to rebuild using other cross-compiling toolchains but all failed.

Providing a FreeBSD installer which doesn't work on the most current OS version isn't a good thing.

On the other side FreeBSD has a compatibility mode to run native Linux binaries. In short tests the Linux binary of NZBGet worked without issues on FreeBSD. Currently universal Linux installer refuses installation on FreeBSD (there is OS check in the installer). That made it necessary to do the installation manually using installer command line option `--unpack` with additional manual adjustments after unpacking.

A solution to incompatibility issue seems to be in allowing FreeBSD users to use the universal Linux installer.

In this issue:
- [x] make universal Linux installer compatible with FreeBSD;
- [x] do more tests on FreeBSD.

**Comment by Dudleydogg** [comment]
so the program works fine, but it cannot Unpack anything always fails, not a permission issue, any one ever resolve the unpack issu?

**Comment by hugbug** [comment]
This topic is about using Linux installer on FreeBSD. There is no reason for you to do that anymore because we have a FreeBSD installer now.

**Comment by Dudleydogg** [comment]
I used the FreeBSD installer, and it works great program works, so perfect except it wont unrar the file's always fails.  I searching everywhere and no one seems to be able to resolve that one problem.  I am used to nzbget and dont want to switch to the other reader.  was just fishing for a unrar failed lead., but thank you for responding appreciate that.

**Comment by hugbug** [comment]
Please create a new issue as the problem you describe has nothing to do with the original old topic.
Post your log of one item - click on the item in history, then button Log, then Save to file, post it via pastebin.com.

> no one seems to be able to resolve that one problem

Has anyone ever reported this problem?

**Comment by Dudleydogg** [comment]
I am not sure there are many entries when I search but no one actually resolved it, just complained about the UNRAR error. I will try to generate a history Sonarr removes history by default.

error | Mon Apr 15 2019 19:09:32 | Unpack for Killing.Eve.S01E01.MULTi.1080p.HDTV.x264.1-HYBRiS-Obfuscated failed.
-- | -- | --
