### ISSUE TITLE
Cannot download from server where password not required

### ISSUE THREAD

**Issue by tetienne** [nzbget/nzbget#428]
Hi,

I've an account on Tweaknews. This server generate me a unique username (!= login name). In nzbget, news servers section, I added a new server with this username, and with an empty password. Test connection is successful.

But, when I downloaded a files, this error message appeared:
> Could not connect to news.tweaknews.eu: server requested authorization but username/password are not set in settings

Any idea how to solve this?

**Comment by hugbug** [comment]
Try a fake password.

**Comment by tetienne** [comment]
Thx for you answer, but I already tested it without success:

>Authorization for test server (news.tweaknews.eu) failed: 502 Authentication Failed

**Comment by tetienne** [comment]
Empty password check is performed here: https://github.com/nzbget/nzbget/blob/5df06a262655b1945609190b1653428c76bd1cad/daemon/nntp/NntpConnection.cpp#L76

**Comment by hugbug** [comment]
Nzbget sends password only when server explicitly asks for it with response code "381 Password required". A fake password would work if the server doesn't require password.

From the relevant RFC:
>  If the server requires only a username, it MUST NOT give a 381 response to AUTHINFO USER and MUST give a 482 response to AUTHINFO PASS.

It seems your server requires password and you have to figure out what it is. Try asking their support.

**Comment by tetienne** [comment]
I dig deeper, and it appears that tweaknews has also a 2nd password. Using this one, it works fine. 
Sorry for this wrong issue, but the test connection made me wrong.

**Comment by hugbug** [comment]
The "test connection" function is probably broken. It doesn't validate username/password at the moment which is a result of some code changes in connection logic. Need to fix this.
