### ISSUE TITLE
Empty job staying in queue (20.0-testing-r2074)

### ISSUE THREAD

**Issue by Nothing4You** [nzbget/nzbget#432]
Hey there,
after the update failed downloads no longer get removed from the queue, having status queued without any files in it.
I have sent you the related log aswell as the part from jsonrpc/listgroups for the entry via email.

**Comment by hugbug** [comment]
I haven't got the email. Have you sent it to nzbget@gmail.com?

In my quick test I can't reproduce the issue. Does it happen for all failed downloads or only with certain nzbs?

**Comment by Nothing4You** [comment]
I have sent it to nzbget@gmail.com at 18:24 UTC, according to my mail server logs it was accepted by gmail servers. I'll send it again, maybe check your spam folder?

I'm not sure it happens with all of them. Is there an easy way to extract the original nzb from the entry in queue?

**Comment by hugbug** [comment]
Just got you files.

I've tried multiple failures and the items go to history correctly.

To get nzb-file look in directory set by option **NzbDir**.

**Comment by hugbug** [comment]
Still can't reproduce this.
What version you were using before? Can you downgrade and test the same files?
To downgrade just install the older version over. Make a backup of QueueDir first.

**Comment by Nothing4You** [comment]
Was using the latest version available via builtin updater, i think it was stable. will try tomorrow.

**Comment by Nothing4You** [comment]
Just tested with some more nzbs that were originally added by Sonarr. 5 failed and got stuck empty in queue.
I removed the files from history (full delete), downgraded to 19.1 and later back to 20.0-r2075 and tried the same files again manually, can't reproduce it reliably, worked fine.
Any other idea how to improve debugging?

Also tried adding one of the nzbs via sonarr manual search on both 19.1 and 20.0-r2075 and it won't reproduce either.

**Comment by hugbug** [comment]
> Any other idea how to improve debugging?

Install debug version. When the problem occurs - create memory dump of the process: on Windows via task manager, on Linux with "gcore pid" or "kill -6 pid" (the latter terminates the process).
For more info please see https://nzbget.net/crash-dump.

**Comment by Nothing4You** [comment]
Alright, now I have several stuck NZBs in the debug version and I created a core dump. Is there any way to remove passwords from the dump?

**Comment by hugbug** [comment]
>Is there any way to remove passwords from the dump?

With a hex editor probably. Maybe sed or this special [tool](http://bbe-.sourceforge.net/) can do that.
In any case make sure to not change the length of password string.

**Comment by Nothing4You** [comment]
Sent you the dump via email, passwords and api keys zeroed out.

**Comment by hugbug** [comment]
The issue should be fixed now. I've sent you current develop build for testing.

**Comment by Nothing4You** [comment]
So far I haven't had any issues with the new build, I just put a few hundred nzbs in the queue and I'll report once they're complete.

**Comment by Nothing4You** [comment]
Nothing so far, seems like it's fixed now. Thanks.
