### ISSUE TITLE
Performance improvements for big download queue

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#438]
A big download queue consisting of thousands of nzb-files currently represents a challenge for smooth work.

## Slow program start
Big queue means a lot of disk state files in QueueDir. For each file included within nzb-file a disk state file is written into QueueDir. For a queue consisting of thousands of nzb-files that means hundreds of thousands of disk state files. All of them must be read on program start. That's slow.

## Reduced download speed
When the program decides which article to download next it has to go through the whole download queue to find a file with highest priority. For certain program functions such as repair or direct rename certain files must be downloaded with extra priority. That means that every individual file of every nzb-file has to be checked to determine what to download next. That takes CPU resources and limits the maximum download speed. More CPU cores don't help here.

## Work items
- [x] optimize disk state format for faster program start;
- [x] reduce CPU overhead in queue management.

**Comment by hugbug** [comment]
## Slow program start

> Big queue means a lot of disk state files in QueueDir. For each file included within nzb-file a disk state file is written into QueueDir. For a queue consisting of thousands of nzb-files that means hundreds of thousands of disk state files. All of them must be read on program start. That's slow.

This is improved by using a technique similar to hibernate mode in OS. Now, when NZBGet terminates it saves all necessary information about all files into one (large) file in QueueDir. At next start it loads all the info from that one file at once, without need to load pieces of information from each file.

### Results
Tested with download queue consisting of over 6000 nzbs (about 500000 individual (rar, par, etc.) files).

**Time needed to load the queue reduced from 5 minutes to a few seconds.**

**Comment by hugbug** [comment]
## Slow program start

Another issue causing slow program start was in a housekeeping routine which detects orphaned files in QueueDir (and deletes them). The time needed to perform cleanup was immense when tested with a large queue - many minutes.

Using a better algorithm the cleanup time has been drastically improved.

### Results
Tested with download queue consisting of over 6000 nzbs (about 500000 individual (rar, par, etc.) files).

**Time needed to cleanup QueueDir reduced from more than one hour to just a couple of seconds.**

**Comment by hugbug** [comment]
## Total result for "Slow program start" issue
Now the startup time is just a few seconds even with a very large queue.

**Comment by hugbug** [comment]
## Reduced download speed

> When the program decides which article to download next it has to go through the whole download queue to find a file with highest priority. For certain program functions such as repair or direct rename certain files must be downloaded with extra priority. That means that every individual file of every nzb-file has to be checked to determine what to download next. That takes CPU resources and limits the maximum download speed. More CPU cores doesn't help here.

The internal data structures were optimised to reduce CPU overhead when choosing next articles to fetch.

### Results
In my tests the speed has improved from 18MB/s to 50 MB/s. That's still slower than downloading with a small queue (75 MB/s) but a big improvement nonetheless.

**Comment by DaftMav** [comment]
> Now, when NZBGet terminates it saves all necessary information about all files into one (large) file in QueueDir. At next start it loads all the info from that one file at once, without need to load pieces of information from each file.

Amazing update! It took forever to start and now it's only a few seconds. However, I've noticed I have to shutdown NZBget from the settings tab for it to work. Sometimes I forget and just shutdown the PC without doing so and I guess NZBget doesn't do what's described above before terminating. Would it be possible for this process to also run just before terminating on system shutdown, like when windows gives a system shutdown notice?

**Comment by hugbug** [comment]
It should terminate properly on system shutdown. I'll check this.

**Comment by hugbug** [comment]
>It should terminate properly on system shutdown.

Fixed.
