### ISSUE TITLE
Ignore nzb filename, but check contents

### ISSUE THREAD

**Issue by mbirth** [nzbget/nzbget#44]
When generating NZBs from e.g. binsearch, they all get the same filename and NZBget ignores all but the first. Even though they have completely different contents.

NZBget should ignore the filename of the container and just check whether the contents are known. Maybe through a checksum over the whole file or the list of the articles.

**Comment by hugbug** [comment]
That's not a general problem but rather specific to certain nzbs.
Please provide a few example nzbs, via pastebin.com or send them to nzbget@ gmail.com.

**Comment by mbirth** [comment]
I just sent you a mail with 3 nzb files.
1. Put the `metropolis 1927.nzb` into the `NzbDir` folder.
2. Wait until it's picked up and the file renamed to `metropolis 1927.nzb.queued`
3. Rename one of the other files to `metropolis 1927.nzb` and put it in the `NzbDir` folder.
4. When it's picked up, it goes straight to History with this entry in the message log:

```
Collection metropolis 1927 is duplicate to metropolis 1927
```

If you look at the files they're rather different.

**Comment by hugbug** [comment]
Thanks for the examples.

What you describe is a correct behavior - the duplicate check rejects duplicate for the same titles. That's the purpose of the duplicate check - to avoid multiple download of the same title.

You can:
- disable duplicate check completely by setting option **DupeCheck**=no;
- if you need this rarely you can check "Disable duplicate check" when adding files via web-interface.

**Comment by mbirth** [comment]
Coming from Sabnzbd+, I'm used to it checking for contents, not for the name of the container. So what I'm proposing with this ticket is to change this behaviour somehow because the current way is questionable IMHO.

E.g. when downloading a series, I tend to search for the series' name and binsearch lists the most current file on top. The downloaded nzb is named after my search term - which will be the same than that of the last episode last week. With the current behaviour, NzbGet would send the new episode's nzb straight to history.

Disabling DupeCheck helps, but I'd like a dupe check based on contents so I don't download content I've already downloaded - regardless of the filename.

**Comment by hugbug** [comment]
Duplicate check in NZBGet is much more than just content check. The title is very important and can't be ignored. If you want more detail please read https://github.com/nzbget/nzbget/wiki/RSS#duplicates

If you don't use RSS you can disable duplicate check and you'll get the same behavior as in SAB, except that the file content will not be checked but that's not an important check anyway (when used without other duplicate check features, which SAB doesn't have at all).

**Comment by mbirth** [comment]
Okay, I'll disable DupeCheck. Thanks for the explanation.

**Comment by hugbug** [comment]
The actual problem here is binsearch which gives the same name to different titles (episodes in your case). If you would use a normal indexer you would have different names for different episodes.

**Comment by mbirth** [comment]
I'm pretty sure that the problem may persist with other sites where you can compile your own nzb files, too. E.g. [SpotWeb](https://github.com/spotweb/spotweb) also lets you merge multiple NZB files into one and the filename is that of the last source nzb file in the list. If you downloaded the last file before, the merged nzb will be ignored by NzbGet.
