### ISSUE TITLE
Large NZB files not being added into NZBGet

### ISSUE THREAD

**Issue by desimaniac** [nzbget/nzbget#444]
Large nzb files (example ~9.1MB) arent being added. No message in history or logs. 

Tested file: https://omgwtfnzbs.me/details?id=q5dwDQ (also sent to email)

If I manually put this nzb file into the monitored folder, it does work this way. 

NZBget version: 19.1 
Chrome: Version 60
MacOS: El capitan

**Comment by hugbug** [comment]
Works fine in my tests.
Have you tried other browsers?
Please check the browser console for errors.

**Comment by Nothing4You** [comment]
Are you using a reverse proxy like nginx in front of nzbget? It might be blocking larger uploads in the default configuration.

**Comment by desimaniac** [comment]
@hugbug OK. Thanks.

@Nothing4You Yes, I am. Would you know where I should look to fix that ?

**Comment by Nothing4You** [comment]
In nginx it's client_max_body_size

**Comment by desimaniac** [comment]
@Nothing4You That helped! Thank You!
