### ISSUE TITLE
Scripts terminate with unknown status when ControlPassword contains special characters

### ISSUE THREAD

**Issue by BernCarney** [nzbget/nzbget#452]
Took me a while to figure out why my extension scripts weren't working. They would execute and then terminate with unknown status every time. Turns out that if you have special characters at the end of the ControlUser password (in my case `#@!`) it fails to build the rpcUrl correctly. Removing those characters from the end of my password fixed the problem.

```
Thu Sep 28 00:23:29 2017        ERROR   Post-process-script Logger.py for [File name being post-processed] failed (terminated with unknown status)
```

I can add the characters back to my password if you would like a log of what's going on with the scripts.

**Comment by hugbug** [comment]
> my extension scripts

Do you mean default scripts Logger.py and Email.py or scripts you wrote yourself?

In the default scripts the username and password are not properly converted into URL format. If you can fix this I'll gladly accept a pull request.

**Comment by BernCarney** [comment]
Sorry for the confusing wording, I meant any extensions scripts I tried default (Logger and Email) and others (Completion, Safe Rename, and a few others).

I'll see what I can do about fixing it but my scripting knowledge is quite a bit behind my problem solving (aka bang it with a hammer in different spots until it works)... so no promises.

**Comment by BernCarney** [comment]
I figured it out, I'll put in a PR for the fix in a few min.
