### ISSUE TITLE
SSE/SIMD versions of CRC32 and yEnc-decoder routines

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#454]
This issue is to test and evaluate SSE/SIMD versions of CRC32 and yEnc-decoder routines.

Details can be found in [this interesting but long discussion](https://github.com/animetosho/node-yencode/issues/4).

**Comment by Safihre** [comment]
[NZBGet v20-testing implemented SIMD and it's as glorious as I hoped it would be](https://www.reddit.com/r/usenet/comments/79vtyb/nzbget_v20testing_implemented_simd_and_its_as/) 😊

**Comment by hugbug** [comment]
That was a bit of exaggeration to explain improved speeds by SIMD only. It was one of many changes contributed to better performance.

I guess that's how advertisement works though :wink:

**Comment by Safihre** [comment]
Hahah yes sorry, we know indeed the details, but for them it's the end result that counts 🏎
