### ISSUE TITLE
First run: "<snip>/downloads/dst/nzbget.log: No such file or directory" repeated over and over again

### ISSUE THREAD

**Issue by sanderjo** [nzbget/nzbget#455]
**Short**: I suggest to create 'dst' at startup of nzbget, just like the other dirs in 'download'

**Long**:

A bit strange: "<snip>/downloads/dst/nzbget.log: No such file or directory" is repeated over and over again. See screenshot. FWIW: This was after a fresh install of nzbget.

At the second download (and/or after restart?), everything is OK. 

So, hypothesis ... Is <snip>/downloads/dst/ only created after the first download?

I removed /home/sander/downloads/, and tried again. During the first download 1) I get the screen full of errors, and 2) downloads/dst/ indeed does not yet exist (and/but the other dirs are created by nzbget). 
So that seems to confirm my hypothesis.

Wouldn't it be handier if dst is created at the same time as the other dirs? 

During first download, 'dst' does not yet exist:
```
sander@nanopineo2:~$ ll /home/sander/downloads/dst/nzbget.log
ls: cannot access '/home/sander/downloads/dst/nzbget.log': No such file or directory

sander@nanopineo2:~$ ll /home/sander/downloads/dst/
ls: cannot access '/home/sander/downloads/dst/': No such file or directory

sander@nanopineo2:~$ ll /home/sander/downloads/
total 24
drwxrwxr-x  6 sander sander 4096 okt  2 21:28 ./
drwxr-xr-x 10 sander sander 4096 okt  2 21:27 ../
drwxrwxr-x  3 sander sander 4096 okt  2 21:28 inter/
drwxrwxr-x  2 sander sander 4096 okt  2 21:28 nzb/
drwxrwxr-x  2 sander sander 4096 okt  2 21:28 queue/
drwxrwxr-x  2 sander sander 4096 okt  2 21:28 tmp/
sander@nanopineo2:~$ 
```
After first download, the 'dst' is there:
```
$ ll /home/sander/downloads/
total 28
drwxrwxr-x  7 sander sander 4096 okt  2 21:30 ./
drwxr-xr-x 10 sander sander 4096 okt  2 21:27 ../
drwxrwxr-x  3 sander sander 4096 okt  2 21:30 dst/
drwxrwxr-x  2 sander sander 4096 okt  2 21:31 inter/
drwxrwxr-x  2 sander sander 4096 okt  2 21:28 nzb/
drwxrwxr-x  2 sander sander 4096 okt  2 21:31 queue/
drwxrwxr-x  2 sander sander 4096 okt  2 21:28 tmp/
```

![image](https://user-images.githubusercontent.com/1273502/31093471-1cf0cc06-a7b2-11e7-94ca-9c02ee5308b3.png)

**Comment by hugbug** [comment]
**DesDir** isn't created at startup because it sometimes points to an external drive (such as USB disk) which may not be mounted yet if nzbget is started from boot scripts.

I guess the default value for `LogFile` isn't optimal and should be changed from
```ini
LogFile=${DestDir}/nzbget.log
```
to
```ini
LogFile=${MainDir}/nzbget.log
```

**Comment by sanderjo** [comment]
... so one step less deep in the directory, as DestDir=${MainDir}/dst ?

Sounds good!
