### ISSUE TITLE
print the config file name used

### ISSUE THREAD

**Issue by sanderjo** [nzbget/nzbget#456]
I believe I have already asked (or even PR-ed) this, but I can't find it anymore ( I tried https://github.com/nzbget/nzbget/issues?utf8=%E2%9C%93&q=author%3Asanderjo%20 )

Anyway:

To me it can be mystery which config file is used by nzbget.
So: can nzbget print that info on stdout / stderr at startup?

**Comment by hugbug** [comment]
`./nzbget -p` prints it.

**Comment by sanderjo** [comment]
Ah, OK.

```
$ ./nzbget  -p | head -1
ConfigFile = "/home/sander/git/nzbget/nzbget.conf"
```

How about printing the config file name (not the contents) always, right after `INFO    nzbget 20.0-testing-r2118M server-mode`?

**Comment by hugbug** [comment]
> How about printing the config file name (not the contents) always, right after INFO nzbget 20.0-testing-r2118M server-mode?

I don't think that's necessary. Most users use installers and have only one config-file on their systems. For a rare case as yours there is a helpful command already.

**Comment by sanderjo** [comment]
OK, thanks for clarification.
