### ISSUE TITLE
ARM and NEON findings with branch "origin/454-simd"

### ISSUE THREAD

**Issue by sanderjo** [nzbget/nzbget#457]
Hi,

I have some findings/questions about nzbget with SIMD on ARM.

First on **ARM64**:

I downloaded the SIMD version of NZBget (https://github.com/nzbget/nzbget/tree/454-simd) and compiled it on my ARM64 aka Aarch64. That worked. Good.

I wanted to check if it indeed had NEON commands in it. Based on http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0489f/CJAJIIGG.html my assumption is that all NEON command start with a "v"

So I did 

```
sander@nanopineo2:~/git/nzbget$ objdump -d  ./nzbget |  cut -c21- | grep -e "^v" 
vsnprintf_chk@plt>:
vfprintf_chk@plt>:
```
.... strange ... (almos) no v-commands? 

AFAIK: ARM64 always has NEON, so you cannot specify it to the compiler
Hypothesis: maybe nzbget's configure/make does something wrong with the gcc options?
(Or Hypothesis 2: my assumpation and/or objdump method is wrong)

Now back to **ARM32** with plain nzbget (from apt-get):

I used the same method:

```
$ objdump -d /usr/bin/nzbget | cut -c21- | grep -e "^v" | head
vpush	{d8}
vmov.f64	d8, d0
vldr	d6, [pc, #108]	; 1adf0 <_ZNSt8ios_base4InitD1Ev@plt+0x6288>
vmul.f64	d7, d8, d6
vmul.f64	d7, d7, d6
vmul.f64	d7, d7, d6
vmov	r0, r1, d7
vmov	r0, r1, d8
vpop	{d8}
vldr	d7, [pc, #44]	; 1adf0 <_ZNSt8ios_base4InitD1Ev@plt+0x6288>
```
and
```
$ objdump -d /usr/bin/nzbget | cut -c21- | grep -e "^v" | awk '{ print $1 }' | sort -u
vadd.f32
vcmpe.f32
vcmpe.f64
vcmp.f32
vcmp.f64
vcvt.f32.f64
vcvt.f32.s32
vcvt.f32.u32
vcvt.f64.f32
vcvt.f64.s32
vcvt.f64.u32
vcvt.s32.f32
vcvt.s32.f64
vdiv.f64
vldr
vmla.f32
vmov
vmoveq.f32
vmov.f32
vmov.f64
vmovne.f32
vmrs
vmul.f32
vmul.f64
vpop
vpush
vstr
vstreq
vsub.f64

```
... so it looks like the plain nzbget (from apt-get) already contains NEON?

**Comment by sanderjo** [comment]
Ouch: from "AArch64 NEON instruction format": "**The V prefix of ARMv7 NEON instructions has been removed."** See http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.den0024a/ch07s03.html

So ... how can I recognize NEON commands on ARM64? Quote: "ADD V0.4H, V1.4H, V2.4H
is a NEON vector instruction.". So, new guess: "V0." is an indicator?

If so, are the commands below NEON?

```
sander@nanopineo2:~/git/nzbget$ objdump -d nzbget  | grep -i  -e "v[0-9]\."
  4120bc:	4c40a2a0 	ld1	{v0.16b, v1.16b}, [x21]
  4120d4:	4c00a040 	st1	{v0.16b, v1.16b}, [x2]
  43caa0:	4c40a020 	ld1	{v0.16b, v1.16b}, [x1]
  43cabc:	4c00a0a0 	st1	{v0.16b, v1.16b}, [x5]
  43cad8:	4c40a020 	ld1	{v0.16b, v1.16b}, [x1]
  43caf4:	4c00a0a0 	st1	{v0.16b, v1.16b}, [x5]
  43cb10:	4c40a020 	ld1	{v0.16b, v1.16b}, [x1]
  43cb2c:	4c00a0a0 	st1	{v0.16b, v1.16b}, [x5]
  43cb94:	4c40a020 	ld1	{v0.16b, v1.16b}, [x1]
  43cba8:	4c00a0a0 	st1	{v0.16b, v1.16b}, [x5]
  43cbc4:	4c40a020 	ld1	{v0.16b, v1.16b}, [x1]
  43cbe0:	4c00a320 	st1	{v0.16b, v1.16b}, [x25]
  43cc6c:	4c40a280 	ld1	{v0.16b, v1.16b}, [x20]
  43cc8c:	4c00a0a0 	st1	{v0.16b, v1.16b}, [x5]
  44d830:	4c40a020 	ld1	{v0.16b, v1.16b}, [x1]
  44d838:	4c00a260 	st1	{v0.16b, v1.16b}, [x19]
  47f580:	4c40a080 	ld1	{v0.16b, v1.16b}, [x4]
  47f5b8:	4c00a2c0 	st1	{v0.16b, v1.16b}, [x22]
  4a3d00:	4c40a020 	ld1	{v0.16b, v1.16b}, [x1]
  4a3d04:	4c00a040 	st1	{v0.16b, v1.16b}, [x2]
  4aac68:	4c40a020 	ld1	{v0.16b, v1.16b}, [x1]
  4aac90:	4c00a020 	st1	{v0.16b, v1.16b}, [x1]
  4ad058:	4c40a060 	ld1	{v0.16b, v1.16b}, [x3]
  4ad074:	4c00a260 	st1	{v0.16b, v1.16b}, [x19]
  4af678:	4c40a020 	ld1	{v0.16b, v1.16b}, [x1]
  4af698:	4c00a360 	st1	{v0.16b, v1.16b}, [x27]
  4d7afc:	4f01e7a5 	movi	v5.16b, #0x3d
  4d7b10:	4e308442 	add	v2.16b, v2.16b, v16.16b
  4d7b20:	4e241c63 	and	v3.16b, v3.16b, v4.16b
  4d7b2c:	5e080460 	mov	d0, v3.d[0]
  4d7b30:	5e180463 	mov	d3, v3.d[1]
  4d7b34:	0e23bc00 	addp	v0.8b, v0.8b, v3.8b
  4d7b38:	0e20bc00 	addp	v0.8b, v0.8b, v0.8b
  4d7b3c:	0e20bc00 	addp	v0.8b, v0.8b, v0.8b
  4d7b40:	0e023c02 	umov	w2, v0.h[0]
  4d7b8c:	5e080460 	mov	d0, v3.d[0]
  4d7b94:	6e180420 	mov	v0.d[1], v1.d[0]
  4d7bac:	4e228402 	add	v2.16b, v0.16b, v2.16b
  4d7bb0:	5e080440 	mov	d0, v2.d[0]
  4d7bb4:	5e180442 	mov	d2, v2.d[1]
  4d7bb8:	0ea01c00 	mov	v0.8b, v0.8b
  4d7bbc:	0ea21c42 	mov	v2.8b, v2.8b
  4d7bc0:	0e120000 	tbl	v0.8b, {v0.16b}, v18.8b
  4d7bc4:	0e010042 	tbl	v2.8b, {v2.16b}, v1.8b
  4d7bc8:	5e080401 	mov	d1, v0.d[0]
  4d7bcc:	6e180441 	mov	v1.d[1], v2.d[0]
  4d7bd0:	4e030020 	tbl	v0.16b, {v1.16b}, v3.16b
  4d7be8:	6e258c43 	cmeq	v3.16b, v2.16b, v5.16b
  4d7bec:	6e278c41 	cmeq	v1.16b, v2.16b, v7.16b
  4d7bf0:	6e268c40 	cmeq	v0.16b, v2.16b, v6.16b
  4d7bf4:	4ea31c21 	orr	v1.16b, v1.16b, v3.16b
  4d7bf8:	4ea01c21 	orr	v1.16b, v1.16b, v0.16b
  4d7bfc:	4e241c21 	and	v1.16b, v1.16b, v4.16b
  4d7c00:	5e080420 	mov	d0, v1.d[0]
  4d7c04:	5e180421 	mov	d1, v1.d[1]
  4d7c08:	0e21bc00 	addp	v0.8b, v0.8b, v1.8b
  4d7c0c:	0e20bc00 	addp	v0.8b, v0.8b, v0.8b
  4d7c10:	0e20bc00 	addp	v0.8b, v0.8b, v0.8b
  4d7c14:	0e023c01 	umov	w1, v0.h[0]
  4d7c20:	4e318442 	add	v2.16b, v2.16b, v17.16b
sander@nanopineo2:~/git/nzbget$ 

```

**Comment by hugbug** [comment]
The target CPU is determined by compiler settings. Official installer from nzbget download page has two ARM targets: for ARMv5 (soft float meaning floating point arithmetic is emulated) and ARMv7 (hard float, meaning CPU with FPU unit). None of these targets should have Neon code unless I made something wrong during building.

What CPU target is used in your apt-get repository? The repository maintainers may have defined target as ARMvX(replace X with a number)+Neon, which would require a CPU with Neon.

Normal FPU commands start with V too.

**Comment by sanderjo** [comment]
OK. That must be it. 

So 'my assumption is that all NEON command start with a "v" ' was incorrect:
* on ARM32, NEON commands do start with v, but not al v-commands are NEON: also floating point commands
* on ARM64, NEON command do not start with v

Thanks for clarification.
