### ISSUE TITLE
Decoding errors on older ARM CPUs (ARMv5)

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#465]
**v20.0-r2147** showed strange behaviour on a system with an older ARMv5 CPU: crc-check reported errors, par2 confirmed total corruption of downloaded data. Download threads eventually hanged and were cancelled.

The same nzbget binary worked on ARMv7 devices when downloading the same nzbs. V19.1 worked fine on the same ARMv5 device.

After a bunch of debug iterations during several days I've got my [Eureka!](https://en.wikipedia.org/wiki/Eureka_(word)) moment when I remembered that older ARM CPUs have troubles reading of unaligned data and the new **scalar decoder** does just that at [one place](https://github.com/nzbget/nzbget/blob/67245d6ca8e08f92fbb57e660c04e484c7710eee/lib/yencode/ScalarDecoder.cpp#L112).

Attempts to read unaligned data on older ARM CPUs result in a garbage loaded into registers; no exceptions, crashes or signals occur, which makes it harder to identify the problematic place.

Once the responsible code in decoder was found the fix was easy.

A similar issue may happen in a new (scalar) crc-routine **slice-by-4**. The issue would probably never occurred there because nzbget passes aligned buffer to the routine. But fixed too nonetheless, to make the routine universally usable.

Pinging @animetosho to incorporate the fix into upstream.

**Comment by animetosho** [comment]
Well, I learned something today. Never knew that some platforms require alignment. I'm probably lucky that Node/V8 doesn't support ARMv5, but I've fixed the code anyway. Thanks for the info!
