### ISSUE TITLE
Windows file association with *.nzb to download via web interface

### ISSUE THREAD

**Issue by francislavoie** [nzbget/nzbget#469]
If I have a random `.nzb` file that I downloaded and I try to open it with nzbget, it tries to download it in a separate command prompt window. I'd prefer if it silently opened it in the existing process instead. Is that possible?

**Comment by hugbug** [comment]
Yes, use option in installer to associate nzb-files with nzbget.

**Comment by francislavoie** [comment]
Ah, I see. I was looking in the settings, didn't see it there. Haven't run the installer in years, because the updater works so well! 😛
