### ISSUE TITLE
Invalid message-id used in connection test

### ISSUE THREAD

**Issue by JvGinkel** [nzbget/nzbget#471]
https://github.com/nzbget/nzbget/blob/ce844367e7e3aa69ba872400ec4cde6c117fa6c6/daemon/remote/XmlRpc.cpp#L3320

The message-id used for the test is an invalid message-id. If you are testing against a strict usenet provider you will receive a response code `501` and not a `4xx` code as you are testing against and now the test will fail because of this.

Solution would be to change the message-id to a valid one like `<connection@test>` but even then when someone create this message-id you will receive a `220` response code so the if-statement will still fail because of this as you want a response code starting with a `4`.

In my opinion the best solution would be to test against a valid msg-id and accept the `220` and the `430` response code.

**Comment by hugbug** [comment]
Why do you think it's invalid? RFC 3977 states only:

> message-id is  an arbitrary opaque string that merely needs to meet certain  syntactic requirements

Without defining those "syntactic requirements".

**Comment by JvGinkel** [comment]
See https://tools.ietf.org/html/rfc1036#section-2.1.5

```
The "Message-ID" line gives the message a unique identifier.  The
    Message-ID may not be reused during the lifetime of any previous
    message with the same Message-ID.  (It is recommended that no
    Message-ID be reused for at least two years.)  Message-ID's have the
    syntax:

                     <string not containing blank or ">">

    In order to conform to RFC-822, the Message-ID must have the format:

                          <unique@full_domain_name>

    where full_domain_name is the full name of the host at which the
    message entered the network, including a domain that host is in, and
    unique is any string of printing ASCII characters, not including "<"
    (left angle bracket), ">" (right angle bracket), or "@" (at sign).
```

So there must be a `@` in the message-id

**Comment by hugbug** [comment]
Thanks for the reference. I'll do the change as you suggest.

**Comment by hugbug** [comment]
Fixed.
I can't test this but I hope it will work correct now.

**Comment by Safihre** [comment]
Why request an article at all? SABnzbd doesn't do it and never had any complaints over the years?

**Comment by hugbug** [comment]
We need to send some command to test credentials. Auth requests should be sent only when server requests authorization. Furthermore requesting articles is what nzbget does during download. Therefore that's a perfect test that everything works properly. If the test implementation isn't buggy of course ;)

**Comment by JvGinkel** [comment]
Thanks for the fix! You can test with a free trial account of https://Usenet.farm or I can test it when you created a pre-release version with this fix in it.

**Comment by JvGinkel** [comment]
Just tested `20.0-testing-r2159` and this problem is fixed!

**Comment by hugbug** [comment]
Thanks for testing!
