### ISSUE TITLE
Extraction fails on android but works on desktop using latest r2159

### ISSUE THREAD

**Issue by krispytom** [nzbget/nzbget#478]
Password in the brackets {{ }}
[Modern.Family.S01E03.Kletten.und.Kakteen.{{by USC_ltH3yDmK7U}}.zip](https://github.com/nzbget/nzbget/files/1485036/Modern.Family.S01E03.Kletten.und.Kakteen.by.USC_ltH3yDmK7U.zip)

**Comment by hugbug** [comment]
On desktop you probably have a script which extracts password from file name and sets it into item properties.

**Comment by krispytom** [comment]
I manually added the password on desktop and android. on android still failed

**Comment by hugbug** [comment]
Am I supposed to guess where the problem is?
Could you at least post the log.

In history click on the item, then button "Log", then "Save to file".

**Comment by krispytom** [comment]
user error...
