### ISSUE TITLE
favicon or apple-touch-icon

### ISSUE THREAD

**Issue by hatemzidi** [nzbget/nzbget#482]
i just noticed that when i bookmark nzbget on my iphone, no icon was selected.
it seems to be that the (fav)icon isn't recognized.

while checking the html code, i found that the metas dedicated to the apple-touch-icon are commented.

<img width="909" alt="screen shot 2017-11-24 at 11 51 20" src="https://user-images.githubusercontent.com/926142/33207404-da604cb0-d10d-11e7-9e85-e3bf4c8f2d99.png">

is there any configuration to activate that? 

thanks

ios 11, nzbget 19.0

**Comment by hugbug** [comment]
No one has drawn the icons yet, that's why. If you can help that would be great.

**Comment by hatemzidi** [comment]
aha,

yeah, i can :)
i'll try to make a PR asap.

**Comment by hatemzidi** [comment]
Touch Icons Pull Request #483

**Comment by hugbug** [comment]
Closing this is the issue is now covered in PR.
