### ISSUE TITLE
saveconfig is broken

### ISSUE THREAD

**Issue by lemnos** [nzbget/nzbget#484]
The saveconfig JSONRPC endpoint does not appear to properly parse the request parameter. It assumes the first element in the serialized map is the name regardless of what the key actually is, thus

[ { "Name": "name", "Value": "value" } ]
[ { "Value": "name", "Name": "value" } ]

do not produce the same result which makes many JSON RPC libraries which do not care about serialization order unusable.

**Comment by hugbug** [comment]
There is a number of limitations in JSON-RPC and XML-RPC implementation in NZBGet. Fixing this requires more efforts than it's worth. Especially because no external app needs this particular API-method.
