### ISSUE TITLE
The application is missing the 'httpOnly' cookie attribute

### ISSUE THREAD

**Issue by walterwhite81** [nzbget/nzbget#485]
Found a small flaw on internal network nzbget configured without https.

Solution type: Mitigation
Set the 'httpOnly' attribute for any session cookie.

The cookies:
Set-Cookie: Auth-Type=http
Set-Cookie: Auth-Token=(removed)
are missing the "httpOnly" attribute.

Vulnerability Insight
The flaw is due to a cookie is not using the 'httpOnly' attribute.
This allows a cookie to be accessed by JavaScript which could lead to session hijacking attacks.

References
URL:https://www.owasp.org/index.php/HttpOnly
URL:https://www.owasp.org/index.php/Testing_for_cookies_attributes_(OTG-SESS-002)

**Comment by mvdpoel** [comment]
yes please

**Comment by hugbug** [comment]
As you suggested added `HttpOnly` to `Auth-Token`.

`Auth-Type` is used in javascript though.
