### ISSUE TITLE
Unpack in destdir?

### ISSUE THREAD

**Issue by damianeickhoff** [nzbget/nzbget#487]
People,

I've installed NZBGet lately, but noticed something weird. NZBGet is unpacking files in the destination directory. I've setup some categories with different destinations on the same hard drive. But when something is downloading in cat1 its also unpacking in the destdir of cat1. This also happends to files downloaded as cat2, that are being unpacks in the destdir of cat2. 

The last time I used NZBGet, is was unpacking the files in the downloaded section. 

Did I do something wrong? Its very annoying because i'm using Plex, so it keeps updating with unpack files.

Like to hear from you guys!

**Comment by hugbug** [comment]
What you describe is a correct behaviour. Files are unpacked into destination directory to avoid unnecessary moving and to speed up unpack (if InterDir and DestDir on separate drives). NZBGet has always worked that way.

Plex has an option to configure files to be skipped from scanning (such as all files in directories with name "_unpack") but I've read somewhere the feature doesn't work properly. If that is still the case users should fill bug reports to Plex for them to fix the issue.

A workaround would be to use a directory for destination which isn't scanned by Plex and move files into final directory using a pp-script such as VideoSort or EasySort.

**Comment by damianeickhoff** [comment]
Hi Hugbug,

It was my fault. Before I also used categories and set the destination location in the download folder, and not the actual folder where the files would go after unpacking.

So you were right and everything works now like it had to.

Thank you for your reply and information, I'm very grateful!
