### ISSUE TITLE
Windows zip build

### ISSUE THREAD

**Issue by ghost** [nzbget/nzbget#489]
right now Windows just has the EXE build - would be nice for a ZIP build so you can try the program without installing

SABnzbd has this:

http://github.com/sabnzbd/sabnzbd/releases

**Comment by isarrider** [comment]
You can extract the exe with for example 7-Zip...

**Comment by ghost** [comment]
@isarrider no, you cant - it creates an error

![untitled](https://user-images.githubusercontent.com/926619/34483827-9215909a-ef86-11e7-958d-64e34e422c8e.png)

**Comment by isarrider** [comment]
and you can find out easy, that it is because of 32/64 bit binaries...

**Comment by hugbug** [comment]
Sorry but I cannot afford providing support for two kinds of installation.
