### ISSUE TITLE
nzbget crashes for an unknown reason

### ISSUE THREAD

**Issue by NicoLeOca** [nzbget/nzbget#490]
Hi,

I need help here to understand what is going on please.

For a couple of days, Nzbget crashes on a regular basis.
It may have started when I changed the path of the log file.
I am on Windows 10 with last stable NZBGET release v19.1
I changed the path twice (back to the initial place) and apparently in the process, something went wrong.

Now log files are named like this: logs-2018-01-01
and there is no extension to the file
I used to have a *.log file.

also NZbget crashes on a regular basis and it seems it occurs when Nzbget wants to create a new log file.
because when I launch Nzbget again, it creates a new log file.

of course logs don't say anything at all.

Can anyone help me please?

**Comment by hugbug** [comment]
What's current value of option "LogFile"?

**Comment by NicoLeOca** [comment]
Hi @hugbug 
rotate 3 days, if I understand your question well

**Comment by NicoLeOca** [comment]
I just noticed that the log file isn't saved into the path set in Nzbget setting
C:\Users\NicoLeOca\Downloads
instead of
C:\Users\NicoLeOca\Downloads\logs

**Comment by NicoLeOca** [comment]
I just noticed that the log file isn't saved into the path set in Nzbget setting
C:\Users\NicoLeOca\Downloads
instead of
C:\Users\NicoLeOca\Downloads\logs

**Comment by NicoLeOca** [comment]
Hi @hugbug 
You were right, "LogFile" option wasn't properly set.
This is fixed now, by restoring the paths section to default.
Hopefully, Nzbget doesn't crash anymore also.
I close the issue and I'll reopen it if necessary.
Thanks for your help

**Comment by NicoLeOca** [comment]
Hi @hugbug 
unfortunately, the log issue wasn't the reason of the crash
I woke up this morning and Nzbget is crashed again.
it happens no matter if it is downloading or not (it happend in the two conditions)
how can I find out what's going on please?

**Comment by NicoLeOca** [comment]
It crashed again during the night
I launch it back and a new log file is created.
the old one doesn't say anything at all.
just another day on planet Earth

**Comment by hugbug** [comment]
Please follow [this guide](https://nzbget.net/crash-dump) and at best use the latest testing version.
