### ISSUE TITLE
An appended dot should not make TLS certificate verification fail

### ISSUE THREAD

**Issue by nberlee** [nzbget/nzbget#491]
When appending an dot to the end of the news server FQDN TLS certificate verification fails.
So a news server FQDN value of for example: `news.myprovider.com.` is not accepted, although a valid FQDN, and should be validated as correct by the certificate validation with and without the appended dot.

An appended dot will prevent resolution of appended search domains. So the searchdomain `my.searchdomain.local` will not be first appended, which would have made the thirst query `news.myprovider.com.my.searchdomain.local`

Although ndots defaults to 1 in the resolv.conf, thereby not considering the search domain when a dot is in the dns query, it is not a theoretical issue.  Kubernetes has a [default ndots of 5](https://rsmitty.github.io/KubeDNS-Tweaks/), combined with 5 searchdomains, leading up to 6 resolving attempts before it returns a valid response.

Yes this is a quirky Kubernetes thing, but an appended dot is a valid notation. When running NZBget in Kubernetes, you should not have to choose between slow DNS lookups or disabling TLS certificate verification.

**Comment by hugbug** [comment]
Hostname is validated using OpenSSL function `X509_check_host`. If OpenSSL fails the validation then that's probably how it should be. I haven't seen examples trimming the last dot.

Whether DNS resolution takes 20ms or 200 ms doesn't matter much. Once the connection to news server is established it is kept until the whole download queue is completed.

**Comment by sanderjo** [comment]
I think the same (SSL/TLS and handling trailing dot in domain name: in SSL/TLS, or in application) is discussed here: https://bugs.python.org/issue31997

**Comment by hugbug** [comment]
I'm not sure how to handle the dot correctly. Considering the issue doesn't bring any problems except slightly increasing DNS lookup time I'm closing this without fix.
