### ISSUE TITLE
Feature Request: nzbget.conf default for "records per page" for the webui

### ISSUE THREAD

**Issue by switchpants** [nzbget/nzbget#492]
My personal preference is that 10 records per page is too few, so each time I use the webui, I set that number to 30 - history, downloads, log files, etc.

I also compile my own nzbget package from source so I've just been applying my own small patch to change the various webui/*.js files from "10" to "30".  Works great!

Would be nice to have a default setting in nzbget.conf though.  Something to consider for a future release perhaps...

**Comment by hugbug** [comment]
> each time I use the webui, I set that number to 30

That should not be necessary. The last used setting must be saved and restored on next opening of webui. Do you have some browser extensions preventing webui to use LocalStorage?

**Comment by switchpants** [comment]
D'oh!  Yes I do...  Time for additional whitelisting.  Sorry for the trouble!
