### ISSUE TITLE
Crash about once a week on Windows 10

### ISSUE THREAD

**Issue by francislavoie** [nzbget/nzbget#493]
Version 20.0-testing-r2159

Seems random, it crashes when nothing is happening usually (no running downloads, etc)

I have some crash dumps that I can send, where would it be best for me to upload/send them?

**Comment by hugbug** [comment]
If the dumps are created with debug build please send them+log-files to nzbget@gmail.com (via google drive or similar service; compress files).

For more info please see https://nzbget.net/crash-dump.

**Comment by francislavoie** [comment]
Will do when I get back home, thanks.

I did look at that link, but it didn't have any specific contact info.

**Comment by francislavoie** [comment]
@hugbug sent, let me know if they help!

**Comment by francislavoie** [comment]
I'll close this for now - never got around to turning on proper crash dumps but I did see a crash yesterday. It's a super infrequent issue. I'll reopen if/when I actually get a proper crash dump for you. Sorry!

**Comment by hugbug** [comment]
I hope the issue was fixed in #501.

**Comment by francislavoie** [comment]
Oh - will you release a new testing version soon? I can install it and I can let you know if it crashes again (in which case it's not fixed)

**Comment by francislavoie** [comment]
@hugbug Can you make a new testing release soon so I can give it a shot? Still been getting the crashes with the current testing release, which doesn't have your fix in.

**Comment by francislavoie** [comment]
I just updated to the latest version - I'll let you know if I ever encounter a crash.

**Comment by francislavoie** [comment]
@hugbug this happened again with the latest build. 😢 

I'm not running debug, I'll do that now. Do you still want my dump from today (not debug mode)?

This was on 2171 btw, not your build from today.

**Comment by francislavoie** [comment]
Do you think this was the same as https://github.com/nzbget/nzbget/issues/529? If so I can close this again until I get a crash

**Comment by hugbug** [comment]
If you have direct rename active and the crash happened during downloading then it can be #529.
If you continue getting crashes please use debug version and then send me the crash dump.

**Comment by francislavoie** [comment]
Crashes were never when downloading, they're always when idle. I have the
latest debug version running now, I'll let you know if/when it crashes.
It's really infrequent though. :(

**Comment by LtRipley36706** [comment]
I am also seeing this crash about once every 5 days on Win10.

```
Wed Jul 25 02:56:02 2018	ERROR	Unhandled Exception: code: 0xC0000005, flags: 0, address: 0xB2FDB99F
Wed Jul 25 02:56:02 2018	INFO	Detailed crash information can be printed by debug version of NZBGet. For more info visit http://nzbget.net/crash-dump

```

it does occur when idle. Seemingly not doing anything at the time, the previous log entry was at `Wed Jul 25 00:37:02 2018`

As you can see above I'm not running a debug build.. I'm on the latest _stable_ release v20

**Comment by hugbug** [comment]
There are **stable** and **testing** versions. For each of them there are **release** and **debug** builds.

**Debug** builds collect more information on a crash. For info on how to install debug build (stable or testing) please see http://nzbget.net/crash-dump.

**Comment by alphaleonis** [comment]
I too have crashes every now and then when idle. I have installed the debug build and enabled crash dumps. Will let you know if/when I capture a crash.

**Comment by alphaleonis** [comment]
Well, it hasn't crashed in several days now since I installed the debug-build. Will go back to release build and see if it comes back (hopefully not)

**Comment by alphaleonis** [comment]
Okat, I just installed the release version on top of the debug version, and have been running now for 5 days straight without a crash, so I'm not sure if I was running another version initially or what may have caused the problem, but it no longer seems to occur, or at least if it does it occurs very infrequent.

**Comment by hugbug** [comment]
Closing this. Please open new issue if there are still any problems.

**Comment by francislavoie** [comment]
Yeah, I haven't had any problems since, so I think you fixed it. Been using the latest testing version (as of last week or so)
