### ISSUE TITLE
Feature request: defining/enabling download speed limit and direct unpack per category

### ISSUE THREAD

**Issue by woiza** [nzbget/nzbget#494]
Eexample:

category 1: direct unpack = yes, downlod speed limit = 2 MB/s
category 2: direct unpack = yes, download speed limit = unlimited
category 3: direct unpack = no, download speed limit = unlimited
...

What do you think?

**Comment by hugbug** [comment]
Speed limit per category is tricky because more than one download can be active.

Direct Unpack per category is possible but it then also requires Direct Rename per category. I didn't want to add two extra options to categories.

Can you please explain in details why do you need both of these features?

**Comment by woiza** [comment]
I use a ARM SBC (Nano Pi Neo 2 Plus) and USB storage for "streaming" video files. Usually 1 MB/s (category 1) is enough for 720p and 2 MB/s for 1080p (category 2). With these settings and thanks to your direct unpack feature this little device has enough horse powers left to make files accessible via SMB while they are still being downloaded. With these limits my internet connection is not fully saturated and other house hold members can use it too without complaining about bad Youtube or whatever quality. Basically I am trying to optimize bandwidth usage without having to access Nzbget's webinterface and defining it manually.

Some downloads do not have a 100% health rating and direct unpack gets cancelled. This is fine for any file except video. I would like to disable direct unpack and limit download speed for some files being downloaded during daytime (category 3) and have a fourth category with unlimited download speed for files being downloaded at night.

I could help with testing on my Nano Pi Neo2, a Synology DS716+ Nas running Nzbget in a docker container, Macbook Pro 13" 2017, Asus UL30VT with Linux Mint.

**Comment by woiza** [comment]
Getting categories from file names should be possible with this script:

https://forum.nzbget.net/viewtopic.php?t=2875

**Comment by woiza** [comment]
Something went wrong, I didn't want to close the issue. Sorry for the noise.

**Comment by hugbug** [comment]
To configure speed limits at day and night use scheduler.

As for direct unpack per category I still didn't get it why you want to disable it for certain items. What should that bring?

**Comment by woiza** [comment]
Thanks for the hint with scheduler. I wasn't aware of it.

Less entries in log and io (since direct download does not get aborted in the middle of a download and already unpacked files get deleted again), but that's not important. I am happy with the scheduler, thanks.
