### ISSUE TITLE
Feature request: clear history button

### ISSUE THREAD

**Issue by bablat** [nzbget/nzbget#495]
(asking for a friend...)

Clearing the history now requires 7 clicks in two screens (marking history, deleting, deleting messages and all confirmation dialogs). Would be great to have a single clear history button on the main screen, with a proper confirmation diaog, but still much quicker.

Thanks for sharing your work!

**Comment by hugbug** [comment]
Why would you want this? I don't think this is a function which many users need. Furthermore adding a button on the first tab which removes data from other tabs isn't intuitive.
Sorry but I'm not going to do that.

**Comment by zackoch** [comment]
I think what he may be getting after is that sometimes it's nice to clear out the history when the client serving NZBGet blacklists a release. I could see it being useful to put a DeleteAll next to the Delete button on page specific for the tab you're viewing when the Hidden tab is enabled.
