### ISSUE TITLE
Incorrect login attempts should not be logged with plaintext passwords

### ISSUE THREAD

**Issue by kaysond** [nzbget/nzbget#496]
Failed log in attempts to the web UI print the username and password in plain text in the log file and on the interface log. This is a completely unnecessary security risk. If I mistype my username, but enter the password correctly, someone could potentially see the password in plain text. Or, if some other application is compromised and grants access to the log file, that would enable an attacker to target nzbget.

I realize that the password is stored in the configuration file in plain text too, but that's its own, more complicated security issue.

I think just listing the username attempt should suffice. It be more useful to log the IP address of the failed attempt.

**Comment by hugbug** [comment]
IP is already logged (in the latest testing version at least).
It is nice to see login attempts, usually with standard or simple passwords.

Would be not printing of password if it was a correct one resolve the issue?

**Comment by kaysond** [comment]
Printing any password submission in plain text is not good security practice. Even if you skipped printing the correct one, it could still reveal password information.

Suppose I enter the correct username, but typo the password by one character. That attempt would be printed. Then I enter the correct username and password immediately after. Someone with the log file would see that and could use the incorrect attempt to guess the correct password.

I really think the log should just have username and IP for successful and failed login attempts. This is what ftp servers generally do. They never print the password.

**Comment by hamiltont** [comment]
Chiming in: Seeing a password in my log files was unpleasant! Especially since it was a password that was accidentally entered into the wrong htaccess box during some configuration testing. Seeing the username would have been enough to know what had happened

**Comment by hugbug** [comment]
That's how it's printed now:

> WARNING Request received on port 6790 from 127.0.0.1, but username (admin) or password invalid

**Comment by kaysond** [comment]
Thank you!
