### ISSUE TITLE
Feature Request: Allow setting of the time the daily quota resets.

### ISSUE THREAD

**Issue by RXWatcher** [nzbget/nzbget#499]
I believe it's  currently midnight however I'd like to have the daily quota reset at a different time...for me that would be 8pm. I can probably fake it out by resetting the time on the server but I'd rather not because it would mess up logs, etc.

Thank you!
-RX

**Comment by hugbug** [comment]
This is not possible because quota doesn't reset. There are download statistics per day. If download volume for current day reaches quota limit the downloading stops. Days are naturally splitted at 0:00.

**Comment by RXWatcher** [comment]
understood. Thanks for the reply and for nzbget...I'm overdue for a donation to you.  I'll close this.
