### ISSUE TITLE
Execute extension scripts from settings page

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#50]
Sometimes it may be helpful to be able to execute extension scripts from settings page. For example pp-script **EMail.py** could use a button "Send test email". For other scripts something like "Validate settings" or "Cleanup database" may be useful too.
- [x] provide a way for scripts to define which buttons to put on settings page;
- [x] when clicking on a button - execute the script;
- [x] send additional env vars to inform the script that it's running in a special context;
- [x] pass all (unsaved options) as if they were already saved in order for script to validate or use the (not yet saved) settings;
- [x] show script's output in a dedicated modal window (similar to the one used for built-in updates).
- [x] ~~optional: provide a way to terminate the script if it hangs, directly from that new window~~;
- [x] extend EMail.py with button "Send test email" as an example of the new functionality;
- [x] update wiki with a description of the new functionality.

**Comment by BlkChockr** [comment]
While you're doing this, could you also add the name of the downloaded file to os.environ? I need this for a Queue-Script! :)

**Comment by hugbug** [comment]
Please don't highjack unrelated issues :)

I'm not really sure what you mean. Can you please create a separate issue or (better) a forum topic and explain in more details?

**Comment by litfoo** [comment]
I think a 'Test e-mail' function would be very useful too.

**Comment by CBers** [comment]
Any update when/if this will be implemented please ??

**Comment by hugbug** [comment]
That's one of the interesting features for v17.

**Comment by CBers** [comment]
OK, thanks :)

**Comment by sarsipius** [comment]
Will definitely be a welcome addition.

**Comment by CBers** [comment]
Just updated to v17 stable, but can't see the test email option in the EMAIL page ??

Did it not make the release ??

**Comment by hugbug** [comment]
No, it's not. Sorry for that.
Other things were more important at that time.

**Comment by CBers** [comment]
No worries.

A future release perhaps ??
