### ISSUE TITLE
Opens Post Process in Apps

### ISSUE THREAD

**Issue by Kurchunk** [nzbget/nzbget#502]
Whenever I run a post process the process runs in the app I associated with it - instead of in an interpreter:

For example if I run a Python file it will open with Pycharm.

If I run a bash/sh file it will open in Notepad++

How do I change this so the script actually runs?

**Comment by hugbug** [comment]
> runs in the app I associated with it

Correct

> instead of in an interpreter

Because Windows doesn't have a way to associate an interpreter.

You should configure the system to launch a correct interpreter for open-command. Alternatively use option **ShellOverride** in NZBGet.

**Comment by Kurchunk** [comment]
Where can I find how to do both of those?

I went into Windows and changed the default apps, but it had no effect.

- and I'm not certain how to use ShellOveride.

I tried using: python=[Windows path to the python.exe file]
which seemed to work for python, but the process stills (but doesn't open Pycharm) - and I don't know what to associate with sh files

**Comment by Kurchunk** [comment]
If anyone is curious...

I found the solution in an NZBGet thread. Attempting to change the interpreter in Windows didn't work. I found the **ShellOverride** option under the **Extensions** options.

The override is written like so:

[.extension] = [path to interpreter]  >> .py = C:\Program Files\Python27

Note that there _is_ a period proceeding the extension.

Answer found [here](https://forum.nzbget.net/viewtopic.php?f=3&t=2565#p16676).
