### ISSUE TITLE
Error following v13->v19.1 upgrade

### ISSUE THREAD

**Issue by barbequesauce** [nzbget/nzbget#503]
Hi - upgraded from v13 to v19.1 today, after discovering how out-of-date the Debian package was...

Copying over the old config file, I've had to make a few changes. I'm pretty sure that's part of why I'm getting this error when accessing the Settings page:

```
Error in http://myhost.local:myport/nzbget/config.js (line 139)

TypeError: undefined is not an object (evaluating 'serverTemplateData[0].Template')

```
Any thoughts?

**Comment by hugbug** [comment]
Reinstall and then restore old config as described in https://nzbget.net/backup-and-restore-settings.

**Comment by barbequesauce** [comment]
Thanks. I went through this... still getting the above error.

**Comment by barbequesauce** [comment]
Happy to provide a sanitized copy of the old config if it helps?

**Comment by barbequesauce** [comment]
I've figured it out - the Debian package has a hardcoded WebDir path of /usr/share/nzbget/webui which breaks the project-packaged file structure of ${MainDir}/webui.

Discovered this through systematically uninstalling & reinstalling plus importing the old config one section at a time...

**Comment by hugbug** [comment]
The manual I've linked above explicitly says to not restore PATH-section. I guess you've missed that part.

**Comment by barbequesauce** [comment]
I did see that - but as it was an install on the same machine, and the warning was about moving a config to a new machine, I didnt expect the warning would apply... my mistake.

Thanks again!

**Comment by hugbug** [comment]
You are right. It's indeed not obvious. I'm glad it works now 😉
