### ISSUE TITLE
Throttled speed on one machine while running fine on the other?

### ISSUE THREAD

**Issue by ryanschmidt** [nzbget/nzbget#504]
I am running 19.1 on both a Mac Mini and a Mac Pro. The Mac Mini's specs are notably inferior to the Mac Pro. I recently set the Mac Pro up as the new primary downloading machine due to the additional RAM and processing power. Since setting up the Mac Pro, I've downloaded roughly 6TB on the two machines and I've noticed a very strange pattern.

My internet connection maxes out at 10 MB/s. When downloading on the Mac Mini, I am always seeing 8.5 - 10 MB/s which is what I'm used to. However on the Mac Pro, I have never seen higher than 5.5 MB/s. It is consistently between 4.4 - 4.8 MB/s.

I've done a few tests with the same NZBs. These numbers are consistent across multiple days, multiple NZBs.

- Both machines downloading: Mac Pro ~4 MB/s, Mac Mini ~6 MB/s
- Mac Mini only downloading: ~10 MB/s
- Mac Pro only downloading: ~4 MB/s

I've reset the settings on both to default and then simply configured the destination folders. They are vanilla other than that and the usenet servers which are identical across both machines. I've tried using a weaker cipher on the Mac Pro but that made no difference so I put it back to default.

The Mac Mini saves to a external hard drive as does the Mac Pro. Both drives are the same speed.

I figured it's a long shot, but does anyone have an idea what could be causing this "throttling"?

**Comment by hugbug** [comment]
You can try [Performing Speed Tests](https://nzbget.net/performing-speed-tests).

**Comment by ryanschmidt** [comment]
I didn't have any luck determining the issue by running the speed test. As mentioned above, it really seems like the speed is throttled because it pegs right under 5 MB/s when I know that download can go faster.

Is it possible (in the meantime) to setup one machine to do the downloading and the other to do the unpacking? I haven't been able to find anything about a machine just doing the unpacking. Any ideas?

**Comment by hugbug** [comment]
What was the speed during speed test?

**Comment by hugbug** [comment]
Closing this for now due to lack of feedback. If you need further assistance feel free to reopen.
