### ISSUE TITLE
"DestDir" NOT Being Honored

### ISSUE THREAD

**Issue by Bowsa2511** [nzbget/nzbget#505]
My main directories are on my SSD, but when leaving the program alone space fills up due to files that need manual processing effectively stopping the program due to space issues on the main drive. I've therefore set the "DestDir" as my Hard-Drive with A LOT more space capable of storing all these files that need extra processing. 

But even with that, complete files are still being placed/completed in the main drive.

**Comment by hugbug** [comment]
I'm sure DestDir works. Maybe another program (run after nzbget) moves them?

**Comment by Bowsa2511** [comment]
I have Sonarr/Radarr, but I'm watching it the process the live. After the files are downloaded in intermediary, they're unpacked/extracted into the "complete" folder. It's not honoring the DestDir
