### ISSUE TITLE
Feature request: better login page

### ISSUE THREAD

**Issue by Aimhere2k** [nzbget/nzbget#506]
Hi,

I have security (user name and password) set up on my NZBGet installations. Whenever I first load up my web browser and go to my NZBGet home page, I get the request to log in as a "basic HTTP authentication", e.g. a pop-up window that appears over the main browser window. This is not compatible with my password manager (LastPass), so I always have to type in my user name and password by hand.

Would it be difficult to recode the NZBGet authentication to use an embedded in-page form for logging in?

**Comment by nomandera** [comment]
I would assume

settings > security > formauth

is what you are looking for

**Comment by Aimhere2k** [comment]
Ahh, yes, that would help. Unfortunately, I have NZBGet installed on my Synology DS413j via the Synology Package Center and a package from SynoCommunity, and they have yet to update beyond NZBGet v16. I'm not sure how to go about updating it from a command shell.

**Comment by Safihre** [comment]
Get it here: https://github.com/SynoCommunity/spksrc/issues/3138

Test package has been used by many, just working out some kinks. Let us know if anything goes wrong with the update. 
After using this new package you can update from within nzbget itself. No longer dependent on SynoCommunity.
