### ISSUE TITLE
All files Queued -non responsive

### ISSUE THREAD

**Issue by ellis1884** [nzbget/nzbget#507]
all files are queued and I can't start them nor set them to paused, no issues apparent in logs and restarted multiple times, (current version in docker) I did run out of NAS/HDD space and I think this has somehow flipped them to queued.

**Comment by hugbug** [comment]
You can click in an individual item, then in button "Log" to see if any errors were logged for the item.
To fix try deleting items (test with one first), then use "Download again" from history.
