### ISSUE TITLE
new-server groups: connection provisioning

### ISSUE THREAD

**Issue by roiz-git** [nzbget/nzbget#510]
as a user I would like to define the number of allowed connection per server group and nzbget will make sure connections are not exceeded between all the servers within that same group.

**Comment by hugbug** [comment]
Just set connections per server and it'll have the same effect.

**Comment by roiz-git** [comment]
Do you mean the max connection per account into all of its related servers?

**Comment by hugbug** [comment]
I mean option "ServerX.Connections" which sets how many connections are to use for a particular news-server.

You probably misunderstand the purpose of option " ServerX.Group", which is a prevention of unnecessary requests for failed articles for accounts on the same server.

**Comment by roiz-git** [comment]
ummm...but I do get a lot "connection exceeded" messages when I have multiple servers defined (of the same account)

**Comment by hugbug** [comment]
> when I have multiple servers defined (of the same account)

Why would you do that?

**Comment by roiz-git** [comment]
load balancing/redundency

**Comment by hugbug** [comment]
Split connections between servers. For example 20 connections for US server and 30 connections for EU server (if total number of allowed connection is 50). This is if you have a superfast Internet connection, otherwise use as little connections as possible.

**Comment by roiz-git** [comment]
> Split connections between servers. For example 20 connections for US server and 30 connections for EU server (if total number of allowed connection is 50)
>
Thus the provisioning feature request :), because if server A has 20 connections and it is not available I am 20 connection short, while a provisioning feature with priorities between servers will allow me to utilize the connections better.
I have 100Mbps connection however I get a realistic speed of 4-7 MB per second.

**Comment by hugbug** [comment]
Connection management is very tricky. I could possibly implement your request if that would be easy but it's not and the benefits are almost non-existent. That's why this will not be implemented.

And with 100Mbps you don't need that feature anyway as you can saturate your Internet connection with 5-10 connections.
