### ISSUE TITLE
Provide portable installation/ZIP

### ISSUE THREAD

**Issue by aureq** [nzbget/nzbget#511]
Hi,

In addition to the .exe files, it would be great to provide a .zip archive to run nzbget from anywhere.

Thanks

**Comment by hugbug** [comment]
Sorry but I cannot afford providing support for two kinds of installation.

**Comment by aureq** [comment]
@hugbug I think it's ok if you don't support that installation mode. You could even include a message saying it's not supported. After all it's for advanced users. 

I just thought it would be convenient to have a .zip with everything needed rather than having to install NZBGet through the installation program, copy the core files and then uninstall NZBGet.

As it turns out, NZBGet runs fine outside of the default installation. I did the following (but it's totally unsupported)
* `MainDir` must have a full path (ie: `D:\...\...`) not just a relative path.
* `NzbDir`, `QueueDir`, `TempDir` should contain a path with `\` and probably not `/` like in the default conf (20.0 beta)
* Add your own NNTP server and custom settings.

And to run NZBGet from the command line: `nzbget.exe -s -c path\to\custom\nzbget.conf`

**Comment by hugbug** [comment]
I've learned over years that Windows users have troubles with zips installations. That's why the installer was created. As I've said above I'm not going to offer two different kinds of installation.

**Comment by aureq** [comment]
It's OK. Thank you for considering it this issue and taking the time to reply to it.

**Comment by reallyuniquename** [comment]
In case someone comes here through the search. Unpack installer with 7z. Copy `nzbget.conf.template` to `nzbget.conf`. NZBGet supports various internal variables like `${AppDir}` so there is no need edit path. Then launch it with `nzbget.exe -s -c nzbget.conf`.
