### ISSUE TITLE
Daemon process doesn't change identity

### ISSUE THREAD

**Issue by aureq** [nzbget/nzbget#513]
Hi,

I've set `DaemonUsername` as `aureq` and run the service from the command line `nzbget -D`, however, the process continues to run as `root` (uid=0, gid=0) and create files under the same identity. Am I missing something?

**Comment by hugbug** [comment]
DaemonUsername works only if the process is started by root.

**Comment by aureq** [comment]
Yes, that's correct and this is also what I'm doing.

**Comment by hugbug** [comment]
Unfortunately errors occurring during changing of user account are not logged.
Maybe you could run NZBGet under `strace` and look for result code from function `setuid`?
Here is the relevant code place -
 https://github.com/nzbget/nzbget/blob/develop/daemon/main/nzbget.cpp#L938.

**Comment by aureq** [comment]
Hi,

NZBGet version: `nzbget version: 20.0-testing-r2159` 
OS: Linux `Debian GNU/Linux 9.3 (stretch)`
Strace command: `strace -f ./nzbget -D >strace 2>&1`

After capturing and reading the output of `strace`, I can see that `getuid()` is called. I can also see the calls related to `getpwnam(m_options->GetDaemonUsername());` and shortly after `signal()`. However, I can't find anything about `setuid()`.

This seems to indicate that the process is correctly executed as `root` (uid = 0), but something fails when retrieving the user profile. Either `m_options->GetDaemonUsername()` doesn't return the right information (no logs for that) or the value passed to `getpwnam()` isn't as expected somehow.
I've double checked the string `DaemonUsername` and its value to avoi any typo.

Last, to avoid some randoms due to my local environment, I did the exact same on EC2 using `Ubuntu 14.04.5 LTS` and it's the same. Despite setting a username, the process identity remains set to `root`.

@hugbug Is this all you need? Or did I miss anything?

**Comment by aureq** [comment]
So, very briefly as part of trying to figure out what;s happening.

* `./configure --prefix=/usr/local/nzbget` is not honored throughout the program, especially after installing `nzbget.conf` via `make install-conf`, NZBget doesn't try to read `/usr/local/nzbget/etc/nzbget.conf`
* `nzbget.conf.template` doesn't come installed by default
* somehow the daemon managed to switch identity (cool), but starts anyway even is log file can't be opened which may not be great

I'm very likely doing something wrong here. But maybe this might help someone else.

**Comment by hugbug** [comment]
What's the current status, have you managed to make it work?

**Comment by dadatuputi** [comment]
> 
> 
> What's the current status, have you managed to make it work?

I was able to get it to work by setting the setuid bit on the nzbget executable: `chmod +s nzbget`

**Comment by jeffreylees** [comment]
Really really sorry to thread necro this, but @dadatuputi thanks so much, from a year and a half in the future. I've been trying to solve the same problem all day, and stumbled on this. That was my solution as well.
