### ISSUE TITLE
Feature: Add browse button to MainDir path to make it easier for newbies

### ISSUE THREAD

**Issue by ghost** [nzbget/nzbget#514]
The same way you can browse folders to add local NZBs in the "add NZB" dialog, there should be a browse button on the MainDir path input field to make it easy for newbies to navigate to the path they want to use. 

Not a high priority feature, but a nice little addition to make NZBGet more user friendly.

**Comment by Nothing4You** [comment]
This would require a completely different implementation.
Reasons:
1. JavaScript code can't see the full path on the filesystem using the file dialog, a remote file browser would have to be implemented.
2. NZB upload accesses the users local PC while nzbget might be running on a remote machine; MainDir location is for a path on the machine running nzbget.

**Comment by ghost** [comment]
@Nothing4You We can at least enable it for when nzbget is running via localhost, which many people use.

**Comment by hugbug** [comment]
It will not work even on localhost as there is no JavaScript API to chose directories.

Even in "add NZB" dialog our script sees only file content and name, without path.

Implementing an own dialog is possible but is a lot of work and isn't worth it.

**Comment by ghost** [comment]
@hugbug Fair enough, I'll close this issue.
