### ISSUE TITLE
Don't have to login when accessing via reverse proxy

### ISSUE THREAD

**Issue by legoblokje** [nzbget/nzbget#515]
I've got nginx configured as a reverse proxy but when I access NZBGet trough it I don't have to provide my login credentials. This happens both with and without FormAuth. If I access NZBGet directly (ip-adress:port) I do have to provide login credentials. I've also reloaded and restarted NZBGet many times to no avail.

Tested on: 19.1 and 20.0-r2159

**nginx config:**
```
server {
    listen 80;
    server_name subdomain.domain.tld;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_redirect off;
    proxy_set_header Host $http_host;

    location /nzbget {
        proxy_pass http://localhost:6789/nzbget;
    }
}
```
**NZBget (security) config:**
```
ControlIP=0.0.0.0
ControlPort=6789
ControlUsername=user
ControlPassword=pass
RestrictedUsername=
RestrictedPassword=
AddUsername=
AddPassword=
SecureControl=no
SecurePort=6791
SecureCert=
SecureKey=
AuthorizedIP=127.0.0.1
DaemonUsername=user
UMask=1000
```

**Comment by hugbug** [comment]
It's not clear what you want. Assuming you want login dialog when accessing via proxy. Then set option AuthorizedIP to empty.

**Comment by legoblokje** [comment]
Thanks that fixed it!
