### ISSUE TITLE
POSIX installation doc update

### ISSUE THREAD

**Issue by aureq** [nzbget/nzbget#516]
Hi,

As part of building nzbget on Posix system, it would be good to ensure users have installed `pkg-config`, otherwise build dependencies (`libxml2`) won't be found. `pkg-config` is only a suggested dependency of `libxml2-dev` [ref](https://packages.ubuntu.com/xenial/libxml2-dev) and doesn't install by default.

I verified this on a fresh EC2 instance (ap-southeast-2) using Ubuntu 16.04.

Thanks

**Comment by hugbug** [comment]
Thanks.

Added a hint about pkg-config to the documentation page.
