### ISSUE TITLE
19.1 Not asking for credentials behind reverse proxy

### ISSUE THREAD

**Issue by plankes-projects** [nzbget/nzbget#517]
Just in case this was not seen yet (I did not find a ticket for this).
https://www.reddit.com/r/usenet/comments/7hpzlo/nzbget_191_not_asking_for_credentials/

I also have this issue on a clean install. 
Seems like authentication is skipped if accessed from localhost.

Setup:
```
docker run --rm \
           --name nzbget \
           -p 6789:6789 \
           -e APP=nzbget \
           -e PUID=<userId> \
           -e PGID=<userGroupId> \
           -e UMASK=022 \
           -e VERSION=stable \
           -e BACKUP=yes \
           -e TZ=Europe/Berlin \
           -v /<local_path>/config:/config \
           hotio/suitarr
```

**Comment by Nothing4You** [comment]
Please check existing issues aswell as configuration options first. Duplicate of #515 and it's just misconfiguration.

**Comment by plankes-projects** [comment]
Thank you! This was indeed a configuration issue from my side.
I had to set the field AuthorizedIP to empty.
