### ISSUE TITLE
Pause on diskspace - Extracting ignored

### ISSUE THREAD

**Issue by if1mad** [nzbget/nzbget#518]
Hello!

I am very impressed with the great work you have done with nzbget, it is truly amazing.

I'm not sure if this is working as intended - When setting a pause when diskspace is X - the queue will pause correctly except for post-processing/extracting.

Is it possible for this to be included?

Thank you!

**Comment by hugbug** [comment]
Unpacking is performed by external tool "unrar", which cannot be paused. Add additional GB to disk space option to take the space required for unpacking into account.

**Comment by if1mad** [comment]
I see, thanks for the quick reply!
