### ISSUE TITLE
Says fetching and failure 

### ISSUE THREAD

**Issue by keremcankabadayi** [nzbget/nzbget#520]
hey there! I'm trying to use NZBget but i got no action so far. I tried different links, servers and nothing changed. It says fetching and after a while failure. I checked my network logs with Little Snitch. It downloads some data from sources but i couldnt find those datas. Any help?

`MacBook Pro (Retina, 13-inch, Late 2013) 10.13.2 Beta (17C79a)`
`NZBget 19.1`

<img width="1279" alt="1" src="https://user-images.githubusercontent.com/23381187/37403888-4efd2446-27a1-11e8-8a9d-394324a91a7b.png">
<img width="1279" alt="2" src="https://user-images.githubusercontent.com/23381187/37403896-51fa2c02-27a1-11e8-8933-7e051bb49995.png">

**Comment by hugbug** [comment]
From your screenshots it seems you are trying to download from web-sites. It's not what NZBGet is for. NZBGet is a tool to download from Usenet. 

You can read more here - https://en.wikipedia.org/wiki/Usenet and https://www.reddit.com/r/usenet/wiki/faq.
