### ISSUE TITLE
Submitting nzb file through webui does nothing

### ISSUE THREAD

**Issue by cjbottaro** [nzbget/nzbget#521]
After submitting an .nzb file, the webui gives me a nice little popup saying "files submitted", but then absolutely nothing else happens. No messages in the log, no messages to stdout (I'm running with args `-s -o outputmode=log`), and nothing in the download queue.

Nzbget is running in a Docker container behind Nginx as a reverse proxy. SSL termination is happening via Nginx, so nzbget is not configured for encryption. I'm logged in as the control user and `AuthorizedIP` is blank.

I am accessing the webui over the internet, not a LAN.

What am I doing wrong? Thanks for the help.

**Comment by hugbug** [comment]
Check option `client_max_body_size` in nginx config.

**Comment by cjbottaro** [comment]
Aaaaahhhhh, thanks a ton, that was it. I didn't realize these nzb files could be so big!
