### ISSUE TITLE
Add debug images to nzbget-version-linux.json

### ISSUE THREAD

**Issue by magma2007** [nzbget/nzbget#523]
Would it be possible to add strings for the debug images (for both testing and stable) to the hosted nzbget-version-linux.json file on nzbget.net/info/?

It will make it easier to incorporate into a docker container versus passing variables, parsing and using logic to determine the proper path to download the appropriate version.

This will make it easier when troubleshooting using a docker container.

**Comment by hugbug** [comment]
The purpose of debug builds is to help me find bugs. Users should install debug builds only when advised to do so. Debug builds are slow and have a lot of logging. When necessary users can install debug build manually. That's totally OK because the next step will be to collect all necessary infos like crash dumps, logs etc. and send them to me. There is no need for a comfortable way to install debug builds via docker settings. Because if a user cannot install debug build via installer (which is a very simple thing to do) he will not be able to do further investigations. That would defeat the purpose of debug builds.

Furthermore, during update via webui only release builds are installed. If you install debug build it will be replaced with release during update. That's OK for rare use of debug builds but would not be OK if you plan a wider usage of them.

**Comment by magma2007** [comment]
Understood, let me explain my thought process.  I currently using the linuxserver/nzbget container and on one of my usenet providers I am getting warning log messages about blocking them repeatedly. but no other messages that would help me debug.

I don't think the sable build is built with debug logging as when I turn it on, I do not get any additional information besides the warning message.

Of course I can build my own container / fork the existing one and modify the Dockerfile to pull down the stable-debug image and then continue troubleshooting but, my thought was that if I am having to go through this, then other probably will as well and by  providing the ability to have them easily choose the debug image for troubleshooting it would help isolate root cause for any problems.

In containers the best practice is to not update the software running in a container, it is to destroy the container and relaunch it with new packages, so your concern about upgrading from a Debug image I believe is very minimal as if the container is built using debug images it will likely be rebuilt with debug images.

If it is too much to ask or still doesn't make sense, then I can move forward with the alternative of me deriving the path from the existing hosted json file.

Thanks

**Comment by hugbug** [comment]
Too much trouble when there is a simple solution: login into container's terminal, install nzbget from debug installer over existing release build installation (that's just too commands - wget/curl + running installer), restart nzbget.

However it is unlikely that you can troubleshoot your issue using debug build, the same for other users. Debug logging is really for developer only. All information which might be of interest for users is either logged in release build too or not logged at all.

In your particular case the blocking occurs when connection to server cannot be established. There must be error messages preceding the message about blocking.

**Comment by magma2007** [comment]
Unfortunately it is not possible to simply overwrite the existing nzbget application as the container is built to only run with that application running.  If it is shutdown, the container stops.  This necessitated me manually editing the dockerfile to use a different image or update it to support the debug images.

As for other messages being generated besides the blocking messages, I didn't see any which is why I was wanting to get the debug image for more details and then prompted my inquiry here about getting a path in the json which would allow me to create a solution that would work for any future issues I (or others run into when trying to troubleshoot.  

No worries, it shouldn't be to hard to derive the download path for the proper image using the version info from the json file, it would just have been much easier if the path was already there like the stable and testing images.  Now I'll have to add additional login or a script to the container to get the debug images.

**Comment by hugbug** [comment]
>  If it is shutdown, the container stops.

That is strange. To my knowledge all nzbget containers allow updating of nzbget via web interface; stopping and starting of nzbget executable is a part of procedure.

>As for other messages being generated besides the blocking messages, I didn't see any 

Can you post your log file via pastebin.com or send it to me to nzbget@gmail.com?
