### ISSUE TITLE
Crash when flushing article cache after direct rename

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#529]
Got crash dumps from a user where crashes occurred during flushing of article cache. The program state was "impossible" and it took a fair amount of time (three months) to collect these crash dumps and analyse them. Only after the third crash dump I finally got an idea of what was happening. 

The critical place is in direct renamer: after renaming a small amount of data downloaded from par2-files is discarded (one article per par2-file) to avoid holding of info for these files, which are rarely used at all (par2-files are needed only for repair). It turned out the discarding of data isn't properly synchronised. As a result the article cache may attempt to write the data which was just deleted from memory.

A proper synchronisation must be developed.

**Comment by JackDandy** [comment]
In this game, at least 50% of the battle is reaching enlightenment - 3 months=nightmare, congrats to you, and kudos to the user.

**Comment by hugbug** [comment]
When a bug happens once a month it isn't a big issue for the user but still frustrating for the developer 😉 

Will be eliminated soon: :bug: :gun:

**Comment by hugbug** [comment]
There is a **bug in the fix** which may lead to unsuccessful attempts to flush articles which in turn produces a lot of logging (a user has reported 85GB log file). Other than large log-file the sub-bug seems to be merely harmless.

**Comment by JackDandy** [comment]
Before/After:
<a name="logs"><img src="https://vgy.me/ulNg8t.png"></a>
Yup, that's a 3.5 Gb log file ;)

**Comment by hugbug** [comment]
Thanks for confirming the fix is working.

These were crazy long logs ;)
