### ISSUE TITLE
Feedback for Readme update

### ISSUE THREAD

**Issue by tifoji** [nzbget/nzbget#53]
Please add the following 3 commands to the documentation for Ubuntu 15.04/most linux releases to run for "./configure" with all options selected

sudo apt-get install libgnutls-dev
sudo apt-get install libncurses-dev
sudo apt-get install libxml2-dev

**Comment by tifoji** [comment]
Apparently the bug with GnuTLS is still there one year later!

So instead of libgnutls-dev, please update to

sudo apt-get install libssl-dev

then

./configure --with-tlslib=OpenSSL

make

sudo make install to install it system wide.

**Comment by hugbug** [comment]
Thank your for your suggestion.

README is a short documentation and can't provide details for specific Linux versions. The names of packages change over time and are different on different Linux variants. Instead README provides general instructions for all POSIX systems.

Nonetheless the manual [Installation on POSIX](https://github.com/nzbget/nzbget/wiki/Installation-on-POSIX) linked from the download page indeed does mention the packages required on Debian/Ubuntu (as example).

Furthermore all these infos are of interest for advanced users who compile themselves. Most users and especially the less tech savvy ones should install from provided Linux installer as explained in manual [Installation on Linux](https://github.com/nzbget/nzbget/wiki/Installation-on-Linux), linked from the download page.
