### ISSUE TITLE
NZBGet.net failing DNSSEC Verification

### ISSUE THREAD

**Issue by articuno1au** [nzbget/nzbget#530]
Apologies if this is the wrong place to post this, but I can't reach the site. NZBGet.net is currently failing DNSSEC which is blocking updates and access to the website. 

I noticed I was unable to update NZBGet. In investigating I noticed I couldn't access the website either. My DNS server returned the following logs
> Apr  4 21:19:28 dnsmasq[611]: 51605 10.1.1.2/59123 query[A] nzbget.net from 10.1.1.2
> Apr  4 21:19:28 dnsmasq[611]: 51605 10.1.1.2/59123 forwarded nzbget.net to 127.0.0.1
> Apr  4 21:19:28 dnsmasq[611]: 51605 10.1.1.2/59123 validation nzbget.net is BOGUS

I ran a DNSSEC verification and noticed a further failure. You can verify the results at [VeriSign DNSSEC Validator](https://dnssec-debugger.verisignlabs.com/nzbget.net) 

**nzbget.net**
:x: No DS records found for nzbget.net in the net zone
:x: No DNSKEY records found
✔️ nzbget.net is a CNAME to nzbget.netlify.com
:x: No RRSIGs found

**netlify.com**
:x: No DS records found for netlify.com in the com zone
:x: No DNSKEY records found
:heavy_exclamation_mark: ns1.netlify.com serial (1522840183) differs from dns3.p04.nsone.net serial (1522762443)
:heavy_check_mark: nzbget.netlify.com A RR has value 35.172.250.236
:x: No RRSIGs found

The only work around is to access _nzbget.netlify.com_ which still leaves the auto update functionality broken.

This isn't something I can contribute a lot to beyond the link at the top. Hopefully it can be resolved.

Love your work btw 👍

**Comment by hugbug** [comment]
I don't think these verification results indicate a real problem. I've tried several sites (google.com, github.com, microsoft.com) in this tool and got the same DNSSEC errors. Yet all these sites work for me as well as nzbget.net.

There might be a problem on your side. If you can't fix it maybe you could use a workaround with adding nzbget.net to your hosts-file.

**Comment by articuno1au** [comment]
You are correct. My apologies for the wasted time.

Turns out the reason is my DNS lookup was running non-recursive and I was getting a bad error message from dig/dnsmasq. I'll add your server's IP directly.

Closing the issue.

**Comment by ppascher** [comment]
I can't resolve nzbget.net using DNSSEC and Cloudflare DNS as my resolver. When I disable DNSSEC it works fine.
[http://dnsviz.net/d/nzbget.net/dnssec/](http://dnsviz.net/d/nzbget.net/dnssec/)
Here is a log from unbound (bottom to top):
```
Aug 24 13:16:30 	unbound 	47081:1 	info: Could not establish a chain of trust to keys for nzbget.net. DNSKEY IN
Aug 24 13:16:30 	unbound 	47081:1 	info: query response was nodata ANSWER
Aug 24 13:16:30 	unbound 	47081:1 	info: reply from <.> 1.1.1.1#853
Aug 24 13:16:30 	unbound 	47081:1 	info: response for nzbget.net. DS IN
Aug 24 13:16:30 	unbound 	47081:1 	info: resolving nzbget.net. DS IN
Aug 24 13:16:30 	unbound 	47081:1 	info: query response was CNAME
Aug 24 13:16:30 	unbound 	47081:1 	info: reply from <.> 1.0.0.1#853
Aug 24 13:16:30 	unbound 	47081:1 	info: response for nzbget.net. DS IN
Aug 24 13:16:30 	unbound 	47081:1 	info: resolving nzbget.net. DS IN
Aug 24 13:16:30 	unbound 	47081:1 	info: query response was nodata ANSWER
Aug 24 13:16:30 	unbound 	47081:1 	info: reply from <.> 1.1.1.1#853
Aug 24 13:16:30 	unbound 	47081:1 	info: response for nzbget.net. DS IN
Aug 24 13:16:30 	unbound 	47081:1 	info: resolving nzbget.net. DS IN
Aug 24 13:16:30 	unbound 	47081:1 	info: query response was CNAME
Aug 24 13:16:30 	unbound 	47081:1 	info: reply from <.> 1.0.0.1#853
Aug 24 13:16:30 	unbound 	47081:1 	info: response for nzbget.net. DS IN
Aug 24 13:16:30 	unbound 	47081:1 	info: resolving nzbget.net. DS IN
Aug 24 13:16:30 	unbound 	47081:1 	info: query response was nodata ANSWER
Aug 24 13:16:30 	unbound 	47081:1 	info: reply from <.> 1.0.0.1#853
Aug 24 13:16:30 	unbound 	47081:1 	info: response for nzbget.net. DS IN
Aug 24 13:16:30 	unbound 	47081:1 	info: resolving nzbget.net. DS IN
Aug 24 13:16:30 	unbound 	47081:1 	info: query response was CNAME
Aug 24 13:16:30 	unbound 	47081:1 	info: reply from <.> 1.1.1.1#853
Aug 24 13:16:30 	unbound 	47081:1 	info: response for nzbget.net. DS IN
Aug 24 13:16:30 	unbound 	47081:1 	info: resolving nzbget.net. DS IN
Aug 24 13:16:30 	unbound 	47081:1 	info: query response was nodata ANSWER
Aug 24 13:16:30 	unbound 	47081:1 	info: reply from <.> 1.1.1.1#853
Aug 24 13:16:30 	unbound 	47081:1 	info: response for nzbget.net. DS IN
Aug 24 13:16:30 	unbound 	47081:1 	info: resolving nzbget.net. DS IN
Aug 24 13:16:30 	unbound 	47081:1 	info: query response was CNAME
Aug 24 13:16:30 	unbound 	47081:1 	info: reply from <.> 1.1.1.1#853
Aug 24 13:16:30 	unbound 	47081:1 	info: response for nzbget.net. DS IN
Aug 24 13:16:29 	unbound 	47081:1 	info: resolving nzbget.net. DS IN
Aug 24 13:16:29 	unbound 	47081:1 	info: query response was nodata ANSWER
Aug 24 13:16:29 	unbound 	47081:1 	info: reply from <.> 1.1.1.1#853
Aug 24 13:16:29 	unbound 	47081:1 	info: response for nzbget.net. DS IN
Aug 24 13:16:29 	unbound 	47081:1 	info: resolving nzbget.net. DS IN
Aug 24 13:16:29 	unbound 	47081:1 	info: query response was CNAME
Aug 24 13:16:29 	unbound 	47081:1 	info: reply from <.> 1.1.1.1#853
Aug 24 13:16:29 	unbound 	47081:1 	info: response for nzbget.net. DS IN
Aug 24 13:16:29 	unbound 	47081:1 	info: resolving nzbget.net. DS IN
Aug 24 13:16:29 	unbound 	47081:1 	info: query response was nodata ANSWER
Aug 24 13:16:29 	unbound 	47081:1 	info: reply from <.> 1.0.0.1#853
Aug 24 13:16:29 	unbound 	47081:1 	info: response for nzbget.net. DS IN
Aug 24 13:16:29 	unbound 	47081:1 	info: resolving nzbget.net. DS IN
Aug 24 13:16:29 	unbound 	47081:1 	info: query response was CNAME
Aug 24 13:16:29 	unbound 	47081:1 	info: reply from <.> 1.0.0.1#853
Aug 24 13:16:29 	unbound 	47081:1 	info: response for nzbget.net. DS IN
Aug 24 13:16:29 	unbound 	47081:1 	info: resolving nzbget.net. DS IN
Aug 24 13:16:29 	unbound 	47081:1 	info: validated DNSKEY net. DNSKEY IN
Aug 24 13:16:29 	unbound 	47081:1 	info: resolving net. DNSKEY IN
Aug 24 13:16:29 	unbound 	47081:1 	info: validated DS net. DS IN
Aug 24 13:16:29 	unbound 	47081:1 	info: query response was ANSWER
Aug 24 13:16:29 	unbound 	47081:1 	info: reply from <.> 1.0.0.1#853
Aug 24 13:16:29 	unbound 	47081:1 	info: response for nzbget.net. A IN
Aug 24 13:16:29 	unbound 	47081:1 	info: resolving nzbget.net. A IN
Aug 24 13:16:29 	unbound 	47081:1 	info: query response was CNAME
Aug 24 13:16:29 	unbound 	47081:1 	info: reply from <.> 1.1.1.1#853
Aug 24 13:16:29 	unbound 	47081:1 	info: response for nzbget.net. A IN
Aug 24 13:16:29 	unbound 	47081:1 	info: resolving nzbget.net. A IN 
```

**Comment by articuno1au** [comment]
Are you using stubby or a similar shim to forward dns requests?

Do you have recursive queries enabled?

NZBGet's DNS configuration is poor, but it is technically compliant. I ended up manually defining their address in my DNS host files to work around it whilst leaving DNSSEC properly enabled.

**Comment by ppascher** [comment]
I am using pfSense unbound resolver with the following settings (which forwards requests to cloudflare using dns-over-tls):
```
do-tcp: yes
minimal-responses: yes
prefetch: yes
qname-minimisation: yes
rrset-roundrobin: yes
forward-zone:
  name: "."
  forward-ssl-upstream: yes
  forward-addr: 1.1.1.1@853
  forward-addr: 1.0.0.1@853
```
Not sure if NZBGet's DNS configuration is strictly compliant, as CNAME records are not supposed to exist at the root of a domain from what I have read ([link](https://serverfault.com/a/613830)).
Though as mentioned in this discussion cloudflare themselves circumvent this with CNAME flattening ([link](https://support.cloudflare.com/hc/en-us/articles/200169056-CNAME-Flattening-RFC-compliant-support-for-CNAME-at-the-root)). Maybe this should be done by netlify in this case.

In any case, if this stays I guess there is no other option than to add a custom dns record or disable dnssec when I want to run the updater.

**Comment by articuno1au** [comment]
> root@PC:/# dig nzbget.net +dnssec
> ; <<>> DiG 9.10.3-P4-Ubuntu <<>> nzbget.net +dnssec
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44386
> ;; flags: qr aa rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
> 
> ;; QUESTION SECTION:
> ;nzbget.net.                    IN      A
> 
> ;; ANSWER SECTION:
> nzbget.net.             60      IN      A       54.252.159.158
> 
> ;; Query time: 0 msec
> ;; SERVER: 10.1.1.250#53(10.1.1.250)
> ;; WHEN: Fri Aug 24 22:46:20 STD 2018
> ;; MSG SIZE  rcvd: 44


> root@PC:/# dig nzbget.net +dnssec +norecurse
> ; <<>> DiG 9.10.3-P4-Ubuntu <<>> nzbget.net +dnssec +norecurse
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 37363
> ;; flags: qr ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
> 
> ;; QUESTION SECTION:
> ;nzbget.net.                    IN      A
> 
> ;; Query time: 0 msec
> ;; SERVER: 10.1.1.250#53(10.1.1.250)
> ;; WHEN: Fri Aug 24 22:46:23 STD 2018
> ;; MSG SIZE  rcvd: 28

So this is the difference. If you allow recursive lookups, then it will work fine. If you don't, it will fail.

I'd love to see the NZBGet team fix this stuff, but clearly they've no interest. Your call on how you'd like to proceed on this ppascher :)

**Comment by mhofer117** [comment]
I have the same problem with unbound as my resolver.

Found this thread which provides an easy workaround and links an open issue:
https://nlnetlabs.nl/pipermail/unbound-users/2018-May/010627.html

```
domain-insecure: "nzbget.net"
```

**Comment by articuno1au** [comment]
Thanks for the extra info.

I think based on the link and the previous information provided by @ppascher, I might re-open this as it does appear that the current nzbget.net configuration is non-compliant and will trip DNSSEC warnings (which was my initial understanding, but obviously self doubt).

Additionally, for those using DNSMasq (including pi-hole implementations), you can modify /etc/dnsmasq.conf to add the following work around
`address=/nzbget.net/104.248.120.187`
The IP address can be obtained by using the DIG tool to obtain the below record (apparently the IP changed since I implemented the workaround..)
`nzbget.netlify.com. 19 IN A 142.93.122.177`

@hugbug et all, given a serious chunk of your user base is going to be security conscious, could we please get some eyes on this. I don't think this would be a hard fix. It's worth noting also that nzbget.net is the only domain I've had to work around in this manner. Everything else JustWorks (tm)

**Comment by hugbug** [comment]
Unfortunately there is nothing I can do about this.

**Comment by mhofer117** [comment]
I believe there are 3 possible solutions you could implement yourself. The first 2 are mentioned in the netlify help here:
https://www.netlify.com/docs/custom-domains/

1. Enable CNAME flattening at your DNS provider if possible (simplest solution)

2. Change your main domain at netlify to www.nzbget.net, not really sure if this will solve the dnssec issue

3. Disable DNSSEC

**Comment by articuno1au** [comment]
If option 1 above isn't available, you can use Cloudflare DNS, which does support flattening, per https://support.cloudflare.com/hc/en-us/articles/200169056-Understand-and-configure-CNAME-Flattening

I'm using Cloudflare DNS for my hosting, works well, and doesn't require you to use their CDN stuff. Also, free.

**Comment by hugbug** [comment]
I have reconfigured the domain to use Netlify DNS instead of using DNS configuration of my registrar. Let's see if it works better now. You may need to wait several hours until the changes are propagated.

**Comment by hugbug** [comment]
> I can't reach the site

I've made some changes. Does it work better now?

**Comment by mhofer117** [comment]
Yes, DNS is responding with a normal A record now which works for unbound and probably any other resolver 👍

**Comment by articuno1au** [comment]
Working for me also with a clean A record and no objections from my systems.

Thanks a bunch @hugbug, really appreciate you looking into it :)
