### ISSUE TITLE
FYI: debian sid: zlib1g-dev needs to be installed too to solve "No package 'zlib' found" 

### ISSUE THREAD

**Issue by sanderjo** [nzbget/nzbget#537]
On Debian Sid, after the usual 

`sudo apt-get install build-essential libncurses5-dev libssl-dev libxml2-dev pkg-config -y`

(from the nzbget posix -> debian / ubuntu instruction), the 

`./configure`

gave the zlib error below.

I needed to do
```
sudo apt-get install zlib1g-dev
```
and everything was fine.

So I'm posting so that Google finds this, and maybe we need it later on.

```
checking for zlib... no
configure: error: Package requirements (zlib) were not met:

No package 'zlib' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables zlib_CFLAGS
and zlib_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

```

**Comment by hugbug** [comment]
Updated docs: added `zlib1g-dev` to example command.
