### ISSUE TITLE
Pinned tab icon for Safari

### ISSUE THREAD

**Issue by foux** [nzbget/nzbget#539]
Contrary to other web browsers, Safari doesn't use the favicon for pinned tabs, but a specific SVG icon. Specifications for those icons are here : https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/pinnedTabs/pinnedTabs.html
It would be great to have one for NZBGet

**Comment by hugbug** [comment]
> It would be great to have one for NZBGet

Yes it would but I don't have an svg icon.

**Comment by hugbug** [comment]
Closing this as I'm not going to draw that SVG icon myself and therefore don't see any TODOs for me in this issue.

I'll be happy to integrate an SVG icon if someone can draws a quality one with the same image as on PNG icons.

Feel free to comment further or reopen the issue if needed.
