### ISSUE TITLE
NZB download failing from NNTmux based indexers

### ISSUE THREAD

**Issue by DariusIII** [nzbget/nzbget#540]
Hello,

i have updated newznab-tmux(NNTmux) to use more of laravel, but now i have experienced a problem that could/should be fixed by mutual effort. 

NNTmux is now using laravel's streamDownload function (https://laravel.com/docs/5.6/responses#other-response-types), which sends the file to sabnzbd/nzbget. 

Better explanation of what it does: https://github.com/laravel/framework/pull/22777

Problem is that is sends additional headers/code before it sends the actual nzb (download works fine in browser and resulting nzb is successfully loaded and downloaded in sab/nzbget). NZBGet reports difference in start **link** and ending **head** tags, but i think it is the same thing in sab (sabnzbd reports an empty nzb file), just reported differently.

I could use the old code, but that beats the point of switching to laravel for NNTmux and i believe it should be fairly easy to fix the problem.

So what i am asking you is: Can we work together to fix the problem in nzbget? 

PS. I have also reached out to safihre for same thing in sabnzbd.

PSS. I have also sent this in an private message to hugbug on nzbget forums.

**Comment by hugbug** [comment]
Can you please provide me with a link which I can put into nzbget to reproduce the issue?

> NZBGet reports difference in start link and ending head tags

A log excerpt would be helpful.

**Comment by DariusIII** [comment]
I have the log on another PC, will send it later. 
Link that fails is: https://www.tabula-rasa.pw/getnzb?id=98c6f7c1-285a-4cb1-b3cb-0caa423c5c3d.nzb&i=1&r=(removed for safety)

You can contact me on nzbget forums in private message, username is same as here,  DariusIII, so i can send you full link.

**Comment by DariusIII** [comment]
Ok, after hugbug contacted me on forums, it was not an problem with sab/nzbget but my own code. 
It was pointed out to me by hugbug, that nzbget was forwarded to login page, i have fixed this in NNTmux code.

I have tested my fix, and now nzbget downloads the releases just fine.
 
I will close this issue, as it was NNTmux and not nzbget related.

@hugbug Thank you for your help in solving this issue.
