### ISSUE TITLE
Suggestion: Change category folder default from ${MainDir}\ to ${DestDir}\

### ISSUE THREAD

**Issue by tastyratz** [nzbget/nzbget#543]
I'm not quite sure why the default would have been the main dir when that is typically on the C:\ drive. It only makes sense for the categories on new installs to have a default of DestDir.  On a setup with Sonarr/Radarr/etc. I was ripping my hair out why my destination directory wasn't respected... until I realized this.

It would be far more intuitive for new users to default otherwise.

**Comment by hugbug** [comment]
MainDir isn't used for categories and categories don't have default DestDir, it's empty by default, which means to use global DestDir with extra folder of category name.

With Sonarr/Radarr they typically are responsible for moving files into final destination. Maybe you should check settings in these programs.

**Comment by tastyratz** [comment]
interesting, I did a fresh install with sonarr/radarr/lidarr/nzbget/nzbhydra2 and my categories were all populated maindir. Maybe it's my mistake then and I forgot doing it somehow.

**Comment by hugbug** [comment]
I guess you are using some third-party package to install nzbget because official installer of nzbget (which you can download from nzbget home page) comes with four example categories and none of them has DestDir set (it's empty in all categories).
