### ISSUE TITLE
unpack to mapped drive fails on Win10 v 19.1

### ISSUE THREAD

**Issue by doubledgedboard** [nzbget/nzbget#544]
I have a mapped drive which is a UNC share mounted to `M:\`

I have my DESTDIR set to `M:\Downloads\USENET\completed`

I get the following failure when attempting to unpack. Note that this works fine using another NZB software with the same path (sabnzbd), so I know it's not a path issue.

Log:

```Sun May 27 2018 05:00:05	INFO	Unrar: UNRAR 5.40 x86 freeware      Copyright (c) 1993-2016 Alexander Roshal
Sun May 27 2018 05:00:05	INFO	Unrar: Extracting from BuZ-tttd1.rar
Sun May 27 2018 05:00:05	INFO	Unrar: Cannot create \\?\M:\Downloads\USENET\completed\The.Lord.of.the.Rings.The.Two.Towers.EE.2DiSC.2002.1080p.BluRay.BD50-SP\_unpack\BuZ-tttd1.iso
Sun May 27 2018 05:00:05	INFO	Unrar: The network path was not found.
Sun May 27 2018 05:00:07	INFO	Unrar: WARNING: Attempting to correct the invalid file name
Sun May 27 2018 05:00:07	INFO	Unrar: Cannot create \\_\M_\Downloads\USENET\completed\The.Lord.of.the.Rings.The.Two.Towers.EE.2DiSC.2002.1080p.BluRay.BD50-SP\_unpack\BuZ-tttd1.iso
Sun May 27 2018 05:00:07	INFO	Unrar: The network path was not found.
```

I also successfully extracted the files manually to the same path using 7zip. Files are good, space is fine. I suspect nzbget or unrar has issues with the mapped drive path.

**Comment by hugbug** [comment]
Please post full log of that nzb - click on nzb in history, then button Log, then "save to file". Preferably post via pastebin.com.

**Comment by doubledgedboard** [comment]
I already pasted the relevant part of the log, not sure how the rest will be useful, but sure.

https://gist.github.com/doubledgedboard/aa441cf5c9371ba1a14a3c6da9bd8783

**Comment by hugbug** [comment]
I ask for full logs because users often omit important messages just like you did:

```
Sun May 27 2018 05:00:05	INFO	Unpacking The.Lord.of.the.Rings.The.Two.Towers.EE.2DiSC.2002.1080p.BluRay.BD50-SP
Sun May 27 2018 05:00:05	ERROR	Could not create directory M:\Downloads\USENET\completed\The.Lord.of.the.Rings.The.Two.Towers.EE.2DiSC.2002.1080p.BluRay.BD50-SP\_unpack: could not create directory M:\: No such file or directory
```

For whatever reason nzbget can't access path "M:\".

**Comment by doubledgedboard** [comment]
"For whatever reason" is unfortunately not very helpful. That's exactly what I'm here to report and to help diagnose.

As I initially stated, it appears it's having issues with mapped UNC paths.

Since the mapped drive is done at login, it will only be valid for processes running as my username, which should be fine for nzbget.exe itself (I confirmed it's running as my username).

However, it may be a problem depending on how the unrar process is spawned.

**Comment by hugbug** [comment]
> For whatever reason nzbget can't access path "M:".

> "For whatever reason" is unfortunately not very helpful.

For you maybe not ;) but for me very helpful. The key part in my message was't "For whatever reason" but rather "**nzbget** can't access path" whereas from you initial report it seemed that "unrar can't unpack into M:". The first error message in log explains why unrar can't unpack - it's because the destination directory wasn't created by nzbget.

It's a very big difference: not being able to unpack to mapped drive and not being able to access mapped drive at all.

In first case there would be an issue with unrar (because nzbget would be able to write into the path) but in the second case there could be a lot of possible reason starting with the incorrect path entered in nzbget settings, then permission issues. Or maybe you are running nzbget as service and services are known to have troubles with mapped drives etc.

Can't you use an UNC path instead?

**Comment by doubledgedboard** [comment]
@hugbug 

Thanks for the response. I already confirmed the path is correct in settings (unless it's getting parsed into an invalid path internally). nzbget.exe is running as my username so the permissions should be good, but I suspect it's having issues with whatever internal library resolves paths and how it accesses them.

I will definitely try a direct UNC path next.

**Comment by hugbug** [comment]
Can you please confirm you start nzbget as application and not as service?

**Comment by doubledgedboard** [comment]
It appears I'm starting it as an application at the moment. I just installed it last night, did not do any setup specifically to make it a service, and it was running in the tray and exited when I exited the app from the tray.

**Comment by hugbug** [comment]
Yes, that's application mode. This excludes service related issues.

**Comment by doubledgedboard** [comment]
Ok. I tried another download this time with UNC path and the extract worked fine.

**Comment by hugbug** [comment]
Could it be that the remote server wasn't available during first test? Can you please repeat the test with M:\?

**Comment by doubledgedboard** [comment]
>Could it be that the remote server wasn't available during first test

Doesn't seem like it, it failed ever time with that file until changing the path.

Repeated test with M:, albeit a much smaller file (~5gb rather than ~40GB) and it succeeded.

I'll close this for now since I can't repro. I'll re-open if I get another repro with more info.
