### ISSUE TITLE
Trailing spaces before 7z extension seem to cause 7z to fail

### ISSUE THREAD

**Issue by RollingStar** [nzbget/nzbget#551]
I get an error like this in postprocessing:

>error	7-Zip: Could not find file 7z

Investigating the file, it looks like the problem is files like this:

    file .7z.001
    file .7z.002

Win10 x64

nzbget 19.1 stable

**Comment by hugbug** [comment]
Can you please send me an example nzb to nzbget@gmail.com?

**Comment by hugbug** [comment]
I've tested with a self constructed nzb contain 7zip archive with filename built just like in your example. The download completed successfully; tested on Linux and Windows.

The nzb you've sent me failed but with other error messages; the error also occurs when unpacking with 7zip without using nzbget.

>  error	7-Zip: Could not find file 7z

Can you post the whole log? Isn't nzbget complaining about not finding executable for 7zip? Default is `${AppDir}/7za.exe`.

**Comment by RollingStar** [comment]
That's embarrassing. Sorry.
