### ISSUE TITLE
Change category for more downloads at once

### ISSUE THREAD

**Issue by mikeo999** [nzbget/nzbget#552]
It would be nice if you could select some active downloads and change the category of them quicky. 
Now we have to change it for every file one by one. Lot of my downloads I needs to change this when the file is loaded in nzbget and I could not place the files in the nzb folder because program is not using it like that.

**Comment by hugbug** [comment]
Select downloads, click edit-button on toolbar, choose category.
Or: select downloads, click on category name (in category column), choose category.

**Comment by mikeo999** [comment]
Thank you. Use nzbget for years and everyday change a lot of downloads and not seen that button.
