### ISSUE TITLE
Windows download named incorrectly

### ISSUE THREAD

**Issue by Taubin** [nzbget/nzbget#553]
The bat file and the link on the nzbget website both attempt to download the following link:
https://github.com/nzbget/nzbget/releases/download/v20.0/nzbget-20.0-bin-win32-setup.exe

However the release is actually located here:
https://github.com/nzbget/nzbget/releases/download/v20.0/nzbget-20.0-bin-windows-setup.exe

The name of the file should be changed to match what the installer bat and the website look for.

**Comment by hugbug** [comment]
Thank you for reporting this.
Fixed. Both download from web-site and update from the app should work now.
