### ISSUE TITLE
NZBGet stopped to work

### ISSUE THREAD

**Issue by Blisk** [nzbget/nzbget#555]
When I open NZBGet web page I get this first

Loading...
Please wait.

and after a while this.

Communication error!
No response received.

I have installed NZBGet on NAS disk version 19.0.0
And no errors in log file

**Comment by hugbug** [comment]
Looks like it crashes.

Please install current version 20 using official installer from nzbget homepage (link to installation manual is on download page). If it crashes too, we'll investigate together.

If your NAS supports docker, there are also containers for nzbget, which are known to work stable.

**Comment by AdamBearWA** [comment]
Same issue for me after upgrade from 19.1 to 20 stable.
For me it's installed on Ubuntu 16.04.04
Logs unhelpful

Clearing browser cache makes no difference, nor does restarting the service (or the server)

edit: not crashed as the service is started and running

edit 2: wait 15 minutes and the interface finally appears

**Comment by hugbug** [comment]
Closing this due to lack of feedback.
Feel free to reopen with further info.

**Comment by hugbug** [comment]
@AdamBearWA 
Your issue is different. Please create a separate issue or (better) a new topic on forum.
