### ISSUE TITLE
Warning with 20.0

### ISSUE THREAD

**Issue by jbrodriguez** [nzbget/nzbget#557]
How can I fix this ?

```
WARNING nzbget.conf(409): TLS certificate verification (option "CertCheck") is limited because the program was compiled with older OpenSSL version not supporting hostname
         validation (at least OpenSSL 1.0.2d is required)
```

**Comment by hugbug** [comment]
There are many ways:
- install newer openssl version and recompile nzbget;
- install nzbget using official installer from nzbget home page;
- disable option CertCheck.

**Comment by jbrodriguez** [comment]
Got it !

I ended up doing

```brew cask install nzbget```

rather than 

```brew install nzbget```

The cask installs the macOS app instead of the command line version.

The only issue is the app looks for the config file in Library/Application Support/NZBGet.

I tried putting it in ~/.nzbget, but didn't work.
