### ISSUE TITLE
Incorrectly tagged pre-release version

### ISSUE THREAD

**Issue by mrhotio** [nzbget/nzbget#559]
Could it be that you by any chance have incorrectly tagged the latest pre-release version as `20.0-testing-r2190` instead of `21.0-testing-r2190`?

**Comment by hugbug** [comment]
Tags and versions are correct. There were no testing releases for v21 yet.

Due to a technical error r2190 has a newer timestamp; unfortunately github has no tools to correct this.

**Comment by mrhotio** [comment]
Ah ok, thanks.

PS: thanks for the best usenet client in the world. :-)
