### ISSUE TITLE
DirectUnpack doesn't seem to work in latest version 

### ISSUE THREAD

**Issue by desimaniac** [nzbget/nzbget#560]
Currently installed: 20.0
Linux (docker based).

Seems like recently all downloads are now piling up in PP-Queued because they are not direct unpacked anymore. 

Uploaded: [Logs & test NZB](https://drive.google.com/file/d/1Hv5JgDpZWE-ry9wFrtkdtvpJ1nQBHGnp/view?usp=sharing)

**Comment by hugbug** [comment]
The log looks perfect. Direct unpacked worked. It took further 22 seconds to unpack remaining files after the download has completed. 

Looks like you have a very speedy line and the unpack is slower than downloading.

**Comment by desimaniac** [comment]
I see. Thanks for looking at it.
