### ISSUE TITLE
Failures are being moved to DestDir

### ISSUE THREAD

**Issue by JoshSchreuder** [nzbget/nzbget#562]
NZBGet 20.0 stable
Lubuntu 18.04

I believe since moving to 20.0 stable / one of the late testing builds, my failures are being moved to DestDir. This is causing problems as they are being post-processed by other apps (Sonarr for example) even though the files are corrupt.

This seems to happen if I get article failures, eg.

```
37 of 625 article downloads failed for "foo.mkv"
```

Status on the download is `PAR: NONE UNPACK: NONE` and the overall status is `FAILURE` yet the files are copied to DestDir.

This seems to be fairly new behaviour that I have only noticed in roughly the last month or so.

**Comment by hugbug** [comment]
This is indeed a bug but it's not new, the program has always behaved like this. This only happens for downloads without par2-files and without archives.

nzb.su started to post a lot of mkv-files without splitting into rar and without par2-files. Not a good Usenet practice definetely.

The bug will be fixed. However why does Sonarr import download which has a clear Failure status in nzbget? That's not correct either.

**Comment by JoshSchreuder** [comment]
> nzb.su started to post a lot of mkv-files without splitting into rar and without par2-files.

Ahh that might explain the recency. I've just re-enabled that one. Might disable it and see how things go.

> However why does Sonarr import download which has a clear Failure status in nzbget? 

Good question - I'm not 100% sure if they're looking at the status, or just looking for the presence of the folder inside of the DestDir. Or perhaps a playable file, which is definitely possible even with missing articles.

Apologies as I didn't see #519 which seems to describe the same or similar issue.
