### ISSUE TITLE
Can't add files to queue

### ISSUE THREAD

**Issue by technikamateur** [nzbget/nzbget#565]
Hi guys,

I installed nzbget on my server, but I'm not able to upload any files.
If I try to upload a file and click the Submit button, a message appears "Files submitted" but nothing happens. The file is also not in the specific nzb folder.
If I copy a file to the nzb folder, everything works fine.

Where could be the issue?

P.S. I have already set the permissions to /home/nzbget to 777, so it should not be a permission problem. Annother Annotation: I am running nzbget behind nginx. Here is a copy of the nginx related config. Maybe it is helpful...

```
  location ~ ^/nzbget($|./*) {
    rewrite /nzbget/(.*) /$1 break;
    proxy_pass http://127.0.0.1:6789;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location ~ ^/nzbget$ {
    return 302 $scheme://$host$request_uri/;
```

**Comment by hugbug** [comment]
See https://github.com/nzbget/nzbget/issues/521.

**Comment by technikamateur** [comment]
thanks for your fast reply! now it works!
You should add this to your [sample conf](https://nzbget.net/behind-other-web-server)
