### ISSUE TITLE
Speed keeps dropping to 0KB/s

### ISSUE THREAD

**Issue by xinseo** [nzbget/nzbget#568]
Using NZBGet Debug latest version and using NewsDemon as NewsServer. Max connections set at 45.

I've tried downloading different stuff with different ages. I've tried 3 different SSL/Non-SSL ports and also tried switching between the EU and US NewsDemon server but I keep facing this issue. My max connection speed is around 5MB/s. I've observed that downloads would reach 4MB/s (that's what I've set scheduler to) and then drop to 0KB/s after a few seconds and then reach max speed again. This keeps on repeating. 

I have the debug log file, where do I send it?

**Comment by hugbug** [comment]
If you remove speed limit - how it works then?

**Comment by xinseo** [comment]
Removing the speed limit fixes the problem entirely. CPU usage is 10-11% and free RAM is 2GB with speed limit so I don't know what's causing this.

**Comment by xinseo** [comment]
Any way to fix this while keeping the speed limit in place?

**Comment by hugbug** [comment]
- What is your speed when not limited?
- Click on remaining time (near speed) to bring up statistics, then click on "Total downloaded". Make a screenshot and post here.
- 45 connections is way to much for 4MB/s. Change to 6-10 connections and test if that helps.

**Comment by xinseo** [comment]
1. I get up to 6MB/s when not limited (in the mornings) and 12MB/s (at night). My speeds double at night

2. Here is the screenshot.
https://i.imgur.com/pA9W39p.png

3. Changed connections to 15. Didn't help at all. Here is a screenshot:
https://i.imgur.com/DHRUXNK.png



When speed limit is removed:
https://i.imgur.com/AhGyniJ.png

**Comment by hugbug** [comment]
What exactly the problem is?
The graph looks OK and the average speed (calculated over 30 seconds) should be as configured.

**Comment by xinseo** [comment]
Check the lower values on the graph. It keeps on going to zero speed when speed limit is active but it doesn't go to zero when speed isn't limited.

**Comment by xinseo** [comment]
When speed limit is active: It goes to zero for a few seconds then jumps back to normal speed.

When speed limit is not active: Speed stays mostly constant.

**Comment by hugbug** [comment]
Speed limiter isn't perfect and can't guarantee speed on per-second basis but at least it can keep the average speed calculated over larger time interval.

**Comment by xinseo** [comment]
So this is normal? I don't face this problem with Deluge by the way.

**Comment by hugbug** [comment]
As long the speed on main speed indicator is maintained the fluctuations on per-second graph are OK. Attempts to smooth the per-second graph would increase CPU load and that's not acceptable.

**Comment by xinseo** [comment]
I just checked Sabnzbd and it works perfectly fine and keeps CPU usage under 10% as well. Not facing this issue with it. I think this issue with nzbget only started a few weeks ago but i don't know what I changed, if anything.

**Comment by hugbug** [comment]
I don't think SAB has a data volume graph. If I remember correctly it has a speed graph and the speed shown there is probably an average speed calculated over multiple seconds.

Anyway I can't make the graph smoother.

**Comment by xinseo** [comment]
Then maybe we can implement an option to disable the graph? I'm losing around 36MBs per minute because of speed falling to zero.

**Comment by hugbug** [comment]
Graph doesn't slow down. Speed limiter does. If you need more speed increase the speed limit.

**Comment by xinseo** [comment]
So concluding, this is normal behavior for speeds to fall to zero every few seconds and then stay like that for 2 seconds and then this keeps on repeating? It just seems so weird. I also checked using Networx to measure speed and it does actually fall to zero every few seconds.

**Comment by hugbug** [comment]
I wonder how v21 (latest testing) performs in this regard. Can you test it?

**Comment by Pentaphon** [comment]
@xinseo I have never had this issue. Using v21 stable right now and I have no issues.
