### ISSUE TITLE
All items stuck in queued, cannot delete.

### ISSUE THREAD

**Issue by hazcod** [nzbget/nzbget#571]
Hi,

Running NZBGet 20.0 on macOS 10.13.6 on a local volume.
For some reason, my whole queue (400 items) was stuck in 'Queued' status.
I could not delete them without deleting download items aswel. (second option)
Resume did not work either. If I checked my download folder, it was greyed out. 
Greyed out folder was fixed by setting creation data, so probably an error on my end.

However, I was only able to resume all my download items once I deleted them to history without already downloaded items, and then manually resumed them.
I turned on debug logging to logfile, but nothing was shown in the log.

**Comment by hugbug** [comment]
Probably the queue was damaged somehow. It's possible that errors were logged when the program was starting.

Anyway since you have the queue repaired already I'm not sure what you expect me to do. If you have a backup of queue when it was in stuck state I could take look.

**Comment by hazcod** [comment]
Just reporting to you so you are aware of this issue, in case it pops up again or you notice something in the code. There were -no- errors with debug logging.

For future reference, how do I take a backup of the queue? Just copy the directory?
