### ISSUE TITLE
Feature request: Edit download path, Auto name truncation over 255 char in workflow

### ISSUE THREAD

**Issue by tastyratz** [nzbget/nzbget#572]
Currently, an NZB is fed to nzbget it can have a very long name that once extracted can easily exceed 255 char. This will lock up the whole workflow with no way to resolve. You can't edit a pending download's path, you can't edit a name after it starts downloading, the only thing you can do is download it all over again and change the path or pick another download.

It would be very helpful if existing downloads could have paths edited (such as when a drive is full or another conflict) and if temp/extracted paths are detected to exceed 255 char then automatically truncate the created folder names.

In the end, it really doesn't matter what things are called while being processed, only that the contents are named properly (or at least created with an error requiring you rename but saving the download).
The most frustrating part is losing the download and starting over or having a good download blacklisted.

As an example: I have Radarr/Sonarr feeding in.
nzbget is set to save to d:\downloads\complete and maybe has a temp dir of d:\downloads\incomplete\tmp and a download dir of d:\downloads\incomplete .
Radarr sends an nzb to download and process. Said download is
reallylongname.nzb

nzbget creates a folder for the download d:\downloads\incomplete\reallylongname\reallylongname.rar
then once downloaded, it extracts to d:\downloads\incomplete\tmp\reallylongname\reallylongname\reallylongfilenameinsidetherar.mkv
If the above path exceeds 255 char, it will fail. Since the path is static in the download and can't be moved or renamed, I can't fix it. The current solution might be to make everything make a mess of the root path and downloading to D:\ but that presents it's own issues.
If nzbget could detect that it would likely exceed 255 char with the option enabled to truncate, it might in an attempt to avoid an error create it as
d:\downloads\incomplete\tmp\reallylo\reallylo\reallylongfilenameinsidetherar.mkv
instead of
d:\downloads\incomplete\tmp\reallylongname\reallylongname\reallylongfilenameinsidetherar.mkv

in addition, if there is an issue with the destination/temp directory (such as path, or space) allowing the download in error to have the directories edited in flight and then re-processed may avoid a complete re-download or blacklisted download which doesn't have an actual error.

Maybe it could be as simple as auto-truncate all created folders not inside the download to x char?
it would need duplicate error handling in that respect though i.e. reallylo, then reallyl1, reallyl2, etc.

The challenge is entirely about the nzb's creating too much unnecessary folder depth through the workflow and failing without the capacity to automatically or manually intervene. 
The bonus of allowing them to be manually edited and reprocessed would overcome space errors as well.
Not knowing what's in the download till you have it makes the x char default folder name limitations more viable. Otherwise it would be error recovery, maybe writing a longname.txt file when checking for errors, etc.

To duplicate the issue, try making a huge char count nzb and importing it. you really do encounter unreasonably long nested naming i.e. releasegroupmrfancyreleases.ripped.by.mr.ripper.fulllengthmoviename.somestudioname.1080p.mkv.aac.5.1.prerelease.webdl.subtitles.2018.nzb

The above example is 137 char long and would fail miserably in almost any path with the current routine.

**Comment by hugbug** [comment]
Manual path editing is an easy way to mess up things. I'm against such feature.

A workaround for (rare) troubleshooting is to edit file "queue" in QueueDir in a text editor and replace paths there. Make a backup of QueueDir and do editing when nzbget isn't running.

> If the above path exceeds 255 char it will fail.

Nzbget supports long file paths (up to 32K characters) on all stages starting from scanning nzb-files through download to par-check/repair and unpack. What step your downloads fail on? Please post an nzb-log - click on an item in history, then button Log, then button "Save to file". Post the log via pastebin.com.

Generally if you want shorter names you should rename nzb-files before adding them to queue. This can be done automatically by an extension script (scan-script) (but some one needs to write it first).

**Comment by tastyratz** [comment]
NZB get does in fact support long file paths, but that doesn't mean the destination file system or path does. If the destination file system is ntfs for example it's going to fail. This seems like a very common use case failure. People might not notice it very often as the download is blacklisted and radarr/sonarr grab the next one/move on or just says missing but I'm sure it happens often.

Renaming these files by hand editing a program file seems like a use case nightmare in an automation implementation.
Doing so via script in flight might work, but could that break something along the workflow such as destination monitoring?

Where it breaks depends on total path length at different steps in the process and when it exceeds 255. Maybe it's too long for the incomplete path, or maybe it fails to unrar because it's too long for the tmp path.

Designing the capacity to assume a 255 limit could avoid these issues. I've encountered this multiple times in the past and changed the everything location to D:\a\ to avoid it (but that's an organizational nightmare). I'd really much prefer the ability to use proper names.

In it's simplest form, would an option to chop new downloaded name& path's to 8 char be difficult to implement?

**Comment by hugbug** [comment]
NTFS supports long paths. Please post a failure log as explained in my previous post.

**Comment by hugbug** [comment]
Closing this due to lack of feedback.
Feel free to post further comments and I may reopen the issue if necessary.
