### ISSUE TITLE
completed download signal/notification not getting to sonarr

### ISSUE THREAD

**Issue by samsepiol59** [nzbget/nzbget#574]
So I have plex connected to sonarr in a way that sonarr warns plex every time a new files is downloaded so that it automatically refreshes the library. This hasn't happened since I decided to switch to nzbget - when I check the sonarr logs, I only see a message for the grab of the episode but not the download/renaming/whatever! Is something happening in nzbget that prevents that?!

**Comment by hugbug** [comment]
NZBGet doesn't communicate with Sonarr or other apps.

Sonarr however can check download status in NZBGet and has a setting to enable/disable this behaviour. It's called something like "Completed download handling".

**Comment by samsepiol59** [comment]
> NZBGet doesn't communicate with Sonarr or other apps.
> 
> Sonarr however can check download status in NZBGet and has a setting to enable/disable this behaviour. It's called something like "Completed download handling".

That's the thing, the download handling is enable!

In radarr this actually works even with movies downloaded via nzbget (plex refreshes), but it doesn't work with sonarr for some reason.

**Comment by hugbug** [comment]
I'm afraid nothing can be done on nzbget side. Since nzbget doesn't communicate with Sonarr there is nothing to fix.
