### ISSUE TITLE
Download sort order no longer updating

### ISSUE THREAD

**Issue by devopsrick** [nzbget/nzbget#576]
Reorganizing downloads, either by column sort, or by individual move up/top/down/bottom no longer adjusts the download order.  They continue to download in the order queued regardless of sort order.  Haven't been able to find any setting that might impact this, so it seems like a bug introduced in a recent version.

Version installed: 21.0-testing-r2220
Platform: QNAP x86_64

**Comment by hugbug** [comment]
Priorities play a role for download order. Other than that the display order and download order is the same.

**Comment by devopsrick** [comment]
Doh...I didn't even notice some were getting added with low priority for some reason. That was it! Thanks!
