### ISSUE TITLE
Retention setting doesn't honor commas

### ISSUE THREAD

**Issue by adaMATTium** [nzbget/nzbget#579]
The "Retention" field in NEWS-SERVERS allows users to input commas, but it ignores anything beyond the comma, e.g. 3,740 becomes 3 days.

Current version: NZBGet 20.0
OS: Windows 10 Pro / 10.0.17134 Build 17134

**Comment by hugbug** [comment]
Yes and why is this an issue?

**Comment by adaMATTium** [comment]
There is nothing documented to say this isn't a supported character in the field. I couldn't find anything in the log to indicate why my downloads were failing on my new server. I would expect an input field to either disallow or have some sort of active warning when an unsupported character is input into it.

I ended up finding this out by guessing since it was the only difference between my two servers, after wasting my own and my usenet provider's support's time.

**Comment by hugbug** [comment]
> I would expect an input field to either disallow or have some sort of active warning when an unsupported character is input into it.

I guess you expect too much. I'm glad you figured it out.
