### ISSUE TITLE
Downloads stuck at PP-queued

### ISSUE THREAD

**Issue by simonszu** [nzbget/nzbget#58]
I have a fresh install of NZBget 15 on Debian, and i just ran into this issue: https://www.reddit.com/r/usenet/comments/2q0t2n/nzbget_download_stuck_at_ppqueued/

I can confirm that i had paused the downloads in between, but resumed, and made sure that the shown drop down field next to the pause button have the correct values.

**Comment by hugbug** [comment]
I assume the program is currently in that state.
In a web-browser open address `http://<nzbget-ip>:<port>/jsonrpc/status` and post the returned content here.

Then save the log-file for further inspection (if we need it) and restart nzbget. Does it help?

**Comment by simonszu** [comment]
This is the content of the jsonrpc:

```
{
"version" : "1.1",
"result" : {
"RemainingSizeLo" : 0,
"RemainingSizeHi" : 0,
"RemainingSizeMB" : 0,
"ForcedSizeLo" : 0,
"ForcedSizeHi" : 0,
"ForcedSizeMB" : 0,
"DownloadedSizeLo" : 2782381617,
"DownloadedSizeHi" : 0,
"DownloadedSizeMB" : 2653,
"ArticleCacheLo" : 0,
"ArticleCacheHi" : 0,
"ArticleCacheMB" : 0,
"DownloadRate" : 0,
"AverageDownloadRate" : 16271237,
"DownloadLimit" : 0,
"ThreadCount" : 9,
"ParJobCount" : 1,
"PostJobCount" : 1,
"UrlCount" : 0,
"UpTimeSec" : 389,
"DownloadTimeSec" : 171,
"ServerPaused" : false,
"DownloadPaused" : false,
"Download2Paused" : false,
"ServerStandBy" : true,
"PostPaused" : false,
"ScanPaused" : false,
"FreeDiskSpaceLo" : 1968316416,
"FreeDiskSpaceHi" : 1743,
"FreeDiskSpaceMB" : 7141205,
"ServerTime" : 1437570183,
"ResumeTime" : 0,
"FeedActive" : false,
"NewsServers" : [
{
"ID" : 1,
"Active" : true
}]
}
}
```

These are the last lines of the log:

```
 [INFO] Successfully downloaded       cLY3s_QPDDJLT6r4eMkVurSR1WL4.par2/cLY3s_QPDDJLT6r4eMkVurSR1WL4.part24.rar
[INFO] Successfully downloaded cLY3s_QPDDJLT6r4eMkVurSR1WL4.par2/cLY3s_QPDDJLT6r4eMkVurSR1WL4.part25.rar
[INFO] Collection cLY3s_QPDDJLT6r4eMkVurSR1WL4.par2 completely downloaded
[INFO] Queueing cLY3s_QPDDJLT6r4eMkVurSR1WL4.par2 for post-processing
```

Restart of NZBget helps. As i can see from ny NAS's process list, the stale postprocessing process does indeed spawn an unrar process (starting with the very last rar file i have downloaded). This unrar process is staling. I assume that it could be the FakeDetector.py script i have installed for exactly this task. Well. 

I will test the download and postprocessing without the FakeDetector.py, but if it should work without, and the python script is faulty, NZBget is basically useless for me, since my movie grabber snatches a lot of fakes lately...

EDIT: Yes, it is definitely the fault of FakeDetector.py. It spawns a unrar process which tries to process the last RAR-file, but never completes, so the postprocessing stales until it finishes. 
According to [this guide](http://www.htpcguides.com/avoid-fake-usenet-files-nzbget/) i set up FakeDetector.py as a queuing script. Since the NZBget forums are offline, i have no idea whether i should better set it up as a postprocessing script. I have a fast connection, and no problems when NZBget will fully download fake releases, but they shouldn't be inserted into my library. 

But i hope you guys do know how to properly install FakeDetector, so that my post processing does not stall?

**Comment by hugbug** [comment]
It hangs not necessary for the last downloaded rar-file. it may hang for a while already. I can imagine that unrar sometimes doesn't like partial archives.

Set option **EventInterval** to "-1" to disable check during download.

The important questions are however:
- why unrar hangs?
- what we can do about this?
  I think the script can be improved to monitor unrar status to automatically kill unrar process if it hangs for too long, possibly retry.

How easy is it for you to reproduce the problem? I can try to implement an automatic unrar killing if you can test then.

**Comment by simonszu** [comment]
Well, somehow the Fakecheck has to happen, right? 
Currently it is very easy to reproduce: Enable Fakecheck, add NZB, wait until download finishes and postprocessing starts. So, yeah, i can try your suggestions. However, i'd rather wait for a very long unrar to finish than to have fake movies in my DB. They are annoying to remove, and it isn't fully automatic, then.

**Comment by hugbug** [comment]
> Well, somehow the Fakecheck has to happen, right? 

With **EventInterval=-1** the script will not be executed **during** download but it will be executed **after** download (before post-processing) and it will detect fakes.

> i'd rather wait for a very long unrar to finish

Do you mean the unrar will eventually finish if you wait long enough? How long? It should not take very long, because the script calls unrar to list archive content, which should work very fast.

**Comment by simonszu** [comment]
I am currently testing a download with **EventInterval=-1**. NZBget isn't spawning the unrar process after downloading the first part, which is some progress. 
However, i have noticed that in the details section of the nzb, the setting for FakeDetector was set to No, although in the global settings it was enabled. I think this was also the case previously, when EventInterval was set to 0. So, what does that mean? NZBget wasn't fake detecting after all? But why did it spawn the unrar process, and why was there log output of FakeDetector? Or is the setting simply disfunctional?

EDIT: Well, the FakeDetector began indeed after downloading the very last part of the nzb, and not after the first one. I had a NZB with 97 RAR files in it, each around 250MB. The FakeDetector chose to unrar part 21 for some reason, but nevermind. So, in my process list i have a unrar process which does something on a 250MB rar file for 6 minutes now. I think, on a dualcore atom CPU with 1,4GHz each, this shouldn't take so long. 
Furthermore, the extraction of the whole bunch of rar files without the FakeDetector needs around 5-10 seconds per part file. 
To be clear: I left the UnrarCmd setting untouched, so NZBget is using its own unrar binary. But i don't think there should be a difference to system's unrar.

**Comment by hugbug** [comment]
> in the details section of the nzb, the setting for FakeDetector was set to No, although in the global settings it was enabled

There is some redundancy about queue scripts. There are **pure queue-scripts** which can be activated via option **QueueScript** and there are **dual mode scripts** which can act as both - pp-scripts and queue-scripts. Dual-mode scripts can be activated either via option **QueueScript** or **PostScript** (or **CategoryX.PostScript**).

> The FakeDetector chose to unrar part 21 for some reason

It checks **each** rar-file using command `unrar vb /path/to/file.rar` which prints the content of the file. No unpacking takes place and the listing should be very fast (less than a second). For some reason "unrar" hangs. Upgrading or downgrading "unrar" could help. Try "unrar" from your system. 

If another "unrar" doesn't help - comment out lines [212](https://github.com/nzbget/FakeDetector/blob/master/FakeDetector.py#L212)-214 to deactivate check of rar-content. The files will be checked for fakes **after** unpack once again anyway. A small disadvantage is that the detection is not performed on early stage and resources are wasted by unpacking of the fake.

**Comment by simonszu** [comment]
So i tried system's unrar. NZBget is starting FakeDetector.py as usual, but that's it. The FakeDetector doesn't spawn any unrar process at all :(

So i think i'll just stick to SABnzbd at all. I don't want to spend my time with adopting NZBget, although it seems lightweiter, cleaner and faster, but....hm.

**Comment by hugbug** [comment]
> The FakeDetector doesn't spawn any unrar process at all 

Why do you think so? If unrar works correctly you will not see the process because it will end almost immediately (nothing is unpacked).

**Comment by simonszu** [comment]
I think so, because then FakeDetector.py should quit at some time, and regular post processing should start.

**Comment by hugbug** [comment]
Do you mean the status is still PP-QUEUED but there are no unrar-process?

Have you tried disabling unrar code completely?

> If another "unrar" doesn't help - comment out lines 212-214 to deactivate check of rar-content. The files will be checked for fakes after unpack once again anyway. A small disadvantage is that the detection is not performed on early stage and resources are wasted by unpacking of the fake.

**Comment by hugbug** [comment]
Created issue #60 (Indicate queue script activity).
Other than that the problem is either in unrar or in FakeDetector script. The script is used by many people and the problem wasn't reported yet.

Closing the issue due to lack of feedback. Feel free to reopen the issue if you have further questions.
