### ISSUE TITLE
Error reading diskstate for download queue and history

### ISSUE THREAD

**Issue by greencopper** [nzbget/nzbget#584]
I have a box running the latest version of nzbget git, but I have also experienced this on the latest stable 20 version - which is why I upgraded to the git version.

This box has a hardware problem which sometimes makes it freeze so a hard-reboot is necessary.

When the box is rebooted nzbget looses every state it was in, history is gone, download queue is gone, and I get the following in the log:

```
error | Thu Nov 29 2018 21:30:38 | Error reading diskstate for download queue and history
error | Thu Nov 29 2018 21:30:38 | Failed  to read queue and history data. Only queue and history from NZBGet v13  or newer can be converted by this NZBGet version. Old queue and history  data still can be converted using NZBGet v16 as an intermediate version.
error | Thu Nov 29 2018 21:30:38 | Error reading diskstate for statistics
error | Thu Nov 29 2018 21:30:38 | Error reading server info from disk
```

I then manually have to delete all files in queue, rename the nzb's, and start all over.

**Comment by hugbug** [comment]
Is option FlushQueue active?
Other than that not much can be done against hardware errors. Make regular backups of queue-directory.

**Comment by greencopper** [comment]
Thanks! The option was disabled (overlook on my part). And yes, gotta get another box for that.
