### ISSUE TITLE
Allowed IP

### ISSUE THREAD

**Issue by behold81** [nzbget/nzbget#587]
This is not working on my Synology install. All local PC’s or phones that are approved that worked when on my server ask for passwords now they are on my NAS. 

What’s the issue?

**Comment by hugbug** [comment]
If you try t login with wrong credentials it should print a warning containing IP of the client. Check this IP with the what you have in AllowedIP.

**Comment by hugbug** [comment]
Closing this due to lack of feedback. Feel free to reopen or add more posts with newer info.
