### ISSUE TITLE
downloads stopped working TLS-problems

### ISSUE THREAD

**Issue by antoonjanssens** [nzbget/nzbget#594]
downloads stopped were working fine running v16 til 30/12, since then i keep getting the same errors:
-Could not resolve hostname usenet.premiumize.me: ErrNo 0, Success
-Could not read from TLS-Socket: Connection closed by remote host
-Could not write to TLS-Socket: Connection closed by remote host

after update to v20 I get these messages

-Article someshow.s1e1 [1/68] @ Premiumize (usenet.premiumize.me) failed, could not fetch article: 
 Connection closed by remote host.
-Could not receive data on socket from usenet.premiumize.me: ErrNo 104, Connection reset by peer

As a test i tried disableing encryption but this solved nothing, and when turning it on again the cypher "RC4-MD5" wasen't recognised anymore (solved after extra reload, or time fixed it idk).
i have contacted my newsprovider and they claim everything is working correctly on their side.
I installed sabnzb as a test and this would download fine with  pm.me .

thoughts?

**Comment by hugbug** [comment]
If sabnzbd is running on the same computer then it should work in nzbget too. Check all server settings (host, port, encryption).

**Comment by antoonjanssens** [comment]
yes it's the same machine, and the same settings.
i have installed nzbget on my desktop and this works fine (so i guess no network problem).

**Comment by hugbug** [comment]
Something prevents network communication between nzbget and the server.

Is this a NAS? Is nzbget running directly on OS or in a virtual machine or docker? When you test with sabnzbd is it running directly near nzbget (same physical machine, same virtual machine or docker instance)?

**Comment by piejanssens** [comment]
I have been in contact with OP about this issue before so I can tune in on the topic.

Yes this is a NAS (Syno DSM). The test of sabnzbd was done on the exact same system.
It's important to note that there were also tests done without encryption, resulting in similar connection issues. So an SSL/cyrpto issue can be ruled out AFAIK.

All settings/ports are correct. Can this be caused by user privileges / file permissions?

**Comment by hugbug** [comment]
Is nzbget running directly on OS or in a virtual machine or docker?
Is sabnzbd running directly on OS or in a virtual machine or docker?

If the programs work in different virtual machines or docker containers the issue can be in virtual machine or docker config.

**Comment by piejanssens** [comment]
Both directly on OS.

**Comment by hugbug** [comment]
As a test configure new news server:
```
Host=us.sslusenet.com
Port=563
Username=a123
Password=123
Encryption=yes
```

Then try downloading from it. You should get error messages about wrong username/password but not  "Connection closed by remote host".

**Comment by piejanssens** [comment]
`(us.sslusenet.com) failed: could not establish connection`
`Authorization for test (us.sslusenet.com) failed: 502 Authentication Failed`

**Comment by hugbug** [comment]
Aha, it works with sslusenet.com. Then that must be something special about `usenet.premiumize.me`.

**Comment by piejanssens** [comment]
Alright, thanks. We'll provide your feedback to the owner and hopefully we can work it out.
