### ISSUE TITLE
File list in history after downloading

### ISSUE THREAD

**Issue by piejanssens** [nzbget/nzbget#598]
AFAIK you can only view downloaded files through the intermediate folder for failed tasks. It would be nice to have the 'Files' button available in the dialog when clicking on a failed task in the history. 
In the list of these files that are already downloaded:
- Show original file name (for files renamed by post processing)
- Show completeness (after par2 checking)
- Allow selecting individual files for redownloading

**Comment by hugbug** [comment]
> Show original file name (for files renamed by post processing)
Show completeness (after par2 checking)

Isn't the information provided in history item log (via button log in history details dialog) sufficient? Although not in a table form as file list but you can see completeness of files and how they were renamed.

>Allow selecting individual files for redownloading

What's the point? Nzb is processed as a whole. If you redownload only part of it the files will not be processed correctly (no rename, repair or extract). Anyway you can use command "Download again" to put nzb to queue for complete redownloading, then in queue you can view file list and delete files you don't want to download. For occasional usage is convenient enough. And there is command "Retry failed articles" if you want retry download of failed pieces, which works fully automatically.

**Comment by piejanssens** [comment]
You are right. I have reconsidered it and the history log in combination with the search is sufficient.
