### ISSUE TITLE
MacOS menubar widget can't connect if password contain special characters

### ISSUE THREAD

**Issue by ryanmatthews** [nzbget/nzbget#599]
When running nzbget with a non-default password, the MacOS menubar widget fails to connect to the downloader to read status. It should read the correct username/password from the config file.

**Comment by hugbug** [comment]
Maybe you have special characters such as &<> which the app has troubles with?
Also option AuthorizedIP if set to at least 127.0.0.1 should help.

**Comment by ryanmatthews** [comment]
the password had a % in it - is that a known issue? AuthorizedIP is set to 127.0.0.1 already.

**Comment by hugbug** [comment]
Not a known issue, just a guess.

**Comment by ryanmatthews** [comment]
seems you're right. I tested with a simple, non-default password and the widget worked.

**Comment by hugbug** [comment]
Fixed.
