### ISSUE TITLE
NZBGet crashes if web interface left open

### ISSUE THREAD

**Issue by dbowles1975** [nzbget/nzbget#602]
If I leave the web interface open in Chrome NZBGet will close on its own with no warning. If I keep the web interface closed it runs just fine. 

Windows 10 - Google Chrome - NZBGet 20.0

**Comment by hugbug** [comment]
Can you please install the debug build of nzbget (preferably the latest testing version) and try to obtain crash dumps as explained in https://nzbget.net/crash-dump?
Thank you.

**Comment by hugbug** [comment]
Closing this due to lack of helpful information.
Feel free to reopen or add further comments if you have more info.
