### ISSUE TITLE
Cant Start via Terminal with German Umlaut

### ISSUE THREAD

**Issue by phenze** [nzbget/nzbget#603]
It is not possible to start nzbget under windows when the config filepath contains german umlauts.

See attached Screenshot.

![nzbget](https://user-images.githubusercontent.com/12610157/51100474-93b40700-17d6-11e9-8835-35def563f768.PNG)

**Comment by hugbug** [comment]
The console window probably uses a different codepage than the rest of the system. You need to pass parameters in Windows default codepage (the same that all file related functions use).

Possible solutions:
- try to pass that specific character using Alt+(character code);
- use relative paths to avoid such characters;
- start NZBGet from Windows Run-dialog;
- start NZBGet via Explorer shortcut;
- create an alias (without such characters) for that path using `mklink`;
- change codepage of console window with `chcp` (may break nzbget output though).
