### ISSUE TITLE
Supported encryption ciphers and how to configure them in nzbget

### ISSUE THREAD

**Issue by woiza** [nzbget/nzbget#606]
Currently I have configured "AES256" in nzbget. However, I am not sure if CBC or GCM etc. is used.
Here is an excerpt of encryption ciphers which are supported by my provider:

- TLS_RSA_WITH_AES_128_CBC_SHA
- TLS_RSA_WITH_RC4_128_SHA
- TLS_RSA_WITH_AES_256_CBC_SHA
- TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA
- TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA
- TLS_RSA_WITH_3DES_EDE_CBC_SHA
- TLS_RSA_WITH_IDEA_CBC_SHA
- TLS_ECDHE_RSA_WITH_RC4_128_SHA
- TLS_RSA_WITH_RC4_128_MD5
- TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
- TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
- TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
- TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
- TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
- TLS_DHE_RSA_WITH_AES_256_CBC_SHA
- TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA
- TLS_RSA_WITH_AES_256_GCM_SHA384
- TLS_RSA_WITH_AES_256_CBC_SHA256
- TLS_RSA_WITH_CAMELLIA_256_CBC_SHA
- TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
- TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
- TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
- TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
- TLS_DHE_RSA_WITH_AES_128_CBC_SHA256
- TLS_DHE_RSA_WITH_AES_128_CBC_SHA
- TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA
- TLS_RSA_WITH_AES_128_GCM_SHA256
- TLS_RSA_WITH_AES_128_CBC_SHA256
- TLS_RSA_WITH_CAMELLIA_128_CBC_SHA

As far as I understand it, "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384" is the most secure one which can be handled by Intel AES-NI and ARMv8 AES (please correct me if I am wrong).

How can I define it in nzbget and verify that it is actually used?

**Comment by hugbug** [comment]
If your nzbget binary were built with OpenSSL then you should use names as printed by `openssl ciphers -v`. Then you put one of them into option ServerX.Cipher. If the name of cipher is correct and server supports the cipher the downloading should work. Otherwise you'll get error messages when nzbget tries to connect.

**Comment by woiza** [comment]
Thanks, ECDHE-RSA-AES256-GCM-SHA384 works like a charm.
