### ISSUE TITLE
Heads up re: linuxserver.io multi-arch docker images

### ISSUE THREAD

**Issue by aptalca** [nzbget/nzbget#609]
Hi, I'm a member of the linuxserver.io team.

I just wanted to give you a heads up that we migrated nzbget over to our new builder and we are now providing multi-arch docker images (x86_64, armv6 and aarch64) through a single repo at https://hub.docker.com/r/linuxserver/nzbget

The separate arm repo has been deprecated.

In the future, users can simply pull `linuxserver/nzbget` and it should automatically download the correct docker image for their arch.

Also, our new images are tagged with specific versions, for both the stable and pre-releases. Our jenkins queries your github repo for new releases and new builds should be pushed shortly after there is a new release.

`linuxserver/nzbget:latest` will follow the stable github releases and `linuxserver/nzbget:testing` will follow the pre-releases.

You can see the concise builds on github: https://github.com/linuxserver/docker-nzbget/releases
and all available docker image tags are right here: https://hub.docker.com/r/linuxserver/nzbget/tags

Feel free to update the your docs to point out the changes.

Thanks so much and keep up the good work ;)

**Comment by woiza** [comment]
Do you compile a 64bit binary for aarch64 or is it still 32bit?

**Comment by aptalca** [comment]
We compile a 64 bit binary: https://github.com/linuxserver/docker-nzbget/blob/master/Dockerfile.aarch64

**Comment by hugbug** [comment]
@aptalca, wouldn't it be better to download release (as source code tarball) instead of git cloning?

`git clone` downloads the whole history and I also believe to read somewhere on GitHub that `clone` isn't meant as way of distribution whereas releases area is exactly for that.

**Comment by aptalca** [comment]
@hugbug I believe it has to do with how the version is retrieved from the git tag, which the tarball did not have

EDIT: Also, since we are doing a multi-stage build, all the unnecessary things from the git clone get discarded after the build stage and only the binary is copied over: https://github.com/linuxserver/docker-nzbget/blob/master/Dockerfile#L76

**Comment by hugbug** [comment]
> I believe it has to do with how the version is retrieved from the git tag, which the tarball did not have

Here is an example URL:
https://github.com/nzbget/nzbget/releases/download/v21.0-r2296/nzbget-21.0-testing-r2296-src.tar.gz

It contains the tag and is easy to construct.
