### ISSUE TITLE
Warn if umask is used wrong

### ISSUE THREAD

**Issue by brokeh** [nzbget/nzbget#612]
I made the same silly mistake with the umask as in #113 where I had the mask backward. This resulted in NZBget not been able to do anything with the queue or intermediate files as the file mode was 000. It also meant that the logs filled up at several GB/day with errors accessing the queue files.

Add a warning to the UI where if the entered umask will result in the user part of the mask will result in NZBget not been able to write the files it created that the umask looks dodgy and suggest it is backwards and/or link to docs on umask.

**Comment by hugbug** [comment]
>Add a warning to the UI 

Currently the web interface has no concept of input validation and there is no place to show such a warning.

What I could do though is to change the option description. Do you have a suggestion how to rewrite it?

**Comment by hugbug** [comment]
I've changed the option description to better prevent confusion with "chmod".
