### ISSUE TITLE
Feature Request: Customisable periods for the total downloaded graph

### ISSUE THREAD

**Issue by theg00s3** [nzbget/nzbget#613]
Currently you can choose to view a monthly or yearly breakdown, but I'm requesting a customizable period function where you can choose several months or years

**Comment by hugbug** [comment]
Thank you for your suggestion but I think it's beyond the scope of the project.

Such customisability of the graph would be appropriate for a network monitor program (as this would be one of the main features) but in NZBGet the purpose of the graph is to provide info about download volumes and current implementation do that job just well.
