### ISSUE TITLE
NZBGet doesnt work on NAS

### ISSUE THREAD

**Issue by tariqghazi** [nzbget/nzbget#614]
hello,

I have a Synology NAS ds218+ and a few weeks ago NZBGet stopped working.
I had the login url bookmarked but all of sudden it didnt work anymore. I asked support to help me out but they wont deliver support to 3rd party packagaes. 

The package is still installed on my NAS but somehow i dont know how to get the login url or get it to work. Can someone help me out?

Tariq

**Comment by hugbug** [comment]
> support to 3rd party packagaes.

Where did you get your NZBGet module then? I guess it's not official NZBGet package from NZBGet home page because you would know how to check it and reinstall if necessary.

**Comment by M0UL** [comment]
i would expect it to be from [SynoCommunity](https://github.com/SynoCommunity/spksrc)

**Comment by hugbug** [comment]
Closing this due to lack of feedback. Feel free to post additional comments if you need further assistance.
