### ISSUE TITLE
Exporting prometheus metrics

### ISSUE THREAD

**Issue by frebib** [nzbget/nzbget#615]
This is a bit of an out-there request but is there any likelihood of having nzbget export prometheus metrics? I'm starting to play with monitoring some more and I would find this really useful.
The kinds of values I'd like to see is download volume, bandwidth, failures, errors, download history, per-newsserver stats, just like the statistics shown when you click on the clock in the top left.

If you're not that familiar with prometheus and how it works: the prometheus server periodically scrapes various metrics sources for a HTTP path containing plaintext output with metrics data. Usually a path like /metrics is used. HTTP basic-auth and the like can still be used if desired.

Thanks

**Comment by hugbug** [comment]
NZBGet provides all data via API.

Does that Prometheus expect all software in the world to provide data in a special Prometheus format? That would be foolish.

There should be a way for you to write modules to import data from certain sources? If that's the case you can fetch data from NZBGet API and feed Prometheus. If that' not possible you have to setup a web-server which allows you to write modules (in php, python, etc.) and write a module which fetches the data from NZBGet and formats it for Prometheus.

**Comment by frebib** [comment]
Often metrics are provided by a 3rd-party "module" which is basically a web-server that translates the API call, exposing the information in the correct format. It's not common to have first-party prometheus support but I thought I'd ask anyway :)

I'll have a go at writing an exporter myself
