### ISSUE TITLE
Update Unrar and 7zip to current versions.

### ISSUE THREAD

**Issue by Dazog** [nzbget/nzbget#616]
7zip is currently at version 19.00

unrar is at 5.7 which removes .ace support and fixes a long standing CVE.

Can these be updated for next release?

Thank you.

**Comment by hugbug** [comment]
Only winrar is affected, unrar isn't. The vulnerable DLL isn't even shipped with nzbget.

You can also easily update unrar and 7zip in nzbget directory or use the system wide installed tools via options UnrarCmd and SevenZipCmd.

I'll update them in v22 nonetheless.

**Comment by hugbug** [comment]
The progress will be tracked in #618.
