### ISSUE TITLE
Update bootstrap and jquery to latest versions?

### ISSUE THREAD

**Issue by Dazog** [nzbget/nzbget#617]
Both bootstrap and jquery used are 6+ years old.

Both have multiple CVE's patched and speed performance increase in that time.

Will these be updated in the current beta or next?

Thank you.

**Comment by hugbug** [comment]
No, they will not be updated. Even a small version bump such as updating bootstrap from 2.03 to 2.04 breaks things.

Do you know any vulnerabilities in these libs which affect nzbget?

**Comment by Dazog** [comment]
6 XSS CVE's for both bootstrap and jquery.

I noticed you started using lgtm to verify your code.

Maybe it isn't affected by using these older versions locally. 

I know it's going to break things, but also has performance increases in 6 years.

Again thank you for this great app, just asking.

**Comment by hugbug** [comment]
> has performance increases in 6 years

Which ones?
