### ISSUE TITLE
Feature request: AuthorizedIP range and or subnet notation

### ISSUE THREAD

**Issue by tastyratz** [nzbget/nzbget#620]
I want to allow my entire local network to be an authorized ip without typing in all of the many ip's it could be individually.

I am not really sure why this hasn't always been the case, but, I wanted to file a request for it as it seems necessary for consistency when using DHCP at home.
 I want password control with access outside of the local subnet, but not inside it.

**Comment by hugbug** [comment]
The easiest would be to support wildcards like this:
```
AuthorizedIP=127.0.0.1,192.168.0.*
```
or even:
```
AuthorizedIP=127.0.0.1,192.168.*.*
```

Would it be enough? Support for ranges and subnets requires special implementation whereas wildcards can be implemented with two lines of code (worked fine in my short test).

**Comment by tastyratz** [comment]
Wildcards are wildly better, that's fantastic! Anything to avoid having to type out the whole dhcp range.

**Comment by nomandera** [comment]
Perhaps a built in selectable IANA private IP filter might help a lot of people specifically since `172.16.0.0 – 172.31.255.255` is a bit ugly to do with wildcards (it could hide the uglyness).

**Comment by hugbug** [comment]
@anoma, that's too much work for little gain.

The main purpose of the option is to login from local host. An ability to add other hosts is a bonus. Wildcards should cover most cases. And if they don't - any browser can save the password, you need to type it only once anyway.

**Comment by hugbug** [comment]
**Implemented wildcards**.
