### ISSUE TITLE
Config API endpoint returns incorrect category DestDirs

### ISSUE THREAD

**Issue by Qstick** [nzbget/nzbget#622]
When setting up categories with specific DestDir, Set Category up as below
![image](https://user-images.githubusercontent.com/376117/55674995-f1ae3300-5889-11e9-9848-b3f17e5dcfe1.png)

Config JSONRPC API endpoint cuts off last letter of category DestDir
```
        {
            "Name": "Category1.Name",
            "Value": "Movies"
        },
        {
            "Name": "Category1.DestDir",
            "Value": "/downloads/completed/Movie"
        },
```

Nzbget Version: 20.0

**Comment by Qstick** [comment]
One note is this only happens with relative paths, if an absolute path is entered in settings no truncation happens

**Comment by hugbug** [comment]
**Fixed.**

Thanks for reporting this.
