### ISSUE TITLE
Post Processing Failed Endless Loop

### ISSUE THREAD

**Issue by ghost** [nzbget/nzbget#623]
Lately Ive been getting endless loops that will constantly retry post processing. When this happens I get constantly disconnections from the UI or unauthorized errors.

I'm running the LSIO docker image.

I have to stop nzbget and then look at the logs for the one it's stuck on, which is easy since it repeats the same thing in the logs every 2 seconds.

From the looks of it, it was having SSL errors. I have 3 main providers set at priority 0, but it seems UNE is the only one that has the file it keeps failing.

This does appear to be an edge case bug in the try logic. This has happened a few times the past few weeks, these same nzbs appear work in sabnzbd.

This happens with the latest preview as well. (Log sent)

**Comment by ghost** [comment]
When this happens nzbget is stuck and won't download or PP anything else until I fix it by deleting the offending download

**Comment by hugbug** [comment]
Nothing suspicious in the submitted log. I also don't see any loops, just an ordinary postprocessing log.

Click on the item in queue or history, then button "Log", then "Save to file".  Post the log via pastebin.com or send it to nzbget@gmail.com. Also upload or send the full log-file.

> until I fix it by deleting the offending download

Does deleting help immediately or you need also to restart the program? In latter case maybe it's restarting what helps and not deleting.

**Comment by ghost** [comment]
The excerpt I posted would just be repeated constantly. As soon as I delete the file it's stuck on l, it's fixed.

I emailed you a log of a download that it does it.
You may be able to replicate this by getting the same nzb.

I'm thinking a bug in either or unrar or par dependencies.

I emailed the log

**Comment by hugbug** [comment]
I'm trying to reproduce the issue but this nzb-file downloads without errors or missing articles for me.

1. Can you try this nzb again to see if you can still reproduce the error with it?

2. The log-file has grown a lot but the webui function shows max 10000 lines. I need the whole log-file though. The log-file (with all lines) is saved in QueueDir and has name "nxxxx.log" where "xxxx" is id of nzb. You don't know id of course. Can you please use some search function to find out the correct file (by searching for nzb-name in file contents) and send the file to me? You can also find id of the nzb in the result of API-call "history" which you can easily see in browser by navigating to http://ip:port/jsonrpc/history.

3. It's possible that the endless loop occurs only with certain program settings. Please send me your config-file (delete account and passwords first).

Thanks.

**Comment by ghost** [comment]
I unfortunately don't have that anymore since I recently wiped the nzbget appdata.

I think this is a case where there's a par needed but the only provider who has it has a tempp server connection issue (like invalid ssl), so it keeps retrying in this loop of reparing -> downloading -> SSL error -> loop.

I also noticed this happening on a fake nzb of a major anticipated production. So it's possible the nzb was maliciously crafted for a DDOS purpose.

I'm going to close the issue until I can provide another nzb and the needed info.
