### ISSUE TITLE
Feature Request: Show RSS source in History

### ISSUE THREAD

**Issue by Slevin90** [nzbget/nzbget#625]
In the History list, it would be nice to see what RSS Feed it came from.
Usecase:  When using multiple sources for RSS Feeds.

At this moment you can see by opening every single item and check the url in the  field "Link"
Suggestion:  Show the FeedX.Name somewhere in the History list.

**Comment by hugbug** [comment]
You can use categories for that - just configure individual category for each RSS feed.

**Comment by hugbug** [comment]
Assuming this is resolved.

**Comment by Slevin90** [comment]
Closing is ok.
Thanks
