### ISSUE TITLE
Unrar e works in Terminal but nzbget wont unrar on its own

### ISSUE THREAD

**Issue by Dudleydogg** [nzbget/nzbget#626]
If I go to intermediate folder and manually run unrar it works, just not automatically as expected.

info | Mon Apr 15 2019 19:36:48 | Collection killing.eve.s01e01.repack.hdtv.x264-w4f-Rakuv added to history
-- | -- | --
error | Mon Apr 15 2019 19:36:48 | Unpack for killing.eve.s01e01.repack.hdtv.x264-w4f-Rakuv failed.
info | Mon Apr 15 2019 19:36:48 | Second unpack attempt skipped for killing.eve.s01e01.repack.hdtv.x264-w4f-Rakuv due to par-check not repaired anything
info | Mon Apr 15 2019 19:36:47 | Repair not needed for killing.eve.s01e01.repack.hdtv.x264-w4f-Rakuv/6a59717891d140df94a3e6666486e2d1
detail | Mon Apr 15 2019 19:36:47 | Par: All files are correct, repair is not required.
info | Mon Apr 15 2019 19:36:47 | Verifying file 6a59717891d140df94a3e6666486e2d1.part11.rar
info | Mon Apr 15 2019 19:36:47 | Verifying file 6a59717891d140df94a3e6666486e2d1.part10.rar
info | Mon Apr 15 2019 19:36:47 | Verifying file 6a59717891d140df94a3e6666486e2d1.part09.rar
info | Mon Apr 15 2019 19:36:47 | Verifying file 6a59717891d140df94a3e6666486e2d1.part08.rar
info | Mon Apr 15 2019 19:36:47 | Verifying file 6a59717891d140df94a3e6666486e2d1.part07.rar

**Comment by hugbug** [comment]
Click on the item in history, then on button Log, then on button Save to file. Upload the file to pastebin.com and post the link here.

**Comment by hugbug** [comment]
Closing this. If the issue still persist feel free to post further comments with the info I asked.

**Comment by Dudleydogg** [comment]
WE are good it was able to download files .rar do the Intermediate folder, but then could not Unrar them which I found strange.  I modified permissions and User running the program and was able to get it working.  Thank you for responding.
