### ISSUE TITLE
Cannot stop extension script from trying to execute

### ISSUE THREAD

**Issue by polizz** [nzbget/nzbget#627]
Running 20.0 on Windows as a service. Have been running the nzbToMedia scripts for over a year with no issues. Specifically had been running the sickbeard script. However, I'm trying to turn that off and run the nzbDrone script instead. Disabling that script and restarting the service seems to have no effect - nzbget is still trying to run the old script and not the new one. When I rename the old script, I get an error about it not finding it which makes sense. How can I update this setting?

![image](https://user-images.githubusercontent.com/10888433/56385314-5c456400-61e4-11e9-8017-72bdaf36f585.png)

**Comment by hugbug** [comment]
Scripts are activated per nzb. When you click on an nzb in queue or history, then button "Postprocess", you can check and change which scripts are activated for a particular nzb.

Options Extensions and CategoryX.Extensions define which scripts should be activated when an nzb is added to queue. Changing these options have effect on new nzbs only.

However if you change category for one or multiple nzbs that also changes activated scripts according to current category settings. You can use this to change scripts for existing queued nzbs if you have many of them and don't want to change each nzb individually.

**Comment by polizz** [comment]
That's what my understanding was. I simply cannot get nzbget to respect the options set for extensions. It seems stuck always trying to do these.

**Comment by polizz** [comment]
For example, with this config, I would expect the nzbDrone script to execute, not another script that is not specified.

![image](https://user-images.githubusercontent.com/10888433/56390048-a896a100-61f0-11e9-8f32-d787878f57fa.png)

**Comment by hugbug** [comment]
Save the settings and reload nzbget. Then add new nzb (without category). Click on nzb in queue, check that it doesn't have a category.
Then click on button Postprocess. Which scripts are active?

**Comment by polizz** [comment]
When I do that, the scripts appear as I thought they would before... for TV categories, they are like they were before I made my changes.

**Comment by polizz** [comment]
I think I realize what you were saying before... my category scripts are still wrong x\
