### ISSUE TITLE
nzbget.sln missing from repository

### ISSUE THREAD

**Issue by minimeh** [nzbget/nzbget#63]
The Visual Studio solution file **nzbget.sln** is missing from the **develop** branch (as well as the downloadable zip archive for the project) It is in the **master** branch, however.

**Comment by hugbug** [comment]
Yes, deleted it as it's not required to build the program.

**Comment by minimeh** [comment]
Not entirely true. Visual Studio will go ahead and create a default solution for the project and prompt to save it when closing the project. Git then sees it as a file that it should manage since **.gitignore** doesn't list solution files. Seems it would be better to provide the solution file with the repository as is usual and customary.

**Comment by hugbug** [comment]
The reason to remove the file is described in #48.
46039698ca4ebe261346cc7a36ff559cc53ad589: added .sln to .gitignore to make life easier for you and other users.

BTW, if something isn't in .gitignore it can be added to local **./git/info/exclude**. But you are right, in that case it's better to have the file in .gitignore.
