### ISSUE TITLE
"nzbget-21.0-bin-macos" thinks it is a 'testing' version and wants to update to final 21.0 release

### ISSUE THREAD

**Issue by core-code** [nzbget/nzbget#632]
when downloading and launching "nzbget-21.0-bin-macos.zip" it reports itself as a testing version:
`Currently installed: 21.0-testing-r2304
`

and it even wants to update to another version although it should be the latest release

![Screen Shot 2019-05-03 at 11 32 57 AM](https://user-images.githubusercontent.com/1261954/57155270-500ff800-6ddb-11e9-86c6-b2c1f26f4ec0.jpg)

**Comment by hugbug** [comment]
Thank you.

**Fixed**. Please test.

**Comment by core-code** [comment]
confirmed fixed - thanks for the swift action
