### ISSUE TITLE
Feature request: Show bandwidth per newsserver stats

### ISSUE THREAD

**Issue by Pentaphon** [nzbget/nzbget#633]
It would be nice to see the amount of bandwidth each newsserver is providing to the current download so people with multiple servers can see if any server is being uncharacteristically slow. The messages only inform us if we are blocked or can't connect but we can't see if any slowdowns are occurring per server. 

A speed graph per server or even just a text display of the current bandwidth would be a useful stat.

**Comment by hugbug** [comment]
Click on remaining time label near big round button at top left, then on "Total downloaded" to show download volume dialog. Here you see the total amount and amount per-server.

Also if you click on a download item in queue or history, then on text "Article completion" in the statistics group it shows some useful statistics as well.

**Comment by Pentaphon** [comment]
@hugbug Thanks for the info. I couldn't find those at all. I kept looking for a dedicated menu item or something like that. I guess that's enough for me so I will close this.
