### ISSUE TITLE
Windows PC no longer sleeping after updating to v21

### ISSUE THREAD

**Issue by tbalcom** [nzbget/nzbget#635]
I recently updated to from NZBGet v20 to NZBGet v21 and found my Windows 10 1809 PC is no longer sleeping. I'm running NZBGet as a Windows Service. I could only make my PC sleep again by stopping the NZBGet Windows Service. Downgrading back to v20 allows the PC to sleep again.

**Comment by hugbug** [comment]
I hope to have this fixed now. Could you test this? Please send me a note to nzbget@gmail.com and I'll provide you with an updated installer.

**Comment by tbalcom** [comment]
The test was a success. The PC can sleep again. Thanks for the fix!
