### ISSUE TITLE
Use sub-directory-name with matching category for web-interface or RPC-API uploads

### ISSUE THREAD

**Issue by nomandera** [nzbget/nzbget#636]
Currently nzbget has the powerful feature:

> A nzb-file queued from a subdirectory is automatically assigned to category with sub-directory-name.

However as far as I can tell `If a new nzb-file is added to queue via web-interface or RPC-API` thre is no option to save these nzbs to the `sub-directory-name` with matching  `category`.

For neatness it would be useful if this was possible either auto-magically or via a selectable save-to option.

**Comment by hugbug** [comment]
When an nzb has a category, the category name is used as a sub-directory unless that category has other DestDir defined. It doesn't matter how the nzb get the category assigned (via directory scan or adding via webui or API).

What exactly doesn't work?

**Comment by nomandera** [comment]
None of my `category has other DestDir defined` .

For the purpose of clarity we are only talking about nzb files.

As expected if I send nzbget a nzb file via the API or GUI assigned with a catagory the nzb is correctly processed as defined by that catagory. 

However the nzb file itself is renamed to `*.nzb.queued` and stored long term in the base watch directory folder rather than utilizing any existing subfolders with matching catagory names.

e.g. if I upload a nzb to `/watch/iso` it is tagged as the iso catagory but if i upload via the GUI and tag it manually as the iso catagory we currently save this nzb to `/watch` and not `/watch/iso`.

**Comment by hugbug** [comment]
Why do you care where the files are stored?
They are used automatically with command "Download again" and they are deleted automatically when they are not needed anymore.

**Comment by nomandera** [comment]
Primarily for neatness and consistency when using both the subfolder and api means of upload to end with the same on disk structure.

**Comment by hugbug** [comment]
Dosing so would also require to move nzb-files after the category is changed in UI.
All of that just to remove the file altogether after KeepHistory days? I don't think it is worth it.
