### ISSUE TITLE
Support dragging zip-files to download queue

### ISSUE THREAD

**Issue by ZenithDK** [nzbget/nzbget#639]
A nice feature of SABnzbd was that you could drag a zip file onto the web UI and have it automatically unpack it and use the .nzb files inside.
Right now I don't even get a notification that anything besides .nzb files are not supported.

**Comment by Prinz23** [comment]
See Extension Script: 
https://forum.nzbget.net/viewtopic.php?f=8&t=1600
https://github.com/Prinz23/nzbgetpp

**Comment by ZenithDK** [comment]
I'm not opposed to extensions, far from it - but this, to me, seems like a basic feature that I would like to have native support for in NZBget.
It's a feature request, not a bug :-)

**Comment by ZenithDK** [comment]
Oh, and I am running nzbget in a docker container so any adding of extensions is a bother - hence the wish for native support.

**Comment by hugbug** [comment]
The idea of extension scripts is that other users can extend the program. That also makes the program smaller and simpler to develop and maintain.

If you have troubles with docker you can install the program on the host. With NZBGet it's much simpler with many other programs - nzbget installed via official installer from nzbget home page installs all files into one directory and doesn't interfere with the rest of the system. Easy to install and easy to remove.
