### ISSUE TITLE
Bug: ArticleTimeout ignored at Test Connection?

### ISSUE THREAD

**Issue by JvGinkel** [nzbget/nzbget#642]
My usenet provider needs around 14-30 seconds to respond to the unknown `ARTICLE <randomnumber@nzbget.net>` request. But after around 10 seconds nzbget will respond with the following error:

`Could not receive data on socket from <server address>: ErrNo 35, Resource temporarily unavailable`

The `ArticleTimeout` is set at `60` so I assumed that it should wait for 60 seconds for a response but it looks like it's not. (https://github.com/nzbget/nzbget/blob/master/daemon/remote/XmlRpc.cpp#L3310)

**Comment by hugbug** [comment]
Looks like during connection test the timeout is limited to max. 10 seconds on purpose: https://github.com/nzbget/nzbget/blob/bbfcf0768949f2e1c2065d9e6b1d2d870c557b59/webui/config.js#L1594

I believe I did this to avoid blocking of the web ui for too long. There is no cancel button during connection test and I probably though that 10 seconds limit is a good thing.

I think it's OK to keep it this way. If you know that your server needs more time then please just ignore the connection test.
