### ISSUE TITLE
_nzblog

### ISSUE THREAD

**Issue by rjulie95** [nzbget/nzbget#644]
Hi,

_nzblog is always created, but this option is disabled in configuration ?

![image](https://user-images.githubusercontent.com/8410772/59156674-835f3a00-8a9f-11e9-89ea-c3b29cf7bd7a.png)

On configuration file :
NzbLog=no

I use the lasted version 21.0 on docker environement

**Comment by hugbug** [comment]
You use post-processing script Logger.py which creates the log-file in download directory. This is not related to option NzbLog.

**Comment by hugbug** [comment]
Closing this. Feel free to post additional comments if you need further help with this case.
