### ISSUE TITLE
 Error: Could not create directory...

### ISSUE THREAD

**Issue by bouwew** [nzbget/nzbget#645]
I see this for every music-item I download. Other types of downloads are being processed without any issue.
Please see the uploaded log for more details.

Is the create directory-action performed with the correct permissions? (sudo missing?)

[Avicii - TIM (2019).log](https://github.com/nzbget/nzbget/files/3275422/Avicii.-.TIM.2019.log)

**Comment by bouwew** [comment]
I'm now also seeing an error when downloading a move. See the attached log.
[Hotel_Mumbai_2018_INTERNAL_1080p_BluRay_X264-AMIABLE.log](https://github.com/nzbget/nzbget/files/3282007/Hotel_Mumbai_2018_INTERNAL_1080p_BluRay_X264-AMIABLE.log)

**Comment by hugbug** [comment]
"Could not create directory" is usually caused either by a wrong path or permissions issue. If you run the program as daemon it may be run under a different user account. For a test please try running nzbget from current user using `nzbget -s` instead of `nzbget -D`.

**Comment by bouwew** [comment]
When thinking a bit more about this problem, the issue happens every time when I use Spotweb to send an nzb-file to Nzbget. When using SickChill for this, the issue does not show up.
Could it be that this caused by the way Spotweb connects to Nzbget, via http?

**Comment by hugbug** [comment]
How Spotweb connects doesn't matter.

What can matter is if you use different categories in SickChill and Spotweb and these categories have different destination paths. When if the directory for Spotweb category is incorrect or have bad permissions, then the downloads for this category will fail.

Is the path "/share/Download/completed/Movies" correct at all? Can you create directories inside this path manually from terminal?

**Comment by bouwew** [comment]
Indeed, it was a permissions issue. I noticed that the completed-directory was owned by root:root which is different from the other NZBGET-directories. I fixed this and now a manually added nzb-file is unpacked properly into the competed-directory.

Thanks for your help!

**Comment by nsar1907** [comment]
> Indeed, it was a permissions issue. I noticed that the completed-directory was owned by root:root which is different from the other NZBGET-directories. I fixed this and now a manually added nzb-file is unpacked properly into the competed-directory.
> 
> Thanks for your help!

im having the same problem on my nas and may u tell pls how did u fix?

**Comment by bouwew** [comment]
@nsar1907 use "sudo chmod 777 ..." to change the permissions of your completed-directory and each directory under it so that the directories become writable for all users.

**Comment by nsar1907** [comment]
@bouwew It didnt work for me. May i ask that your docker on nas?

**Comment by bouwew** [comment]
I have NZBGET running on a container in Proxmox. Not the same, but quite similar.

Please read all the messages above, the cause could also be something else, like the directory does not exist.
