### ISSUE TITLE
Compact mode setting in view options for settings page unticks itself when nzbget is closed

### ISSUE THREAD

**Issue by Pentaphon** [nzbget/nzbget#646]
This is for Windows 10. Whenever I close nzbget, the compact mode setting in the view option for the settings pages unticks itself and I have to tick it again. This happens every single time I close nzbget and go to the settings page after restarting it.

**Comment by hugbug** [comment]
The settings is saved in the browser, in its local storage. Maybe you have activated some security setting in your browser which denies access to local storage.

**Comment by Pentaphon** [comment]
@hugbug  Yep. You're right. It was my cookie autodelete extension. Whitelisting it fixed it. Thought it was saved outside of the browser. Thanks. Closing this.
