### ISSUE TITLE
LICENSE file to be included as part of this repository

### ISSUE THREAD

**Issue by caronc** [nzbget/nzbget#647]
I got a real easy one for you! In fact probably anyone can do it.

Could you just include a LICENSE file somewhere (anywhere) in this repository that just identifies the GPLv2 licensing details.  It can be cut and paste from any other project on GitHub (and just swap their name for yours at the head of the file).

This makes it really easy to package it properly with upstream distributions.  For a while i've been hosting your project on [nuxref](http://nuxref.com/nuxref-repository/) but I figured it's about time I take advantage of my Fedora sponsorship and just host it to a much wider audience for you. The license file already packaged with the project makes life much easier! :slightly_smiling_face: 

For now, all versions of Fedora/EPEL (in the meantime) are built and tested on my [COPR page](https://copr.fedorainfracloud.org/coprs/lead2gold/nzbget/).

One last thing (I can open another ticket for this though).  Can you check that _scripts/Email.py_ and _scripts/Logger.py_ are compatible with Python 3?

After I'm done with your project, i'll probably move on to all of the popular plugins and SABnzbd.  Keep up the great work!

**Comment by hugbug** [comment]
License is in file COPYING as recommended for software licensed under GPL.

Scripts should work with Python 3.

**Comment by caronc** [comment]
I'm good then! Thank you!
