### ISSUE TITLE
Keep track of server usage

### ISSUE THREAD

**Issue by thegr8brian** [nzbget/nzbget#65]
Would it be possible to implement some way of tracking some statistics about usenet server usage?  This would be helpful for tracking usage of servers with block accounts.  Sabnzbd has this functionality.

**Comment by hugbug** [comment]
Already there - [Downloaded volume statistics](http://forum.nzbget.net/viewtopic.php?f=3&t=1156).

**Comment by thegr8brian** [comment]
Thanks, had no idea that icon was clickable.
