### ISSUE TITLE
Failure after successful fetch

### ISSUE THREAD

**Issue by Dhop84** [nzbget/nzbget#653]
I don't seam to have an issue fetching the shows from rss but then when it goes to download it, it just stops and fails

**Comment by hugbug** [comment]
Check the logs.

**Comment by Dhop84** [comment]
Thanks for the reply but I don't really no what I'm looking for tbh

**Comment by hugbug** [comment]
Switch to history tab, click on a failed download, then button "Log", then button "Save to file". Post the log to pastebin.com and the link to it here.

**Comment by Dhop84** [comment]
https://pastebin.com/iCuWrjBs

**Comment by hugbug** [comment]
Looks like the nzb-file was empty. Check it in a text editor.

**Comment by Dhop84** [comment]
https://pastebin.com/p2HXgXnF

**Comment by hugbug** [comment]
Check the nzb-file in a text editor. The file is in NzbDir.

**Comment by Dhop84** [comment]
Ok so it says this "Error parsing nzb-file: Start tag expected, '<' not found"

**Comment by hugbug** [comment]
Looks like the file fetched from your indexer isn't a proper nzb-file. That's why I suggested:

> Check the nzb-file in a text editor. The file is in NzbDir.

**Comment by Dhop84** [comment]
Ooooooo! I thought if it came through RSS then it could be a magnet link. Is there anyway to add this functionality ? As I've searched for ages for a app like this for torrents
