### ISSUE TITLE
PAR2 files leftover after download is checked as a success?

### ISSUE THREAD

**Issue by hl2guide** [nzbget/nzbget#659]
I'm running the latest stable version on Windows 10.

Currently for all downloads I run it has files like:

______________.vol001+01.PAR2

left in the download's folder.

How can we set it to delete PAR2s if the download is successful?

**Comment by hl2guide** [comment]
I found **ExtCleanupDisk** but I think you should consider a more apparent option 💃

**Comment by hugbug** [comment]
These files should be deleted automatically unless you have par-check disabled.
Please post a processing log of one such download - click on a history item, then button "Log", then "Save to file", post the file via pastebin.com.
