### ISSUE TITLE
Request: Smart rename of junk NZB names

### ISSUE THREAD

**Issue by RollingStar** [nzbget/nzbget#660]
Often, I get NZB files with a hexadecimal file name. (http://nzbking.com/ provides them this way).

I wonder if it would make sense to detect hexadecimal names and substitute other information from the NZB. More broadly, NZBget could search a dictionary to determine if the given NZB name has any words in it.

In my files downloaded from nzbking, line 4 of the NZB is much more informative. It contains the "subject" of the NZB.

**Comment by hugbug** [comment]
This is a typical case for a scan-script - please see https://nzbget.net/scan-scripts.

However much easier (and more logical) would be to ask the site to fix the issue and provide files with proper names.
