### ISSUE TITLE
Javascript Errors on Firefox 69.0.2

### ISSUE THREAD

**Issue by f0ff886f** [nzbget/nzbget#662]
In Firefox (69.0.2, win64) I'm always getting this error (on screen, in the red error box up top) for the last few weeks (months?). NZBGet 21.0 stable installed running on Linux. The WebUI mostly works, but some functions (like check for updates) don't work at all. I diffed what I have on disk in `webui` to a fresh download of 21.0 and there are no differences... I don't think its an extension, I have just uBlock Origin and even that disabled makes no difference.

```
Error in https://url/nzbget/combined.js?lib/jquery.min.js+lib/bootstrap.min.js+lib/raphael.min.js+lib/elycharts.min.js+fasttable.js+index.js+util.js+downloads.js+edit.js+status.js+messages.js+history.js+upload.js+config.js+feed.js (line 12732)

SyntaxError: JSON.parse: expected property name or '}' at line 1 column 2 of the JSON data
```

**Comment by hugbug** [comment]
Do you still have the issue with newer Firefox versions?

**Comment by f0ff886f** [comment]
Yes I just tested on Firefox 74.0 on Windows 10, exact same problem and log.

I checked the network request for `combined.js` and saw that the response looks like an appropriate giant Javascript file to me, so it looks to be OK from the network side.

**Comment by hugbug** [comment]
This is probably related to #650 and therefore fixed.
