### ISSUE TITLE
NZBget auto pause downloads

### ISSUE THREAD

**Issue by CurlyFlow** [nzbget/nzbget#665]
NZBGet keeps auto pausing some downloads (its the incomplete and or fakes)

I dont want NZBGET to pause anyhting, i disabled EVERY auto pause in the settings. It still does that. The problem is, if he pauses it, the download clients wont search for new releases...

> What to do if download health drops below critical health.
> 
> **Delete** - delete nzb-file from queue, also delete already downloaded files;

**It does not do that!** Instead it just pauses it???

I asked on reddit 2 times for help, no one knows anything, whats this all about? For gods sake, please help me, im getting crazy about this.

Yes i have extentions installed (but this also happens without extentions!!) and dont ask for logs, there is nothing unusual in it. (the download logs, i dont know where i could get other logs from)

Im using a docker image https://hub.docker.com/r/linuxserver/nzbget/

Please help me. I dont know where else to ask.

As a workaround - i know there is a command i can send to unpause, but its just the global nzbget pause, unpause.

> docker exec nzbget /app/nzbget/nzbget -c /config/nzbget.conf -U

Is there any command i could send to automaticcly unpause all downloads? (or maybe can this bug be fixxed or is it wrong setting)

Sorry my english is not the best. I hope you can understand what i mean.

**Comment by hugbug** [comment]
For one download (nzb) which misbehaves, after it is auto-paused, click on the item, make a screenshot, post here. Then click on button Log, then button „save to file“, upload to pastebin.com and post a link here.

Open setting page, scroll the page if necessary to make all extensions in the left menu visible on screen, make a screenshot and post it here.

**Comment by CurlyFlow** [comment]
> For one download (nzb) which misbehaves, after it is auto-paused, click on the item, make a screenshot, post here. Then click on button Log, then button „save to file“, upload to pastebin.com and post a link here.
> 
> Open setting page, scroll the page if necessary to make all extensions in the left menu visible on screen, make a screenshot and post it here.

THANKS! For your amazing fast and friendly response!

I will do that!

For now im tryin the nzbget:testing version and it SEEMS to be working so far. But i will report back asap when i see another paused download!

Thanks also for the detailed info on how to obtain the needed information!!!

**Comment by CurlyFlow** [comment]
OK it happend again to 7 downloads over night.

Because of content of the information i will sent it to you via e-mail, i hope thats ok, i dont want to post it public...

Ive sent it to nzbget @ g...l.com ...

I really wonder why in the log there is nothing about "pausing download" and still it does that. From reddit i know atleast some people have the same "problem".

**Comment by hugbug** [comment]
Your nzbs contain nothing but par2-files. There is no video or other data in them. Since nzbget downloads only necessary amount of par2-files and pauses the remaining par2-files, all you have after the download completes is one par2-file on disk and the remaining par2-files in queue in paused state.

You should check your source of nzb-files. Maybe you need a better indexer.
