### ISSUE TITLE
feature request: recognize zipped nzb file upload

### ISSUE THREAD

**Issue by ahmedtds** [nzbget/nzbget#666]
Hi

Often I want to upload zipped/rarred package of nzb files via web ui.

You know nzb files compress very well so it would save time if it could accept archive files and then unpack nzb files from it.

Also often I can't upload very big (like 30-40-50 MB) nzb files via web ui, it just stucks there forever, so it would help to solve this issue as well

Thanks

**Comment by vergessen** [comment]
You can always use a preprocess script.  I wrote a simple *zip one in my repository this one expanded on that for several type

https://github.com/Prinz23/nzbgetpp

**Comment by hugbug** [comment]
As pointed out there are post-processing scripts for this. For example https://forum.nzbget.net/viewtopic.php?f=8&t=1600
