### ISSUE TITLE
Download speed capped to 30MB/s on Linux? 

### ISSUE THREAD

**Issue by RaymondMouthaan** [nzbget/nzbget#669]
Hi All,

I face download speed limitation of about 30MB/s with Nzbget v21 and performed tests on different host systems.

**MacBook Pro 16"**
Download speed reaches about **60MB/s** (+/-500Mb/s) which is my maximum download speed. So basically no issues here. Side note: I've installed NZBGet as per default according to the [installation guide for mac](https://nzbget.net/installation-on-mac).

**Mac Mini mid 2012**
On a Mac Mini mid 2012 (I5 & 4GB mem) with Ubuntu server installed, I've installed NZBGet as per default according to the [installation guide for linux](https://nzbget.net/installation-on-linux), the maximum download speed reaches about **30MB/s** (+/-250Mb/s). 

**Mac Mini mid 2012 Docker**
On the same Mac Mini, using Docker image from [linuxserver/nzbget](https://hub.docker.com/r/linuxserver/nzbget/) the max download speed reaches about **30MB/s** (+/-250 Mb/s). 

**Synology NAS DS1813+**
Similar to the Mac-Mini Docker test, running the Docker image on a Synology NAS, shows the same behaviour of a maximum of **30MB/s** (+/-250Mb/s). 

**Speed tests**
On all systems I performed a speed test with curl to download a 10GB bin, which shows a download speed of about **60MB/s**. This test was also performed from within the Docker containers, to make sure Docker doesn't cap the speed somehow. 

For all NZBGet tests the same usenet provider has been used via ssl and 40 connections.

**Summery**

| System | Max Download Speed | OS |
|--------|---------------------|---|
|Macbook Pro|60MB/s| macOS Catalina |
|Mac Mini |30MB/s      | Linux Ubuntu 18.04.3 LTS  |
|Mac Mini Docker|30MB/s| Linux Alpine 3.11 |
|Synology DS1813+ Docker|30MB/s| Linux Alpine 3.11 |

Based on all tests - cpu, memory, disk I/O or network should be the limited factor. 
Look as if running NZBGet on Linux gets capped to 30MB/s for some reason, while running on macOS doesn't.

Anyone suggestions/ideas ? 
If more info is required to analyse this issue, let me know.

Best regards,
Raymond

**Comment by hugbug** [comment]
On Mini and NAS you probably download to HDD whereas on MacBook to SSD.

Try putting **QueueDir** and **DestDir** to different physical drives.

**Comment by RaymondMouthaan** [comment]
thanks for your response @hugbug 

Both Macbook and Mac mini have SSD installed. The NAS has 8 HDD configured in SHR (raid 5).

A quick hdparm on the **Mac-mini** shows the following:

```
sudo hdparm -Tt /dev/sda
[sudo] password for raymond:

/dev/sda:
 Timing cached reads:   13074 MB in  1.99 seconds = 6556.61 MB/sec
 Timing buffered disk reads: 1382 MB in  3.00 seconds = 460.57 MB/sec
```

And on the Synology:
```
sudo hdparm -Tt /dev/vg1/volume_1
Password:

/dev/vg1/volume_1:
 Timing cached reads:   1880 MB in  2.00 seconds = 939.85 MB/sec
 Timing buffered disk reads: 750 MB in  3.00 seconds = 249.62 MB/sec
```

**Comment by hugbug** [comment]
If option **FlushQueue** is enabled try disabling it for a test.

**Comment by RaymondMouthaan** [comment]
**FlushQueue disabled**
Just reinstalled NZBGet on the Mac-mini, with all setting per default and changed the FlushQueue to disabled. Download starts nicely at 60MB/s, but after about 30 seconds, it drops to about **32 MB/s** ... 

**FlushQueue disabled &  DirectUnpack disabled**
I've noticed DirectUnpack is enabled per default, which I disabled and re-ran the download, which seems to improve the download speed to about **53 MB/s**.

**FlushQueue enabled & DirectUnpack disabled**
Download speeds starts at 60 MB/s but drops to **38 MB/s**.

So looks as if both options should be disabled to get the best speed?

**Comment by ulrick65** [comment]
As I mentioned on the forum, I run Linux (Ubuntu 18.04) and have no issue getting to 55+MB/s (my max download pipe).  So I doubt this is an NZBGet issue.  I have to ask because I don't see where you mention it...you don't have the Download Rate set to 30 by default, do you?  I don't recall what the default is for this setting is, but perhaps it is 30 in the Linux install?  I set mine to 35 so the rest of the house doesn't get starved for bandwidth when NZBGet is doing its thing.

**Comment by hugbug** [comment]
I'm closing this thread as we have here a configuration or hardware issue, which cannot be fixed in nzbget code.
