### ISSUE TITLE
Endless Failure Loop?

### ISSUE THREAD

**Issue by pctweakz** [nzbget/nzbget#670]
Hello! It appears my NZBGET has been in an endless failure loop where it attempts to parse a file every single minute for months now.

It will attempt to add article to collection then error as parsing - cannot find path. It is a file that has been deleted long ago. There are about 34,000 failures, due to it constantly trying and failing.

I can not find a way to make it stop. Does anyone have any idea on how I can clear this from it's memory and have it stop attempting to work on a file that no longer exists?

Error from Log on one of the 34,000 entries in history of failures, all the same:
Error parsing nzb-file *********************** : The system cannot find the path specified.

**Comment by hugbug** [comment]
Do you still have this issue?
