### ISSUE TITLE
Unpack rar sometimes fails to name file correctly

### ISSUE THREAD

**Issue by polizz** [nzbget/nzbget#671]
Unable to track this down. Just updated to latest version 21 and it did not fix it. What I am seeing is that the unpack of some rar sets creates a cryptic file name without a proper file extension (i.e. `1dda7c134f6a8333bea4a7a096de019b`).

Not sure where it's coming up with this name, but I first see it introduced during the cleanup stage and it says it's cleaning up archive files: `Deleting file 1dda7c134f6a8333bea4a7a096de019b.part1.rar`

There are other downloads that are succeeding and those all have no pars - that seems to be the thing that is changing the behavior here. The ones that are failing have pars that are being pulled down and processed.

If I look inside the completed rar set, I see a proper file name and file extension and I can extract this archive fine manually. This malformed file name is breaking down stream scripts.

Right now I'm using the following unpack command:
`/usr/local/bin/unrar e -ai`

Let me know what other information I can provide.

**Comment by hugbug** [comment]
Please send me a few example nzbs to nzbget@gmail.com.
