### ISSUE TITLE
extract zip and 7z not working when the password is provided in the nzb header...

### ISSUE THREAD

**Issue by mbruel** [nzbget/nzbget#672]
Hi,
For a zip file, here is my log:
```
Mon Jan  6 04:18:02 2020	INFO	Join: Joining splitted file ngPostZipArchive.zip
Mon Jan  6 04:18:02 2020	INFO	Join: Joining from ngPostZipArchive.zip.001
Mon Jan  6 04:18:02 2020	INFO	Join: Joining from ngPostZipArchive.zip.002
Mon Jan  6 04:18:03 2020	INFO	Join: Joining from ngPostZipArchive.zip.003
Mon Jan  6 04:18:03 2020	INFO	Join: Joining from ngPostZipArchive.zip.004
Mon Jan  6 04:18:03 2020	INFO	Join: Joining from ngPostZipArchive.zip.005
Mon Jan  6 04:18:03 2020	INFO	Deleting archive files
Mon Jan  6 04:18:03 2020	INFO	Deleting file ngPostZipArchive.zip.005
Mon Jan  6 04:18:03 2020	INFO	Deleting file ngPostZipArchive.zip.004
Mon Jan  6 04:18:03 2020	INFO	Deleting file ngPostZipArchive.zip.001
Mon Jan  6 04:18:03 2020	INFO	Deleting file ngPostZipArchive.zip.002
Mon Jan  6 04:18:03 2020	INFO	Deleting file ngPostZipArchive.zip.003
Mon Jan  6 04:18:03 2020	INFO	Unpack for ngPostZipArchive successful
Mon Jan  6 04:18:03 2020	INFO	Checking renamed files for ngPostZipArchive
Mon Jan  6 04:18:03 2020	INFO	No renamed files found for ngPostZipArchive
Mon Jan  6 04:18:03 2020	INFO	Cleaning up ngPostZipArchive
Mon Jan  6 04:18:03 2020	INFO	Deleting file ngPostZipArchive.par2
Mon Jan  6 04:18:03 2020	INFO	Cleanup for ngPostZipArchive successful
Mon Jan  6 04:18:03 2020	INFO	Moving completed files for ngPostZipArchive
Mon Jan  6 04:18:03 2020	INFO	Move for ngPostZipArchive successful
```
so it seems the unzip worked but it is not the case, I've the zip file in the successful folder.

For 7z it is not working but we see the 7za error:
```
Mon Jan  6 04:19:03 2020	INFO	Executing 7-Zip
Mon Jan  6 04:19:03 2020	INFO	7-Zip: 7-Zip (a) [64] 9.38 beta  Copyright (c) 1999-2014 Igor Pavlov  2015-01-03
Mon Jan  6 04:19:03 2020	INFO	7-Zip: p7zip Version 9.38.1 (locale=C,Utf16=off,HugeFiles=on,8 CPUs)
Mon Jan  6 04:19:03 2020	INFO	7-Zip: Processing archive: myArchive.7z.001
Mon Jan  6 04:19:03 2020	INFO	7-Zip: Error: Can not open encrypted archive. Wrong password?
Mon Jan  6 04:19:03 2020	INFO	7-Zip: Can't open as archive: 1
Mon Jan  6 04:19:03 2020	INFO	7-Zip: Files: 0
Mon Jan  6 04:19:03 2020	INFO	7-Zip: Size:       0
Mon Jan  6 04:19:03 2020	INFO	7-Zip: Compressed: 0
Mon Jan  6 04:19:03 2020	ERROR	7-Zip error code: 2
```

I've checked manually with the 7za binary provided and it is working so I'm guessing the -pMyPass is missing in the command

**Comment by hugbug** [comment]
Zip-archives are generally not supported.

7z-archives should work fine. After the file is added to queue, click on download item, then on button Postprocess. Is the password set?

**Comment by Mak3rde** [comment]
similar problem, using nzbget, i'm on unraid, running in a docker from linuxserver.io,
if i have nzb files that contain the password in the filename {{password}} the unpack will fail with error message : Incorrect password for file.xyz. (nzbt get is trying unpack with winrar 5.80)

but if i copy that files (rar fileset) to my workstation and try to unpack it with 7zip and/or winrar 5.80 x64 and the same password it works witout problems.

just downloaded 12 new nzbfiles with password in title -> xoxoxoxoxox{{123456789654213}}
every single one of them failed with the exact same message.

**Comment by hugbug** [comment]
@phillipsko 
Nzbget doesn’t process passwords from nzb file names. If you need this please take a look in post-processing section of the forum. There is an extension script for that - https://forum.nzbget.net/viewtopic.php?f=8&t=915.

**Comment by Mak3rde** [comment]
thx for the info, will take a look at the scripts
