### ISSUE TITLE
Crashing, Windows 10 - Sonarr/Radarr

### ISSUE THREAD

**Issue by BioHazard2000** [nzbget/nzbget#673]
I saw a thread that was closed do to lack of information that might be what is happening with me.

Basically nzbget crashes a lot when open in Chrome.  I am currently leaving it closed for the night as I have installed the debug version and setup Windows 10 to allow for crash logs.

If it crashes overnight I will have a couple logs I can send and if it doesn't then I will leave Chrome open to get you a few dumps.

These files so far have been ranging from 180-220MB.

As the title implies I am using Sonarr/Radarr to deal with NZBget.

I tried to register for your official forums but need the answer to your security question.  You'll have an email with an email address containing beelo.

**Comment by markheloking** [comment]
Did you manage to get the crash logs? What version of NZBGet did you get this issue on?

**Comment by BioHazard2000** [comment]
I did but couldn't send them to anyone.  Shortly after these issues my system blew up.  Picked up a Synology box as a replacement and haven't had any issues since.
