### ISSUE TITLE
Case sensitivity in storing .queued files

### ISSUE THREAD

**Issue by ulrick65** [nzbget/nzbget#675]
I have noticed this issue for a long time, and always intended on bring it up, but never got around to it.  So here it is:

It appears to me that when two nzb files are named the same, NZBGet will add a .2 (or I assume 3, 4 or whatever but I haven't checked) to the end of the filename before storing it.

Since I am on a Linux system, the check is done with regard to the case of the letters (upper vs lower).  So NZBGet would see the following files as NOT the same filename (which is correct on Linux):

"Some file downloaded.nzb.queued"
"SOME file downloaded.nzb.queued"

Can this be changed to do the comparison without regard for case and in my example above add the (1) to the filename so it becomes:

"SOME file downloaded.nzb.2.queued"

The reason for this is that if/when these files get accessed by a Windows machine (my backup scheme goes through a windows environment) the files are seen as duplicates as throws errors in the process.  I don't see any harm in adding the .2 but perhaps I am missing something that would be a potential issue.

Thanks, I appreciate the consideration.

**Comment by hugbug** [comment]
When checking if the file exists nzbget uses system function `stat` which takes the file name as parameter. To do the check case-insensitive we need to read the whole directory content and compare each file. That's a lot less efficient. The file-exists-checks are used at many program places, which would be affected by a change to the check-function.

If you need to access files on both Linux and Windows, shouldn't you use a case insensitive file system generally?

**Comment by ulrick65** [comment]
Couldn't you simply convert the stat to either upper or lower before doing the compare?  Obviously I don't know the code or the issue with doing that, it's just an idea.  I do some very basic Python scripts and that's what I do when comparing file names that might hit both Windows and Linux.

Thanks.

**Comment by hugbug** [comment]
The thing is I don't do any compare. I call the system function `stat` and passing the file name. The function tells me if the file exists. The function probably does some compare or it works in cooperation with file system driver. Anyway that's not a part I can change.

The only solution I can think of is to read the whole directory content and check every file. This is however an expensive fix for a rare problem.

**Comment by ulrick65** [comment]
Ahh...I see your point.  Thanks for taking a look. Go ahead and close this out.

Thanks again.
