### ISSUE TITLE
Logging / Messages in Scan-script?

### ISSUE THREAD

**Issue by jasonla** [nzbget/nzbget#676]
I apologize if this is the incorrect place to ask. If it is, please redirect me, and I'll close the topic/move my question.

I'm using this [scan-script extension](https://forum.nzbget.net/viewtopic.php?p=18394#p18394) I found on the forums and have modified it slightly to output some information to logger.

The script does work, but when I tried to add some logging to it, nothing shows up in the web interface:

```
if fwp:
	print("[INFO] Found " + os.environ['NZBNP_NZBNAME']) # Added this
	print("[INFO] Replacing with " + fwp) # Added this
	print("[NZB] NZBNAME=%s" % fwp)
	sys.stdout.flush()
	sys.exit(POSTPROCESS_SUCCESS)
```

Is there something different I should be doing? I see that FakeDetector uses something similar, but for whatever reason, I can't get the logging to show up.

I do know that the rename of the NZB file is working as I can see the removal of obfuscated, scrambled, etc etc.

**Comment by hugbug** [comment]
This should work. Maybe you have logging disabled in nzbget? Check options InfoTarget, etc.
