### ISSUE TITLE
Prevent Nzbget phoning home

### ISSUE THREAD

**Issue by iio7** [nzbget/nzbget#677]
I see a lot of this:

```
Downloading nzbget version info
https://nzbget.net/info/nzbget-version.json?nocache=1581045881704
Downloading nzbget version info
```

How do I disable that? Nzbget get's upgraded using a package manager and I don't need it to repeatedly phoning home.

Thanks.

**Comment by hugbug** [comment]
Disabling option **UpdateCheck** should help.

**Comment by iio7** [comment]
Doh! Yes, that would properly do it!

Sorry, overlooked that.
