### ISSUE TITLE
nzbget installation failled on Debian 9.9 : Libssl1.0.0 is not installable

### ISSUE THREAD

**Issue by etienne954** [nzbget/nzbget#678]
Hi everyone,
I'm trying to install nzbget on a raspberry pi (debian stretch 9.9).
I get an error message saying that libssl1.0.0 but it is not installable.

```
The following packages have unmet dependencies
xbian-package-nzbget : Depends : libssl1.0.0 but is not installable
E : Unable to correct problems, you have held broken  packages.
```

Here's the list of libssl installed 
```
xbian@xbian ~ $ apt list libssl*
Listing... Done
libssl-dev/oldstable 1.1.0l-1~deb9u1 armhf
libssl-doc/oldstable 1.1.0l-1~deb9u1 all
libssl-ocaml/oldstable 0.5.2-2 armhf
libssl-ocaml-dev/oldstable 0.5.2-2 armhf
libssl1.0-dev/oldstable 1.0.2u-1~deb9u1 armhf
libssl1.0.2/oldstable 1.0.2u-1~deb9u1 armhf [upgradable from: 1.0.2r-1~deb9u1]
libssl1.1/oldstable 1.1.0l-1~deb9u1 armhf [upgradable from: 1.1.0j-1~deb9u1]
```
Did anyone already have this issue before ? Is there any workaround ? Should I try to remove libssl1.0.2 and install libssl1.0.0 ? It doesn't sound like a good idea to me but I'm not a big expert.

Thank you in advance for your support.

**Comment by hugbug** [comment]
You use a package created and maintained by third party. Please report the issue to the maintainer of the package.

You can download the official nzbget installer from nzbget download page. It will most likely work on your system.
