### ISSUE TITLE
DirectUnpack + UnpackCleanupDisk not working

### ISSUE THREAD

**Issue by lolrofllol** [nzbget/nzbget#681]
Hi,
I am running NZBGet on a machine with a very small disk, so I am using every "Direct..." Setting to minimize disk usage.

I have switched on DirectUnpack and UnpackCleanupDisk, but the Cleanup is still triggered **after** the download of all rar parts. When I manually delete the .rxx files after they were unpacked due to DirectUnpack, there is no error with the output file. So they are not needed after they were extracted.

Is this a bug or working as intended? If not this would be a nice feature to minimize disk usage.

**Comment by hugbug** [comment]
That's a correct behavior. The files may become necessary for repair if a download error occurs later.
