### ISSUE TITLE
HTML encode special characters in username and password

### ISSUE THREAD

**Issue by jagandeepbrar** [nzbget/nzbget#682]
Authenticating to the API by passing the username and password after the host but before `jsonrpc` works great, except when there are specific special characters in the password (such as `/`).

```html
<host>/<username>:<password>/jsonrpc/...
```

Is there anyway that you can support HTML-encoding the username and password when using this authentication type? I am unable to use basic auth methods (appending before the host) because some of my users have a second layer of security through a reverse proxy and they interfere with one another.

**Comment by hugbug** [comment]
Implemented this. There are restrictions through:
- username may not contain `:` or `/`
- password may not contain `/`
