### ISSUE TITLE
pause pauses everything, not just downloads

### ISSUE THREAD

**Issue by sjpotter** [nzbget/nzbget#685]
If I pause nzbget, it seems to pause everything.  i.e. it wont import new NZBs I drop into its nzb dir, it wont finish post processing and perhaps more (just  those are 2 things I noticed)

There are times I want it to be paused downloading (example: perhaps I'm on a voip call or video conference, especially these days) but I still want it to continue with its other tasks.

**Comment by hugbug** [comment]
You use button "pause everything" and it does just that.

If you want to pause downloading only then use this command from menu near the round button.

**Comment by sjpotter** [comment]
There's a big round button (green when downloading, orange when paused).  the text when paused for the button says "Download paused (click to resume) [Shift+P]".  when running it says "Download active (click to pause) [Shift+P]".  That sounds like a pause download only to me, not everything, though clearly it is everything.  

I finally found what you mean, (the small down triangle next to the big round button).  Perhaps configuration options can be added to what pressing the big round button means?  i.e. what to pause?

**Comment by hugbug** [comment]
The reason to pause is to give other programs more bandwidth and CPU. An option would make it more confusing.
