### ISSUE TITLE
Unpacking / post-processing halts - binhex container

### ISSUE THREAD

**Issue by zab-01** [nzbget/nzbget#686]
NZBGet is getting stuck unpacking an NZB after download.  In order to fix the issue I end up having to restart the container.  I believe this issue has been present/happening for around a year now?  Some have created user scripts to restart the docker container to work around the defect.

There are other reports of the same issue on the Unraid user forums, i'll quote below.

**Comment by zab-01** [comment]
Quote from another user: https://forums.unraid.net/topic/44140-support-binhex-nzbget/?do=findComment&comment=805772

> I and other users are seeing the same issue. I've discovered a few issues that seem to be related. First is that the par check/repair stage seems to fail randomly. Sometimes nzbget reports 'PAR Success' but no matter how many times I try and re-postprocess the download, the unpack fails or gets stuck. If I run QuickPAR from Windows using the same PAR set, it often finds 1 or 2 files that have all blocks present but they need to be re-joined. Once QuickPAR has re-joined these blocks/files, then nzbget can successfully unpack.

>The other issue is some PAR repairs leave the renamed damaged files in the source folder. I find this confuses nzbget's unpack processing, especially when the first file in the archive set has a renamed copy. For example, if nzbget PAR does a repair/rejoin, it sometimes seems to create a file with one more leading '0' in the filename, i.e. xxxxxxxxxxxxxxxxx.7z.001 is repaired/rejoined but there is a copy of the bad file named xxxxxxxxxxxxxxxxx.7z.0001. The same can happen with rar archives - the filename might be  xxxxxxxxxxxxxxxxx.part001.rar and after the repair/rejoin there's a 2nd file named xxxxxxxxxxxxxxxxx.part0001.rar.

>When you look at the source folder (the 'intermediate' folder for most, depending on how you have nzbget configured) and delete all the 'bad' files that have been renamed and then do a re-postprocess, the unpack will usually succeed. The 3rd case of failure I've found is the complete 'halt' of the extract/unpack process, which seems to be a bug on the way 7zip is called to process .7z archives. The logs show the unpack request is calling 7zip but the unpack hangs for some reason that the logs don't identify.

>Hope these findings might help others and maybe even help the nzbget team further refine their post-processing routines. Note that I've also found these same issues when using the Linuxserver.io build of the nzbget Docker container. This means the issues are likely inherent to the nzbget app and/or the par/unrar/7zip extensions.

**Comment by hugbug** [comment]
This is a known issue with binhex container on Unraid. The binhex container uses nzbget binary  (compiled executable) provided on nzbget download page. This combination isn't working well. No one knows what's causing this.

I recommend you to install nzbget using official installer from nzbget download page. Install it directly on the system, not in a docker container. If you still want to use docker, you need to compile nzbget in the container. That way you'll have a binary optimized for your system.

**Comment by zab-01** [comment]
You are correct.  After your response I migrated to the LSIO container, and I have had zero issues.  Thank you for the support.

**Comment by nomandera** [comment]
For reference the LSIO container https://github.com/linuxserver/docker-nzbget
