### ISSUE TITLE
Anyway to have nzbget to checkmy home folder for disk space instead of the whole drive?

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [nzbget/nzbget#689]
I have a shared seedbox with 2 TB allocated to me, but the hard drive is 7TB. Nzbget is seeing the 7TB drive which is not useful. Would it be possible to add a spot to only check a certain folder (My home folder)?

**Comment by hugbug** [comment]
It checks destination folder (option DestDir), because that's there the downloads end up.
I don't understand from your description what is exactly the problem and what are you trying to achieve.
