### ISSUE TITLE
nzbget-nserv: core dump with input "-z 0" 

### ISSUE THREAD

**Issue by sanderjo** [nzbget/nzbget#690]
I keep on fighting with the input for nzbget's nserv option "-z". I even get core dumps.

I'll send a PR for:
* clearer usage (for people like me): the number is optional, so ... note to self: just leave out any number and leave it to nserv (so: 500000)
* protection against silly input: 0 or negative/overflow numbers

```
$ ./nzbget --nserv -d ~/some-data-dir -z 0 -q
[INFO] NServ 21.1-testing-r2312 (Test NNTP server)
[INFO] Generating nzbs for /home/sander/some-data-dir
Floating point exception (core dumped)
```
```
$ ./nzbget --nserv -d ~/some-data-dir -z something -q
[INFO] NServ 21.1-testing-r2312 (Test NNTP server)
[INFO] Generating nzbs for /home/sander/some-data-dir
Floating point exception (core dumped)
```

resulting in
```
$ ll ~/some-data-dir
total 102408
drwxr-xr-x  2 sander sander      4096 apr 13 11:56 ./
drwxr-xr-x 29 sander sander      4096 apr 13 11:55 ../
-rw-r--r--  1 sander sander 104857600 apr 13 11:55 bla-100M.bin
-rw-r--r--  1 sander sander         0 apr 13 11:56 bla-100M.bin.nzb
```
which will not create a new nzb on the next try with correct input ... 

EDIT

Also unwise usage:
```
./nzbget --nserv -d ~/some-data-dir -z 1 -q
```
which will create a .NZB about 100 times bigger than the file to be handled. So inflicting a DoS on your own system.
I'll build in a protection against that too.

**Comment by markheloking** [comment]
Can this be closed now that the PR is closed? Seems like not many people are using nserv anyway...
