### ISSUE TITLE
Crash seconds after startup when downloading and disk unwritable

### ISSUE THREAD

**Issue by arberg** [nzbget/nzbget#692]
NZBGet 16.4
UnRaid Linux os.
Docker image: https://hub.docker.com/r/gfjardim/nzbget

I am using UnRaid, and due to some cache-disk settings and disk being below minimum free space mark, new files could no longer be written to the folder which was assigned to nzbget incoming downloads.
Nzb crashes on each startup.
After resolving the low-space situation, nzbget ran smoothly again. 

I use docker, and could not find any logs, besides exit notice.

**Comment by hugbug** [comment]
Was option DiskSpace correctly set? Because the program should have paused automatically.
Was the QueueDir writable with enough space? I can imagine weird behavior if queue (program stat) cannot be written.

**Comment by arberg** [comment]
yeah diskspace was set at 250MB, but it wouldn't have helped, as unRaid prevented writing new files to disk at 50GB in my config. queueDir was also on that same cache-disk of unRaid, so no new files could be written there as well. Old files could be updated fine, but no movement, even no new directory could be created.

I just wanted to report the weird behaviour, if for no other reason, then that others might come across the same issue. I can understand if its not worth your time to fix it.

**Comment by Pentaphon** [comment]
> NZBGet 16.4

Shouldn't you be using a more up to date version?

**Comment by arberg** [comment]
Ups, thx for letting me know. I'm glad I included the version at least. My docker-container apparently stopped being updated.

**Comment by markheloking** [comment]
Is this issue still present on new releases? Seems like this might be resolved in the meantime...

**Comment by arberg** [comment]
I thought I tested it, and I seem to remember running some tests on it, but probably I forgot or got it wrong, given that I didn't wirte anything about it here, and it seems to working.

I just tested again by requiring huge amount of free space (same issue that I had last), I tested on NZBGet 16.4. It starts and runs, and it gives nice erors in the error log visible in the gui:

```
INFO | Mon Jul 06 2020 08:40:09 | nzbget 16.4 daemon-mode
-- | -- | --
INFO | Mon Jul 06 2020 08:40:09 | Pausing all activities due to errors in configuration
ERROR | Mon Jul 06 2020 08:40:09 | nzbget.conf(1428): Invalid value for option "HealthCheck": "park"
ERROR | Mon Jul 06 2020 08:40:09 | nzbget.conf(1692): Invalid option "Category5.Extensions"
```

I've closed the issue. Sorry about wasting your time...
