### ISSUE TITLE
10060 on test connection

### ISSUE THREAD

**Issue by cryptowhizzard** [nzbget/nzbget#695]
Hello,

NZB produces an error when doing test connection

"Could not receive data on socket from" ErrNo 10060

Running the latest diablo version. Is there any setting i missed or patch available for this?

Downloading etc. works so everything is working except test.

**Comment by hugbug** [comment]
"ErrNo 10060" is for time out.

During connection test the timeout is limited to max. 10 seconds. Maybe your server is too slow to respond?
