### ISSUE TITLE
Reference to undefined entity 'auml'

### ISSUE THREAD

**Issue by colemar** [nzbget/nzbget#699]
Windows 10 64-bit
nzbget version: 21.0

It seems that NZBGet does not like entity `&auml;` 

Log file chunk:
```
Mon Jun  1 00:21:35 2020	INFO	Adding collection 90] - _Folterzug der geschändeten Frauen.nzb_ yEnc.nzb to queue
Mon Jun  1 00:21:35 2020	ERROR	Error parsing nzb-file 90] - _Folterzug der geschändeten Frauen.nzb_ yEnc.nzb: Reference to undefined entity 'auml'.

Mon Jun  1 00:21:35 2020	ERROR	Could not add collection 90] - _Folterzug der geschändeten Frauen.nzb_ yEnc.nzb to queue
Mon Jun  1 00:21:35 2020	INFO	Collection 90] - _Folterzug der geschändeten Frauen.nzb_ yEnc added to history
```
Offending NZB file:
[Folterzug-nzb.zip](https://github.com/nzbget/nzbget/files/4708617/Folterzug-nzb.zip)

**Comment by hugbug** [comment]
`&auml;` isn't a valid entity for xml, which nzb-files are. It's valid for html but not xml.
Therefore this nzb-file is invalid.

**Comment by colemar** [comment]
Then NZBIndex is to blame.
