### ISSUE TITLE
Convert NZB RSS to audio podcast feed

### ISSUE THREAD

**Issue by TD540** [nzbget/nzbget#701]
Looking for a solution, if it even exists, to convert an NZB RSS feed to a feed I could subscribe to in my podcast app.

Could nzbget somehow be extended so it can republish an RSS feed where perhaps the only thing it needs to do would be to change `<enclosure url=“https_link_to_nzb_download” type=“application/x-nzb”/>` to `<enclosure url=“http://local_nzbget/nzb_download.mp3” type=“audio/mpeg”/>`?

**Comment by hugbug** [comment]
This request is way beyond the purpose of nzbget application and therefore cannot be fulfilled.
