### ISSUE TITLE
Python 2 deprecation and https://nzbget.net/catalog-of-extension-scripts

### ISSUE THREAD

**Issue by nomandera** [nzbget/nzbget#702]
As far as I can tell Python 2 deprecation is not mentioned at https://nzbget.net/catalog-of-extension-scripts 

A quick test seems to suggest that quite a few of the older extensions are now broken under python 3.

At the very least the list could do with some TLC but something more radical should maybe be done to fix and promote what is a very useful system/community and make it a bit less like the "wild west".

**Comment by hugbug** [comment]
I've removed this outdated page altogether.
