### ISSUE TITLE
Prevent appending nzb files to completed folder

### ISSUE THREAD

**Issue by afsharsafavi** [nzbget/nzbget#703]
Hi
I've searched a lot but I didn't find any solution for this issue:
When downloading a file is completed, nzbget copy the main nzb file to destination folder.
Is it possible to prevent it? Is there any switch?

**Comment by markheloking** [comment]
Maybe this is due to setting the NZBDir and DestDir to the same directory? I haven't seen this behavior before myself.

**Comment by afsharsafavi** [comment]
No, They are different (default values) 
<img width="352" alt="Screen Shot 2020-07-01 at 5 09 30 AM" src="https://user-images.githubusercontent.com/14315351/86190308-427a0d80-bb59-11ea-8102-ecd904d6ea32.png">

**Comment by hugbug** [comment]
> When downloading a file is completed, nzbget copy the main nzb file to destination folder.

No, it doesn't copy. Your download probably contains nzb-file, which is then downloaded form the Usenet and saved into destination. Cleanup scripts could help, for example **VideoSort**.
