### ISSUE TITLE
Tar/tar.gz support

### ISSUE THREAD

**Issue by freezeeedos** [nzbget/nzbget#707]
Hello dear devs,

After using nzbget for a while, coupled with lidarr, I notice that a lot of music releases are packed using tar, and it seems that nzbget is unable to unpack them. I went through the changelog, and i see 7z,rar and zip being mentioned, but I'm not sure that tar is implemented.
7z already being used internally, I'm guessing tar/tar.gz would be quite easy to implement :)

What do you think ?

Regards,

Quentin

**Comment by hugbug** [comment]
NZBGet has built-in support for rar and 7z archives only. Other archive types can be unpacked using post-processing script but you need to write one yourself.

Please visit [forum](https://forum.nzbget.net/viewforum.php?f=8) for examples of post-processing scripts.

**Comment by Nothing4You** [comment]
@hugbug is there any reason not to support tar files at least?

recently i'm also seeing tar files being used for other media too.

as long as they're just tar files and not tgz archives they can also be extracted in a single run of the bundled 7za.

tgz archives are not possible in just a single step using 7z unfortunately.
