### ISSUE TITLE
 binding socket failed for 0.0.0.0 errno 0, the operation completed successfully

### ISSUE THREAD

**Issue by Optikn3rv** [nzbget/nzbget#708]
Been using NZBGet for about 2 years without issues and yesterday after 3 changes to my computer it started giving the error  **binding socket failed for 0.0.0.0 errno 0, the operation completed successfully** and when it opens firefox it fails to connect to **http://127.0.0.1:6789/**
I have searched for other people having this issue and done what was advised there like rename the nzbget.conf file though all i see in the install folder is nzbget.conf.template. If I delete this and run nzbget it does not create a new conf file either.

I uninstalled and cleared the registry and reinstalled and still the same.
The 3 changes I made to my PC are
1. updated the motherboard bios
2. uninstalled malwarebytes
3. update some microsoft framework via windows update.

I am using windows 10 pro.

**Comment by hugbug** [comment]
I guess this issue is obsolete.
