### ISSUE TITLE
Connection refused when NZBHydra sends nzb from a reverse proxy

### ISSUE THREAD

**Issue by lenaxia** [nzbget/nzbget#709]
**Description:**
If NZBHydra is under a reverse proxy (i.e. http://nzbhydra.lan -> http://nzbhydra:5075), any NZBs sent to NZBGet fail with the following error:

"Connection to nzbhydra.lan failed: ErrNo 111, Connection refused"

**Reproduction:**
1. launch instances of NZBHydra (http://host:5075) and NZBGet (http://host:6789)
2. Create a reverse proxy that redirects http://nzbhydra.lan to http://host:5075
3. Create a reverse proxy that redirects http://nzbget.lan to http://host:6789
4. Configure NZBHydra with NZBGet downloader using 'host' and '6789' as hostname and port.
5. Search for something on NZBHydra and click "Sent to NZBGet"
6. Observe the following error in NZBGet: "Connection to nzbhydra.lan failed: ErrNo 111, Connection refused"
7. Go to NZBHydra via http://host:5075 and try "Send to NZBGet" again, this time it will work

**Comment by hugbug** [comment]
That isn't an issue in nzbget and cannot be fixed in nzbget. You have to fix your configuration of proxies, hydra and firewalls.
