### ISSUE TITLE
Cannot start GUI from console

### ISSUE THREAD

**Issue by GameProgramer** [nzbget/nzbget#710]
NZBGet v21 on Windows 10 x64. 

NZBGet needs to be started up after the VPN is up. To do this, I have batch file that starts/connects to the VPN server and then runs applications that depend on the VPN. This works fine with most apps, but NZBGet does not start up in GUI mode in this particular scenario.

I have tried passing in the -app command line parameter but that is rejected and the command line usage is printed. 

Note that the -s command line parameter works, but in this scenario, downloading a NZB directly from the browser starts up another server instance and causes issues with the running instance.

Can this please be fixed?

Thanks.

**Comment by hugbug** [comment]
What's the exact command you try to start nzbget?

**Comment by GameProgramer** [comment]
There's two issues here, but the latter follows because of the first, I believe. 

What I'm trying to do, is get NZBGet to run in "app" mode even though it's started from the batch file. Looking at the code, it looks like there is explicit code that prevents that.

Anyway, repro steps:
- Double click the NZBGet app from Explorer. Notice that app starts up in server mode, BUT also that it shows the icon in the notification tray (running in app mode).
- Open a command window (cmd.exe) run NZBGet.exe -s. Notice the app starts up in server mode BUT the icon is missing from the notification tray.

The second problem, happens when the app is started from the console, running in server mode:
- Click on an NZB link in the browser. Notice it starts a second instance of the app, which is the issue, as every download spawns a new instance.
- This does NOT happen if the server was started directly by clicking it from Explorer.

Note: I did try NZGet.exe -app -s and it doesn't work. The help message is displayed.

What I'd like is to specify the -app parameter from the command line to force it to run exactly like if it was run by double clicking on it in Explorer.

Thanks.

**Comment by hugbug** [comment]
This should work:
```
start C:\nzbget\nzbget.exe -app -s
```

**Comment by GameProgramer** [comment]
That works. Thanks!
