### ISSUE TITLE
ControlIP hostname

### ISSUE THREAD

**Issue by Anuskuss** [nzbget/nzbget#711]
I want to access NZBGet from my local network so I've set the `ControlIP` to my local IP address. To keep my server flexible (aka let DHCP do its thing) I would like to instead set it to my hostname. But because I'm on Debian my hostname redirects to `127.0.1.1` instead of `192.168.x.x`.
I see three possible solutions to this:
1. I remove the entry in `/etc/hosts` (the consequences are not clear to me so I'd rather not mess with that)
2. Just bind the whole subnet like e.g. Transmission (would probably require a big rewrite)
3. Allow domains in `ControlIP` (e.g. `device.local` redirects to my local IP)

I think the easiest way would be the third option.

**Comment by hugbug** [comment]
Why not use "0.0.0.0"?

**Comment by Anuskuss** [comment]
Because that's really insecure, I'd rather use `192.168.0.0` (2nd suggestion).

**Comment by hugbug** [comment]
Sorry but such flexibility is beyond the scope of the project.

If you need more flexible binding please use 127.0.0.1 in nzbget and setup a proxy server (such as nginx), which you can bind as you like.

**Comment by Anuskuss** [comment]
Well, I don't really understand why things are handled in such a unusual way (instead of per interface or CIDR), but in the end I've decided to just remove the `127.0.1.1` entry in my `hosts` file (the implications are still unclear to me but I haven't noticed any changes), so `<hostname>` redirects to the correct ip address now.
