### ISSUE TITLE
Pausing Files of a NZB is not working at the first Try

### ISSUE THREAD

**Issue by Friday13th87** [nzbget/nzbget#712]
This is a "always happening problem" and everyone can test it by:
1. Pause Download in nzbget
2. Add a NZB to the list
3. open NZB file list, select some or all files, set them to PAUSE, select others and set them to START (for example, everything to pause but part 20 till 30 to START)
3. Press SAVE
4. open NZB again and check if the files set as you desired (you will see, they are)

and now
5. Hit the start download button / end the download pause in nzbget

Result:
the NZB gives a damn about your premade settings and the files will be in starndard setting, as if you would just have imported the NZB (every rar file on START and every par2vol file on PAUSE)
you need to pause all files again and select the files you want to download again wile the part1 etc is already downloading.

**Comment by hugbug** [comment]
This is a side effect of option **DirectRename**. After the proper file names became known the usual handling of par and non-par files kicks in.

This is hard to fix. Disabling DirectRename should help.
