### ISSUE TITLE
Cannot create directory due to permissions issue (ACL ?)

### ISSUE THREAD

**Issue by thing4711** [nzbget/nzbget#716]
Hello,

I am having a strange bug with regards to permissions where I hope that I didn't just miss a simple issue.

I am using NZBGet stable version 21.0 on
Debian GNU/Linux 9 (stretch)
running in an LXC container on Proxmox 6.2-2
Linux 5.4.65-1-pve #1 SMP PVE 5.4.65-1 (Mon, 21 Sep 2020 15:40:22 +0200).

The nzbget daemon is started via systemd and runs under user nzbget and group smb_usenet:
```
root@filedump ~# cat /etc/systemd/system/nzbget.service
[Unit]
Description=NZBGet Daemon
Documentation=http://nzbget.net/Documentation
After=network.target

[Service]
User=nzbget
Group=smb_usenet
Type=forking
ExecStart=/var/lib/nzbget/nzbget -D
ExecStop=/var/lib/nzbget/nzbget -Q
ExecReload=/var/lib/nzbget/nzbget -O
KillMode=process
Restart=on-failure

[Install]
WantedBy=multi-user.target

root@filedump ~# netstat -tlpen | grep nzbget
tcp        0      0 127.0.0.1:6789          0.0.0.0:*               LISTEN      1008       81777      253/nzbget

root@filedump ~# cat /etc/passwd | grep 1008
nzbget:x:1008:1001::/home/nzbget:/bin/sh

root@filedump ~# cat /etc/group | grep -E "1001|nzbget"
smb_services:x:1001:
smb_usenet:x:1005:nzbget
```

Permissions for smb share are set classic and via ACL:
```
root@filedump ~# namei -l /srv/cifs_enc/data/Usenet/
f: /srv/cifs_enc/data/Usenet/
drwxr-xr-x root root      /
drwxr-xr-x root root      srv
drwxrws--- root smb_users cifs_enc
drwxrws--- root smb_users data
drwxrws--- root smb_users Usenet

root@filedump ~# getfacl /srv/cifs_enc/data/Usenet/
getfacl: Removing leading '/' from absolute path names
# file: srv/cifs_enc/data/Usenet/
# owner: root
# group: smb_users
# flags: -s-
user::rwx
group::rwx
group:smb_services:r-x
group:smb_audio:r-x
group:smb_video:rwx
group:smb_usenet:rwx
mask::rwx
other::---
default:user::rwx
default:group::rwx
default:group:smb_services:r-x
default:group:smb_audio:r-x
default:group:smb_video:rwx
default:group:smb_usenet:rwx
default:mask::rwx
default:other::---
```

As you can see, user nzbget should have write permissions via group permissions of either smb_users or smb_usenet.
When I try manually on the console, everything works fine:
```
nzbget@filedump ~$ whoami
nzbget
nzbget@filedump ~$ cd /srv/cifs_enc/data/Usenet/
nzbget@filedump .../data/Usenet$ ls -alF test
ls: cannot access 'test': No such file or directory
nzbget@filedump .../data/Usenet$ mkdir test
nzbget@filedump .../data/Usenet$ ls -alF | grep test
drwxrws---+  2 nzbget smb_users          2 Oct 24 14:28 test/
nzbget@filedump .../data/Usenet$ rm -rf test
```

However, when I add an nzb file to be downloaded by NZBGet, it shows the following error multiple times in the log before moving the job as failed to the history due to health being below the threshold:
`Could not create directory /srv/cifs_enc/data/Usenet/test/: could not read information for directory /srv/cifs_enc/data/Usenet/test: errno 13,`

When I manually start NZBGet as user nzbget, it works fine:
```
nzbget@filedump ~$ /var/lib/nzbget/nzbget -D
nzbget@filedump ~$ netstat -tlpen | grep nzbget
tcp        0      0 127.0.0.1:6789          0.0.0.0:*               LISTEN      1008       23030999   18567/nzbget
```

Do you have any idea how I can debug this any further and/or where the issue is I am missing ?

Thank you in advance.

**Comment by thing4711** [comment]
While reviewing again what I wrote I just realized that the manually created test directory had group ownership set to **smb_users** while systemd runs under group **smb_usenet**. I just changed the systemd config to group smb_users for testing and now it works.

However, I think it should have worked also with group smb_usenet, shouldn't it ?

**Comment by hugbug** [comment]
Besides option **DaemonUserName** nzbget doesn't have any special code for permissions. All permissions are handled by the system.

Maybe the permissions got screwed when nzbget forks a background process?

As a test you can try to run nzbget in a non-daemon mode:
```
Type=simple
ExecStart=/var/lib/nzbget/nzbget -S -o outputmode=log
```
