### ISSUE TITLE
NZB environment variables are not filtered out correctly

### ISSUE THREAD

**Issue by ghost** [nzbget/nzbget#717]
The filter for NZB variables in InitFromCurrentProcess() doesn't work.

Wrong code:
`if (!(!strncmp(var, "NZB", 3) && strlen(var) > 5 && var[5] == '_'))`
Corrected code:
`if (!(strncmp(var, "NZB", 3) && strlen(var) > 5 && var[5] == '_'))`

**Comment by hugbug** [comment]
The code is OK. Why do you think it's wrong?

**Comment by ghost** [comment]
Due to comments it is intended to filter NZBXX_YYYY variables. In case of the wrong code **!strncmp(var, "NZB", 3)** is true for all env vars doesn't contain at the beginning due to the NOT operator in front. In the corrected code NZB variables are filtered out if all 3 checks are true. This is not the case in the wrong code because the first check is inverted.

NZBXX_YYY
Wrong code: if (!( **!** true && true && true ) != **true** => NZBXX_YYY are added
Corrected code: if (!( true && true && true )) != **false** => NZBXX_YYY are filtered out

Intended behaviour is that NZB variables are filtered if at least one of the 3 checks is false. This is not the case with the wrong code!

**Comment by hugbug** [comment]
Please read the docs for **strncmp**.

**Comment by ghost** [comment]
My mistake, thanks.
