### ISSUE TITLE
Dev dead?

### ISSUE THREAD

**Issue by seitzbg** [nzbget/nzbget#723]
Is any work still being done on this?

Thanks!

**Comment by hugbug** [comment]
It's in maintenance mode for quite some time now.
No new features are being developed at the moment.
I can't tell when (if) I resume the work on it.
That's a hobby project after all.

Do you have any particular issue which I should look into?

**Comment by seitzbg** [comment]
Nope, just been using the latest testing release wondering when a new stable would come out.  No worries, the app works great and thanks!

**Comment by witalit** [comment]
Its a shame to see not much developerment recently. There is still a long outstanding issue with files getting stuck when post processing which as far as I can tell no one is able to work out the issue. 

Such a great bit of software but I have had to create a script to reload NZBGet every hour to prevent NZB's stuck in post-processing forever and pegging CPU at 100%.
