### ISSUE TITLE
Total Download Custom Period

### ISSUE THREAD

**Issue by mouzzampk2014-zz** [nzbget/nzbget#726]
Hi, not an issue but feature request :)

Currently we have Download volumes set for 60 seconds, minutes 24 hours, Month.

Is it possible to add custom time period if I want to look for between 01/01/2020 16:00 - 02/01/2020 15:00?

Thank you

**Comment by hugbug** [comment]
Per-hour statistic data is saved only for the last 24 hours. For older data only daily volumes are saved.
Therefore it's not possible to show volumes for custom hours.
Saving data for each hour forever would require a rework of statistic concept. I don't think it is worth it.
