### ISSUE TITLE
Error: 404 Not Found

### ISSUE THREAD

**Issue by Kru83** [nzbget/nzbget#727]
Hi All, I just set up a new Docker in my Synology NAS.  I am able to get NZBGet to work but during my option for shortcut i only place the IP and Port number, but when I click on the shortcut to open, I am getting 404, not found.  I looked at the URL and it has additional launchParam. 

I don't remember adding them, I actually don't even where I go to remove them.

I am using Synology Docker Verison: 18.09.0.-0513.  NZBGet Version: v21.0-ls66

http://My IP:My Port/?launchParam=data%3D%255Bobject%2520Object%255D

[WARNING] Web-Server: 404 Not Found, Resource: /?launchParam=data%3D%255Bobject%2520Object%255D | stdout
-- | --

**Comment by hugbug** [comment]
If this 404 message comes from nzbget, then check option WebDir in nzbget configuration file.
Otherwise the error seems to be specific to this docker container or synology. You could probably get help from the author of this container or on synology forum.
