### ISSUE TITLE
Windows IPv6 Control IP issue

### ISSUE THREAD

**Issue by BadAd84** [nzbget/nzbget#728]
Hi,

I have a full IPv4 and IPv6 setup, nzbget doesnt respond on the IPv6 address when the ControlIP is set to 0.0.0.0 (or any other IPv4 address).

This makes sense, as its limiting to this IP. If I change the ControlIP to ::, then NZBget works on the IPv6 address, but obviously now not the IPv4 address.

I tried to enter 0.0.0.0, :: in the ControlIP but this breaks both.

Could we get comma separated support for the ControlIP parameter? This should allow people with multiple NIC's restrict the listening range (without having to do 0.0.0.0) and also seemingly fix IPv6 too.

Thanks!

**Comment by hugbug** [comment]
Sorry but such flexibility is beyond the scope of the project.

If you need more flexible binding please use 127.0.0.1 in nzbget and setup a proxy server (such as nginx), which you can bind as you like.
