### ISSUE TITLE
File selector in WebKit based browsers doesn't allow to choose the same file again

### ISSUE THREAD

**Issue by Peronia** [nzbget/nzbget#731]
Hi,

when you add a download paused or when it being downloaded, you can change the status. Hit delete and at the next screen the option "Delete download without history tracking, delete already downloaded files". The entry is gone away as it should be.
Then try to add the same nzb, (no matter of mode, paused or unpaused). Nothing happens. When nzbget are reloaded, all works fine.
Or add a nzb which isn't the same, that works, too. So you can switch the nzb:

1. start nzb1
2. delete nzb1
3. start nzb2
4. delete nzb2
5. start nzb1

**Comment by hugbug** [comment]
Looks like an issue with the web-interface or browser. Please try another browser.
With "nzbget reloaded" do you mean going into settings and hitting "reload" or just reloading browser page?

**Comment by Peronia** [comment]
It works fine in Edge and I mean settings -> reload

**Comment by hugbug** [comment]
What was the browser with issues?

**Comment by Peronia** [comment]
Chrome
