### ISSUE TITLE
From FreeBSD jails to Docker: download performance dropped

### ISSUE THREAD

**Issue by Zamana** [nzbget/nzbget#732]
Hi!

First of all, some info regarding my environment.

I've been running a whole stack of containers (FreeNAS jails) with absolute success. Sonarr, Radarr, Lidarr, Bazarr, Jacket, Nzbhydra2, Plex, qBitTorrent and NZBGet for more than 2 years. No issues at all.

Unfortunately, though, Radarr3 is coming with .NET Core dependency and it seems that the FreeBSD community is not too much interested in .NET Core. Radarr3 still runs (sort of...) in FreeBSD but with very low to none performance.

Then, I decided to migrate all these apps from jails to docker, and to summarize a long story, I succeeded.

The question, though, is that, from the 2 downloaders I use (qBitTorrent and NZBGet), the last one is not working well regarding download performance. qBitTorrent is running fine, with the same download speeds as before, but the performance of NZBGet lowered from 16 MB/s (the top speed) to less than 3 MB/s.

The dockers are running in a FreeNAS VM (Debian 10) with Portainer and Traefik.

I already tried using volumes and binds, with NFS and CIFS shares, changing the mount options, and nothing seems to cause any difference: qBitTorrent runs fine but NZBGet continues with slow performance.

I'm comparing the 2 downloaders because if it was something related with the VM, shares (NFS/CIFS) or Traefik, I would expect a drop of performance in both downloaders, but this change from jails to dockers (keeping all the rest unaltered) seems to cause issues only in NZBGet.

Am I comparing apples with oranges or is there something else that I can do in order to debug and improve the NZBGet performance?

Thanks.

**Comment by hugbug** [comment]
Check performance indicators: CPU usage, disk speed usage.
Then check options in nzbget: FlushQueue, DirectWrite.
For a test use option SkipWrite to check if it's CPU or disk speed.

**Comment by Zamana** [comment]
Hi.

Thanks for reply.

I forgot to say that I migrated NZBGet from jails to docker but I kept all the settings that I was using, changing only the download folders for obvious reasons.

I'll try the SkipWrite soon, but that's the configuration on both environments:

![nzbget_settings](https://user-images.githubusercontent.com/6900313/104849537-f7430480-58c8-11eb-9189-3e8c49d467be.png)

Do you think they should be different?

**Comment by hugbug** [comment]
ArticleCache should be enabled for high performance. Try 100-200.

**Comment by Zamana** [comment]
> ArticleCache should be enabled for high performance. Try 100-200.

Wow! With 100 for ArticleCache (and only this change) my download speed is back to the top!

Thank you very much!

But the question that remains (or arises) is: why this setting wasn't necessary when running through jails?

Thanks.

**Comment by hugbug** [comment]
Probably because a docker running in a VM has much worse disk performance than a jail.

Without article cache the data is written into disk in small chunks (several KB) and simultaneously by many threads.

**Comment by Zamana** [comment]
Thank you very for the support and explanation.

Thanks!
