### ISSUE TITLE
All NZB fails unpack

### ISSUE THREAD

**Issue by Zipties** [nzbget/nzbget#735]
Recently all NZBs started failing to unpack. Manually unpacking them works fine. I dnt see anything in the logs pointing to the issue. All directories are local on the C drive.

Platform is Windows Server 2016
NZBGet: 21.0

https://pastebin.com/WzYcGLtQ

**Comment by hugbug** [comment]
Could it be that the logging for Warnings and Errors is disabled? Please check options **WarningTarget** and **ErrorTarget**.

**Comment by hugbug** [comment]
Closing this issue for now. Feel free to post further comments and I'll reopen the issue if necessary.
