### ISSUE TITLE
WebUI freeze when extension scripts are activated

### ISSUE THREAD

**Issue by kylemd** [nzbget/nzbget#737]
NZBGet v21.0

Steps to reproduce issue:

1. Add extension scripts under EXTENSION-SCRIPTS > Extensions.
2. Click "save all changes"

Once this is done the WebUI hangs - the tab needs to be closed and another one opened. 
Settings page cannot be opened after this as the WebUI will hang.

If there is a log file I can pull to assist in debugging please let me know!

**Comment by hugbug** [comment]
This is probably something very specific to your installation.
Please provide more details about your platform (OS, hardware) and where you get NZBGet (downloaded from nzbget home page or installed from some other repository).

**Comment by hugbug** [comment]
Closing this issue for now. Feel free to post further comments and I'll reopen the issue if necessary.
