### ISSUE TITLE
Debug Logging without recompile

### ISSUE THREAD

**Issue by liambresnahan** [nzbget/nzbget#738]
Hi Folks, I have an issue I'm running into that every few days I get `Communication error! Invalid Status: 502` or `Communication error! Cannot establish connection to NZBGet.` (if I browse directly bypassing the reverse proxy) presented when I try to connect to nzbget. Restarting the container doesn't fix this and the only thing that does it to blow away the root directory and start again, then wait for the issue to come back. This isn't tenable. 
I'd like to dig into this in more detail but can't recompile with the debug flag (or at least would prefer not to due to this being docker and I think it goes a bit beyond what I'm hoping). Is there a way to switch debug logging on without that? At the moment the only thing I can get from the logging is the below single line which is logged every time I browse to the site:
`Sat Mar  6 16:25:56 2021	INFO	nzbget 21.0 server-mode`

**Comment by throwaway481** [comment]
May be related to #741 #745

**Comment by liambresnahan** [comment]
thanks for linking, looks like it, yes. I switched to a different app as the fact is this app isn't really actively maintained.

**Comment by hugbug** [comment]
Debug logging is possible only in debug builds. Debug builds can be downloaded from nzbget download page, no need to recompile.
