### ISSUE TITLE
Crashing every minute

### ISSUE THREAD

**Issue by Toucan-Sam** [nzbget/nzbget#741]
Hey guys, at the moment I'm getting a crash every minute or so that results in NZBGet reloading.
```
[INFO] nzbget 21.0 server-mode
[INFO] nzbget 21.0 server-mode
[INFO] nzbget 21.0 server-mode
```
This causes everything to stop, but then continues downloading for a minute or so, then restarts again.
I'm using the linuxserver.io container, but posting here because I don't think it's container specific.

Previously (and still occasionally) I get
```
[ERROR] Binding socket failed for 0.0.0.0: ErrNo 98, Address in use
[ERROR] Binding socket failed for 0.0.0.0: ErrNo 98, Address in use
[ERROR] Binding socket failed for 0.0.0.0: ErrNo 98, Address in use
[ERROR] Binding socket failed for 0.0.0.0: ErrNo 98, Address in use
```
But there is nothing else on or trying to be on the same port
```
# netstat -ntlpa | grep 6789
#
```
If anyone has thoughts or suggestions, I'd appreciate them. :)

**Comment by zombiehoffa** [comment]
are you running the linuxserver container in docker? I am and this started happening to me today as well.

**Comment by Toucan-Sam** [comment]
@zombiehoffa Yep. Ubuntu 20.04.

**Comment by zombiehoffa** [comment]
ubuntu 20.04 running as an lxc in proxmox over here. I also tried testing, same error. Nothing has really changed on this system and there are no obvious things binding to that port.

**Comment by Toucan-Sam** [comment]
The errors I'm getting at the moment is
`[36509.026027] nzbget[191497]: segfault at 0 ip 00007f90d89f2352 sp 00007f90d7ff1bb0 error 4 in ld-musl-x86_64.so.1[7f90d89b7000+48000]`

Surely there must be more people with this issue?
Some additional links I've found that might be related:
https://jira.hyperledger.org/browse/BE-743 which links to...
https://github.com/nodejs/docker-node/issues/1158
https://github.com/nodejs/docker-node/issues/1158#issuecomment-577261378

**Comment by Toucan-Sam** [comment]
Ultimately I've been able to solve this issue by clearing things from the intermediate, queue, nzb, and tmp folders in the downloads directory. I don't know exactly what the issue is/was but I assume it's crashing trying to interpret a particular character or long file name.

While I'm sure there's a bug here to be filed, I'm not sure what it is, so I'll close this and folks can just find it. @zombiehoffa , hopefully this solves your issue too! Worth a comment if so.

**Comment by zombiehoffa** [comment]
it still breaks over here. It seems to relate back to something breaking in the rss feed parser because I keep getting a whole bunch of stuff added to my queue that was already downloaded and that is where it starts to break.

**Comment by throwaway481** [comment]
@zombiehoffa you are correct. The error that @Toucan-Sam mentioned is/was memory corruption in the nzb parser. Changes in alpine just made this visible. See #745
