### ISSUE TITLE
Server Crash on potential bad NZB from sonarr/radarr

### ISSUE THREAD

**Issue by SeeThruHead** [nzbget/nzbget#744]
Hi sorry I've been having issues since upgrading my unraid servers.

My issue:

NZBget server seems to crash when being sent certain NZB from sonarr/radarr

issue is present on: 
https://hub.docker.com/layers/linuxserver/nzbget/latest/images/sha256-755ac7458a0a0272751af4dbaf789490f238568937902f03b1e02714f9468ac8?context=explore

issue is not present on:
https://hub.docker.com/layers/linuxserver/nzbget/v21.0-ls70/images/sha256-c5dccc23bcae9bf83e6f9c6f99459ea62fac869e5bd1d23af6300e9414d84ac2?context=explore

ls70 container shows an error in the sonarr UI rather than crashing the NZBGET server.
The error that shows up in sonarr on ls70 is `name cannot begin with the '6' character, hexadecimal value 0x36. Line 8, position 68`

It looks to me like an error is no longer being handle correctly and as such the server is crashing. 

I found my "fix" 

here
https://forum.openmediavault.org/index.php?thread/38669-communication-error-cannot-establish-connection-to-nzbget/

clearing the queue and nzb folders fix the issue until sonarr tries to send a error causing nzb back to nzbget

I wish I had more time to figure out exactly what commit are part of ls70 vs ls71. For now I've reverted to ls70

if there is already an issue for this uncaught error i apologize. Thank you

**Comment by nemchik** [comment]
> I wish I had more time to figure out exactly what commit are part of ls70 vs ls71.

https://github.com/linuxserver/docker-nzbget/compare/v21.0-ls70...v21.0-ls71

Edit:

Most of those changes are improvements to our (LSIO) build system and would not affect the output of the container itself with the exception of rebasing from alpine 3.12 to alpine 3.13, which bumps many of the package versions up. The package versions is where you will probably want to look in order to narrow down the issue. Likely a dependency that nzbget uses has made a change that affects how nzbget is able to handle things, thus causing this issue.

If you are able to identify the specific package and version causing the issue it may be possible for us to force a working version of the package into future releases of the container until nzbget can issue a fix on their end to handle the changes in the dependency, or a bug is filed with the dependency and a new version is released without the issue present.

**Comment by throwaway481** [comment]
This is a bug in nzbget. Changes in alpine just made this segfault instead of silently corrupting memory. See #745

**Comment by hugbug** [comment]
How sure you are this issue is caused by #745? Can we close this issue since #745 is fixed or should we wait for the tests with the new nzbget release?

I could provide a new testing build if necessary but I'm not sure you can integrate it into docker container.

**Comment by nemchik** [comment]
> How sure you are this issue is caused by #745? Can we close this issue since #745 is fixed or should we wait for the tests with the new nzbget release?
> 
> I could provide a new testing build if necessary but I'm not sure you can integrate it into docker container.

Our build system does build Docker images for pre-releases from your github repo.

**Comment by hugbug** [comment]
I’ve prepared new build 21.1-testing-r2319 (x86_64 only).

Can the docker image be tested using one of these installers (before I release them through GitHub releases)?

**Comment by nemchik** [comment]
I would probably need to setup a new tag on the image for something like this. If you think you'll have a need for this kind of build often I don't mind to chat with you about the best way to put that in place (a preview tag or something).

If this seems more like a one-off it would be quicker to push the pre-release to github and if there's an issue with it you could revert it in another pre-release. Our build system will pick all that up automatically.

**Comment by nemchik** [comment]
P.s. if you want to chat about anything related to the lsio docker image, join our discord https://discord.gg/YWrKVTn and tag me (username is ixnyne on discord).

**Comment by hugbug** [comment]
I'll make a new testing release.

However I think any system should allow installation of pre-release software for testing purposes.

If I understand the process correctly the docker container downloads nzbget installer from GitHub and runs it. It would be great if instead of downloading there were a way to use local nzbget installer package instead.

**Comment by nemchik** [comment]
Actually, I am digging into it more (I am not originally the team member who made the image), and it looks like we are cloning your git repository and running `make` and other things.
https://github.com/linuxserver/docker-nzbget/blob/91756d5c02f04a7706a2779567915d531b71d5ca/Dockerfile#L26-L32

Releases/Prereleases on github are what the build system uses to check for when to do these builds. We aren't actually using the assets from the releases on github. So I think we could manually make image builds for any given commit in any branch of your repo (and the automation would continue to build from commits when a release is created).

**Comment by hugbug** [comment]
Release 21.1-testing-r2322 with the fix #745 is out.
Please test and report back if it has fixed the issue.

**Comment by nemchik** [comment]
Our docker image with this new build is now released under the `:testing` tag, or to specifically grab this exact version `:testing-version-v21.1-r2322`

**Comment by davidjameshowell** [comment]
Just wanted to comment that I was having some transient issues with 401 after about 2 minutes of inactivity. The current testing branch commented above by @nemchik worked. Is there a diff changelog for the differences that I can review?

**Comment by hugbug** [comment]
All and every change in NZBGet is documented in release notes of each release. Please see https://github.com/nzbget/nzbget/releases.

**Comment by davidjameshowell** [comment]
Thank you @hugbug. I was not aware that the testing branch releases were included in that. Appreciate the sidebar!

**Comment by nemchik** [comment]
> Just wanted to comment that I was having some transient issues with 401 after about 2 minutes of inactivity. The current testing branch commented above by @nemchik worked. Is there a diff changelog for the differences that I can review?

Container changes for the most recent release on the testing branch are here https://github.com/linuxserver/docker-nzbget/compare/testing-v21.1-r2311-ls26...testing-v21.1-r2322-ls27 but I believe you're looking for the changes in nzbget itself, which would be here in this repo as @hugbug mentioned.

Edit: most of the changes are to our build system, nothing about nzbget itself.

**Comment by PearsonFlyer** [comment]
After upgrading to r2322 on Windows 10, nzbget crashes constantly. The system event viewer has this error:

```
Faulting application name: nzbget.exe, version: 0.0.0.0, time stamp: 0x6078c168
Faulting module name: ntdll.dll, version: 10.0.19041.928, time stamp: 0x9bed63d6
Exception code: 0xc0000374
Fault offset: 0x00000000000ff0b9
Faulting process id: 0x4738
Faulting application start time: 0x01d73452aa4eec95
Faulting application path: C:\Program Files\NZBGet\nzbget.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: f95d104c-d485-4fd3-a3ae-25347c982f1f
Faulting package full name: 
Faulting package-relative application ID:
```

There is currently one thing in my queue, and it appears to be choking on it every time I restart it, and it shuts down again. If I manually wipe all trace of this download off my system, it does the same thing with the next download.

```
Sun Apr 18 09:53:33 2021	INFO	Successfully repaired ShowName.S16E03.1080p.AMZN.WEB-DL.DDP2.0.H.264-FLUX\iSwQonAJNMLghmVIzxanXlTqj6PLADe0
Sun Apr 18 09:53:33 2021	INFO	Deleting file 25585aad95f744e281a383130c99338b.part28.rar.1
Sun Apr 18 09:53:33 2021	INFO	Checking renamed archive files for ShowName.S16E03.1080p.AMZN.WEB-DL.DDP2.0.H.264-FLUX
Sun Apr 18 09:54:44 2021	INFO	nzbget 21.1-testing-r2322 server-mode
Sun Apr 18 09:54:44 2021	INFO	Checking renamed archive files for ShowName.S16E03.1080p.AMZN.WEB-DL.DDP2.0.H.264-FLUX
Sun Apr 18 10:08:29 2021	INFO	nzbget 21.1-testing-r2322 server-mode
Sun Apr 18 10:08:29 2021	INFO	Checking renamed archive files for ShowName.S16E03.1080p.AMZN.WEB-DL.DDP2.0.H.264-FLUX
Sun Apr 18 10:10:35 2021	INFO	nzbget 21.1-testing-r2322 server-mode
Sun Apr 18 10:10:35 2021	INFO	Checking renamed archive files for ShowName.S16E03.1080p.AMZN.WEB-DL.DDP2.0.H.264-FLUX
```

**Comment by hugbug** [comment]
@PearsonFlyer please create another issue. It's obviously not related to current one.

**Comment by hugbug** [comment]
@PearsonFlyer your issue is not related to current one. I've created #749 and replied to you there.

**Comment by ghost** [comment]
I've been having this issue for a while now. I thought it happened with a large queue, but I've seen it happen with smaller queues too.

Clearing the queue and restarting the container fixes it temporarily.

I've installed the testing LSIO container and will report back on if #745 has resolved this for me.

**Comment by ghost** [comment]
I'm still having issues where the queue gets corrupted. NZBGet is still running but I get a http response of 504.

Hopefully this can get fixed as soon as possible. In the meantime I have to use SABnzbd.

**Comment by hugbug** [comment]
@davidjameshowell 
> I'm still having issues where the queue gets corrupted.

Sounds like a different issue, not related to crash with certain nzb. Can you please create a separate issue with as much details as possible?

**Comment by ghost** [comment]
> @davidjameshowell 
> > I'm still having issues where the queue gets corrupted.
> 
> Sounds like a different issue, not related to crash with certain nzb. Can you please create a separate issue with as much details as possible?

Yeah, I'll try and get this done tomorrow. :)
