### ISSUE TITLE
Cipher auto-negotiation fails for usenet.premiumize.me

### ISSUE THREAD

**Issue by hurricane-dorian** [nzbget/nzbget#746]
Issue referenced in https://github.com/nzbget/nzbget/issues/594 witch was closed but never resolved.

This is the list of supported ciphers. Picking one of these manually, works fine.
Not sure if this is something that can be fixed in nzbget  but I'm posting this for reference.

Testing ECDHE-RSA-AES256-GCM-SHA384...YES
Testing DHE-RSA-AES256-GCM-SHA384...YES
Testing ECDHE-RSA-AES128-GCM-SHA256...YES
Testing DHE-RSA-AES128-GCM-SHA256...YES
Testing ECDHE-RSA-AES256-SHA384...YES
Testing DHE-RSA-AES256-SHA256...YES
Testing ECDHE-RSA-AES128-SHA256...YES
Testing DHE-RSA-AES128-SHA256...YES
Testing ECDHE-RSA-AES256-SHA...YES
Testing DHE-RSA-AES256-SHA...YES
Testing DHE-RSA-CAMELLIA256-SHA...YES
Testing ECDHE-RSA-AES128-SHA...YES
Testing DHE-RSA-AES128-SHA...YES
Testing DHE-RSA-SEED-SHA...YES
Testing DHE-RSA-CAMELLIA128-SHA...YES
Testing AES256-GCM-SHA384...YES
Testing AES128-GCM-SHA256...YES
Testing AES256-SHA256...YES
Testing AES128-SHA256...YES
Testing AES256-SHA...YES
Testing CAMELLIA256-SHA...YES
Testing AES128-SHA...YES
Testing SEED-SHA...YES
Testing CAMELLIA128-SHA...YES

**Comment by hugbug** [comment]
Please describe the issue in more details. From the very limited info you gave I don't see how this is related to #594. In the mentioned issue DNS requests did not work and many other things.

**Comment by hugbug** [comment]
Closing this issue for now. Feel free to post further comments and I'll reopen the issue if necessary.
