### ISSUE TITLE
Question: Build warnings

### ISSUE THREAD

**Issue by fernandog** [nzbget/nzbget#75]
Should I do something ?
It builds ok (Latest testing build)

```
WARNING: `aclocal-1.9' is missing on your system.  You should only need it if
         you modified `acinclude.m4' or `configure.ac'.  You might want
         to install the `Automake' and `Perl' packages.  Grab them from
         any GNU archive site.
 cd . && /bin/bash /home/osmc/nzbget/posix/missing --run automake-1.9 --foreign
/home/osmc/nzbget/posix/missing: line 46: automake-1.9: comando não encontrado
WARNING: `automake-1.9' is missing on your system.  You should only need it if
         you modified `Makefile.am', `acinclude.m4' or `configure.ac'.
         You might want to install the `Automake' and `Perl' packages.
         Grab them from any GNU archive site.
cd . && /bin/bash /home/osmc/nzbget/posix/missing --run autoconf
/home/osmc/nzbget/posix/missing: line 46: autoconf: comando não encontrado
WARNING: `autoconf' is missing on your system.  You should only need it if
         you modified `configure.ac'.  You might want to install the
         `Autoconf' and `GNU m4' packages.  Grab them from any GNU
         archive site.

```

**Comment by hugbug** [comment]
You shouldn't have these messages if you build using distribution source archive **nzbget-16.0-testing-r1420-src.tar.gz**.

You may have these messages if you build from Git clone and don't follow instructions from [Build the latest development version](https://github.com/nzbget/nzbget/wiki/Build-the-latest-development-version).

You may have these messages as well if you use sources obtained via links "Source code (zip)" and "Source code (tar.gz)", which GitHub creates automatically and which I can't remove unfortunately.

**Comment by fernandog** [comment]
Thanks!

Missing
touch configure
touch Makefile.in
touch config.h.in

**Comment by fernandog** [comment]
even with those 'touch' I still have those warnings:
need to touch as root or as my user (osmc) ?

plus this one:
notice the touch config.h.in here:

```
WARNING: `autoheader' is missing on your system.  You should only need it if
         you modified `acconfig.h' or `configure.ac'.  You might want
         to install the `Autoconf' and `GNU m4' packages.  Grab them
         from any GNU archive site.
rm -f stamp-h1
touch config.h.in
cd . && /bin/bash ./config.status config.h
config.status: creating config.h
config.status: config.h is unchanged
```

**Comment by hugbug** [comment]
Some files were probably already changed. Do `git reset --hard`, then the touches. Hope it helps.

**Comment by fernandog** [comment]
still nothing. Can I ignore this warnings?

did this:
git reset --hard HEAD
git clean -df
git pull
and run my script:

```
#!/bin/bash
cd ~/nzbget && result=$(git pull)
if ! [ -f configure ]; then configure; fi
if ! [ -f Makefile.in ]; then touch Makefile.in; fi
if ! [ -f config.h.in ]; then touch config.h.in; fi
if ! [ "$result" == "Already up-to-date.." ]; then # added extra . to force make
sudo systemctl stop nzbget && ./configure && make --always-make && sudo make install && sudo systemctl start nzbget
else
echo $result
fi
```

**Comment by hugbug** [comment]
You missed "touch"  in "touch configure". What these "ifs" are for? I think they never work. You should "touch" after every "pull", no conditions.

**Comment by fernandog** [comment]
still with that touch
https://gist.github.com/fernandog/f1c49f4ab7b194fdc2e4

can I ignore ?

**Comment by hugbug** [comment]
You can ignore it as long as you don't have autotools installed. Once you install it they may destroy the configure script, because you will most likely will have a different version of autotools and they are not always compatible.
I still,think your build script is buggy, the "ifs" prevent touches from execution.
Do you have these warnings if you build using instuctions from wiki?

**Comment by fernandog** [comment]
did exactly as the wiki. Same warnings

```
cd ~/
git clone https://github.com/nzbget/nzbget.git nzbget-git
cd nzbget-git
git pull
touch configure
touch Makefile.in
touch config.h.in
./configure
make
```

https://gist.github.com/fernandog/d072a5b4baed9f1b5c99

**Comment by hugbug** [comment]
You already have "nzbget-git" which may have modified files (due to previous attempts). Please retry with a fresh path (e. g. "nzbget-git2").

**Comment by fernandog** [comment]
No. My previous is only nzbget. See gist

**Comment by hugbug** [comment]
You are right. Something makes the build script thinking that the autotools files require rebuild.

**I'll investigate it.**

The good news is that a build from distribution archive (nzbget-16.0-testing-r1420-src.tar.gz) works OK, without these messages.

**Comment by fernandog** [comment]
My nzbget is running ok with latest build. Thats why I asked If I can ignore.

**Comment by hugbug** [comment]
This works for me without warnings:

```
touch aclocal.m4 configure Makefile.in config.h.in
```

(added aclocal.m4 to touch-list)

**Comment by fernandog** [comment]
with '--always-make' I get the warning. 
without it I get no warnings

I added the always-make to force make when I 'git pull'

**Comment by hugbug** [comment]
I don't know what "--always-make" does.
You could do `make clean`, then `make` if you want to force it.

**Comment by fernandog** [comment]
Ok! Thanks
