### ISSUE TITLE
nzbget post-processing rsync sshpass issue

### ISSUE THREAD

**Issue by Merlincool** [nzbget/nzbget#751]
Forum post have not been touched since long I suppose.

https://forum.nzbget.net/viewtopic.php?f=8&t=2874

error I get is

`ReTransfer: rsync error: error in rsync protocol data stream (code 12) at io.c(235) [sender=3.1.2]
INFO Wed Apr 21 2021 22:33:50 ReTransfer: rsync: connection unexpectedly closed (0 bytes received so far) [sender]
INFO Wed Apr 21 2021 22:33:50 ReTransfer: ssh: connect to host ***.**.***.*** port 22: Connection refused`

the sshpass is not working

when I have sshpass -p my_real_pass it works but I don't want to put that pass that way.

For some reason I am not using ssh key way (disallowing password prompt)

**Comment by hugbug** [comment]
This is a wrong issue tracker for third-party post-processing scripts. Sorry.
