### ISSUE TITLE
Add support for de-obfuscating abc.xyz files

### ISSUE THREAD

**Issue by TheFiZi** [nzbget/nzbget#752]
Not sure if this is something you're interested in dealing with but according to the Sonarr Devs:

```
Deobfuscating season packs should be handled by your download clients if needed
No plans to have sonarr handle deobfuscating season packs
Source: https://github.com/Sonarr/Sonarr/issues/4154
```

They supposedly addressed it for individual file downloads via this PR: https://github.com/Sonarr/Sonarr/commit/f9e045d14c0bc7a16159e3850bf755351ada5035 but even that doesn't work consistently I'm finding.

The files look like this: `abc.xyz.4c3b0f28a92b34.mkv` after being extracted.

sabnzbd has a plugin for it: https://github.com/sabnzbd/sabnzbd/blob/develop/scripts/Deobfuscate.py

If it's something you can add to nzbget it'd be much appreciated.

**Comment by hugbug** [comment]
Please explain the issue. From the little information you gave I don't understand what is requested.

NZBGet does deobfuscation for downloaded files using par2-files and via scanning of archives. This is similar to the linked SAB-script but is more sophisticated. BTW the linked script doesn't deal with season packs as stated in the comments in the script. Maybe you linked wrong script?

Anyway the main reason for deobfuscation is to be able to unpack files. No further processing is made for extracted files. If renaming of the unpacked files is needed this is an ideal use case for post-processing scripts. This is for example what [VideoSort](https://forum.nzbget.net/viewtopic.php?f=8&t=840) does. If you explain in details what the script should do then someone (maybe me) could write it. The best place for such discussion is [forum post-processing scripts](https://forum.nzbget.net/viewforum.php?f=8&sid=77bf4f67f8a4a8f0dd087e957ded950a).

**Comment by TheFiZi** [comment]
I was not aware nzbget already did de-obfuscation.

I assumed it didn't because I randomly find individual files downloaded that aren't getting de-obfuscated.

I consistently find season packs that are not being de-obfuscated.

My request was specific to season packs, sorry for not being clear.

I will check the resources you've linked.

**Comment by hugbug** [comment]
Season packs are generally difficult to process. Normally season pack nzbs should not exist at all if the indexer does a proper job. If multiple episodes were merged into one nzb the downloaded file may not contain any info to determine which file contain which episode.

If you can send me several example nzbs (the more the better) I'll take a look - nzbget@gmail.com. If there is a pattern and some info to use for renaming, then maybe a script can be written.

**Comment by SteffanCline** [comment]
See  https://github.com/nzbget/nzbget/issues/795

**Comment by paul-chambers** [comment]
I've submitted a Pull Request that should fix this (I had run into similar problems). Please see https://github.com/nzbget/nzbget/pull/832

**Comment by SteffanCline** [comment]
@hugbug I just sent you several examples to use for testing. Will you be releasing another build incorporating @paul-chambers 's changes? I'm happy to test again. Would it be as simple as post-processing again or do they have to be re-downloaded?

**Comment by SteffanCline** [comment]
@hugbug, I have tested @paul-chambers 's patch and it works amazingly well. Not a single failure with it. Can you please merge and put out a new build?
