### ISSUE TITLE
Backup+Restore news servers only

### ISSUE THREAD

**Issue by eadmaster** [nzbget/nzbget#754]
Is it possible to backup and restore the news-servers only?

This is useful if you are moving your installation from a PC to another.

**Comment by hugbug** [comment]
Yes.

**Comment by eadmaster** [comment]
the only way i've found to do that is manually copying the server settings from one `nzgget.conf` to another.

**Comment by hugbug** [comment]
There are BACKUP SETTINGS and RESTORE SETTINGS functions in web interface.
