### ISSUE TITLE
How to create static-linked, self-contained nzbget?

### ISSUE THREAD

**Issue by sanderjo** [nzbget/nzbget#756]
I want to create a static-linked, self-contained nzbget.
I don't see the instruction in https://github.com/nzbget/nzbget/blob/develop/README

I tried this line in Makefile

`LDFLAGS = -static`

but that results in an error:

```
rvice.o daemon/util/FileSystem.o daemon/util/Util.o daemon/nserv/NServMain.o daemon/nserv/NServFrontend.o daemon/nserv/NntpServer.o daemon/nserv/NzbGenerator.o daemon/nserv/YEncoder.o code_revision.o  lib/yencode/SimdInit.o lib/yencode/SimdDecoder.o lib/yencode/ScalarDecoder.o lib/yencode/Sse2Decoder.o lib/yencode/Ssse3Decoder.o lib/yencode/PclmulCrc.o lib/yencode/NeonDecoder.o lib/yencode/AcleCrc.o lib/yencode/SliceCrc.o    -lpthread  -lxml2  -lncurses -ltinfo
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lxml2
/usr/bin/ld: cannot find -lncurses
/usr/bin/ld: cannot find -ltinfo
/usr/bin/ld: cannot find -lstdc++
/usr/bin/ld: cannot find -lm
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:1465: nzbget] Error 1
make[1]: Leaving directory '/root/git/nzbget'
make: *** [Makefile:980: all] Error 2
```

Instruction how to do it? Maybe just another "./configure" or "make" parameter?

**Comment by hugbug** [comment]
Looks like the linker cannot find static libraries. Check if you have for `libpthread.a` (with .a extension), `libxml2.a`, etc.

I set linker flags during configure step:
```
LDFLAGS="-static" ./configure
```
- - -
Be aware that static linking is discouraged. Even if you succeed with linking the resulting binary still may not work or not work properly on other computers. In particular glibc by default doesn't work in static mode properly. It has to be compiled with special parameters. Google for "glibc --enable-static-nss".

**Comment by sanderjo** [comment]
> Be aware that static linking is discouraged. Even if you succeed with linking the resulting binary still may not work or not work properly on other computers.

But ... **you** are able to create statically linked, self-contained executables, right?

Anyway: if you want access to an (emulated so very slow) riscv64, let me know.
