### ISSUE TITLE
Safari tab favicon showing Plex icon

### ISSUE THREAD

**Issue by asemev** [nzbget/nzbget#757]
Hi, my Safari favicon for the tab window for nzbget is showing a plex icon. I tried permanently deleting the favicon cache folder (~/Library/Safari/Favicon Cache) but still it shows the plex icon. Any ideas on how to fix this? Thx.

![image](https://user-images.githubusercontent.com/30929896/116815075-24f04880-ab5c-11eb-8fc9-fc9ad6055b5a.png)

**Comment by hugbug** [comment]
For a test try another browser.

**Comment by asemev** [comment]
Works properly on the Chrome browser. So its a Safari bug then?

![image](https://user-images.githubusercontent.com/30929896/116815218-d68f7980-ab5c-11eb-96aa-7217d6e97185.png)

**Comment by hugbug** [comment]
For me Safari shows a proper icon on both Mac and iPad.
There is probably some glitch on your system. Maybe Safari was still running when you were clearing the cache? Try rebooting (without restoring windows) and then delete the favicon cache.

**Comment by asemev** [comment]
No, still didn't fix it. so weird :(

**Comment by asemev** [comment]
guess what :) the favourites bar shows the correct favicon. 

<img width="161" alt="image" src="https://user-images.githubusercontent.com/30929896/116885591-56364a80-ac28-11eb-875b-56a1c57ddea4.png">

so the bug is definitely in Safari and in the tab view... LOL

**Comment by cxhamilton** [comment]
@asemev I assume that you are running NZBGet and Plex Media Server on the same host? This is definitely a Safari issue that I have as well, though my "universal" favicon is Portainer.

**Comment by asemev** [comment]
Yes indeed same server! So thats the issue. Ok. Thank you! :)
