### ISSUE TITLE
Feature Request (or Documentation Request): API - Get Active Queue

### ISSUE THREAD

**Issue by LeeThompson** [nzbget/nzbget#763]
I haven't found a way to get a list of the active queue for NZBget, there's history, edit queue but nothing to just get the download queue.

**Comment by hugbug** [comment]
First of all the web interface works 100% via API. If something is possible in web ui then there is API for that.

To be more specific you are looking for method [listgroups](https://nzbget.net/api/listgroups).

**Comment by LeeThompson** [comment]
Ah, thank you!
