### ISSUE TITLE
Where do I ask questions about nzbget configuration?

### ISSUE THREAD

**Issue by mkanet** [nzbget/nzbget#767]
Hi, I would like to know where I can ask support questions.  I tried to register on the forum.  However, new user registration is disabled currently.

Per https://github.com/nzbget/nzbget/issues/554, I sent an email to nzbget@gmail.com; but, didn't get a response.

I also couldn't find any Discord channels.

**Comment by hugbug** [comment]
I've replied via e-Mail.
