### ISSUE TITLE
Updating the Windows version fails if NZBGet is not installed on the system drive

### ISSUE THREAD

**Issue by Zepmann** [nzbget/nzbget#78]
This issue has been observed when NZBGet is running as a Windows service and the web-interface is used to run the update.

install-update.bat executes this command:

```
cd %NZBGET_DIR%
```

Because of this, execution will look like this when NZBGet is installed on another drive:

```
C:\Windows\system32>rem "D:\NZBGet\" means the location of the current batch file
C:\Windows\system32>set NZBGET_DIR=D:\NZBGet\
C:\Windows\system32>cd D:\NZBGet\
C:\Windows\system32>rem Determine if NZBGet is running as a service
```

All further execution will still be done in the default (system) directory of Windows, because `cd` by default does not change the current working directory to another drive. This is bad, because nzbget.exe cannot be executed if the current working directory is not the NZBGet directory, and the update cannot be applied.

The fix:

```
cd /D %NZBGET_DIR%
```

This makes the current working directory that of NZBGet, even if it is on another drive.

**Comment by hugbug** [comment]
Thank you for reporting this and for the fix.
