### ISSUE TITLE
Question: What Requires 'Local Dom Storage'?

### ISSUE THREAD

**Issue by ghost** [nzbget/nzbget#79]
I use the Random Agent Spoofer with Firefox;

https://github.com/dillbyrne/random-agent-spoofer

I have a lot of about:config options disabled like the `local dom storage`, but I noticed with this disabled nzbget complains, so I had to enable it.

What is requiring this, and is there a setting I can disable so I don't need local dom storage?

I really don't like using local dom storage in Firefox.

thanks

**Comment by hugbug** [comment]
It's to store web-interface settings such as records per page, refresh rate, etc.

**Comment by ghost** [comment]
Well if I don't want to store these can the app still work ok, and if so, where can I disable it?

**Comment by hugbug** [comment]
That's a required browser functionality. What do you try to achieve by disabling browser functions? The app requires a modern browser which supports latest standards.

**Comment by ghost** [comment]
It can be a security risk, so I don't like using it, and it sucks to need to enable and disable it all the time...

You should look into this, if you are not aware of it, an application should not be made to need it...

thanks

**Comment by hugbug** [comment]
> an application should not be made to need it.

Who says that?

**Comment by ghost** [comment]
I guess it's how someone wants to look at it, but what we can consider here is that Mozilla does allow the end-user to disable this.

If Local Storage was critical, I would consider that Mozilla would not even allow an option to disable it, so you would not break functionality.

I guess the question is, can nzbget be made to work without it? Hmm

**Comment by ghost** [comment]
Not to thrown fire in a flame and start a flame war, LOL, but SABnzbd does not require local storage, maybe that can help you to figure away around this too... :/

**Comment by hugbug** [comment]
> Mozilla does allow the end-user to disable this.

No, it doesn't. That's a hidden setting which isn't supposed to be changed by end users. 

> If Local Storage was critical, I would consider that Mozilla would not even allow an option to disable it, so you would not break functionality.

When you open "about:config" in Firefox it gives a clear warning that these settings **are critical** and should not be changed.

**Comment by ghost** [comment]
about:config is pretty common...

Actually it says; it can be harmful to the security, stability and performance.

Anyhow, we are geeks I'm assuming in this conversation, so we need to move beyond this... :)

**Comment by ghost** [comment]
Truth is, Mozilla doesn't seem to also want to ADD by using some of the default settings they can be harmful too...

**Comment by ghost** [comment]
By the way, I wasn't implying that by using nzbget with the local dom storage a problem, I'm just saying, enabling and disabling it all the time is a pain...

Surfing the web with it, is the problem...

**Comment by hugbug** [comment]
If you don't care about saving UI settings you can modify **index.js** to disable usage of local storage.
- put `return def;` before https://github.com/nzbget/nzbget/blob/develop/webui/index.js#L101 ;
- comment out line https://github.com/nzbget/nzbget/blob/develop/webui/index.js#L114.

You need to do that modification after each NZBGet update, make a script for that using `sed` or a similar tool.

**Comment by ghost** [comment]
Sorry, under > Settings, these all need the local storage enabled, to be able to make setting changes and have them saved?

**Comment by hugbug** [comment]
No, the global Settings are stored in the config file on PC where NZBGet runs.

The local storage is for web ui settings:
- refresh rate;
- records per page;
- compact view mode (on/off) on settings page;
- quick filters (new in v16).

**Comment by ghost** [comment]
ok, sure would be nice if the web ui settings could be stored somewhere else, maybe a sqlite db?

**Comment by hugbug** [comment]
> would be nice if the web ui settings could be stored somewhere else

These are settings which you want different on your different devices and therefore must be saved on device (in the browser).

Please understand that I'm not going to invest time into this just because you don't like local storage, for no obvious reason actually. I have many other todos which I consider far more important. If you can provide info why using local storage should be avoided I may reconsider. My view is that it's part of web standards and is a normal practice to be used.

**Comment by hugbug** [comment]
You can create a second Firefox profile for NZBGet (with enabled local storage) and start it via a desktop shortcut as explained [here](http://kb.mozillazine.org/Opening_a_new_instance_of_Firefox_with_another_profile).

**Comment by ghost** [comment]
I don't want you to invest time for me, it's not the point. 

As a developer building an application using Firefox you should be aware of the security risks certain settings in Firefox pose, such as the local storage.... As I mentioned before, I'm not saying that nzbget poses the risk, it's just the need to turn it on, then by mistake a user forgets to turn it off when using Firefox online...

For the sake of ease for yourself, yes using another profile seems the way to go, but for the ease and security of the end-user, I'm not sure it's the way to go...

There is a lot of information online regarding local storage and security...

thanks
