### ISSUE TITLE
Add Option "All" to Show [x] Records per Page

### ISSUE THREAD

**Issue by jwillmer** [nzbget/nzbget#80]
I can't rearange items in queue accross multible pages so I need a option to show all items to rearange (move) them to the desired position.

**Comment by hugbug** [comment]
Screen updates are CPU intensive, therefore a limitation for page size.
Are you going to rearrange more than 100 items manually?
In a case you don't know - the items can be sorted by clicking on column title; if there are selected items, then only they are sorted (and grouped together).

**Comment by jwillmer** [comment]
Oh I have an older version I am affraid. I give the new version a try :-)
