### ISSUE TITLE
nzbget.conf(1775): Invalid value for option "Category4.Unpack": ""

### ISSUE THREAD

**Issue by ghost** [nzbget/nzbget#81]
I notice these under the messages;

nzbget.conf(1775): Invalid value for option "Category4.Unpack": ""
nzbget.conf(1771): Invalid value for option "Category3.Unpack": ""
nzbget.conf(1767): Invalid value for option "Category2.Unpack": ""

**Comment by hugbug** [comment]
"Empty" isn't a valid value for option "Unpack". Check the config file in a text editor.

**Comment by ghost** [comment]
I didn't touch or change anything, so I'm assuming default values should be added...

This is what it shows;

```
# NOTE: This options affects only queue-scripts and only
# "file-downloaded"-events. Queue-scripts can be activated using
# option <QueueScript> (for pure queue-scripts) or option <PostScript>
# (for dual-mode scripts which act as queue- and post-processing-scripts
# at the same time).
EventInterval=0
Category2.DestDir=
Category2.Unpack=yes
Category2.PostScript=
Category2.Aliases=
Category3.DestDir=
Category3.Unpack=yes
Category3.PostScript=
Category3.Aliases=
Category4.DestDir=
Category4.Unpack=yes
Category4.PostScript=
Category4.Aliases=
Category2.DestDir=
Category2.Unpack=
Category2.PostScript=
Category2.Aliases=
Category3.DestDir=
Category3.Unpack=
Category3.PostScript=
Category3.Aliases=
Category4.DestDir=
Category4.Unpack=
Category4.PostScript=
Category4.Aliases=
```

**Comment by ghost** [comment]
Looks like some of the sections repeat themself, hmm

**Comment by hugbug** [comment]
> Looks like some of the sections repeat themself,

The mess may happen if the option **ConfigTemplate** points to the actual configuration file (instead of the template file). Please check option **ConfigTemplate** first.

A similar problem was reported when using an older version of nzbToMedia scripts. The script manipulates the config file and there was a bug there.

### Resolution

Using a text editor scroll to the part where the duplicate entries start and delete everything after that. Then try saving options from settings page (change something) and check the file again if duplicates were added.

**Comment by hugbug** [comment]
Closed due to lack of feedback.
Feel free to comment and reopen if the issue still persist.

**Comment by daviddp4** [comment]
I'have the same problem, I've deleted every duplicate but if i change something in the setting page, duplicate appears again...
Any idea ?

**Comment by hugbug** [comment]
Check opion ConfigTemplate.

**Comment by daviddp4** [comment]
What do you mean ? Do I have to modify the configtemplate files or must i make a copy  of the nzbgzt.conf in a different folder?

**Comment by hugbug** [comment]
If you install using official installers from download page then everything should work without extra steps. If you use other package there is a chance that it is not prroperly configured.

To fix: download source code of your nzbget version. Extract file nzbget.conf. Put it into any folder on device where you run nzbget. This is your config-template file. Stop nzbget. Open your actual configuration (not config-template) and set option ConfigTemplate to the file you just downloaded. Never edit the config-template-file.
Then remove duplicate entries and start nzbget.
That should fix it.

**Comment by daviddp4** [comment]
I'm trying on a Qnap NAS, i'll try your tips...

**Comment by daviddp4** [comment]
Well, I think  there must be something wrong with the QNZB Package, I found this 
[http://forum.nzbget.net/viewtopic.php?f=3&t=2404](url)
The same problem, I'll try a clean install...
Thanks for your answers.

**Comment by daviddp4** [comment]
With the official installer, all works fine...
Thanks again.

**Comment by Blizzke** [comment]
Had the same issue on a regular linux machine. Just fixed the config file, updated the ConfigTemplate to point to another filename and then duplicated the config to that file. Seems that resolved the issue indeed.
