### ISSUE TITLE
is it possible to disable username/pw auth?

### ISSUE THREAD

**Issue by edwmurph** [nzbget/nzbget#817]
my nzbget instance is behind an auth proxy for external access and only otherwise accessed from within my cluster's network so i'd prefer to be able to bypass nzbget's built in auth

i tried setting `NZBGET_USER` and `NZBGET_PASS` env vars to empty strings, and omitting them, but both those attempts defaulted to the `nzbget` and `tegbzn6789` creds

my current workaround is just to set creds that are really easy for me to type since im not relying on it for security

**Comment by hugbug** [comment]
Set option **ControlPassword** to an empty string in NZBGet web-interface.

**Comment by edwmurph** [comment]
that worked thanks! it'd be ideal if disabling auth could be done declaratively via env vars but nbd
