### ISSUE TITLE
osx 16 r1439 bin doesn't include app binary 

### ISSUE THREAD

**Issue by spaham** [nzbget/nzbget#82]
I downloaded twice just to make sure, and the app can't be launched, as it doesn't contain any binary inside Contents/MacOS . The folder is empty...

This is from : 
https://github.com/nzbget/nzbget/releases/download/v16.0-r1439/nzbget-16.0-testing-r1439-bin-osx.zip

**Comment by hugbug** [comment]
Xcode update has screwed things up.

**Fixed.** Please download again.
Thank you for reporting this.

**Comment by spaham** [comment]
thanks :)
