### ISSUE TITLE
Update Emby

### ISSUE THREAD

**Issue by DraZtiK** [nzbget/nzbget#83]
Is it possible to create a notification to update the Emby library? as an example we have [Couchpotato notification](https://github.com/RuudBurger/CouchPotatoServer/blob/37fb6e0fe6780e6a291ea90d87cc1e8c17896022/couchpotato/core/notifications/emby.py). And a little more information [here.](https://github.com/RuudBurger/CouchPotatoServer/pull/5187)

Obviously this is a feature request. :-)

**Comment by hugbug** [comment]
This can be implemented as extension script, similar to other notification scripts.
Please post a request in [extension scripts subforum](http://forum.nzbget.net/viewforum.php?f=8) and may be someone can create it.

**Comment by hugbug** [comment]
How about writing the script yourself? Useful info:
- [Extension script (documentation, general info)](https://github.com/nzbget/nzbget/wiki/Extension-scripts);
- [Post-processing scripts (documentation)](https://github.com/nzbget/nzbget/wiki/Post-processing-scripts);
- [Example notification scripts](https://github.com/nzbget/nzbget/wiki/Catalog-of-post-processing-scripts#notifications).
