### ISSUE TITLE
Loading Configuration Failed on r1439

### ISSUE THREAD

**Issue by mannibis** [nzbget/nzbget#84]
I am running NZBGet 16.0-testing-r1439 on a QNAP (the .qkpg is maintained by Clinton). I used the update from within the UI to upgrade from the latest testing release to 1439.

When attempting to go to Settings i get the following error:

_Loading configuration failed_

_Could not load template configuration file nzbget.conf. The file contains descriptions of options and is needed to display settings page. The file comes with NZBGet distribution archive and is usually automaically installed into the right location. This seems not to be a case with your installation though._

_Please edit your configuration file (/share/CACHEDEV1_DATA/.qpkg/NZBGet/nzbget/nzbget.conf) in a text editor and set the option ConfigTemplate to point to the template configuration file nzbget.conf._

My Path for the Template is: **/share/CACHEDEV1_DATA/.qpkg/NZBGet/nzbget/webui/nzbget.conf.template**

And my ConfigTemplate variable in nzbget.conf is set to: **ConfigTemplate=/share/CACHEDEV1_DATA/.qpkg/NZBGet/nzbget/webui/nzbget.conf.template**

So everything looks kosher. Is there perhaps a permission issue that happened after the update. Like I said, I updated from within the NZBGet UI. I have also restarted the qpkg a few times to no avail. Any help would be appreciated. Thank you!

**Comment by hugbug** [comment]
Closed (discussed on forum and via email).
