### ISSUE TITLE
Segfault at 28 ip 00000000004020a0

### ISSUE THREAD

**Issue by mrafcho001** [nzbget/nzbget#85]
In the past 2 days I've seen 2 seg faults while NZBGet has been downloading things:

```
[187995.964096] nzbget[15757]: segfault at 28 ip 00000000004020a0 sp 00007fdd65696d00 error 4 in nzbget[400000+43e000]
[67223.228545] nzbget[32689]: segfault at 98 ip 00000000004020a0 sp 00007f98fca01d00 error 4 in nzbget[400000+43e000]
```

I can't reliably reproduce the issue, it seems to randomly happen on its own. Its worth nothing that I'm running NZBGet in a docker container and it is the latest stable version 15.0 installed as per the instructions on "Installation for Linux".

**Comment by hugbug** [comment]
Please install the debug variant of the latest testing version - [nzbget-16.0-testing-r1439-bin-linux-debug.run](https://github.com/nzbget/nzbget/releases/download/v16.0-r1439/nzbget-16.0-testing-r1439-bin-linux-debug.run) and activate option **DumpCore**.

When it crashes again it should create a core-file. This file will help me to find the location where it crashes. The log-file should also have callstack information printed on crash but it is sometimes not there or not accurate (depends on platform).

Please write back when you have the core-file or the log with callstack and we'll look into it.

**Comment by hugbug** [comment]
Closing due to lack of feedback.
Feel free to comment or reopen with additional info.

**Comment by mrafcho001** [comment]
Have not had the crash since updating to requested version. Will update with requested information if I encounter the crash again.

**Comment by emopinata** [comment]
I've been having this issue as well, and have a core-dump and log files for the last time it happened (within the last hour).

**Comment by hugbug** [comment]
Please me the log and core files to nzbget@gmail.com, possibly via google drive or dropbox if they are big. Also add the info what is the exact nzbget version and CPU architecture.
Note that core files may contain your logins and passwords such as for news server.

**Comment by emopinata** [comment]
The core dump is ~7.4gb, but I'll email you with the links as soon as it's done. Thanks!

**Comment by hugbug** [comment]
Wow, that's big. May be compressing helps?

**Comment by emopinata** [comment]
Should have tried that first before I said it. 34mb now :-)

**Comment by emopinata** [comment]
Sent!

**Comment by hugbug** [comment]
@jalmansor:
I've checked the core-file. You have the same issue as #104.

I'll send you current version which shouldn't crash. But nonetheless it doesn't fix the actual problem; it isn't clear what causing it. The fixed version prints better error message which will hopefully help to find the cause.
