### ISSUE TITLE
Warning: Web-Server: 400 Bad Request, Resource: /api

### ISSUE THREAD

**Issue by blancomorao** [nzbget/nzbget#90]
Hello guys!

I come across this issue that is plaguing my log file since I installed NZBget for the first time a few days ago while still version 15 was stable and persist after update to version 16, I have Re-installed the application but still the issue appears I have changed all related configuration trying to identify the source of the Warning but not luck.

THE ISSUE:

After NZBGet start on boot or manually the following Warning is shown on the message center:

WARNING: Web-Server: 400 Bad Request, Resource: /api

The above message continues to appears at a rate of 2 secs between messages until the massage center gets to 1000 message after that it stops in the Web UI and in the log file, but if a clear the messages using the WebUI it start again.

Apparently this does not affect any other downloading, renaming or connecting functionalities.

THE SOFTWARE INSTALLED:

OS:
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:    14.04
Codename:   trusty

APPS:

NZBGet: Version Currently installed: 16.0
CouchPotato: e6fa8b8b (4/10/2015 4:43:08)
Deluge: 1.3.12
Sonarr: 2.0.0.3357
Headphones: 6720575bd94cda8ef153d4781c06dff2813975e0

LOG FILE:

http://pastebin.com/J8T27jM2

**Comment by hugbug** [comment]
Some other program tries to communicate with NZBGet in a wrong way.
From the URL it seems that other program uses SAB protocol.
Make sure you have configured Sonarr and others to talk to NZBGet (not to SAB).
It can also be a browser plugin.

**Comment by blancomorao** [comment]
Hugbug,

Thank you for your reply; unfortunately the issue happens even when no other apps are trying to connect to NZBGet, I have checked it before and now I just did it again and is still occurring.

Partial Log with all apps not conecting to NZBGet:

Tue Oct 13 08:16:47 2015    WARNING Web-Server: 400 Bad Request, Resource: /api
Tue Oct 13 08:16:50 2015    WARNING Web-Server: 400 Bad Request, Resource: /api
Tue Oct 13 08:16:53 2015    WARNING Web-Server: 400 Bad Request, Resource: /api
Tue Oct 13 08:16:55 2015    WARNING Web-Server: 400 Bad Request, Resource: /api
Tue Oct 13 08:16:56 2015    WARNING Web-Server: 400 Bad Request, Resource: /api
Tue Oct 13 08:16:59 2015    WARNING Web-Server: 400 Bad Request, Resource: /api
Tue Oct 13 08:17:02 2015    WARNING Web-Server: 400 Bad Request, Resource: /api
Tue Oct 13 08:17:05 2015    WARNING Web-Server: 400 Bad Request, Resource: /api
Tue Oct 13 08:17:08 2015    WARNING Web-Server: 400 Bad Request, Resource: /api
Tue Oct 13 08:17:10 2015    WARNING Web-Server: 400 Bad Request, Resource: /api
Tue Oct 13 08:17:11 2015    WARNING Web-Server: 400 Bad Request, Resource: /api
Tue Oct 13 08:17:14 2015    WARNING Web-Server: 400 Bad Request, Resource: /api
Tue Oct 13 08:17:17 2015    WARNING Web-Server: 400 Bad Request, Resource: /api
Tue Oct 13 08:17:20 2015    WARNING Web-Server: 400 Bad Request, Resource: /api

**Comment by blancomorao** [comment]
Hugbug,

Another interesting thing is why I'm getting this error if none of the Apps conecting to NZBGet are using API calls ( I believe they are not) since they have to connect via username and password.

**Comment by hugbug** [comment]
You had SAB on that same PC before, right? You have some program configured to connect to SAB but now you have NZBGet running on that port. The program still thinks it connects to SAB and access it in a wrong way.

You can change the port in nzbget settings (option **ControlPort**) and you'll see the messages go away.

You can install debug version of NZBGet, activate option **DebugTarget**, then inspect the log, which will contain all headers passed in the request. You may be able to identify the program via header **User-Agent**, but that require the program to set it properly.

If that doesn't help use [Wireshark](https://www.wireshark.org) to capture the traffic. It may be able to show you where the requests come from.

**Comment by blancomorao** [comment]
Hugbug,

Thank you very much! you where right! I had a firefox plugin for SABnzb installed but not deactivated.

Issue Solved!
