### ISSUE TITLE
Failed Downloads Auto-deleting from the History

### ISSUE THREAD

**Issue by Snipe3000** [nzbget/nzbget#93]
I'm running nzbget on my synology NAS.
When my downloads fail to unpack, I noticed that in the History tab, the failed download only stays around for a few seconds, then is removed.
I have DeleteCleanupDisk set to NO,
NzbCleanupDisk set to NO,
KeepHistory set to 9999,
I've tried HealthCheck on all three settings (Delete, Pause, None),
And in my Categories section I'm using a post script so I disabled it, but the results are the same. If the unpack fails, the failed download will be remove from the History.

Here is an Example of the errors from the Log:
ERROR   Wed Oct 14 2015 21:53:53    Unpack for TVshowName failed

ERROR   Wed Oct 14 2015 21:53:53    Could not delete temporary directory /volume1/TVshowName/_unpack:

ERROR   Wed Oct 14 2015 21:53:53    Unrar error code: 10

ERROR   Wed Oct 14 2015 21:53:53    Could not create directory /volume1/TVshowName/_unpack: could not read information for directory /volume1/TVshowName/_unpack: errno 13.

INFO    Wed Oct 14 2015 21:55:11    Deleting TVshowName from history

I'm know how to fix the error, but I'm trying to fix the History issue. I need these failed unpacks to stay in the History.

**Comment by hugbug** [comment]
It's Sonarr deleting them. I don't know why it is doing this but at least it has a setting to disable that strange behavior.

**Comment by Snipe3000** [comment]
Thanks, that was the problem.
