### ISSUE TITLE
Add download time/rate to statistics

### ISSUE THREAD

**Issue by cxhamilton** [nzbget/nzbget#94]
Could the download/rate time be added to the statistics table?

<img width="561" alt="screen shot 2015-10-15 at 10 23 34 am" src="https://cloud.githubusercontent.com/assets/1507178/10516651/55854982-7327-11e5-9466-42f6d95cce7b.png">

**Comment by hugbug** [comment]
Click on **Total ->**.

**Comment by cxhamilton** [comment]
GTFO. Well done.
