### ISSUE TITLE
Daily/Monthly download limit

### ISSUE THREAD

**Issue by boerngen-schmidt** [nzbget/nzbget#99]
Hello folks,

this is not a bug, but a feature request with a low priority.

What I have in mind is a setting where I can set how much MB/GB/TB NZBGet should download a day/week/months. 

Why do I want to have such a feature. Well when I add lots of stuff to download, which I do not need instantly, it would be nice to spread the download of these items over time, since I might have stuff I want to download instantly. The Usenet-provider I use has a monthly limit. With such a feature I could control this limit better and if I want to I could force the download.

Maybe the limit could also be connected with a priority or a category.

**Comment by hugbug** [comment]
Considering current prices for unlimited plans (which start from $5 per month) spending time on this feature isn't really worth it.

**Comment by war59312** [comment]
Well, you do also have ISPs that limit bandwidth per month. Lame aholes! But none the less..

**Comment by nomandera** [comment]
To be fair the  "$5 per month" price is very USA-centric. There are still plenty of places in the world where you cannot for any price buy unlimited internet and others where it costs $500-$1800 per month.

Another factor to keep in mind is that many people use mobile broadband which can be very fast but is almost always capped.

I dont have an opinion on the feature itself just pointing out these use cases.

**Comment by hugbug** [comment]
> To be fair the "$5 per month" price is very USA-centric.

No, it's not. The topic starter was talking about **Usenet provider**.

I agree the download limits can be useful if the **Internet provider** sets such limits. I'm not sure if there are many NZBGet users who need the feature though.

**Please everyone who needs the feature post to this thread.**

**Comment by nomandera** [comment]
Yes I was incorrect in the $5 quote but my use cases still apply. The reason I went this reply route so quickly was that until 18 months ago I was paying approximately 230 times more per GB in ISP charges  than I am now.

That has changed for me so I do not need this feature.

**Comment by leeramsay** [comment]
I would hugely benefit from a monthly download limit feature, as I have a set gb limit per month. Capped internet is very common in Australia, and it's a feature that other popular nzb fetcher has.

**Comment by TVBoy999** [comment]
+1 for the quota. Overage charges for my ISP will buy you a small car.

**Comment by hugbug** [comment]
A couple of questions to the feature request:
- what is the quota period, does it always start at the first of the month at 0:00 local time and ends the last day of the month?
- daily quotas (mentioned in the issue title) - is this something real?
- we are talking about ISP quotas, not Usenet quotas, right? Therefore there is no need for per news-server settings.
- what should happen when the quota limit is reached? I would do:
  - during downloading the quota is constantly monitored and the downloading is automatically paused with a message if the limit is reached.
  - if the user resumes downloading it will remain resumed until next program start.
  - on start the program checks if the limit is reached and pauses downloading again. 
  - downloads with force-priority are downloaded regardless of pause state.

**Comment by leeramsay** [comment]
@hugbug 

My thoughts inline..
- what is the quota period, does it always start at the first of the month at 0:00 local time and ends the last day of the month?
  - ^^ Unfortunately not, my ISP, and several others I know of start your quota'd month on the day you signed up, so for example every month it might be the 9th day. This has been how other download applications I've used handle it, they simply ask for an integer between 1-31.

I guess the other thing to bare in mind is if someone has a 200gb per month quota, generally they won't want to spend 100% on downloading from usenet. They will likely set a 150gb quota within their primary download app, so complete technical accuracy isn't paramount, mainly that it's going to consume within the ballpark of what you expect it to do.
- daily quotas (mentioned in the issue title) - is this something real?
  - ^^ The only place I can think of daily quotas existing is for 3G/4G services, and hotels. That doesn't apply to me, I guess it's possible that people require it.
- we are talking about ISP quotas, not Usenet quotas, right? Therefore there is no need for per news-server settings.
  - ^^ In my case, yes. Most applications are just considering download quotas for the application, not per "source".
- what should happen when the quota limit is reached? I would do:
  - ^^ What you've laid out sounds fine, I've seen other apps with as basic functionality as to force pause, and have a "reset quota for this month" button, which is not exactly desirable. 
    I think pausing everything with allowing force-priority to override the pause is sufficient.

**Comment by TVBoy999** [comment]
Hi, 

Sorry for not getting back sooner.

My feedback Is pretty much the same as Lee's.  My quota is tied to my sign up date and I have no daily quotas.  Overage is something like $5 a GB. They do send warnings when I'm getting close though.

**Comment by hugbug** [comment]
**Implemented quota management.**

Who wanna test it? Send me a note to nzbget@gmail.com with the info about your OS and CPU and I'll send the development version.

I have some concerns about the behavior when the quota limit is reached (pause downloading). I'll write up later.

**Comment by hugbug** [comment]
### Update

Instead of interfering with global pause state the quota management now uses a separate `quota reached`-status.

When the `quota reached`-status is set the downloading is stopped (as if the pause state were active). Downloads with force-priority are still processed.

This has many advantages:
- user cannot accidentally resume downloads and must knowingly use force-priority;
- the download is automatically resumed when the quota status is lifted on the start of the next billing month or day. Especially useful with daily quotas;
- no interferences with scheduler pause/resume tasks.
